User-agent: *
Allow: /
Disallow: /invoice
Disallow: /order
Disallow: /invoicePdf/*
Disallow: /orderPdf/*
Disallow: /stAvailabilityFrontend/showAddOverlay
Disallow: /stQuestionFrontend/showAddOverlay
Disallow: /webpage/regulamin.html
Disallow: /basket/index
Disallow: /user/createAccount
Disallow: /user/loginUser
Disallow: /search
Disallow: /productsCompare
Disallow: /webpage/english.html
Disallow: /webpage/wysylka.html
Disallow: /webpage/platnosci.html
Disallow: /webpage/deutsch.html
Disallow: /webpage/rodo.html
Disallow: /user/showTerms
Disallow: /recommend_shop/showAddOverlay
Disallow: /review/showAddOverlay
Disallow: /manufacturer/sperian
Disallow: /manufacturer/peltor
