Sitemap: https://agroprofil.pl/sitemap_index.xml
User-agent: *
Disallow: /wp-admin/
Allow: /wp-admin/admin-ajax.php
Allow: /wp-content/uploads/*/*/*.png
Allow: /wp-content/uploads/*/*/*.jpg
Allow: /wp-content/uploads/*/*/*.jpeg
Allow: /wp-content/themes/woodmart/images/*.png
Allow: /wp-content/themes/woodmart/images/*.jpg
Allow: /wp-content/themes/woodmart/images/*.jpeg
Allow: /wp-content/themes/woodmart/images/*.svg
Allow: /wp-content/themes/woodmart/fonts/*.woff
Allow: /wp-content/themes/woodmart/fonts/*.woff2
Allow: /wp-content/themes/woodmart/fonts/*.ttf
Allow: /wp-content/themes/woodmart/fonts/*.svg
Allow: /wp-content/themes/woodmart/fonts/*.eot
Allow: /wp-content/themes/woodmart/js/*.js
Allow: /wp-includes/js/jquery/*.js*
Allow: /wp-includes/js/*.js*
Allow: /wp-content/themes/woodmart/css/*.css
Allow: /wp-content/themes/woodmart/*.css
Disallow: /tag/*
Disallow: /category/*
Disallow: /*/page/*
