# robots.txt file for http://aikidokaiten.pl/
# Generated by SOFTplus GSiteCrawler v1.23 rev. 286 / http://gsitecrawler.com/
# 2011-08-29  12:56

User-agent: *
# No exclusions found, disallow nothing.
Disallow:

# end of file


