# robots.txt automaticaly generated by PrestaShop e-commerce open-source solution
# http://www.prestashop.com - http://www.prestashop.com/forums
# This file is to prevent the crawling and indexing of certain parts
# of your site by web crawlers and spiders run by sites like Yahoo!
# and Google. By telling these "robots" where not to go on your site,
# you save bandwidth and server resources.
# For more information about the robots.txt standard, see:
# http://www.robotstxt.org/wc/robots.html
User-agent: *
# Private pages
Disallow: /*orderby=
Disallow: /*orderway=
Disallow: /*tag=
Disallow: /*id_currency=
Disallow: /*search_query=
Disallow: /*back=
Disallow: /*n=
Disallow: /*controller=addresses
Disallow: /*controller=address
Disallow: /*controller=authentication
Disallow: /*controller=cart
Disallow: /*controller=discount
Disallow: /*controller=footer
Disallow: /*controller=get-file
Disallow: /*controller=header
Disallow: /*controller=history
Disallow: /*controller=identity
Disallow: /*controller=images.inc
Disallow: /*controller=init
Disallow: /*controller=my-account
Disallow: /*controller=order
Disallow: /*controller=order-opc
Disallow: /*controller=order-slip
Disallow: /*controller=order-detail
Disallow: /*controller=order-follow
Disallow: /*controller=order-return
Disallow: /*controller=order-confirmation
Disallow: /*controller=pagination
Disallow: /*controller=password
Disallow: /*controller=pdf-invoice
Disallow: /*controller=pdf-order-return
Disallow: /*controller=pdf-order-slip
Disallow: /*controller=product-sort
Disallow: /*controller=search
Disallow: /*controller=statistics
Disallow: /*controller=attachment
Disallow: /*controller=guest-tracking
# Directories
Disallow: */classes/
Disallow: */config/
Disallow: */download/
Disallow: */mails/
Disallow: */modules/
Disallow: */translations/
Disallow: */tools/
Disallow: /blog/wp-admin/
Disallow: /blog/wp-includes/
# Files
Disallow: /odzyskiwanie-hasla
Disallow: /adres
Disallow: /adresy
Disallow: /logowanie
Disallow: /koszyk
Disallow: /discount
Disallow: /historia-zamowien
Disallow: /identity
Disallow: /moje-konto
Disallow: /order-follow
Disallow: /order-slip
Disallow: /order
Disallow: /szukaj
Disallow: /zamow-szybko
Disallow: /guest-tracking
Disallow: /potwierdzenie-zamowienia
# Sitemap
Sitemap: http://ale-fotoobrazy.pl/sitemap.xml

User-Agent: Googlebot
Allow: /


user-agent: AhrefsBot
disallow: /

user-agent: Twice
disallow: /

user-agent: Yand
disallow: /

user-agent: Voil
disallow: /

user-agent: libw
disallow: /

user-agent: Java
disallow: /

user-agent: Sogou
disallow: /

user-agent: psbot
disallow: /

user-agent: Exabot
disallow: /

user-agent: boitho
disallow: /

user-agent: ajSitemap
disallow: /

user-agent: Rankivabot
disallow: /

user-agent: DBLBot
disallow: /

user-agent: MJ1
disallow: /

user-agent: Rankivabot
disallow: /

user-agent: Roge
disallow: /

user-agent: Baidu
disallow: /

user-agent: site
disallow: /

user-agent: Ahre
disallow: /

user-agent: seo
disallow: /

user-agent: MJ12bot
disallow: /

User-agent: spbot
Disallow: /

user-agent: LinkpadBot
disallow: /

user-agent: AhrefsBot
disallow: /

user-agent: dotbot
disallow: /

User-agent: meanpathbot
Disallow: /

User-agent: BLEXBot
Disallow: /

User-agent: XoviBot
Disallow: /

User-agent: Mail.Ru
Disallow: /

User-agent: linkdexbot/2.1
Disallow: /

User-agent: woobot
Disallow: /

User-agent: MegaIndex.ru
Disallow: /

