User-agent: AhrefsBot
Disallow: /

# https://megaindex.com/crawler
User-agent: MegaIndex.ru
Disallow: /

User-agent: *
Disallow: /int/my-office
Disallow: /pl/moje-biuro
Disallow: /int/login
Disallow: /int/my-account
Disallow: /pl_en/my-account
Disallow: /pl/moje-konto
Disallow: /pl/zaloguj-sie
Disallow: /int/registration
Disallow: /pl/rejestracja
Disallow: /int/new-inquiry
Disallow: /pl/nowe-zapytanie
Disallow: /int/new-buying-auction
Disallow: /pl/nowa-aukcja-zakupowa
Disallow: /int/new-selling-auction
Disallow: /pl/nowa-aukcja-wyprzedazowa
Disallow: /_auction_attachment/*
Disallow: /_inquiry_attachment/*
Disallow: /_download/*.htm$
Disallow: /_download/*.html$
Disallow: /_attachment/*.htm$
Disallow: /_attachment/*.html$
Disallow: /_logJsError
Disallow: /pl_en/
Disallow: /pl/zapytania-stale-rejestracja-kupujacy
Disallow: /pl/zapytania-stale-rejestracja-sprzedajacy
Disallow: /*download$
Disallow: /_download/
Disallow: /pl/plik_zapytanie/
Disallow: /int/file_inquiry/
Disallow: /pl/plik_firma/
Disallow: /int/file_company/
Disallow: /pl/plik_produkt/
Disallow: /int/file_product/
Disallow: *_cyclical_purchases_attachment*
Disallow: *_item_attachment*
Disallow: /_download/
Disallow: /_attachment/
Disallow: /pl/blog/sprawozdania-finansowe
Disallow: /pl/test-page

Sitemap: https://aleo.com/sitemapindex.xml
