User-agent: *
Disallow: /administrator/
Disallow: /classes/
Disallow: /config/
Disallow: /download/
Disallow: /controllers/
Disallow: /localization/
Disallow: /log/
Disallow: /mails/
Disallow: /modules/
Disallow: /override/
Disallow: /themes/
Disallow: /tools/
Disallow: /translations/
Disallow: /webservice/
Disallow: /module/
Disallow: /autoryzacja
Disallow: /odzyskiwanie-hasla
Disallow: /moje-konto
Disallow: /dane-osobiste
Disallow: /adresy
Disallow: /adres
Disallow: /koszyk
Disallow: /zamowienie
Disallow: /historia-zamowien
Disallow: /rabaty
Disallow: /pokwitowania
Disallow: /nowe-produkty
Disallow: /mapa-strony
Disallow: /producenci
Disallow: /dostawcy
Disallow: /sklepy
Disallow: /nie-znaleziono-strony
User-agent: *
Allow: /modules/*.css$
Allow: /modules/*.js$
Allow: /modules/*.png$
Allow: /modules/*.gif$
Allow: /modules/*.jpg$
Allow: /themes/przeczytaj-pl/*.css$
Allow: /themes/przeczytaj-pl/*.js$
Allow: /themes/przeczytaj-pl/*.png$
Allow: /themes/przeczytaj-pl/*.gif$
Allow: /themes/przeczytaj-pl/*.jpg$
Allow: /module/mailalerts/actions*
