User-agent: *
Sitemap: http://art.widi.pl/1_index_sitemap.xml


Disallow: /*addresses
Disallow: /*filters=
Disallow: /authentication
Disallow: /buscar*
Disallow: /*category=
Disallow: //buscar
Disallow: /m/
Disallow: /mobile
Disallow: /cms.php?
Disallow: /search.php?
Disallow: /modules/productquestion
Disallow: /modules/productquestion
Disallow: /product.php
Disallow: /category.php
Disallow: /content/2-legalnosc
Disallow: /content/3-regulamin-sklepu
Disallow: /autenticacion
Disallow: /quick-order
Disallow: /cart.php
Disallow: /cart.php
Disallow: /*szukaj?controller=
Disallow: /*?n=
Disallow: /mails/
Disallow: /addresses.php
Disallow: /address.php
Disallow: /cart.php
Disallow: /init.php
Disallow: /my-account.php
Disallow: /order.php
Disallow: /order-slip.php
Disallow: /order-detail.php
Disallow: /order-follow.php
Disallow: /order-return.php
Disallow: /order-confirmation.php
Disallow: /password.php
Disallow: /pdf-order-return.php
Disallow: /pdf-order-slip.php
Disallow: /statistics.php
Disallow: /zoom.php
Disallow: /express-order.php
Disallow: /*orderby=
Disallow: /*orderway=
