User-agent: Baiduspider
Disallow: /

User-agent: *
Disallow: /default.asp
Disallow: /default.asp/
Disallow: /default_gb.asp
Disallow: /default_gb.asp/
Disallow: /default_f.asp
Disallow: /default_f.asp/
Disallow: /mojagielda/
Disallow: /forum/
Disallow: /pub/
Disallow: /ogloszenia/
Disallow: /ogloszenia/wywieszka.asp
Disallow: /foto/
Disallow: /artpics/
Disallow: /en/bok/
Disallow: /szukaj_.asp
Disallow: /en/szukaj_.asp
Disallow: /js/
Disallow: /img/
Disallow: /_vti_bin/
Disallow: /MSOffice/
Disallow: /nr1/
Disallow: /nr2/
Disallow: /nr3/
Disallow: /nr4/
Disallow: /nr5/
Disallow: /nr6/
Disallow: /nr7/
Disallow: /nr8/
Disallow: /content/
Disallow: /help/
Disallow: /en/adtools/adtoolsadd/
Disallow: /handlers/
Disallow: /mail/
Disallow: /admin/
Disallow: /api/
Disallow: /payments/
Disallow: /pl/ogloszenie/
Disallow: /pl/ogloszenia/kategoria/
Disallow: /pl/wyszukaj/
Disallow: /ar/adtools/
Disallow: /be/adtools/
Disallow: /bs/adtools/
Disallow: /bg/adtools/
Disallow: /cs/adtools/
Disallow: /me/adtools/
Disallow: /da/adtools/
Disallow: /de/adtools/
Disallow: /et/adtools/
Disallow: /el/adtools/
Disallow: /en/adtools/
Disallow: /es/adtools/
Disallow: /fa/adtools/
Disallow: /fr/adtools/
Disallow: /ko/adtools/
Disallow: /hi/adtools/
Disallow: /hr/adtools/
Disallow: /it/adtools/
Disallow: /he/adtools/
Disallow: /lv/adtools/
Disallow: /lt/adtools/
Disallow: /hu/adtools/
Disallow: /mk/adtools/
Disallow: /nl/adtools/
Disallow: /ja/adtools/
Disallow: /nb/adtools/
Disallow: /pl/adtools/
Disallow: /pt/adtools/
Disallow: /ro/adtools/
Disallow: /ru/adtools/
Disallow: /sq/adtools/
Disallow: /sk/adtools/
Disallow: /sl/adtools/
Disallow: /sr/adtools/
Disallow: /fi/adtools/
Disallow: /sv/adtools/
Disallow: /tr/adtools/
Disallow: /uk/adtools/
Disallow: /vi/adtools/
Disallow: /zh/adtools/


user-agent: AhrefsBot
disallow: /

User-agent: Yandex
Disallow: /

