User-agent: Rogerbot
User-agent: Exabot
User-agent: MJ12bot
User-agent: Dotbot
User-agent: Gigabot
User-agent: AhrefsBot
User-agent: BlackWidow
User-agent: HTTrack
User-agent: Wget
User-agent: Zeus
Disallow: /
User-agent: *
