User-agent: *
Disallow: /404/
Disallow: /app/
Disallow: /cgi-bin/
Disallow: /downloader/
Disallow: /js/
Disallow: /lib/
Disallow: /magento/
Disallow: /pkginfo/
Disallow: /report/
Disallow: /skin/
Disallow: /stats/
Disallow: /var/
Disallow: /catalog/product_compare/
Disallow: /catalog/category/view/
Disallow: /catalog/product/view/
Disallow: /catalogsearch/
Disallow: /sendfriend/
Disallow: /wishlist/
Disallow: /cron.php
Disallow: /cron.sh
Disallow: /error_log
Disallow: /install.php
Disallow: /LICENSE.html
Disallow: /LICENSE.txt
Disallow: /LICENSE_AFL.txt
Disallow: /STATUS.txt
Disallow: /*.php$
Disallow: /*/projekt-gotowy/*-*-
Disallow: /*/filtry/*-*-*-
Disallow: /*shop_id=
Disallow: /*ask=
Disallow: /*SID
Disallow: /*?
Disallow: /*?p=*&*
Allow: /*?p=
Allow: /*.js*
Allow: /*.css*
Allow: /*.jpg*
Allow: /*.png*

