User-agent: *
Disallow: /wp-admin/
Disallow: /wp-includes/
Disallow: /pliki-do-pobrania
Disallow: /polityka-prywatnosci
Disallow: /wyszukiwarka
Disallow: /nasze-okazje
Disallow: /wiosenna-promocja
Disallow: /biezace-informacje
Disallow: /oferta-specjalna-promocja-2
Disallow: /katalogi-i-cenniki
Disallow: /katalogi-i-cenniki/cennik-2012
Disallow: /katalogi-i-cenniki/katalog-pobierz
Disallow: /katalogi-i-cenniki/katalog
Disallow: /aktualnosci
Disallow: /polityka-prywatnosci
Disallow: /biezace-informacje
Disallow: /assets/uploads
Disallow: /ogolne-warunki-sprzedazy
Disallow: /oferta-pracy
Disallow: /informacje-o-przetwarzaniu-danych-osobowych
