User-agent: *
Disallow: /wp-admin/
Disallow: /wp-includes/
Disallow: /xmlrpc.php
Disallow: /calendar-2/action~posterboard/
Disallow: /calendar-2/action~agenda/
Disallow: /calendar-2/action~oneday/
Disallow: /calendar-2/action~month/
Disallow: /calendar-2/action~week/
Disallow: /calendar-2/action~stream/
Disallow: /calendar-3/action~posterboard/
Disallow: /calendar-3/action~agenda/
Disallow: /calendar-3/action~oneday/
Disallow: /calendar-3/action~month/
Disallow: /calendar-3/action~week/
Disallow: /calendar-3/action~stream/
Disallow: /linki/action~posterboard/
Disallow: /linki/action~agenda/
Disallow: /linki/action~oneday/
Disallow: /linki/action~month/
Disallow: /linki/action~week/
Disallow: /linki/action~stream/
