# robots.txt automaticaly generated by PrestaShop e-commerce open-source solution
# http://www.prestashop.com - http://www.prestashop.com/forums
# This file is to prevent the crawling and indexing of certain parts
# of your site by web crawlers and spiders run by sites like Yahoo!
# and Google. By telling these "robots" where not to go on your site,
# you save bandwidth and server resources.
# For more information about the robots.txt standard, see:
# http://www.robotstxt.org/wc/robots.html

User-agent: *
Allow: /

Allow: /modules/paypal/about.php
Allow: /modules/megamenuiqit//uploads/20130718right51e7ce41b76e9-s1.jpg
Allow: /modules/columnadverts/slides/tournamentchampion-s.jpg
Allow: /modules/columnadverts/slides/mcdermott.jpg
Allow: /modules/columnadverts/slides/lucky-r.jpg
Allow: /modules/columnadverts/slides/star-s.jpg
Allow: /modules/columnadverts/slides/players-s.jpg
Allow: /modules/ratyzagiel/logos/1.jpg
Allow: /modules/paypal/views/img/default_logos/PayPal_logo.svg
Allow: /modules/pluginadder/plugins.js
Allow: /modules/favoriteproducts/favoriteproducts.js
Allow: /themes/bilardshop_new/js/modules/blockcart/ajax-cart.js
Allow: /modules/simpleslideshow/jquery.eislideshow.js
Allow: /modules/manufactuterslider/manufactuterslider.js
Allow: /modules/homefeatured_mod/homefeatured_mod.js
Allow: /modules/homenewproduct/homenewproduct.js
Allow: /modules/crossselling_mod/crossselling.js
Allow: /modules/megamenuiqit/megamenuiqit.js
Allow: /modules/fblogin/js/fblogin.js
Allow: /modules/ganalytics/views/js/GoogleAnalyticActionLib.js
Allow: /modules/plpganalytics/views/js/plAnalyticsLib.js
Allow: /modules/ratyzagiel/js/zagiel.js
Allow: /modules/blockfblikebox/likebox.js
Allow: /modules/themeeditor/css/big_responsive.css
Allow: /modules/themeeditor/css/responsive.css
Allow: /modules/invoiceorbill/invoiceorbill.css
Allow: /modules/blockfblikebox/likebox.css
Allow: /modules/themeeditor/images/mobile_footer_in.png
Allow: /*orderby=
Allow: /*orderway=
Allow: /*tag=
Allow: /*id_currency=
Allow: /*search_query=
Allow: /*back=
Allow: /*utm_source=
Allow: /*utm_medium=
Allow: /*utm_campaign=
Allow: /*n=
Allow: /*modules/*.jpg
Allow: /*modules/*.png
Allow: /*modules/*.gif
Allow: /*img/
Allow: /*images/
Allow: /modules/simpleslideshow/slides/saloon-1.jpg
Allow: /modules/simpleslideshow/slides/slider3-good.jpg
Allow: /modules/simpleslideshow/slides/baner-pzsiba3.jpg

# Private pages
Disallow: /*orderby=
Disallow: /*orderway=
Disallow: /*tag=
Disallow: /*id_currency=
Disallow: /*search_query=
Disallow: /*back=
Disallow: /*utm_source=
Disallow: /*utm_medium=
Disallow: /*utm_campaign=
Disallow: /*n=
Disallow: /*controller=addresses
Disallow: /*controller=address
Disallow: /*controller=authentication
Disallow: /*controller=cart
Disallow: /*controller=discount
Disallow: /*controller=footer
Disallow: /*controller=get-file
Disallow: /*controller=header
Disallow: /*controller=history
Disallow: /*controller=identity
Disallow: /*controller=images.inc
Disallow: /*controller=init
Disallow: /*controller=my-account
Disallow: /*controller=order
Disallow: /*controller=order-opc
Disallow: /*controller=order-slip
Disallow: /*controller=order-detail
Disallow: /*controller=order-follow
Disallow: /*controller=order-return
Disallow: /*controller=order-confirmation
Disallow: /*controller=pagination
Disallow: /*controller=password
Disallow: /*controller=pdf-invoice
Disallow: /*controller=pdf-order-return
Disallow: /*controller=pdf-order-slip
Disallow: /*controller=product-sort
Disallow: /*controller=search
Disallow: /*controller=statistics
Disallow: /*controller=attachment
Disallow: /*controller=guest-tracking
# Directories
Disallow: /*classes/
Disallow: /*config/
Disallow: /*download/
Disallow: /*mails/
Disallow: /*modules/
Disallow: /*translations/
Disallow: /*tools/

