# This file is automatically generated, do not edit this file manually
#
#
User-agent: *
Disallow: /style/
Disallow: /javascript/
Disallow: /szukaj/
Disallow: /rozrywka/szukaj/
Disallow: /pdf/

#
User-agent: Enrise-Webcrawler
Disallow: /style/
Disallow: /javascript/
Disallow: /szukaj/
Disallow: /rozrywka/szukaj/
Disallow: /pdf/

