User-agent: *
Disallow: /cgi-bin/
Disallow: /wp-admin/
Disallow: /wp-includes/
Disallow: /wp-content/plugins/
Disallow: /wp-content/cache/
Disallow: /trackback/
Disallow: /comments/
Disallow: */trackback/
Disallow: */comments/
Disallow: /*?
Disallow: /feed
Disallow: /tag/
Disallow: /page/
Disallow: /2011/
Disallow: /2012/
Disallow: /poradnik/
Disallow: /files/
Disallow: /form/
Disallow: /skup/
Disallow: /kontakt/
