# robots.txt automaticaly generated by PrestaShop e-commerce open-source solution
# http://www.prestashop.com - http://www.prestashop.com/forums

# This file is to prevent the crawling and indexing of certain parts
# of your site by web crawlers and spiders run by sites like Yahoo!
# and Google. By telling these "robots" where not to go on your site,
# you save bandwidth and server resources.

# For more information about the robots.txt standard, see:
# http://www.robotstxt.org/wc/robots.html

User-agent: *
# Directories
Disallow: /bodybooster.pl/classes/
Disallow: /bodybooster.pl/config/
Disallow: /bodybooster.pl/download/
Disallow: /bodybooster.pl/mails/
Disallow: /bodybooster.pl/modules/
Disallow: /bodybooster.pl/translations/
Disallow: /bodybooster.pl/tools/
Disallow: /bodybooster.pl/lang-pl/
# Files
Disallow: /bodybooster.pl/addresses.php
Disallow: /bodybooster.pl/address.php
Disallow: /bodybooster.pl/authentication.php
Disallow: /bodybooster.pl/cart.php
Disallow: /bodybooster.pl/discount.php
Disallow: /bodybooster.pl/footer.php
Disallow: /bodybooster.pl/get-file.php
Disallow: /bodybooster.pl/header.php
Disallow: /bodybooster.pl/history.php
Disallow: /bodybooster.pl/identity.php
Disallow: /bodybooster.pl/images.inc.php
Disallow: /bodybooster.pl/init.php
Disallow: /bodybooster.pl/my-account.php
Disallow: /bodybooster.pl/order.php
Disallow: /bodybooster.pl/order-opc.php
Disallow: /bodybooster.pl/order-slip.php
Disallow: /bodybooster.pl/order-detail.php
Disallow: /bodybooster.pl/order-follow.php
Disallow: /bodybooster.pl/order-return.php
Disallow: /bodybooster.pl/order-confirmation.php
Disallow: /bodybooster.pl/pagination.php
Disallow: /bodybooster.pl/password.php
Disallow: /bodybooster.pl/pdf-invoice.php
Disallow: /bodybooster.pl/pdf-order-return.php
Disallow: /bodybooster.pl/pdf-order-slip.php
Disallow: /bodybooster.pl/product-sort.php
Disallow: /bodybooster.pl/search.php
Disallow: /bodybooster.pl/statistics.php
Disallow: /bodybooster.pl/attachment.php
Disallow: /bodybooster.pl/guest-tracking
Disallow: /bodybooster.pl/*orderby=
Disallow: /bodybooster.pl/*orderway=
Disallow: /bodybooster.pl/*tag=
Disallow: /bodybooster.pl/*id_currency=
Disallow: /bodybooster.pl/*search_query=
Disallow: /bodybooster.pl/*id_lang=
Disallow: /bodybooster.pl/*back=
Disallow: /bodybooster.pl/*utm_source=
Disallow: /bodybooster.pl/*utm_medium=
Disallow: /bodybooster.pl/*utm_campaign=
Disallow: /bodybooster.pl/*n=
# Sitemap


