User-agent: *
User-agent: Googlebot
Disallow: /cgi-bin
Disallow: /wp-admin$
Disallow: /wp-admin*/
Disallow: /author/admin$
Disallow: /author/admin/
Disallow: /archives$
Disallow: /archives/
Disallow: /category/uncategorised$
Disallow: /category/uncategorised/
Disallow: /tag$
Disallow: /tag/
Disallow: /tag/*
Disallow: /page$
Disallow: /page/
Disallow: */page/
Disallow: */page/*
Disallow: /comments/feed
Disallow: /comments/feed/
Disallow: /2015$
Disallow: /2016$
Disallow: /print$
Disallow: /print/
Disallow: /*?s=*
Disallow: /wp-login.php?*
Allow: /wp-content/themes/smd2016/*.css
Allow: /wp-content/themes/smd2016/*/*.css
Allow: /wp-content/themes/smd2016/js/*
Allow: /wp-content/themes/smd2016/*/*/front*
Allow: /wp-includes/js/wp-em*.js
Allow: /wp-includes/js/*-reply.min.js
Allow: /wp-includes/js/jq*/*.js
Allow: /wp-content/uploads/*
Allow: /*.js
Allow: /*.css
