User-Agent: *
Disallow: /ar_SA
Disallow: /eu_ES
Disallow: /bg_BG
Disallow: /ca_AD
Disallow: /ca_ES
Disallow: /zh_CN
Disallow: /zh_TW
Disallow: /cs_CZ
Disallow: /nl_NL
Disallow: /en_NZ
Disallow: /en_AU
Disallow: /en_US
Disallow: /en_GB
Disallow: /en_HQ
Disallow: /et_EE
Disallow: /fi_FI
Disallow: /fr_FR
Disallow: /gl_ES
Disallow: /de_DE
Disallow: /el_GR
Disallow: /iw_IL
Disallow: /hi_IN
Disallow: /hu_HU
Disallow: /in_ID
Disallow: /it_IT
Disallow: /ja_JP
Disallow: /ko_KR
Disallow: /nb_NO
Disallow: /fa_IR
Disallow: /pl_PL
Disallow: /pt_BR
Disallow: /pt_PT
Disallow: /ru_RU
Disallow: /sk_SK
Disallow: /es_ES
Disallow: /es_MX
Disallow: /es_CO
Disallow: /sv_SE
Disallow: /tr_TR
Disallow: /uk_UA
Disallow: /vi_VN
Disallow: /th_TH
Disallow: /en_NZ
Disallow: /story-detail
Disallow: /news-detail
Allow: /story-detail/+
Allow: /news-detail/+
Sitemap: http://www.carel.pl/sitemap.xml
