User-agent: *
Disallow: /calendar/action~posterboard/
Disallow: /calendar/action~agenda/
Disallow: /calendar/action~oneday/
Disallow: /calendar/action~month/
Disallow: /calendar/action~week/
Disallow: /calendar/action~stream/
Disallow: /grafik-zajec/action~posterboard/
Disallow: /grafik-zajec/action~agenda/
Disallow: /grafik-zajec/action~oneday/
Disallow: /grafik-zajec/action~month/
Disallow: /grafik-zajec/action~week/
Disallow: /grafik-zajec/action~stream/
Disallow: /calendar-2/action~posterboard/
Disallow: /calendar-2/action~agenda/
Disallow: /calendar-2/action~oneday/
Disallow: /calendar-2/action~month/
Disallow: /calendar-2/action~week/
Disallow: /calendar-2/action~stream/
Disallow: /calendar-2/action~undefined/
Disallow: /calendar-2/action~http:/
Disallow: /calendar-2/action~default/
Disallow: /*controller=ai1ec_exporter_controller*
