User-agent: *
Disallow: /html/
Disallow: /ar/
Disallow: /dlhpoczta/
Disallow: /ankieta/
Disallow: /lexport/
Disallow: /kontener/
Disallow: /newsadm/
Disallow: /fpc/
Disallow: /oldimages/
Disallow: /oldmedia/
Disallow: /oldmedia1/
Disallow: /pic/
Disallow: /produkty/
Disallow: /sfset/
Disallow: /silnik/
Disallow: /squidtaild/
Disallow: /wm/
Disallow: /wwwother/
Allow: /
