User-agent: *
Disallow: /author/gogler/
Disallow: /polityka-plikow-cookies/
Disallow: /cut-log.html
Disallow: /construction-timber.html
Disallow: /structure-timber.html
Disallow: /products.html?lang=en
Disallow: /brykieciarka-adelmann-500kgh.html
Disallow: /biomass.html?lang=en
Disallow: /square-sawn-timber.html
Disallow: /slat-timber-beams.html
Disallow: /rough-sawn-timber.html
Disallow: /structure-timber.html?lang=en
Disallow: /secondhand-machines.html?lang=en
Disallow: /send-an-offer-inquiry.html
Disallow: /slat-timber-beams.html?lang=en
Disallow: /rough-sawn-timber.html?lang=en
Disallow: /send-an-offer-inquiry.html?lang=en
Disallow: /linia-do-obrabiania-krawedzi-blatow-hmettali.html
Disallow: /automatyczna-linia-lakiernicza-barberan-cena-248000-.html
Disallow: /strugarka-6cio-glowicowa-costa-cena--11500-.html
Disallow: /linia-optymalizacyjna-do-wycinania-wad-z-drewna-video-scanner.html
Disallow: /linia-odpylajaca-system-gaszenia-firefly-cena--34000-.html
Disallow: /linia-do-kopiowania-elemntow-krzywoliniowych-pbacci-cena--36000-.html
