User-agent: *
Disallow: /cgi-bin/
Disallow: /test/
Disallow: /ikkes/
Disallow: /artworks/
Disallow: /catalog/admin/
Disallow: /catalog/css/
Disallow: /catalog/download/
Disallow: /catalog/ext/
Disallow: /catalog/fonts/
Disallow: /catalog/_fpdf/
Disallow: /catalog/images/pending/
Disallow: /catalog/images/mail/
Disallow: /catalog/images/icepay/
Disallow: /catalog/images/estimatedshippingBox/
Disallow: /catalog/images/default/
Disallow: /catalog/images/work/
Disallow: /catalog/images/cart/
Disallow: /catalog/images/custom/
Disallow: /catalog/images/uploads/
Disallow: /catalog/includes/
Disallow: /catalog/jscolor/
Disallow: /catalog/jsselect/
Disallow: /catalog/jsscroll/
Disallow: /catalog/lightbox/
Disallow: /catalog/profiles/
Disallow: /catalog/pub/
Disallow: /catalog/working/
Disallow: /catalog/mmenu/
Disallow: /catalog/reviews.php
Disallow: /catalog/create_account.php

