User-agent: *
Allow: /showPrivacy
Disallow: /stAvailabilityFrontend/showAddOverlay
Disallow: /stDeliveryFrontend/*
Disallow: /stQuestionFrontend/showAddOverlay
Disallow: /stNavigationFrontend
Disallow: /stAccessoriesFrontend/*
Disallow: /review/showAddOverlay
Disallow: /question/showAddOverlay
Disallow: /productsCompare
Disallow: /productsCompare/
Disallow: /product_options
Disallow: /product_options/
Disallow: /product_options/*
Disallow: */recommendProducts/*
Disallow: /*.php$
Disallow: /paypal
Disallow: /basket/*
Disallow: /basket/
Disallow: /basket
Disallow: /files/*
Disallow: /files/
Disallow: /files
Disallow: /404_links.txt
Disallow: /index.php/*
Disallow: /index.php*
Disallow: /index.php/basket
Disallow: /index.php/basket/
Disallow: /index.php/user/loginUser
Disallow: */long/name/*
Disallow: /search
Disallow: /currency
Disallow: /producer
