# robots.txt automaticaly generated by PrestaShop e-commerce open-source solution
# http://www.prestashop.com - http://www.prestashop.com/forums
# This file is to prevent the crawling and indexing of certain parts
# of your site by web crawlers and spiders run by sites like Yahoo!
# and Google. By telling these "robots" where not to go on your site,
# you save bandwidth and server resources.
# For more information about the robots.txt standard, see:
# http://www.robotstxt.org/robotstxt.html
User-agent: *
# Allow Directives
Allow: */modules/*.css
Allow: */modules/*.js
# Private pages
Disallow: /*?orderby=
Disallow: /*?orderway=
Disallow: /*?tag=
Disallow: /*?id_currency=
Disallow: /*?search_query=
Disallow: /*?back=
Disallow: /*?n=
Disallow: /*&orderby=
Disallow: /*&orderway=
Disallow: /*&tag=
Disallow: /*&id_currency=
Disallow: /*&search_query=
Disallow: /*&back=
Disallow: /*&n=
Disallow: /*controller=addresses
Disallow: /*controller=address
Disallow: /*controller=authentication
Disallow: /*controller=cart
Disallow: /*controller=discount
Disallow: /*controller=footer
Disallow: /*controller=get-file
Disallow: /*controller=header
Disallow: /*controller=history
Disallow: /*controller=identity
Disallow: /*controller=images.inc
Disallow: /*controller=init
Disallow: /*controller=my-account
Disallow: /*controller=order
Disallow: /*controller=order-opc
Disallow: /*controller=order-slip
Disallow: /*controller=order-detail
Disallow: /*controller=order-follow
Disallow: /*controller=order-return
Disallow: /*controller=order-confirmation
Disallow: /*controller=pagination
Disallow: /*controller=password
Disallow: /*controller=pdf-invoice
Disallow: /*controller=pdf-order-return
Disallow: /*controller=pdf-order-slip
Disallow: /*controller=product-sort
Disallow: /*controller=search
Disallow: /*controller=statistics
Disallow: /*controller=attachment
Disallow: /*controller=guest-tracking
Disallow: /fototapeta-6-Krajobraz.html
Disallow: /fototapeta-33-Kwiaty.html
Disallow: /fototapeta-7-Owoce.html
Disallow: /fototapeta-15-Zwierzeta.html
Disallow: /fototapeta-34-Tekstura.html
Disallow: /fototapeta-5-Kawa.html
Disallow: /fototapeta-35-Abstrakcja.html
Disallow: /fototapeta-36-Znane-miejsca.html
Disallow: /fototapeta-37-Sport.html
Disallow: /fototapeta-38-Architektura.html
Disallow: /fototapeta-39-Kosmos.html
Disallow: /fototapeta-40-Dla-dzieci.html
Disallow: /fototapeta-22-gory.html
Disallow: /fototapeta-26-lasy.html
Disallow: /fototapeta-27-jeziora.html
Disallow: /fototapeta-28-niebo.html
Disallow: /fototapeta-29-pustynia.html
Disallow: /fototapeta-31-z-lotu-ptaka.html
Disallow: /fototapeta-32-plaza.html
# Directories
Disallow: */classes/
Disallow: */config/
Disallow: */download/
Disallow: */mails/
Disallow: */modules/
Disallow: */translations/
Disallow: */tools/
# Files
Disallow: /*odzyskiwanie-hasla
Disallow: /*adres
Disallow: /*adresy
Disallow: /*logowanie
Disallow: /*koszyk
Disallow: /*rabaty
Disallow: /*historia-zamowien
Disallow: /*dane-osobiste
Disallow: /*moje-konto
Disallow: /*sledzenie-zamowienia
Disallow: /*pokwitowania
Disallow: /*zamowienie
Disallow: /*szukaj
Disallow: /*szybkie-zakupy
Disallow: /*sledzenie-zamowienia-gosc
Disallow: /*potwierdzenie-zamowienia

