User-Agent: *
Disallow: /content/3-regulamin*
Disallow: /order.php*
Disallow: /authentication.php*
Disallow: /search.php*
Disallow: /szybkie-zakupy*
Disallow: /category.php*
Disallow: /content/4-o-nas
Disallow: /content/100-historia
Disallow: /content/101-wladze-spolki
Disallow: /content/102-relacje-inwestorskie
Disallow: /content/103-wspolpraca-i-partnerstwo
Disallow: /content/104-organizacje-biznesowe
Disallow: /content/105-klienci-i-rekomendacje
Disallow: /content/7-krok-po-kroku
Disallow: /content/106-jak-czytac-legende
Disallow: /content/5-platnosci
Disallow: /content/1-dostawa
Disallow: /content/3-regulamin
Disallow: /content/26-dobrewina-pl
Disallow: /index.php*
Disallow: /password.php*
Disallow: /_wadmin/
Disallow: /cms.php
Disallow: /*orderby*
Disallow: /*searchInAllCategories*
Disallow: /sklepy.php?miasto=*
Disallow: /news.php
Disallow: /*searchWina=*
Disallow: /*shopgate_redirect=*
