User-agent: *
Disallow: /cart.php
Disallow: /order.php
Disallow: /my-account.php
Disallow: /history.php
Disallow: /addresses.php
Disallow: /identity.php
Disallow: /discount.php
Disallow: /authentication.php
Disallow: /pdf-invoice.php
Disallow: /classes/
Disallow: /config/
Disallow: /download/
Disallow: /mails/
Disallow: /modules/
Disallow: /themes/
Disallow: /translations/
Disallow: /tools/
