User-agent: *
Disallow: /*wersja-lustrzana
Disallow: /*zamowienie=tak
Disallow: /*sortuj
Disallow: /*.ajax
Disallow: /_files/
Disallow: /WebAdmin/
Disallow: /WebAdminExt/
Disallow: /admin/
Disallow: /upload/
Disallow: /themes/
Disallow: /*.pdf
Disallow: /*.swf
Disallow: /error-happened
Disallow: /*/zamowienie
Disallow: /schowek
Disallow: /*page=
Disallow: /kondygnacje=*
Disallow: /garaz=*
Disallow: /styl=*
Disallow: /technologia=*
Disallow: /dach_rodzaj=*
Disallow: /piwnica=*
Disallow: /*kondygnacje
Disallow: /*dach
Disallow: /*piwnica
Allow: /
