# robots.txt automaticaly generated by PrestaShop e-commerce open-source solution
# http://www.prestashop.com - http://www.prestashop.com/forums
# This file is to prevent the crawling and indexing of certain parts
# of your site by web crawlers and spiders run by sites like Yahoo!
# and Google. By telling these "robots" where not to go on your site,
# you save bandwidth and server resources.
# For more information about the robots.txt standard, see:
# http://www.robotstxt.org/wc/robots.html
User-agent: Googlebot-Image
Disallow:
User-agent: *
# Private pages
Allow: /szukaj?tag=
Allow: /modules/themconf/config.css
Allow: /modules/twitterfeed/img/twitt.png
Allow: /themes/reviver/css/modules/blocksearch/img/search-btn.png
Allow: /themes/reviver/css/modules/blockcart/img/cart-img.png
Allow: /modules/overrider/img/nexti.png
Allow: /modules/overrider/img/previ.png
Allow: /themes/reviver/css/modules/blocklayered/delete.gif
Allow: /modules/overrider/images/glyphicons_halflings.svg
Allow: /modules/plblog/CaptchaSecurityImages.php?width=65&height=20&characters=4
Allow: /modules/revsliderprestashop/rs-plugin/assets/loader.gif
Allow: /modules/revsliderprestashop/rs-plugin/assets/bullet.png
Allow: /modules/revsliderprestashop/uploads/664027_8772066rajstopy.jpg
Allow: /modules/revsliderprestashop/rs-plugin/assets/timer.png
Allow: /modules/revsliderprestashop/uploads/2589404galanteria-kamea.jpg
Allow: /modules/revsliderprestashop/images/dummy.png
Allow: /modules/revsliderprestashop/rs-plugin/assets/large_left.png
Allow: /modules/revsliderprestashop/rs-plugin/assets/large_right.png
Allow: /modules/twitterfeed/connect.php
Allow: /modules/overrider/fonts/glyphicons-regular.woff
Allow: /modules/overrider/fonts/glyphicons-regular.ttf
Allow: /modules/overrider/fonts/glyphicons-regular.svg
Disallow: /*orderby=
Disallow: /*orderway=
Disallow: /*tag=
Disallow: /*id_currency=
Disallow: /*search_query=
Disallow: /*back=
Disallow: /*n=
Disallow: /*controller=addresses
Disallow: /*controller=address
Disallow: /*controller=authentication
Disallow: /*controller=cart
Disallow: /*controller=discount
Disallow: /*controller=footer
Disallow: /*controller=get-file
Disallow: /*controller=header
Disallow: /*controller=history
Disallow: /*controller=identity
Disallow: /*controller=images.inc
Disallow: /*controller=init
Disallow: /*controller=my-account
Disallow: /*controller=order
Disallow: /*controller=order-opc
Disallow: /*controller=order-slip
Disallow: /*controller=order-detail
Disallow: /*controller=order-follow
Disallow: /*controller=order-return
Disallow: /*controller=order-confirmation
Disallow: /*controller=pagination
Disallow: /*controller=password
Disallow: /*controller=pdf-invoice
Disallow: /*controller=pdf-order-return
Disallow: /*controller=pdf-order-slip
Disallow: /*controller=product-sort
Disallow: /*controller=search
Disallow: /*controller=tag
Disallow: /*controller=statistics
Disallow: /*controller=attachment
Disallow: /*controller=guest-tracking
# Directories
Disallow: */classes/
Disallow: */config/
Disallow: */download/
Disallow: */mails/
Disallow: */modules/
Disallow: */translations/
Disallow: */tools/
# Files
Disallow: /odzyskiwanie-hasla
Disallow: /adres
Disallow: /adresy
Disallow: /logowanie
Disallow: /koszyk
Disallow: /rabaty
Disallow: /historia-zamowien
Disallow: /dane-osobiste
Disallow: /moje-konto
Disallow: /sledzenie-zamowienia
Disallow: /pokwitowania
Disallow: /zamowienie
Disallow: /szukaj
Disallow: /szybkie-zakupy
Disallow: /sledzenie-zamowienia-gosc
Disallow: /potwierdzenie-zamowienia
Disallow: /tag

