# robots.txt automaticaly generated by PrestaShop e-commerce open-source solution
# http://www.prestashop.com - http://www.prestashop.com/forums
# This file is to prevent the crawling and indexing of certain parts
# of your site by web crawlers and spiders run by sites like Yahoo!
# and Google. By telling these "robots" where not to go on your site,
# you save bandwidth and server resources.
# For more information about the robots.txt standard, see:
# http://www.robotstxt.org/wc/robots.html
User-agent: *
# Private pages
Disallow: /*orderby=
Disallow: /*orderway=
Disallow: /*tag=
Disallow: /*id_currency=
Disallow: /*search_query=
Disallow: /*back=
Disallow: /*utm_source=
Disallow: /*utm_medium=
Disallow: /*utm_campaign=
Disallow: /*n=
Disallow: /*controller=addresses
Disallow: /*controller=address
Disallow: /*controller=authentication
Disallow: /*controller=cart
Disallow: /*controller=discount
Disallow: /*controller=footer
Disallow: /*controller=get-file
Disallow: /*controller=header
Disallow: /*controller=history
Disallow: /*controller=identity
Disallow: /*controller=images.inc
Disallow: /*controller=init
Disallow: /*controller=my-account
Disallow: /*controller=order
Disallow: /*controller=order-opc
Disallow: /*controller=order-slip
Disallow: /*controller=order-detail
Disallow: /*controller=order-follow
Disallow: /*controller=order-return
Disallow: /*controller=order-confirmation
Disallow: /*controller=pagination
Disallow: /*controller=password
Disallow: /*controller=pdf-invoice
Disallow: /*controller=pdf-order-return
Disallow: /*controller=pdf-order-slip
Disallow: /*controller=product-sort
Disallow: /*controller=search
Disallow: /*controller=statistics
Disallow: /*controller=attachment
Disallow: /*controller=guest-tracking
# Directories
Disallow: /*classes/
Disallow: /*config/
Disallow: /*download/
Disallow: /*mails/
Disallow: /*modules/
Disallow: /*translations/
Disallow: /*tools/
# Files
Disallow: /*pl/password-recovery
Disallow: /*pl/address
Disallow: /*pl/addresses
Disallow: /*pl/authentication
Disallow: /*pl/cart
Disallow: /*pl/discount
Disallow: /*pl/order-history
Disallow: /*pl/identity
Disallow: /*pl/my-account
Disallow: /*pl/order-follow
Disallow: /*pl/order-slip
Disallow: /*pl/order
Disallow: /*pl/search
Disallow: /*pl/quick-order
Disallow: /*pl/guest-tracking


Allow: /modules/blockbestsellers/*.css
Allow: /modules/blockpermanentlinks/*.css
Allow: /modules/blockviewed/*.css
Allow: /modules/blockcontact/*.css
Allow: /modules/blockcart/*.css
Allow: /modules/blockspecials/*.css
Allow: /modules/blockcurrencies/*.css
Allow: /modules/blockmyaccountfooter/*.css
Allow: /modules/blocknewproducts/*.css
Allow: /modules/blockuserinfo/*.css
Allow: /modules/blocklanguages/*.css
Allow: /modules/blocktags/*.css
Allow: /modules/blocksearch/*.css

Allow: /modules/favoriteproducts/*.css
Allow: /modules/homefeatured/*.css

Allow: /modules/blocknewsletter/*.css
Allow: /modules/mailalerts/*.css
Allow: /modules/productcomments/*.css
Allow: /modules/productcomments/*.js
Allow: /modules/crossselling/*.css
Allow: /modules/blocktopmenu/css/*.css
Allow: /modules/homeslider/*.css
Allow: /modules/blockreinsurance/*.css
Allow: /modules/blockcart/*.js
Allow: /modules/favoriteproducts/*.js
Allow: /modules/favoriteproducts/*.gif
Allow: /themes/default/js/tools/*.js
Allow: /modules/askproduct/*.css
Allow: /modules/askproduct/*.js

Allow: /modules/blocktopmenu/js/*.js
Allow: /modules/homeslider/js/*.js
Allow: /modules/blocksearch/img/*.png
Allow: /modules/blockuserinfo/img/icon/*.gif
Allow: /modules/blocktopmenu/img/*.png
Allow: /modules/blockadvertising/*.jpg
Allow: /modules/blockcategories/img/*.png
Allow: /modules/blockcms/img/*.png
Allow: /modules/blocknewsletter/img/icon/*.png
Allow: /modules/blocknewsletter/img/*.png
Allow: /modules//homeslider/images/*.jpg
Allow: /modules/homefeatured/img/*.png
Allow: /modules/blockreinsurance/img/*.gif
Allow: /modules/blockreinsurance/img/*.jpg

Allow: /modules//homeslider/images/*.png
Allow: /?controller=cart&ajax=true&token=b53ec13100320a19cde9c741c6f26353&_=1412687268513
Allow: /modules/homeslider/*.png
