User-agent: *
Disallow:
Disallow: /cms/dzial/82/maecenas-sed-diam-eget-risus-varius-blandit-sit-amet-non-magna-etiam-porta-sem

Sitemap: http://www.ekomeritum.pl/sitemap.xml

Disallow: /referencje/szczegoly/
Disallow: /oplaty-produktowe.html
Disallow: /ocena-oddzialywania-na-srodowisko.html
Disallow: /gospodarka-opakowaniowa.html
Disallow: /operat-ochrony-powietrza.html
Disallow: /targi,informacje.html
Disallow: /strony/7-Kontakt.html
Disallow: /oplaty-za-korzystanie-ze-srodowiska.html
Disallow: /badanie-wody.html
Disallow: /strony/5-Obowiazki-podmiotow-w-zakresie-ochrony-srodowiska.html
Disallow: /pozwolenie-wodnoprawne.html
Disallow: /pozwolenie-na-emisje.html
Disallow: /pozwolenie-na-wytwarzanie-odpadow.html
Disallow: /strony/2-O-nas.html
Disallow: /slownik.html
Disallow: /raport-oddzialywania-na-srodowisko.html

Disallow: /admin/
Disallow: /artykuly/lista/page-2
Disallow: /artykuly/lista/page-3
Disallow: /artykuly/lista/page-4
Disallow: /cms/dzial/148/test
Disallow: /cms/dzial/166/chmurki
Disallow: /cms/dzial/116/pozwolenie-zintegrowane
Disallow: /cms/dzial/150/test-2
Disallow: /referencje/szczegoly/120/nasze-referencje
Disallow: /referencje/szczegoly/69/nasze-referencje
Disallow: /referencje/szczegoly/100/nasze-referencje
Disallow: /cms/dzial/168/podstrona-str-8
Disallow: /cms/dzial/163/ffffffffffffffffffffffffffffffffffffffff-rrrrrrrrrrrrrrrrrr-yyyyyyyyyyyyyyyy
Disallow: /cms/dzial/79/fusce-etiam-fermentum-loremy
Disallow: /cms/dzial/80/maecenas-faucibus-mollis-interdum
Disallow: /cms/dzial/83/pellentesque-sed-diam-eget-risus-varius-blandit-sit-amet-non-magna
Disallow: /referencje/szczegoly/118/nasze-referencje
Disallow: /referencje/szczegoly/73/nasze-referencje
Disallow: /referencje/szczegoly/67/nasze-referencje
Disallow: /referencje/szczegoly/158/nasze-referencje
Disallow: /referencje/szczegoly/114/nasze-referencje
Disallow: /referencje/szczegoly/56/nasze-referencje
Disallow: /referencje/szczegoly/35/nasze-referencje
Disallow: /referencje/szczegoly/127/nasze-referencje
Disallow: /referencje/szczegoly/30/nasze-referencje
Disallow: /referencje/szczegoly/58/nasze-referencje
Disallow: /referencje/szczegoly/50/nasze-referencje
Disallow: /referencje/szczegoly/84/nasze-referencje
Disallow: /referencje/szczegoly/148/nasze-referencje

Disallow: /artykuly
Disallow: /artykuly/szczegoly/70/sprawdzanie-instalacji-tak-niezbedne
Disallow: /artykuly/szczegoly/75/wzrosna-rachunki-za-wywoz-smieci
Disallow: /artykuly/szczegoly/81/zalety-biowegla
Disallow: /artykuly/szczegoly/86/sytuacja-klimatyczna-polski-na-tle-innych-krajow
Disallow: /artykuly/szczegoly/80/kominek-a-ochrona-srodowiska
Disallow: /artykuly/szczegoly/82/pomiar-halasu-w-miejscu-pracy---jak-czesto
Disallow: /artykuly/szczegoly/98/dzis-dzien-ziemi
Disallow: /artykuly/szczegoly/73/nowelizacja-ustawy-dotyczacej-utrzymania-czystosci-w-gminach
Disallow: /artykuly/szczegoly/87/4-dzialania-ktore-moga-pomoc-w-ochronie-powietrza
Disallow: /artykuly/szczegoly/71/odprowadzanie-sciekow-a-strona-prawna
Disallow: /artykuly/szczegoly/72/przekroczenia-norm-jakosci-powietrza
Disallow: /artykuly/szczegoly/85/nadzor-inwestorski-w-pracach-budowlanych---na-czym-polega
Disallow: /artykuly/szczegoly/78/powracajacy-problem-zanieczyszczenia
Disallow: /artykuly/szczegoly/79/jak-przygotowac-sprawozdanie-odpadowe
Disallow: /artykuly/szczegoly/92/skad-sie-biora-pyly-w-miejscu-pracy
Disallow: /artykuly/szczegoly/76/czy-przemysl-moze-ochraniac-srodowisko
Disallow: /artykuly/szczegoly/94/firmy-transportujace-odpady-protestuja
Disallow: /artykuly/szczegoly/74/smog-opanowuje-polskie-miasta
Disallow: /artykuly/szczegoly/88/kolej-bedzie-przeprowadzac-pomiary-halasu
Disallow: /artykuly/szczegoly/95/odsiarczanie-biogazu---jak-to-sie-robi
Disallow: /artykuly/szczegoly/84/spelniane-normy-w-miejscu-pracy
Disallow: /artykuly/szczegoly/77/pozytywny-nawyk-segregacji
Disallow: /artykuly/szczegoly/90/oczyszczanie-sciekow-ultrafioletem---alternatywa-dla-chloru
Disallow: /artykuly/szczegoly/69/badanie-odpadow
Disallow: /artykuly/szczegoly/97/oplaty-za-wode-i-scieki-wzrosna
Disallow: /artykuly/szczegoly/91/miliony-ofiar-zanieczyszczonego-powietrza
Disallow: /artykuly/szczegoly/96/haloizyt---nowy-sposob-na-scieki-i-zanieczyszczenia
Disallow: /artykuly/szczegoly/93/separatory---czym-sa-i-do-czego-sluza
Disallow: /artykuly/szczegoly/83/5-zagrozen-jakie-niesie-ze-soba-smog
Disallow: /artykuly/szczegoly/89/grunt-to-dobry-grunt-kilka-slow-o-badaniach-gruntu
Disallow: /artykuly/szczegoly/6/pozwolenia-wodnoprawne
Disallow: /artykuly/szczegoly/22/oplaty-srodowiskowe
Disallow: /artykuly/szczegoly/30/kompleksowe-uslugi
Disallow: /artykuly/szczegoly/38/odsiarczanie-biogazu
Disallow: /artykuly/szczegoly/18/obowiazki-srodowiskowe
Disallow: /artykuly/szczegoly/7/pomiary-halasu
Disallow: /artykuly/szczegoly/11/ewidencja-odpadow
Disallow: /artykuly/szczegoly/23/audyty-srodowiskowe
Disallow: /artykuly/szczegoly/15/dokumentacja-hydrogeologiczna
Disallow: /artykuly/szczegoly/5/pozwolenie-zintegrowane
Disallow: /artykuly/szczegoly/21/badania-gruntu
Disallow: /artykuly/szczegoly/1/operat-ochrony-powietrza
Disallow: /artykuly/szczegoly/32/montaz-kroccow-pomiarowych
Disallow: /artykuly/szczegoly/53/szczelne-instalacje-przemyslowe
Disallow: /artykuly/szczegoly/14/projekt-robot-geologicznych
Disallow: /artykuly/szczegoly/42/znaczenie-uslug-konsultingowych
Disallow: /artykuly/szczegoly/13/redukcja-emisji-lzo
Disallow: /artykuly/szczegoly/29/wlasciwe-warunki-pracy
Disallow: /artykuly/szczegoly/26/badanie-szczelnosci-instalacji
Disallow: /artykuly/szczegoly/9/karta-informacyjna-przedsiewziecia
Disallow: /artykuly/szczegoly/20/kontrola-dzialalnosci-gospodarczej
Disallow: /artykuly/szczegoly/28/przeglady-okresowe-instalacji
Disallow: /artykuly/szczegoly/8/monitorowanie-szczelnosci-instalacji
Disallow: /artykuly/szczegoly/62/aktualizacje-decyzji-srodowiskowych
Disallow: /artykuly/szczegoly/68/czad-jako-cichy-zabojca
Disallow: /artykuly/szczegoly/16/badanie-wody-i-sciekow
Disallow: /artykuly/szczegoly/50/emisja-lzo-przez-przedsiebiorstwa
Disallow: /artykuly/szczegoly/25/badania-wody-i-sciekow
Disallow: /artykuly/szczegoly/37/ocena-oddzialywania-na-srodowisko
Disallow: /artykuly/szczegoly/35/decyzja-o-srodowiskowych-uwarunkowaniach
Disallow: /artykuly/szczegoly/2/wymagania-srodowiskowe-dla-firm
Disallow: /artykuly/szczegoly/65/wielki-krok-dla-planety
Disallow: /artykuly/szczegoly/43/nadzor-inwestorski-nad-instalacjami
Disallow: /artykuly/szczegoly/36/pozwolenia-przy-rozbudowie-inwestycji
Disallow: /artykuly/szczegoly/54/audyty-srodowiskowe-dla-firm
Disallow: /artykuly/szczegoly/27/miedzynarodowy-dzien-matki-ziemi
Disallow: /artykuly/szczegoly/61/warunki-na-stanowiskach-pracy
Disallow: /artykuly/szczegoly/64/badanie-gruntu-czy-konieczne
Disallow: /artykuly/szczegoly/24/zezwolenie-na-transport-odpadow
Disallow: /artykuly/szczegoly/52/pobieranie-probek-wod-podziemnych
Disallow: /artykuly/szczegoly/47/szkolenia-srodowiskowe-dla-firm
Disallow: /artykuly/szczegoly/3/decyzja-o-srodowiskowych-uwarunkowaniach
Disallow: /artykuly/szczegoly/40/ewidencja-odpadow-w-przedsiebiorstwie
Disallow: /artykuly/szczegoly/39/badania-wody-i-sciekow
Disallow: /artykuly/szczegoly/41/konsulting-srodowiskowy---wygodna-wspolpraca
Disallow: /artykuly/szczegoly/12/pomiary-halasu-na-stanowiskach-pracy
Disallow: /artykuly/szczegoly/55/jak-byc-firma-przyjazna-srodowisku
Disallow: /artykuly/szczegoly/19/oplata-produktowa---kogo-dotyczy
Disallow: /artykuly/szczegoly/57/pomiary-emisji-gazow-i-pylow
Disallow: /artykuly/szczegoly/45/gospodarka-odpadami-w-swietle-prawa
Disallow: /artykuly/szczegoly/59/ocena-oddzialywania-inwestycji-na-srodowisko
Disallow: /artykuly/szczegoly/67/srodowisko--za-co-placimy
Disallow: /artykuly/szczegoly/4/instalacje-ktore-nie-wymagaja-pozwolen
Disallow: /artykuly/szczegoly/17/konsulting-w-zakresie-ochrony-srodowiska
Disallow: /artykuly/szczegoly/48/co-to-sa-pozwolenia-wodnoprawne
Disallow: /artykuly/szczegoly/10/oplaty-za-korzystanie-ze-srodowiska
Disallow: /artykuly/szczegoly/51/przeglady-instalacji-i-sieci-sanitarnych
Disallow: /artykuly/szczegoly/58/kogo-dotyczy-oplata-produktowa-za-opakowania
Disallow: /artykuly/szczegoly/63/woda--zwiazek-nie-taki-prosty
Disallow: /artykuly/szczegoly/44/co-to-jest-karta-informacyjna-przedsiewziecia
Disallow: /szczegoly/92/skad-sie-biora-pyly-w-miejscu-pracy?module=artykuly&action=szczegoly&arg0=92&arg1=skad-sie-biora-pyly-w-miejscu-pracy
Disallow: /artykuly/szczegoly/66/nie-za-glosno-czyli-jak-zmierzyc-halas
Disallow: /artykuly/szczegoly/46/praca-biurowa-a-bhp-na-stanowisku-pracy
Disallow: /artykuly/szczegoly/49/oplaty-za-korzystanie-ze-srodowiska-a-przepisy-prawne
Disallow: /artykuly/szczegoly/60/okresowe-przeglady-instalacji---dlaczego-sa-tak-wazne
