User-agent: *
Disallow: /1/
Disallow: /2015/
Disallow: /tmp/
Disallow: /common_files/
Disallow: /epodatnik2/
Disallow: /geoip/
Disallow: /interpretacje-podatkowe/at_work_biezace
Disallow: /interpretacje-podatkowe/at_work_old
Disallow: /interpretacje-podatkowe/unused201309
Disallow: /logs/
Disallow: /pobierz/epodatnikpl/
Disallow: /pobierz/zrzuty/
Disallow: /redakcja/
Disallow: /semantic-examples/
Disallow: /semantic-extended/
Disallow: /semantic-ui/
Disallow: /tmp/
User-agent: msnbot
Disallow: /
