User-agent: *
Allow: /environment/cache/images/
Disallow: /application/
Disallow: /environment/
Disallow: /libraries/
Disallow: /*/reg
Disallow: /*/login
Disallow: /*/basket
Disallow: /*/p/mail/recommend/
Disallow: /*/p/q/
Disallow: /*/p/comment/add/
Disallow: /*/searchquery/
Disallow: /*/fav/add/
Disallow: /login
Disallow: /reg
Disallow: /*passremind
Disallow: /basket
Disallow: /pl/index/*
Disallow: /pl/links/*
Disallow: /*default*
Allow: /skins/default/*
Disallow: /pl/new/*
Disallow: /mobile$
Disallow: /mobile/pl_PL
