# robots.txt automaticaly generated by PrestaShop e-commerce open-source solution
# http://www.prestashop.com - http://www.prestashop.com/forums

# This file is to prevent the crawling and indexing of certain parts
# of your site by web crawlers and spiders run by sites like Yahoo!
# and Google. By telling these "robots" where not to go on your site,
# you save bandwidth and server resources.

# For more information about the robots.txt standard, see:
# http://www.robotstxt.org/wc/robots.html

User-agent: *
# Directories
Disallow: /14/classes/
Disallow: /14/config/
Disallow: /14/download/
Disallow: /14/mails/
Disallow: /14/modules/
Disallow: /14/translations/
Disallow: /14/tools/
Disallow: /14/lang-pl/
# Files
Disallow: /14/addresses.php
Disallow: /14/address.php
Disallow: /14/authentication.php
Disallow: /14/cart.php
Disallow: /14/discount.php
Disallow: /14/footer.php
Disallow: /14/get-file.php
Disallow: /14/header.php
Disallow: /14/history.php
Disallow: /14/identity.php
Disallow: /14/images.inc.php
Disallow: /14/init.php
Disallow: /14/my-account.php
Disallow: /14/order.php
Disallow: /14/order-opc.php
Disallow: /14/order-slip.php
Disallow: /14/order-detail.php
Disallow: /14/order-follow.php
Disallow: /14/order-return.php
Disallow: /14/order-confirmation.php
Disallow: /14/pagination.php
Disallow: /14/password.php
Disallow: /14/pdf-invoice.php
Disallow: /14/pdf-order-return.php
Disallow: /14/pdf-order-slip.php
Disallow: /14/product-sort.php
Disallow: /14/search.php
Disallow: /14/statistics.php
Disallow: /14/attachment.php
Disallow: /14/guest-tracking
Disallow: /14/*orderby=
Disallow: /14/*orderway=
Disallow: /14/*tag=
Disallow: /14/*id_currency=
Disallow: /14/*search_query=
Disallow: /14/*id_lang=
Disallow: /14/*back=
Disallow: /14/*utm_source=
Disallow: /14/*utm_medium=
Disallow: /14/*utm_campaign=
Disallow: /14/*n=
# Sitemap
Sitemap: http://expandor.pl/14/sitemap.xml


