User-Agent: *
Disallow: /fdb3/
Disallow: /main/
Disallow: /_fanAcc/
Disallow: /_fanAdm/
Disallow: /_fanDB/src/
Disallow: /tmp/
Disallow: /src/
Disallow: /fsrc/
Disallow: /stat/
Disallow: /registration/
Disallow: /phtml/
Disallow: /other/
Disallow: /js/
Disallow: /img/
Disallow: /download/
Disallow: /css/
Disallow: /common/
Disallow: /class/
Disallow: /admpanel/
Disallow: /account/
Disallow: /catalogue/
Disallow: /wdIx.php
Disallow: /wdDl.php
Disallow: /trIx.php
Disallow: /trBk.php
Disallow: /trNl.php
Disallow: /ssIx.php
Disallow: /ssDl.php
Disallow: /shrt.php
Disallow: /reset.php
Disallow: /prIx.php
Disallow: /prDl.php
Disallow: /phpinfo.php
Disallow: /ssDl.php
Disallow: /nlLt.php
Disallow: /nlDl.php
Disallow: /neDl.php
Disallow: /meTe.php
Disallow: /meIe.php
Disallow: /meDl.php
Disallow: /index_old.php
Disallow: /erSl.php
Disallow: /dnld.php
Disallow: /config.php
Disallow: /ceIx.php
Disallow: /ceDl.php
Disallow: /bkTe.php
Disallow: /bkSt.php
Disallow: /bkNw.php
Disallow: /bkFe.php
Disallow: /bkDl.php
Disallow: /ax_bkDl.php
Disallow: /arNl.php
Disallow: /arIx.php
Disallow: /arIn.php
Disallow: /arEr.php
Disallow: /arCe.php
Disallow: /arBk.php
Disallow: /aktywuj.php
Disallow: /wersja.php
Allow: /
Allow: /_fanDB/

