User-agent: Googlebot-Image
Allow: /images/

User-agent: bingbot
Disallow: /?
Disallow: /product
Disallow: /index.php
Disallow: /auth-loginform
Disallow: /*gclid
Disallow: /*nokaut
Disallow: /*skapiec
Disallow: /*ceneo
Disallow: /app/
Disallow: /add/
Disallow: /design/
Allow: /js/
Allow: /var/
Disallow: /store_closed.html

User-agent: *
Allow: /$
Disallow: /
Allow: /*.html$
Allow: /*/$
Allow: /images/
Allow: /robots.txt
Allow: /index.php?dispatch=
Disallow: /*/*
Allow: /*.xml$
Disallow: /?
Disallow: /product
Disallow: /index.php
Disallow: /auth-loginform
Disallow: /*gclid
Disallow: /*nokaut
Disallow: /*skapiec
Disallow: /*ceneo
Disallow: /app/
Disallow: /add/
Disallow: /store_closed.html
Allow: /design/
Allow: /var/
Allow: /js/
Allow: /*js
Allow: /*js*
Allow: /*css
Allow: /index.php?dispatch=products.desc
