Sitemap: https://filtreo.pl/sitemap.xml.gz

### Automatically banned scanners and crawlers section ###
User-agent: 008
Disallow: /
user-agent: AhrefsBot
Disallow: /
User-agent: MJ12bot
Disallow: /
User-agent: metajobbot
Disallow: /
User-agent: Exabot
Disallow: /
User-agent: Ezooms
Disallow: /
User-agent: fyberspider
Disallow: /
User-agent: dotbot
Disallow: /
User-agent: MojeekBot
Disallow: /
User-agent: BLEXBot
Disallow: /
User-agent: wotbox
Disallow: /
### Section end ###

User-agent: TwengaBot-Discover
Disallow: /
User-agent: TwengaBot/2.0
Disallow: /
User-agent: TwengaBot
Disallow: /
User-agent: TwengaBot-2.0
Disallow: /

User-agent: baiduspider
Disallow: /

User-agent: Yandex
Disallow: /
Sitemap: http://filtreo.pl/sitemap.xml.gz
User-agent: *
Crawl-delay: 1
Disallow: /basketchange.php
Disallow: /basketedit.php
Disallow: /basket-onchange.php
Disallow: /client-address.php
Disallow: /client-addresses.php
Disallow: /client-new.php
Disallow: /client-orders.php
Disallow: /client-save.php
Disallow: /login.php
Disallow: /loginedit.php
Disallow: /loginonce.php
Disallow: /membership-card.php
Disallow: /order1.php
Disallow: /order2.php
Disallow: /order3.php
Disallow: /ordercancel.php
Disallow: /orderconfirm.php
Disallow: /orderdetails.php
Disallow: /order-document.php
Disallow: /order-newpayment.php
Disallow: /order-payment.php
Disallow: /order-postauction.php
Disallow: /order-wrappers.php
Disallow: /payments-confirm.php
Disallow: /products-bought.php
Disallow: /products-requests.php
Disallow: /przelew.php
Disallow: /rebate-code.php
Disallow: /rma-add.php
Disallow: /rma-list.php
Disallow: /settings.php
Disallow: /Regulamin-filtreo-pl-cterms-pol-73.html
Disallow: /Regulamin-filtreo-pl-cterms-pol.html
Disallow: http://regulamin.filtreo.pl
Disallow: /Aktualizacja-regulaminu-sklepu-filtreo-pl-news-pol-1384419186.html
Disallow: /Regulamin-sklepu-filtreo-pl-cterms-pol-47.html
Disallow: /terms.php
Disallow: /Polityka-prywatnosci-cterms-pol-39.html
Disallow: /Reklamacje-i-zwroty-cterms-pol-69.htmlDisallow: /checkup.php
Disallow: /VOOM-Polska-oficjalny-sklep-marki-VOOM-w-Polsce-stock-2-pol.html
Disallow: /VOOM-Polska-stock-2-pol.html
