User-agent: *

Disallow: /about/
Disallow: /archives/
Disallow: /author/
Disallow: /category/
Disallow: /folder/
Disallow: /index.php/
Disallow: /login/
Disallow: /page/
Disallow: /tag/
Disallow: /trackback/
Disallow: /wp-admin/
Disallow: /wp-icludes/

Disallow: /?orderby=*
Disallow: /baner_diety/
Disallow: /bkg_footer/
Disallow: /catering-eventy*
Disallow: /fitcamp_fitpack/
Disallow: /fitpack_drugie-sniadanie/
Disallow: /fitpack_kolacja/
Disallow: /fitpack_obiad/
Disallow: /fitpack_podwieczorek/
Disallow: /fitpack_sniadanie/
Disallow: /fitpack-logo/
Disallow: /footer-payment/
Disallow: /home/
Disallow: /home/basket_ico/
Disallow: /home/food-black-04/
Disallow: /juz_od_55/
Disallow: /menu/
Disallow: /moje-konto/
Disallow: /my-account/
Disallow: /packshot_basic_pack_1500kcal_55pln/
Disallow: /packshot_glutenfree_pack_1500kcal_58pln/
Disallow: /packshot_glutenfree_pack_1800kcal_60pln/
Disallow: /packshot_sport_pack_3000kcal_75pln/
Disallow: /packshot_sport_pack_3500kcal_78pln/
Disallow: /packshot_wege_fish_pack_1200kcal_61pln/
Disallow: /packshot_wege_pack/
Disallow: /packshot_wege_pack_1200kcal_58pln/
Disallow: /packshot_wege_pack_1500kcal_58pln/
Disallow: /packshot_wege_pack_2000kcal_62pln/
Disallow: /partnerzy_azs_awf/
Disallow: /partnerzy_prime/
Disallow: /partnerzy_sheraton/
Disallow: /slider_bg_1920x690-smaller/
Disallow: /slider_glutenfree_pack/
Disallow: /slider_strzalka/
Disallow: /slider_wege_and_fish_pack/
Disallow: /slider_widelec/
Disallow: /tulipany-tlo/
Disallow: /wishlist/
Disallow: /wishlist-2/
