User-agent: *
Disallow: /calendar.php
Disallow: /cron.php
Disallow: /editpost.php
Disallow: /member.php
Disallow: /memberlist.php
Disallow: /misc.php
Disallow: /newreply.php
Disallow: /newthread.php
Disallow: /printthread.php
Disallow: /private.php
Disallow: /register.php
Disallow: /report.php
Disallow: /search.php
Disallow: /showgroups.php
Disallow: /usercp.php
Disallow: /impressum.php
Disallow: /online.php
Disallow: /subscription.php
Disallow: /sendtofriend.php
Disallow: /threadrate.php
Disallow: /poll.php
Disallow: /attachment.php
Disallow: /avatar.php
Disallow: /faq.php
Disallow: /usercp.php
Disallow: /profile.php
Disallow: /external.php
Disallow: /admincp/
Disallow: /modcp/

