User-agent: *
Disallow: /viewtopic.php
Disallow: /viewforum.php
Disallow: /viewonline.php
Disallow: /style.php
Disallow: /index.php
Disallow: /posting.php
Disallow: /search.php
Disallow: /ucp.php
Disallow: /mcp.php
Disallow: /post
Disallow: /member
Disallow: /memberlist.php
Disallow: /faq.php
Disallow: /download_url.php
Disallow: /juliee-u4841-posts-432.html
Disallow: /whydoc-u5200-posts-1584.html
Disallow: /juliee-u4841-posts-396.html
Disallow: /pool275-u9701-posts-72.html
Disallow: /juliee-u4841-posts-450.html
Disallow: /whydoc-u5200-posts-1656.html
