User-agent: *

Disallow: /*.cfg$
Disallow: /*.css$
Disallow: /*.js$

Disallow: /adm/
Disallow: /cache/
Disallow: /docs/
Disallow: /files/
Disallow: /includes/
Disallow: /language/
Disallow: /sitemaps/
Disallow: /store/
Disallow: /styles/
Disallow: /common.php
Disallow: /config.php
Disallow: /cron.php
Disallow: /maps/
Disallow: /mcp.php
Disallow: /memberlist.php
Disallow: /news/
Disallow: /posting.php
Disallow: /report.php
Disallow: /search.php
Disallow: /style.php
Disallow: /ucp.php
Disallow: /viewonline.php
Disallow: /user
