User-agent: *
Disallow: /application/
Disallow: /installer/
Disallow: /lib/
Disallow: /modules/
Disallow: /system/
Disallow: /themes/
Disallow: /var/logs/
Disallow: /var/modules/
Disallow: /var/resizes/
Disallow: /var/thumbs/
Disallow: /var/tmp/
Disallow: /var/uploads/
Disallow: /digibug/print_photo/
Disallow: /index.php/rss/feed/comment/
Disallow: /rss/feed/comment/
Disallow: /form/add/
Disallow: /index.php/comments/
Disallow: /comments/
User-agent: *
Crawl-delay: 5
User-agent: Baiduspider
Disallow: /
User-agent: AhrefsBot
Disallow: /
User-agent: Ezooms
Disallow: /
User-agent: YandexBot
Disallow: /
User-agent: MJ12bot
Disallow: /
User-agent: bingbot
Disallow: /
User-agent: TwengaBot-2.0
Disallow: /
User-agent: googlebot
Disallow: /
