User-agent: MJ12bot
Disallow: /
User-agent: AhrefsBot
Disallow: /
User-agent: Slurp
Disallow: /
User-agent: Teoma
Disallow: /
User-agent: twiceler
Disallow: /
User-agent: Gigabot
Disallow: /
User-agent: Scrubby
Disallow: /
User-agent: Robozilla
Disallow: /
User-agent: Nutch
Disallow: /
User-agent: baiduspider
Disallow: /
User-agent: naverbot
Disallow: /
User-agent: yeti
Disallow: /
User-agent: yahoo-mmcrawler
Disallow: /
User-agent: asterias
Disallow: /
User-agent: yahoo-blogs/v3.9
Disallow: /
User-agent: ia_archiver
Disallow: /

User-agent: *
Disallow: /js/
Disallow: /css/
Disallow: /wp-admin/
Disallow: /wp-includes/
Disallow: /2012/07/
Disallow: /category/spolki-wydobywajace-zloto/
Disallow: /category/zloto/
Disallow: /blog/gdzie-kupic-zloto-i-srebro-opinie/
Disallow: /tag/zloto/
Disallow: /tag/srebro/
Disallow: /tag/zloto-bulionowe/
Disallow: /srebro/
Disallow: /tag/uncja-zlota/
Disallow: /blog/gdzie-kupic-zloto-i-srebro-opinie/feed/
Disallow: /tag/spolki-zlota/
Disallow: /tag/prognoza-cen-zlota/
Disallow: /tag/hui-index/
Disallow: /blog/zloto-bulionowe-zlote-sztabki-w-etfach/-sztabki
Disallow: /blo../
Disallow: /blog/gdzie-kupic-zloto-opinie-i-porady-baza-wiedzy/http://
Disallow: /zloto-10-lat-pozniej-spolki-zlota-mocno-w-tyle-ale/
Disallow: /blog/certicard-zwana-tez-certipack-czyli-zloto-certyfikowane-w-mennicy/
Disallow: /blog/jak-sprawdzic-autentycznosc-zlotej-sztabki-i-zlotej-monety/
Disallow: /blog/wydobycie-zlota-przez-ludzkosc-oraz-ile-jest-zlota-na-swiecie/
Disallow: /blog/w-co-inwestowac-goldman-sachs-radzi-wrzesien2012/
Disallow: /blog/perspektywy-dla-zlota-i-srebra-wedlug-ubs/
Disallow: /blog/zloto-czy-akcjegdzie-by-tu-zainwestowac-z-cyklu-goldman-sachs-radzi/
Disallow: /blog/qe3-fed-wznowi-drukowanie-pieniedzy-odslona-trzecia/
Disallow: /blog/standard-zlota-i-zloto-jako-pieniadz-wedlug-ubs/
Disallow: /blog/w-co-inwestowac-goldman-sachs-radzi/
Disallow: /blog/qe3-w-opinii-bankow-inwestycyjnych/
Disallow: /blog/fxcm-forex-zloto-na-2-tydzien-wrzesnia/
Disallow: /blog/goldman-sachs-w-co-inwestowac-notatki/
Disallow: /blog/wplyw-drukowania-pieniedzy-na-ceny-akcji/
Disallow: /blog/kupno-akcji-czy-teraz-to-sie-oplaca/
Disallow: /dostep-tylko-dla-subskrybentow-biuletynu-goldco/
Disallow: /join-us/registration/
Disallow: /member-login/
Disallow: /blog/jak-zainwestowac-i-zarobic-podczas-qe3-deutsche-bank/
Disallow: /blog/zloto-czy-akcje-gdzie-by-tu-zainwestowac-z-cyklu-goldman-sachs-radzi/
Disallow: /blog/zloto-czy-akcjegdzie-by-tu-zainwestowac-z-cyklu-goldman-sachs-radzi/feed/
Disallow: /blog/eur-usd-analiza-techniczna-wgz-bank/
Disallow: /blog/certicard-zwana-tez-certipack-czyli-zloto-certyfikowane-w-mennicy/feed/
Disallow: /blog/standard-zlota-i-zloto-jako-pieniadz-wedlug-ubs/?replytocom=28
Disallow: /blog/perspektywy-dla-zlota-i-srebra-wedlug-ubs/feed/
Disallow: /blog/zloto-czy-akcje-gdzie-by-tu-zainwestowac-z-cyklu-goldman-sachs-radzi/feed/
Disallow: /blog/jpmorgan-zlote-notatki/
Disallow: /blog/w-co-inwestowac-goldman-sachs-radzi-wrzesien2012/?replytocom=24
Disallow: /blog/standard-zlota-i-zloto-jako-pieniadz-wedlug-ubs/?replytocom=2
Disallow: /blog/gdzie-kupic-zloto-i-srebro-opinie/
Disallow: /blog/wydobycie-zlota-przez-ludzkosc-oraz-ile-jest-zlota-na-swiecie/feed/
Disallow: /blog/standard-zlota-i-zloto-jako-pieniadz-wedlug-ubs/?replytocom=82
Disallow: /cos-poszlo-nie-tak/
Disallow: /jak-inwestowac-w-zloto/
Disallow: /member-login/feed/
Disallow: /join-us/registration/feed/
Disallow: /join-us/feed/
Disallow: /blog/w-co-inwestowac-goldman-sachs-radzi/?replytocom=64
Disallow: /blog/w-co-inwestowac-goldman-sachs-radzi/?replytocom=66
Disallow: /blog/standard-zlota-i-zloto-jako-pieniadz-wedlug-ubs/?replytocom=79
Disallow: /blog/w-co-inwestowac-goldman-sachs-radzi-wrzesien2012/?replytocom=68
Disallow: /zloto/
Disallow: /blog/standard-zlota-i-zloto-jako-pieniadz-wedlug-ubs/?replytocom=81
Disallow: /blog/jak-sprawdzic-autentycznosc-zlotej-sztabki-i-zlotej-monety/feed/
Disallow: /blog/qe3-fed-wznowi-drukowanie-pieniedzy-odslona-trzecia/feed/
Disallow: /blog/ile-dotyhczas-wydobyto-zlota-i-kto-je-posiada/
Disallow: /blog/qe3-fed-wznowi-drukowanie
Disallow: /dostep-tylko-dla-subskrybentow-biuletynu-goldco/feed/
Disallow: /blog/w-co-inwestowac-goldman-sachs-radzi/?replytocom=11
Disallow: /wp-content/uploads/2012/09/UBS_NewTarget_2012_9_10.pdf
Disallow: /blog/kupno-akcji-czy-teraz-to-sie-oplaca/?replytocom=20

Sitemap: http://goldco.pl/sitemap_index.xml
