User-Agent: AddSearchBot
Allow: /$
Allow: /documents/
Allow: /web/cyfryzacja/
Allow: /web/diplomacy/
Allow: /web/dyplomacja/
Allow: /web/edukacja/
Allow: /web/energia/
Allow: /web/energy/
Allow: /web/e-dowod/
Allow: /web/finance/
Allow: /web/finanse/
Allow: /web/gospodarkamorska/
Allow: /web/infrastruktura/
Allow: /web/inwestycje-rozwoj/
Allow: /web/kas/
Allow: /web/krmc/
Allow: /web/kultura/
Allow: /web/mobywatel/
Allow: /web/mswia/
Allow: /web/national-defence/
Allow: /web/national-revenue-administration/
Allow: /web/nauka/
Allow: /web/nck/
Allow: /web/obrona-narodowa/
Allow: /web/podjednostki/
Allow: /web/popcwsparcie/
Allow: /web/przedsiebiorczosc-technologia/
Allow: /web/rodzina/
Allow: /web/rolnictwo/
Allow: /web/science/
Allow: /web/sport-turystyka/
Allow: /web/sprawiedliwosc/
Allow: /web/srodowisko/
Allow: /web/uslugi/
Allow: /web/zdrowie/
Disallow: /

User-Agent: *
Allow: /$
Allow: /documents/
Allow: /cyfryzacja
Allow: /diplomacy
Allow: /dyplomacja
Allow: /edukacja
Allow: /energia
Allow: /energy
Allow: /e-dowod
Allow: /finance
Allow: /finanse
Allow: /gospodarkamorska
Allow: /infrastruktura
Allow: /inwestycje-rozwoj
Allow: /kas
Allow: /krmc
Allow: /kultura
Allow: /mobywatel
Allow: /mswia
Allow: /national-defence
Allow: /national-revenue-administration
Allow: /nauka
Allow: /nck
Allow: /obrona-narodowa
Allow: /podjednostki
Allow: /popcwsparcie
Allow: /przedsiebiorczosc-technologia
Allow: /rodzina
Allow: /rolnictwo
Allow: /science
Allow: /sport-turystyka
Allow: /sprawiedliwosc
Allow: /srodowisko
Allow: /uslugi
Allow: /zdrowie
Allow: /web/cyfryzacja
Allow: /web/diplomacy
Allow: /web/dyplomacja
Allow: /web/edukacja
Allow: /web/energia
Allow: /web/energy
Allow: /web/e-dowod
Allow: /web/finance
Allow: /web/finanse
Allow: /web/gospodarkamorska
Allow: /web/infrastruktura
Allow: /web/inwestycje-rozwoj
Allow: /web/kas
Allow: /web/krmc
Allow: /web/kultura
Allow: /web/mobywatel
Allow: /web/mswia
Allow: /web/national-defence
Allow: /web/national-revenue-administration
Allow: /web/nauka
Allow: /web/nck
Allow: /web/obrona-narodowa
Allow: /web/podjednostki
Allow: /web/popcwsparcie
Allow: /web/przedsiebiorczosc-technologia
Allow: /web/rodzina
Allow: /web/rolnictwo
Allow: /web/science
Allow: /web/sport-turystyka
Allow: /web/sprawiedliwosc
Allow: /web/srodowisko
Allow: /web/uslugi
Allow: /web/zdrowie
Disallow: /

