User-agent: *
Disallow: /home-27/action~posterboard/
Disallow: /home-27/action~agenda/
Disallow: /home-27/action~oneday/
Disallow: /home-27/action~month/
Disallow: /home-27/action~week/
Disallow: /home-27/action~stream/
Disallow: /calendar/action~posterboard/
Disallow: /calendar/action~agenda/
Disallow: /calendar/action~oneday/
Disallow: /calendar/action~month/
Disallow: /calendar/action~week/
Disallow: /calendar/action~stream/
Disallow: /terminarz-szkolen/action~posterboard/
Disallow: /terminarz-szkolen/action~agenda/
Disallow: /terminarz-szkolen/action~oneday/
Disallow: /terminarz-szkolen/action~month/
Disallow: /terminarz-szkolen/action~week/
Disallow: /terminarz-szkolen/action~stream/
