# robots.txt automaticaly generated by PrestaShop e-commerce open-source solution
# http://www.prestashop.com - http://www.prestashop.com/forums
# This file is to prevent the crawling and indexing of certain parts
# of your site by web crawlers and spiders run by sites like Yahoo!
# and Google. By telling these "robots" where not to go on your site,
# you save bandwidth and server resources.
# For more information about the robots.txt standard, see:
# http://www.robotstxt.org/wc/robots.html
User-agent: *
# Private pages
Disallow: /*id_currency=
Disallow: /*n=
Disallow: /*controller=addresses
Disallow: /*controller=address
Disallow: /*controller=authentication
Disallow: /*controller=cart
Disallow: /*controller=discount
Disallow: /*controller=footer
Disallow: /*controller=get-file
Disallow: /*controller=header
Disallow: /*controller=identity
Disallow: /*controller=images.inc
Disallow: /*controller=init
Disallow: /*controller=my-account
Disallow: /*controller=order
Disallow: /*controller=order-opc
Disallow: /*controller=order-slip
Disallow: /*controller=order-detail
Disallow: /*controller=order-follow
Disallow: /*controller=order-return
Disallow: /*controller=order-confirmation
Disallow: /*controller=pagination
Disallow: /*controller=password
Disallow: /*controller=pdf-invoice
Disallow: /*controller=pdf-order-return
Disallow: /*controller=pdf-order-slip
Disallow: /*controller=product-sort
Disallow: /*controller=statistics
Disallow: /*controller=attachment
Disallow: /*controller=guest-tracking
# Directories
Disallow: /*classes/
Disallow: /*config/
Disallow: /*download/
Disallow: /*mails/
Disallow: /*translations/
Disallow: /*tools/
# Files
Disallow: /*pl/password-recovery
Disallow: /*pl/address
Disallow: /*pl/cart
Disallow: /*pl/order-history
Disallow: /*pl/my-account
Disallow: /*pl/order-follow
Disallow: /*pl/order-slip
Disallow: /*pl/guest-tracking
Disallow: /*pl/order-confirmation
Disallow: /*en/password-recovery
Disallow: /*en/address
Disallow: /*en/addresses
Disallow: /*en/cart
Disallow: /*en/order-history
Disallow: /*en/my-account
Disallow: /*en/order-follow
Disallow: /*en/order-slip
Disallow: /*en/order
Disallow: /*en/guest-tracking
Disallow: /*en/order-confirmation
Disallow: /*cs/password-recovery
Disallow: /*cs/address
Disallow: /*cs/addresses
Disallow: /*cs/cart
Disallow: /*cs/order-history
Disallow: /*cs/my-account
Disallow: /*cs/order-follow
Disallow: /*cs/order-slip
Disallow: /*cs/order
Disallow: /*cs/guest-tracking
Disallow: /*cs/order-confirmation
Disallow: /*sk/password-recovery
Disallow: /*sk/address
Disallow: /*sk/addresses
Disallow: /*sk/cart
Disallow: /*sk/order-history
Disallow: /*sk/my-account
Disallow: /*sk/order-follow
Disallow: /*sk/order-slip
Disallow: /*sk/order
Disallow: /*sk/guest-tracking
Disallow: /*sk/order-confirmation

