User-agent: *
Allow: /
Disallow: /t3lib/
Disallow: /typo3/
Allow: /typo3/sysext/cms/tslib/media/fileicons/
Allow: /typo3/pics/artykuly_tresc/
Disallow: /fer/
Disallow: /test-wrap/
Disallow: /typo3conf/
Allow: /typo3temp/compressor/
Allow: /typo3conf/ext/wt_socialbookmarks/files/
Allow: /typo3conf/ext/perfectlightbox/res/js/
Allow: /typo3conf/ext/sk_pagecomments/res/smileys/
Allow: /typo3/sysext/rtehtmlarea/res/accessibilityicons/img/
Allow: /typo3conf/ext/wt_directory/files/
Allow: /typo3conf/ext/rgtabs/res/scripts/
Allow: /typo3conf/ext/t3mootools/res/
Allow: /typo3conf/ext/sk_pagecomments/res/
Allow: /typo3conf/ext/ke_yac/res/js/
Allow: /typo3conf/ext/ke_yac/res/images/
Allow: /typo3conf/ext/xajax/xajax_js/
Allow: /typo3/sysext/cms/tslib/media/fileicons/
Allow: /typo3conf/ext/xajax/xajax_js/
Allow: /typo3conf/ext/bootstrap_grids/Resources/Public/Flexslider2/css/
Allow: /typo3conf/ext/t3colorbox/Resources/Public/
Allow: /typo3conf/ext/bootstrap_package/Resources/Public/JavaScript/
Allow: /typo3conf/ext/mindshape_cookie_hint/Resources/Public/Css/
Allow: /typo3conf/ext/bootstrap_grids/Resources/Public/Flexslider2/
Allow: /typo3conf/ext/mindshape_cookie_hint/Resources/Public/Js/
