User-agent: 008
Disallow: /
user-agent: AhrefsBot
Disallow: /
User-agent: MJ12bot
Disallow: /
User-agent: metajobbot
Disallow: /
User-agent: Exabot
Disallow: /
User-agent: Ezooms
Disallow: /
User-agent: fyberspider
Disallow: /
User-agent: dotbot
Disallow: /
User-agent: MojeekBot
Disallow: /
User-agent: BLEXBot
Disallow: /
User-agent: wotbox
Disallow: /
User-agent: TwengaBot-Discover
Disallow: /
User-agent: TwengaBot/2.0
Disallow: /
User-agent: TwengaBot
Disallow: /
User-agent: TwengaBot-2.0
Disallow: /
User-agent: baiduspider
Disallow: /

User-agent: *
Allow: /o-nas
Disallow: /*?
Disallow: /*&
Disallow: /*%
Disallow: /_OLD/
Disallow: /admin/
Disallow: /download/
Disallow: /system/
Disallow: /test/
Disallow: /vqmod/
Disallow: /.well-known/
Disallow: /customer/

Sitemap: https://www.indianmeble.pl/indianmeble/sitemap.xml
