User-agent: *
Disallow: /wp-admin/
Disallow: /auditgroup/
Disallow: /auditgroup2/
Disallow: /coinarbs/
Disallow: /coinarbs2/
Disallow: /cozakrem/
Disallow: /cozakrem2/
Disallow: /buhara/
Disallow: /mitex/
Disallow: /kgbeauty/
Disallow: /smiiiles/
Disallow: /akademiapodrozy/
Disallow: /drehkopf/
Disallow: /hds/
Disallow: /hds2/
Disallow: /zadaszeniebasenu/
Disallow: /airport-transfer/
Disallow: /pilomat/
Disallow: /slupkiparkingowe/
Disallow: /yore/
Disallow: /modernwohnen2/
Disallow: /magnails/
Disallow: /lbp/
Disallow: /allegro/
Disallow: /generator/
Disallow: /installation/
Disallow: /blog/
Disallow: /produkty/
Disallow: /html/
Disallow: /milda/
Disallow: /grom/
Disallow: /perrosi/
Disallow: /allegro/
Disallow: /blokady/
Disallow: /mood/
Disallow: /szlabany/
Disallow: /stankiewicz/
Disallow: /studnie/
Disallow: /wckici/
Disallow: /polishcosmetics/
Disallow: /klobialapodlaska/
Disallow: /akwa-deko/
Disallow: /resbroker/
Disallow: /fastba/
Disallow: /bootstrap-material-ui-master/
Disallow: /bez-klamstw/
Disallow: /efekt/
Disallow: /slupkiautomatyczne/
Disallow: /homemarbella/
Disallow: /pse/
Disallow: /zapory/
Disallow: /bcmarket/
Disallow: /slupki/
Disallow: /zaporyanty/
Disallow: /slupkidrogowe/
Disallow: /best4cars/
Allow: /wp-admin/admin-ajax.php

Sitemap: http://inov.pl/sitemap.xml.gz
