# robots.txt automaticaly generated by PrestaShop e-commerce open-source solution
# http://www.prestashop.com - http://www.prestashop.com/forums
# This file is to prevent the crawling and indexing of certain parts
# of your site by web crawlers and spiders run by sites like Yahoo!
# and Google. By telling these "robots" where not to go on your site,
# you save bandwidth and server resources.
# For more information about the robots.txt standard, see:
# http://www.robotstxt.org/wc/robots.html
User-agent: *
# Private pages
Disallow: /*orderby=
Disallow: /*orderway=
Disallow: /*tag=
Disallow: /*id_currency=
Disallow: /*search_query=
Disallow: /*back=
Disallow: /*n=
Disallow: /*controller=addresses
Disallow: /*controller=address
Disallow: /*controller=authentication
Disallow: /*controller=cart
Disallow: /*controller=discount
Disallow: /*controller=footer
Disallow: /*controller=get-file
Disallow: /*controller=header
Disallow: /*controller=history
Disallow: /*controller=identity
Disallow: /*controller=images.inc
Disallow: /*controller=init
Disallow: /*controller=my-account
Disallow: /*controller=order
Disallow: /*controller=order-opc
Disallow: /*controller=order-slip
Disallow: /*controller=order-detail
Disallow: /*controller=order-follow
Disallow: /*controller=order-return
Disallow: /*controller=order-confirmation
Disallow: /*controller=pagination
Disallow: /*controller=password
Disallow: /*controller=pdf-invoice
Disallow: /*controller=pdf-order-return
Disallow: /*controller=pdf-order-slip
Disallow: /*controller=product-sort
Disallow: /*controller=search
Disallow: /*controller=statistics
Disallow: /*controller=attachment
Disallow: /*controller=guest-tracking
# Directories
Disallow: */classes/
Disallow: */config/
Disallow: */download/
Disallow: */mails/
Disallow: */translations/
Disallow: */tools/
Disallow: */tes/
# Files
Disallow: /*pl/odzyskaj-haslo
Disallow: /*pl/address
Disallow: /*pl/addresses
Disallow: /*pl/autoryzacja
Disallow: /*pl/koszyk
Disallow: /*pl/rabaty
Disallow: /*pl/historia-zamowien
Disallow: /*pl/identity
Disallow: /*pl/moje-konto
Disallow: /*pl/order-follow
Disallow: /*pl/order-slip
Disallow: /*pl/zamowienie
Disallow: /*pl/wyszukiwarka
Disallow: /*pl/moje-zamowienie
Disallow: /*pl/guest-tracking

Disallow: /odzyskaj-haslo
Disallow: /address
Disallow: /addresses
Disallow: /autoryzacja
Disallow: /koszyk
Disallow: /rabaty
Disallow: /historia-zamowien
Disallow: /identity
Disallow: /moje-konto
Disallow: /order-follow
Disallow: /order-slip
Disallow: /zamowienie
Disallow: /wyszukiwarka
Disallow: /moje-zamowienie
Disallow: /guest-tracking

#moje

Allow: */themes/kronan/js/tools/treeManagement.js

