User-agent: Yandex
Disallow: /wp-login.php
Disallow: /wp-register.php
Disallow: /xmlrpc.php
Disallow: /wp-admin
Disallow: /wp-includes
Disallow: /wp-content/
Disallow: /*trackback
Disallow: /*feed
Disallow: /*comments
Disallow: /*?s=
Disallow: /tag
Disallow: /tag/
Disallow: */tag/
Disallow: */page/
Disallow: /&post=
Disallow: /?p=
Disallow: /author/
Disallow: /cgi-bin
Disallow: /?
Disallow: /wp-
Disallow: *?s=
Disallow: *&s=
Disallow: /search
Disallow: /author/
Disallow: *?attachment_id=
Disallow: */feed
Disallow: */rss
Disallow: */embed
Disallow: */page/
Disallow: */category/
Disallow: /aktualnosci/
Disallow: /referencje/
Allow: /wp-content/uploads
Allow: */uploads
Allow: /*/*.js
Allow: /*/*.css
Allow: /wp-*.jpg
Allow: /wp-*.jpeg
Allow: /wp-*.gif
Allow: /wp-*.svg
Allow: /wp-*.png
Allow: /wp-*.pdf

Host: https://jdmercury.com.pl

User-agent: *
Disallow: /wp-login.php
Disallow: /wp-register.php
Disallow: /xmlrpc.php
Disallow: /wp-admin
Disallow: /wp-includes
Disallow: /wp-content/
Disallow: /*trackback
Disallow: /*feed
Disallow: /*comments
Disallow: /*?s=
Disallow: /tag
Disallow: /tag/
Disallow: */tag/
Disallow: */page/
Disallow: /&post=
Disallow: /?p=
Disallow: /author/
Disallow: /cgi-bin
Disallow: /?
Disallow: /wp-
Disallow: *?s=
Disallow: *&s=
Disallow: /search
Disallow: /author/
Disallow: *?attachment_id=
Disallow: */feed
Disallow: */rss
Disallow: */embed
Disallow: */page/
Disallow: /category
Disallow: /category/
Disallow: */category/
Disallow: /aktualnosci/
Disallow: /referencje/
Allow: /wp-content/uploads
Allow: */uploads
Allow: /*/*.js
Allow: /*/*.css
Allow: /wp-*.jpg
Allow: /wp-*.jpeg
Allow: /wp-*.gif
Allow: /wp-*.svg
Allow: /wp-*.png
Allow: /wp-*.pdf
Sitemap: https://jdmercury.com.pl/sitemap.xml

