User-agent: Lycos_Spider_(T-Rex)
User-agent: Gulliver/1.3
User-agent: DELTASCAN
User-agent: msnbot
User-agent: sohu-search
User-agent: TurnitinBot
User-agent: Gigabot
User-agent: NetSprint
User-agent: ia_archiver
User-agent: Yahoo!
User-agent: Polkomtel
User-agent: IpwalkBot
User-agent: ZyBorg
User-agent: voyager
User-agent: findlinks
User-agent: GetRight
User-agent: GetWeb!
User-agent: Gigabot
Disallow: /

User-agent: *
Disallow: /cgi-bin/
Disallow: /admin/
Disallow: /hurtownicy/
Disallow: /images/
Disallow: /images_u/
Disallow: /lang/
Disallow: /partner/
Disallow: /szablony/
Disallow: /users/
