User-agent: *
Disallow: /calendar/action~posterboard/
Disallow: /calendar/action~agenda/
Disallow: /calendar/action~oneday/
Disallow: /calendar/action~month/
Disallow: /calendar/action~week/
Disallow: /calendar/action~stream/
Disallow: /kalendarz/action~posterboard/
Disallow: /kalendarz/action~agenda/
Disallow: /kalendarz/action~oneday/
Disallow: /kalendarz/action~month/
Disallow: /kalendarz/action~week/
Disallow: /kalendarz/action~stream/
Disallow: /calendar-2/action~posterboard/
Disallow: /calendar-2/action~agenda/
Disallow: /calendar-2/action~oneday/
Disallow: /calendar-2/action~month/
Disallow: /calendar-2/action~week/
Disallow: /calendar-2/action~stream/
Disallow: /test/action~posterboard/
Disallow: /test/action~agenda/
Disallow: /test/action~oneday/
Disallow: /test/action~month/
Disallow: /test/action~week/
Disallow: /test/action~stream/
Disallow: /event/
