User-agent: *
Disallow: http://mail.kajaki-sztum.pl
Disallow: /a/kg.php?skyn=wood
Disallow: /a/kg.php?skyn=blueforest
Disallow: /a/kg.php?skyn=nothing
Disallow: /a/kgcall.php?engine=addkg.php
Disallow: /a/kgcall.php?engine=uploadzdj.php
Disallow: /a/kgcall.php?engine=kgadminlogin.php
Disallow: /a/kgcall.php?engine=testzdjecia.php
Disallow: /kajaki-sztum.pl/a/kg.php?skyn=wood
Disallow: /kajaki-sztum.pl/a/kg.php?skyn=blueforest
Disallow: /kajaki-sztum.pl/a/kg.php?skyn=nothing
Disallow: /kajaki-sztum.pl/a/kgcall.php?engine=addkg.php
Disallow: /kajaki-sztum.pl/a/kgcall.php?engine=uploadzdj.php
Disallow: /kajaki-sztum.pl/a/kgcall.php?engine=kgadminlogin.php
Disallow: /kajaki-sztum.pl/a/kgcall.php?engine=testzdjecia.php
Disallow: /robots.txt
Disallow: /wietcisa.html
