<!doctype html>
<html lang="pl-PL" data-n-head="lang">
<head data-n-head="">
<title data-n-head="true">Kashmir</title><meta data-n-head="true" charset="utf-8"><meta data-n-head="true" name="viewport" content="width=device-width,initial-scale=1"><meta data-n-head="true" data-hid="description" name="description" content="Zapraszam Panstwa do autoryzowanego gabinetu marki Dermalogica, w ktorym proponujemy zarowno zabiegi kosmetologii tradycyjnej, jak i te z zakresu kosmetologii i medycyny estetycznej. "><link data-n-head="true" rel="icon" type="image/x-icon" href="/favicon.ico"><script data-n-head="true" src="//translate.google.com/translate_a/element.js"></script><link rel="preload" href="/_nuxt/aad33a75f783a9da9f4e.js" as="script"><link rel="preload" href="/_nuxt/75f088be142e1f2b32ba.js" as="script"><link rel="preload" href="/_nuxt/3a8e7f124a420d7c2a2a.js" as="script"><link rel="preload" href="/_nuxt/9e84903041f297d1e0c1.css" as="style"><link rel="preload" href="/_nuxt/18e10f0df89808078d08.js" as="script">
<link href="/_nuxt/9e84903041f297d1e0c1.css" rel="stylesheet"></head>
<body data-n-head="">
<div id="__nuxt"><style>#__nuxt,body,html{background:#fff;width:100%;height:100%;display:flex;justify-content:center;align-items:center;margin:0;padding:0}.spinner{width:40px;height:40px;position:relative;text-align:center;-webkit-animation:sk-rotate 2s infinite linear;animation:sk-rotate 2s infinite linear}.dot1,.dot2{width:60%;height:60%;display:inline-block;position:absolute;top:0;background-color:#000;border-radius:100%;-webkit-animation:sk-bounce 2s infinite ease-in-out;animation:sk-bounce 2s infinite ease-in-out}.dot2{top:auto;bottom:0;-webkit-animation-delay:-1s;animation-delay:-1s}@-webkit-keyframes sk-rotate{100%{-webkit-transform:rotate(360deg)}}@keyframes sk-rotate{100%{transform:rotate(360deg);-webkit-transform:rotate(360deg)}}@-webkit-keyframes sk-bounce{0%,100%{-webkit-transform:scale(0)}50%{-webkit-transform:scale(1)}}@keyframes sk-bounce{0%,100%{transform:scale(0);-webkit-transform:scale(0)}50%{transform:scale(1);-webkit-transform:scale(1)}}</style><div class="spinner">  <div class="dot1"></div>  <div class="dot2"></div></div></div>
<script type="text/javascript" src="/_nuxt/aad33a75f783a9da9f4e.js"></script><script type="text/javascript" src="/_nuxt/75f088be142e1f2b32ba.js"></script><script type="text/javascript" src="/_nuxt/3a8e7f124a420d7c2a2a.js"></script><script type="text/javascript" src="/_nuxt/18e10f0df89808078d08.js"></script></body>
</html>

