User-agent: *
Disallow: /kalendarz/action~posterboard/
Disallow: /kalendarz/action~agenda/
Disallow: /kalendarz/action~oneday/
Disallow: /kalendarz/action~month/
Disallow: /kalendarz/action~week/
Disallow: /kalendarz/action~stream/
Disallow: /calendar/action~posterboard/
Disallow: /calendar/action~agenda/
Disallow: /calendar/action~oneday/
Disallow: /calendar/action~month/
Disallow: /calendar/action~week/
Disallow: /calendar/action~stream/
Disallow: /events/action~posterboard/
Disallow: /events/action~agenda/
Disallow: /events/action~oneday/
Disallow: /events/action~month/
Disallow: /events/action~week/
Disallow: /events/action~stream/
Disallow: /events/action~undefined/
Disallow: /events/action~http:/
Disallow: /events/action~default/
Disallow: /events/action~poster/
Disallow: /events/action~*/
Disallow: /*controller=ai1ec_exporter_controller*
Disallow: /*/action~*/
Disallow: /wydarzenia/action~posterboard/
Disallow: /wydarzenia/action~agenda/
Disallow: /wydarzenia/action~oneday/
Disallow: /wydarzenia/action~month/
Disallow: /wydarzenia/action~week/
Disallow: /wydarzenia/action~stream/
Disallow: /wydarzenia/action~undefined/
Disallow: /wydarzenia/action~http:/
Disallow: /wydarzenia/action~default/
Disallow: /wydarzenia/action~poster/
Disallow: /wydarzenia/action~*/
