User-agent: *
Disallow: /calendar/action~posterboard/
Disallow: /calendar/action~agenda/
Disallow: /calendar/action~oneday/
Disallow: /calendar/action~month/
Disallow: /calendar/action~week/
Disallow: /calendar/action~stream/
Disallow: /calendar/action~undefined/
Disallow: /calendar/action~http:/
Disallow: /calendar/action~default/
Disallow: /calendar/action~poster/
Disallow: /calendar/action~*/
Disallow: /*controller=ai1ec_exporter_controller*
Disallow: /*/action~*/
Disallow: /zycie-osrodka/aktualnosci/action~posterboard/
Disallow: /zycie-osrodka/aktualnosci/action~agenda/
Disallow: /zycie-osrodka/aktualnosci/action~oneday/
Disallow: /zycie-osrodka/aktualnosci/action~month/
Disallow: /zycie-osrodka/aktualnosci/action~week/
Disallow: /zycie-osrodka/aktualnosci/action~stream/
Disallow: /zycie-osrodka/aktualnosci/action~undefined/
Disallow: /zycie-osrodka/aktualnosci/action~http:/
Disallow: /zycie-osrodka/aktualnosci/action~default/
Disallow: /zycie-osrodka/aktualnosci/action~poster/
Disallow: /zycie-osrodka/aktualnosci/action~*/
