# robots.txt automaticaly generated by PrestaShop e-commerce open-source solution
# http://www.prestashop.com - http://www.prestashop.com/forums
# This file is to prevent the crawling and indexing of certain parts
# of your site by web crawlers and spiders run by sites like Yahoo!
# and Google. By telling these "robots" where not to go on your site,
# you save bandwidth and server resources.
# For more information about the robots.txt standard, see:
# http://www.robotstxt.org/wc/robots.html
User-agent: *
# Private pages
Disallow: /*orderby=
Disallow: /*orderway=
Disallow: /*tag=
Disallow: /*id_currency=
Disallow: /*search_query=
Disallow: /*back=
Disallow: /*n=
Disallow: /*controller=addresses
Disallow: /*controller=address
Disallow: /*controller=authentication
Disallow: /*controller=cart
Disallow: /*controller=discount
Disallow: /*controller=footer
Disallow: /*controller=get-file
Disallow: /*controller=header
Disallow: /*controller=history
Disallow: /*controller=identity
Disallow: /*controller=images.inc
Disallow: /*controller=init
Disallow: /*controller=my-account
Disallow: /*controller=order
Disallow: /*controller=order-opc
Disallow: /*controller=order-slip
Disallow: /*controller=order-detail
Disallow: /*controller=order-follow
Disallow: /*controller=order-return
Disallow: /*controller=order-confirmation
Disallow: /*controller=pagination
Disallow: /*controller=password
Disallow: /*controller=pdf-invoice
Disallow: /*controller=pdf-order-return
Disallow: /*controller=pdf-order-slip
Disallow: /*controller=product-sort
Disallow: /*controller=search
Disallow: /*controller=statistics
Disallow: /*controller=attachment
Disallow: /*controller=guest-tracking
# Directories
Disallow: */classes/
Disallow: */config/
Disallow: */download/
Disallow: */mails/
Disallow: */modules/
Disallow: */translations/
Disallow: */tools/
Disallow: */sole/14-sol-epsom-2kg-farmaceutyczna-1.html
Disallow: */sole/15-sol-epsom-5kg-farmaceutyczna-1.html
Disallow: */domowe-spa/887-sol-epsom-15kg-farmaceutyczna-1.html
Disallow: */domowe-spa/814-sol-epsom-700g-farmaceutyczna-1.html
Disallow: */sole/18-sol-z-morza-martwego-1.html
Disallow: */sole/19-sol-z-morza-martwego-1.html
Disallow: */domowe-spa/812-sol-z-morza-martwego-z-jordanii-700g-1.html
Disallow: */sole/282-rozowa-sol-himalajska-gruba-1.html
Disallow: */superfoods/799-chlorella-400-tabletek-1.html
Disallow: */witaminy-zwiazki-mineralne/648-witamina-c-kwas-l-askorbinowy-1.html
Disallow: */oleje/796-olej-kokosowy-rafinowany-1.html
Disallow: */shea/97-maslo-shea-nierafinowane-12.html
Disallow: */shea/99-maslo-shea-nierafinowane-12.html
Disallow: */domowe-spa/320-maslo-shea-75g-nierafinowane-12.html
Disallow: */domowe-spa/809-maslo-kakaowe-50g-nierafinowane-1.html
Disallow: */kakaowe/93-maslo-kakaowe-nierafinowane-12.html
Disallow: */kakaowe/95-maslo-kakaowe-nierafinowane-12.html
# Files
Disallow: /*pl/odzyskiwanie-hasla
Disallow: /*pl/adres
Disallow: /*pl/adresy
Disallow: /*pl/logowanie
Disallow: /*pl/koszyk
Disallow: /*pl/rabaty
Disallow: /*pl/historia-zamowien
Disallow: /*pl/dane-osobiste
Disallow: /*pl/moje-konto
Disallow: /*pl/sledzenie-zamowienia
Disallow: /*pl/pokwitowania
Disallow: /*pl/zamowienie
Disallow: /*pl/szukaj
Disallow: /*pl/szybkie-zakupy
Disallow: /*pl/sledzenie-zamowienia-gosc
Disallow: /*pl/potwierdzenie-zamowienia

