# robots.txt file for http://www.krsformoza.pl/
# Generated by SOFTplus GSiteCrawler v1.23 rev. 286 / http://gsitecrawler.com/
# 2014-06-15  20:13

User-agent: *
/php_sendmail_upload2.php
/kontakt.php

# end of file


