User-agent: *
Disallow: /adm/
Disallow: /class/
Disallow: /config/
Disallow: /cron/
Disallow: /css/
Disallow: /flv/
Disallow: /galeria/
Disallow: /images/
Disallow: /include/
Disallow: /javascript/
Disallow: /kamery/
Disallow: /modules/
Disallow: /rss/
Disallow: /template/
Disallow: /test/
Disallow: /tmp/
Disallow: /UserFiles/
Allow: /sitemap.xml
Sitemap: http://www.kryniczno.pl/sitemap.xml
