User-agent: *
Disallow: /administrator/
Disallow: /cache/
Allow: /cache/mod_vm_accordion_theme/120/*.css
Disallow: /components/
Allow: /components/com_virtuemart/*.js
Allow: /components/com_virtuemart/*.css
Allow: /components/com_virtuemart/shop_image/product/*.jpg
Allow: /components/com_virtuemart/shop_image/product/resized/*.jpg
Allow: /components/com_virtuemart/shop_image/category/*.jpg
Allow: /components/com_virtuemart/shop_image/category/resized/*.jpg
Allow: /components/com_virtuemart/shop_image/vendor/*.png
Allow: /components/com_virtuemart/shop_image/vendor/*.jpg
Allow: /components/com_virtuemart/themes/pbv_multi/images/*.jpg
Allow: /components/com_virtuemart/themes/pbv_multi/images/*.png
Allow: /components/com_virtuemart/themes/pbv_multi/images/*.gif
Allow: /components/com_virtuemart/themes/pbv_multi/images/stars/*.gif
Allow: /components/com_virtuemart/themes/pbv_multi/images/availability/*.png
Allow: /components/com_virtuemart/themes/monro/*.css
Allow: /components/com_virtuemart/themes/monro/css/*.css
Allow: /components/com_virtuemart/themes/monro/js/*.js
Allow: /components/com_virtuemart/themes/monro/*.js
Allow: /images/stories/*.png
Allow: /images/stories/logos/*.png
Allow: /images/stories/przelewy24/*.png
Disallow: /includes/
Disallow: /installation/
Disallow: /language/
Disallow: /libraries/
Disallow: /media/
Allow: /media/system/js/*.js
Disallow: /modules/
Allow: /modules/mod_slick_login_vm/styles/horizontal/*.css
Allow: /modules/mod_slick_login_vm/styles/vertical/*.css
Allow: /modules/mod_pp_vm_quicksummary/images/*.png
Allow: /modules/mod_vm_accordion/js/*.js
Allow: /modules/mod_vm_accordion/themes/default/images/*.gif
Allow: /modules/mod_vm_accordion/themes/default/images/*.jpg
Allow: /modules/mod_vm_accordion/themes/default/images/*.png
Allow: /modules/mod_GI_productscroller/Engine/*.js
Disallow: /plugins/
Disallow: /private/
Allow: /templates/oswietlenie_lampy_monro/css/*.css
Allow: /templates/oswietlenie_lampy_monro/*.js
Allow: /templates/system/css/*.css
Allow: /templates/oswietlenie_lampy_monro/images/*.jpg
Allow: /templates/oswietlenie_lampy_monro/images/*.png
Disallow: /tmp/
Disallow: /xmlrpc/
Disallow: /private/
Sitemap: http://www.lampy-oswietlenie.com.pl/index.php?option=com_xmap&sitemap=1&view=xml
Sitemap: http://www.lampy-oswietlenie.com.pl/index.php?option=com_xmap&sitemap=1&view=xml&images=1

