User-agent: *
Disallow: /konto/
Disallow: /paywall/
Disallow: /ajax/
Disallow: /esi/
Disallow: /hit/
Disallow: /new_hit/
Disallow: /strossle/
Disallow: /konferencje/*/rejestracja
Disallow: /konferencje/*/uczestnicy
Disallow: /konferencje/*/podsumowanie
Disallow: /konferencje/*/podziekowanie
Disallow: /konferencje/potwierdzenie
Disallow: /konferencje/uczestnik
Disallow: /konferencje/proforma
Disallow: /bnp-paribas
Disallow: /bnp-paribas/rejestracja
Sitemap: https://www.pb.pl/sitemap/index
