# robots.txt automaticaly generated by PrestaShop e-commerce open-source solution
# http://www.prestashop.com - http://www.prestashop.com/forums
# This file is to prevent the crawling and indexing of certain parts
# of your site by web crawlers and spiders run by sites like Yahoo!
# and Google. By telling these "robots" where not to go on your site,
# you save bandwidth and server resources.
# For more information about the robots.txt standard, see:
# http://www.robotstxt.org/wc/robots.html
User-agent: *
# Private pages
Disallow: /*orderby=
Disallow: /*orderway=
Disallow: /*tag=
Disallow: /*id_currency=
Disallow: /*search_query=
Disallow: /*back=
Disallow: /*n=
Disallow: /*controller=addresses
Disallow: /*controller=address
Disallow: /*controller=authentication
Disallow: /*controller=cart
Disallow: /*controller=discount
Disallow: /*controller=footer
Disallow: /*controller=get-file
Disallow: /*controller=header
Disallow: /*controller=history
Disallow: /*controller=identity
Disallow: /*controller=images.inc
Disallow: /*controller=init
Disallow: /*controller=my-account
Disallow: /*controller=order
Disallow: /*controller=order-opc
Disallow: /*controller=order-slip
Disallow: /*controller=order-detail
Disallow: /*controller=order-follow
Disallow: /*controller=order-return
Disallow: /*controller=order-confirmation
Disallow: /*controller=pagination
Disallow: /*controller=password
Disallow: /*controller=pdf-invoice
Disallow: /*controller=pdf-order-return
Disallow: /*controller=pdf-order-slip
Disallow: /*controller=product-sort
Disallow: /*controller=search
Disallow: /*controller=statistics
Disallow: /*controller=attachment
Disallow: /*controller=guest-tracking
# Directories
Disallow: */classes/
Disallow: */config/
Disallow: */download/
Disallow: */mails/
Disallow: */modules/
Disallow: */translations/
Disallow: */tools/
# Files
Disallow: /odzyskiwanie-hasla
Disallow: /adres
Disallow: /adresy
Disallow: /logowanie
Disallow: /koszyk
Disallow: /rabaty
Disallow: /historia-zamowien
Disallow: /dane-osobiste
Disallow: /moje-konto
Disallow: /sledzenie-zamowienia
Disallow: /pokwitowania
Disallow: /zamowienie
Disallow: /szukaj
Disallow: /szybkie-zakupy
Disallow: /sledzenie-zamowienia-gosc
Disallow: /potwierdzenie-zamowienia

Disallow: /2-glowna
Disallow: /logowanie
Disallow: /content/category/2-komentarze
Disallow: /blogs/category/4-edytor-online.html
Disallow: /*?content_only*
Disallow: /5-fotokalendarze
Disallow: /62-fotoksiazki-slub
Disallow: /71-pusty-proje
Disallow: /79-julcia
Disallow: /78-dziennik-podrozy
Disallow: /15-fotoksiazki-podroz
Disallow: /80-kolorowe-kwadraty
Disallow: /41-w-ciemnej-tonacji
Disallow: /55-retro
Disallow: /34-chicago
Disallow: /67-janek
Disallow: /74-janek
Disallow: /76-walentynka
Disallow: /70-retro
Disallow: /60-elegancka
Disallow: /57-pusty-projekt
Disallow: /31-milosne-cytaty
Disallow: /66-kolorowe-zoo
Disallow: /56-pusty-projekt
Disallow: /39-fotoksiazki-okolicznosciowe
Disallow: /16-fotoksiazki-slub
Disallow: /59-fotoksiazki-uniwersalne
Disallow: /30-fotoksiazki-uniwersalne
Disallow: /52-fotoksiazki-slub
Disallow: /49-fotoksiazki-uniwersalne
Disallow: /65-fotoksiazki-dziecko
Disallow: /28-z-kwiatowym-motywem
Disallow: /68-cytaty-o-milosci
Disallow: /82-fotoksiazka-zielono-mi
Disallow: /61-w-ciemnej-tonacji
Disallow: /64-w-jasnej-tonacji
Disallow: /27-julek
Disallow: /36-elegancka
Disallow: /26-julcia
Disallow: /81-chicago
Disallow: /18-niezapomniane-chwile
Disallow: /45-schoolbook-3
Disallow: /38-szalone-wakacje
Disallow: /42-fotoksiazki-szkolne-schoolbook
Disallow: /33-kolorowe-zoo
Disallow: /35-rodzinna
Disallow: /23-rodzinna-1
Disallow: /25-janek
Disallow: /content/3-regulamin
User-agent: Googlebot

Disallow:
User-agent: AdsBot-Google
Disallow:
User-agent: Googlebot-Image
Disallow:

Sitemap: https://lumabook.pl/1_pl_0_sitemap.xml


