User-agent: *
Disallow: /config/
Disallow: /download/
Disallow: /mails/
Disallow: /addresses.php
Disallow: /address.php
Disallow: /authentication.php
Disallow: /cart.php
Disallow: /discount.php
Disallow: /footer.php
Disallow: /get-file.php
Disallow: /header.php
Disallow: /history.php
Disallow: /identity.php
Disallow: /init.php
Disallow: /product-sort.php
Disallow: /statistics.php
Disallow: /attachment.php
Disallow: /guest-tracking
Disallow: /*login
Disallow: /*cart?
Disallow: /*order
Disallow: /*my-account
Allow: /themes/prestashop/css/
Allow: /themes/prestashop/img/icon/
Allow: /modules/jbx_menu/gfx/menu/
Allow: /

