User-agent: *
User-agent: Googlebot
Disallow:
User-agent: Googlebot-image
Sitemap: https://madomi.pl/1_pl_0_sitemap.xml
Disallow:
Disallow: /aukcje/
Disallow: /sk/
Disallow: /classes/
Disallow: /config/
Disallow: /controllers/
Disallow: /download/
Disallow: /mails/
Disallow: /modules/
Disallow: /translations/
Disallow: /tools/
Disallow: /madomi81/
Disallow: /old/
Disallow: /dodatki/
Disallow: /dodatki_slubne1/
Disallow: /dokumenty/
Disallow: /komentarze/
Disallow: /komentarze_madomi_pl/
Disallow: /misiaszek/
Disallow: /moj/
Disallow: /katalog/
Disallow: /allegro/
Disallow: /allegro2/
Disallow: /de/
Disallow: /en/
Disallow: /pl/content/6-regulamin
Disallow: /addresses.php
Disallow: /address.php
Disallow: /authentication.php
Disallow: /cart.php
Disallow: /contact-form.php
Disallow: /discount.php
Disallow: /get-file.php
Disallow: /header.php
Disallow: /history.php
Disallow: /identity.php
Disallow: /images.inc.php
Disallow: /init.php
Disallow: /my-account.php
Disallow: /order.php
Disallow: /order-slip.php
Disallow: /order-detail.php
Disallow: /order-follow.php
Disallow: /order-return.php
Disallow: /order-confirmation.php
Disallow: /pagination.php
Disallow: /password.php
Disallow: /pdf-invoice.php
Disallow: /pdf-order-return.php
Disallow: /pdf-order-slip.php
Disallow: /product-sort.php
Disallow: /search.php
Disallow: /statistics.php
Disallow: /zoom.php

