User-agent: *
Disallow: /.PAST
Disallow: /admin
Disallow: /biblio
Disallow: /cache
Disallow: /config
Disallow: /css
Disallow: /img
Disallow: /inc
Disallow: /js
Disallow: /ks
Disallow: /locale
Disallow: /materialy
Disallow: /moodle_pliki
Disallow: /pages
Disallow: /panels
Disallow: /plugins
Disallow: /themes
Disallow: /uploads
Disallow: /zebrania
Disallow: /updates.php
Disallow: /php.ini
