<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="pl" lang="pl">
<head>
<title>Strona WWW - Blad 404</title>

<base href="http://milag.pl/" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

<link rel="stylesheet" type="text/css" href="/tmp/cache/stylesheet_combined_fae5a76721b38ed2de8f36ceee21117f.css" />
<link rel="stylesheet" type="text/css" href="/tmp/cache/stylesheet_combined_236f20d10b8aac73ed0fde5d99632084.css" media="screen" />

<!--[if lte IE 7]><link rel="stylesheet" type="text/css" href="/tmp/cache/stylesheet_combined_fd27d1c43da63da3b2e2c2a3513c59aa.css" />
<![endif]-->

<!--css for show1-->
<link rel="stylesheet" type="text/css" href="uploads/Showtime/Show_1.css" />
<!--LOAD SHOWTIME swfobject-->
<script type="text/javascript" src="http://milag.pl/modules/Showtime/showtime/swfobject/swfobject.js?ver=2.2"></script>
<!--END SHOWTIME-->
</head> <body id="404 Error">
<div id="wrapper">
<!-- top -->
<div id="top">
<h1><a href=" "><p><span style="color: #ffffff;"><span style="font-family: arial black,avant garde;">MILAG MICHAL LAGA</span></span></p>
<p> </p>
<p> </p>
<p> </p>
<p> </p>
<p> </p></a></h1>
<h2>Stawiamy na jakosc!</h2>
<div class="top_picture">
<!-- generated by showtime Module start -->
<script type='text/javascript'>

var flashvars =  {
xml 			: 'http://milag.pl/modules/Showtime/showtime/getxml.php?showid=1',
width           : '768',
height          : '254',
classid         : 'st_1',
rotationtime    : '5',
transition      : 'KenBurns',
transitiontime  : '1',
transitionease  : 'LinearEaseNone',
autoplay        : 'on',
showcontrols    : 'on',
controls        : '1004',
textbgcolor     : '#000000',
showtext        : '',
showalt         : 'on',
shuffle         : '',
scale           : 'exactfit',
target          : ''
};

var params = {};
params.allowFullScreen = 'true';
params.bgcolor = '#000000';
params.quality = 'autohigh';
params.wmode = 'window';
//params.wmode = 'transparent';
//params.base = 'dirname(__FILE__)';
params.allowScriptAccess = 'always';
params.allowNetworking = 'all';

var attributes = {};
attributes.styleclass = 'showtime';

swfobject.embedSWF ('http://milag.pl/modules/Showtime/showtime/st16.swf', 'st_1', '768', '254', '10.0.0', 'false', flashvars, params, attributes);
</script>

<!-- alternative content -->
<div id='st_1'>
<div id='gallery-1' class='gallery'>
<dl class='gallery-item'><dt class='gallery-icon'><img width='768' height='254' src='http://strona.michallaga.nazwa.pl/uploads/images/slider/foto1.jpg' class='attachment-thumbnail' alt='' title='foto1.jpg' /></dt></dl>
<dl class='gallery-item'><dt class='gallery-icon'><img width='768' height='254' src='http://strona.michallaga.nazwa.pl/uploads/images/slider/foto2.jpg' class='attachment-thumbnail' alt='' title='foto2.jpg' /></dt></dl>
<dl class='gallery-item'><dt class='gallery-icon'><img width='768' height='254' src='http://strona.michallaga.nazwa.pl/uploads/images/slider/foto3.jpg' class='attachment-thumbnail' alt='' title='foto3.jpg' /></dt></dl>
<dl class='gallery-item'><dt class='gallery-icon'><img width='768' height='254' src='http://strona.michallaga.nazwa.pl/uploads/images/slider/foto4.jpg' class='attachment-thumbnail' alt='' title='foto4.jpg' /></dt></dl>
<dl class='gallery-item'><dt class='gallery-icon'><img width='768' height='254' src='http://strona.michallaga.nazwa.pl/uploads/images/slider/foto5.jpg' class='attachment-thumbnail' alt='' title='foto5.jpg' /></dt></dl>

<br style='clear: both;' />
</div>
</div>
<!-- generated by showtime Module end -->
</div>
<!--MENU-->
<div class="menu">
<div id="menuwrapper">
<ul id="primary-nav">

<li id="menu_index"

><a
href="index" accesskey="1" title="Strona glown">

Strona glowna</a>



</li>

<li id="menu_oferta"

><a
href="/oferta.html">

Oferta</a>



</li>

<li id="menu_realizacje"

><a
href="/realizacje.html">

Realizacje</a>



</li>

<li id="menu_galeria"

><a
href="/galeria.html">

Galeria</a>



</li>

<li id="menu_referencje"

><a
href="/referencje.html">

Referencje</a>



</li>

<li id="menu_kontakt"

><a
href="/kontakt.html">

Kontakt</a>



</li>

<li id="menu_grudziadz"

class="last"><a
href="/grudziadz.html">

Grudziadz</a>



</li>
</ul>
<div class="clearb"></div>
</div>

</div>
<!--MENU-->
</div>
<!-- end top -->

<!-- content -->
<div id="content">


<div id="main">
<h2>Blad 404</h2>
<div class="article"><p>Podana strona nie istnieje.</p>
<p>Przejdz do:</p>

<ul>
<li><a href="/">Strona glowna</a></li>
<li><a href="/oferta.html">Oferta</a></li>
<li><a href="/realizacje.html">Realizacje</a></li>
<li><a href="/galeria.html">Galeria</a></li>
<li><a href="/referencje.html">Referencje</a></li>
<li><a href="/kontakt.html">Kontakt</a></li>
<li><a href="/grudziadz.html">Grudziadz</a></li>
</ul></div>

</div>


<div id="sub">
<h2 style="text-align: center;">wspolpraca:</h2>
<table border="0" align="center">
<tbody>
<tr>
<td><img style="width: 180px; height: 75px; margin-right: auto; margin-left: auto; display: block;" src="uploads/images/Gallery/LOGO/gddkia.png" alt="" width="28" height="30" /></td>
</tr>
</tbody>
</table>
<table border="0" align="center">
<tbody>
<tr>
<td><img style="width: 65px; height: 75px; float: left;" src="uploads/images/Gallery/LOGO/beznazwy.png" alt="" /></td>
<td><img style="width: 65px; height: 75px;" src="uploads/images/Gallery/LOGO/herb-2012-bez-tla.png" alt="" /></td>
</tr>
<tr>
<td><img style="width: 65px; height: 75px;" src="uploads/images/Gallery/LOGO/bialybor.png" alt="" /></td>
<td><img style="width: 65px; height: 100px;" src="uploads/images/Gallery/LOGO/przelewice.png" alt="" /></td>
</tr>
<tr>
<td><img style="width: 70px; height: 57px;" src="uploads/images/Gallery/LOGO/pwik-debno.png" alt="" /></td>
<td><img style="width: 65px; height: 65px;" src="uploads/images/Gallery/LOGO/lp.png" alt="" /></td>
</tr>
</tbody>
</table>
<p> </p>
<div class="box">
<h2 class="yellow">Kontakt z nami</h2>
<h4>Michal Laga</h4>
<p>tel. 506 550 121</p>
<p>e-mail: <a href="mailto:michal.laga@wp.pl">milag@milag.pl</a></p>
</div>
</div>


</div>
<!-- end content -->

<!-- footer -->
<div id="footer">
<p>Copyright &copy; 2019 <a href="http://www.nazwa.pl" rel="blank" title="Domeny, Serwery, Hosting, Strony WWW">nazwa.pl</a></p>

<ul class="clearfix">

<li class="first"><a href="index"> Strona glowna </a>


</li>

<li ><a href="/oferta.html"> Oferta </a>


</li>

<li ><a href="/realizacje.html"> Realizacje </a>


</li>

<li ><a href="/galeria.html"> Galeria </a>


</li>

<li ><a href="/referencje.html"> Referencje </a>


</li>

<li ><a href="/kontakt.html"> Kontakt </a>


</li>

<li class="last"><a href="/grudziadz.html"> Grudziadz </a>



</li>
</ul>

</div>
<!-- end footer -->
</div>
<script type="text/javascript">
var aCMSCounter = document.getElementById("aCMSCounter");

if (aCMSCounter != undefined) {
aCMSCounter.innerHTML = "193929";
}
</script></body>
</html>
