User-agent: *
Allow: /
Disallow /en-it/*
Sitemap: https://www.modis.com/sitemap-modis-us-en.xml
Sitemap: https://www.modis.com/sitemap-modis-au-en.xml
Sitemap: https://www.modis.com/sitemap-modis-uk-en.xml
Sitemap: https://www.modis.com/sitemap-modis.xml
Sitemap: https://www.modis.com/sitemap-modis-nl-nl.xml
Sitemap: https://www.modis.com/sitemap-modis-en-nl.xml
Sitemap: https://www.modis.com/sitemap-modis-es-es.xml
Sitemap: https://www.modis.com/sitemap-modis-en-es.xml
Sitemap: https://www.modis.com/sitemap-modis-sv-se.xml
Sitemap: https://www.modis.com/sitemap-modis-nb-no.xml
Sitemap: https://www.modis.com/sitemap-modis-en-bg.xml
Sitemap: https://www.modis.com/sitemap-modis-en-it.xml
Sitemap: https://www.modis.com/sitemap-modis-it-it.xml
Sitemap: https://www.modis.com/sitemap-modis-en-ca.xml
Sitemap: https://www.modis.com/sitemap-modis-fr-ca.xml
