# Alexa
User-agent: ia_archiver
Allow: /
Disallow: /category
Disallow: /category/aktualnosci
Disallow: /zbiory/katalog/stare
Disallow: /zbiory/katalog/admin
Disallow: /zbiory/adr/admin
Disallow: /zbiory/arch/admin
Disallow: /zbiory/biblio/admin
Disallow: /zbiory/kon/admin
Disallow: /html
Disallow: /html/old
Disallow: /html/generator
Disallow: /html1
Disallow: /html2
Disallow: /admin
Disallow: /test
Disallow: /gen
Disallow: /platnik
Disallow: /html10
Disallow: /html20
Disallow: /tomaszow
Disallow: /zbiory/katalog/include
Disallow: /inw
Disallow: /zbiory/katalog/en0
Disallow: /zbiory/katalog/de0
Disallow: /zbiory/katalog/fr0
Disallow: /zbiory/katalog/pl0
Disallow: /zbiory/katalog/uk0
Disallow:/author/admin

# Ask Jeeves
User-agent: Teoma
Allow: /
Disallow: /category
Disallow: /category/aktualnosci
Disallow: /zbiory/katalog/stare
Disallow: /zbiory/katalog/admin
Disallow: /zbiory/adr/admin
Disallow: /zbiory/arch/admin
Disallow: /zbiory/biblio/admin
Disallow: /zbiory/kon/admin
Disallow: /html
Disallow: /html/old
Disallow: /html/generator
Disallow: /html1
Disallow: /html2
Disallow: /admin
Disallow: /test
Disallow: /gen
Disallow: /platnik
Disallow: /html10
Disallow: /html20
Disallow: /tomaszow
Disallow: /zbiory/katalog/include
Disallow: /inw
Disallow: /zbiory/katalog/en0
Disallow: /zbiory/katalog/de0
Disallow: /zbiory/katalog/fr0
Disallow: /zbiory/katalog/pl0
Disallow: /zbiory/katalog/uk0
Disallow:/author/admin

# Google
User-agent: googlebot
Allow: /
Disallow: /category
Disallow: /category/aktualnosci
Disallow: /zbiory/katalog/stare
Disallow: /zbiory/katalog/admin
Disallow: /zbiory/adr/admin
Disallow: /zbiory/arch/admin
Disallow: /zbiory/biblio/admin
Disallow: /zbiory/kon/admin
Disallow: /html
Disallow: /html/old
Disallow: /html/generator
Disallow: /html1
Disallow: /html2
Disallow: /admin
Disallow: /test
Disallow: /gen
Disallow: /platnik
Disallow: /html10
Disallow: /html20
Disallow: /tomaszow
Disallow: /zbiory/katalog/include
Disallow: /inw
Disallow: /zbiory/katalog/en0
Disallow: /zbiory/katalog/de0
Disallow: /zbiory/katalog/fr0
Disallow: /zbiory/katalog/pl0
Disallow: /zbiory/katalog/uk0
Disallow:/author/admin

# MSN
User-agent: msnbot
Allow: /
Disallow: /category
Disallow: /category/aktualnosci
Disallow: /zbiory/katalog/stare
Disallow: /zbiory/katalog/admin
Disallow: /zbiory/adr/admin
Disallow: /zbiory/arch/admin
Disallow: /zbiory/biblio/admin
Disallow: /zbiory/kon/admin
Disallow: /html
Disallow: /html/old
Disallow: /html/generator
Disallow: /html1
Disallow: /html2
Disallow: /admin
Disallow: /test
Disallow: /gen
Disallow: /platnik
Disallow: /html10
Disallow: /html20
Disallow: /tomaszow
Disallow: /zbiory/katalog/include
Disallow: /inw
Disallow: /zbiory/katalog/en0
Disallow: /zbiory/katalog/de0
Disallow: /zbiory/katalog/fr0
Disallow: /zbiory/katalog/pl0
Disallow: /zbiory/katalog/uk0
Disallow:/author/admin

# Yahoo!
User-agent: Slurp
Allow: /
Disallow: /category
Disallow: /category/aktualnosci
Disallow: /zbiory/katalog/stare
Disallow: /zbiory/katalog/admin
Disallow: /zbiory/adr/admin
Disallow: /zbiory/arch/admin
Disallow: /zbiory/biblio/admin
Disallow: /zbiory/kon/admin
Disallow: /html
Disallow: /html/old
Disallow: /html/generator
Disallow: /html1
Disallow: /html2
Disallow: /admin
Disallow: /test
Disallow: /gen
Disallow: /platnik
Disallow: /html10
Disallow: /html20
Disallow: /tomaszow
Disallow: /zbiory/katalog/include
Disallow: /inw
Disallow: /zbiory/katalog/en0
Disallow: /zbiory/katalog/de0
Disallow: /zbiory/katalog/fr0
Disallow: /zbiory/katalog/pl0
Disallow: /zbiory/katalog/uk0
Disallow:/author/admin

# Amfibi
User-agent: Amfibibot
Allow: /
Disallow: /category
Disallow: /category/aktualnosci
Disallow: /zbiory/katalog/stare
Disallow: /zbiory/katalog/admin
Disallow: /zbiory/adr/admin
Disallow: /zbiory/arch/admin
Disallow: /zbiory/biblio/admin
Disallow: /zbiory/kon/admin
Disallow: /html
Disallow: /html/old
Disallow: /html/generator
Disallow: /html1
Disallow: /html2
Disallow: /admin
Disallow: /test
Disallow: /gen
Disallow: /platnik
Disallow: /html10
Disallow: /html20
Disallow: /tomaszow
Disallow: /zbiory/katalog/include
Disallow: /inw
Disallow: /zbiory/katalog/en0
Disallow: /zbiory/katalog/de0
Disallow: /zbiory/katalog/fr0
Disallow: /zbiory/katalog/pl0
Disallow: /zbiory/katalog/uk0
Disallow:/author/admin

# Amidalla
User-agent: amibot
Allow: /
Disallow: /category
Disallow: /category/aktualnosci
Disallow: /zbiory/katalog/stare
Disallow: /zbiory/katalog/admin
Disallow: /zbiory/adr/admin
Disallow: /zbiory/arch/admin
Disallow: /zbiory/biblio/admin
Disallow: /zbiory/kon/admin
Disallow: /html
Disallow: /html/old
Disallow: /html/generator
Disallow: /html1
Disallow: /html2
Disallow: /admin
Disallow: /test
Disallow: /gen
Disallow: /platnik
Disallow: /html10
Disallow: /html20
Disallow: /tomaszow
Disallow: /zbiory/katalog/include
Disallow: /inw
Disallow: /zbiory/katalog/en0
Disallow: /zbiory/katalog/de0
Disallow: /zbiory/katalog/fr0
Disallow: /zbiory/katalog/pl0
Disallow: /zbiory/katalog/uk0
Disallow:/author/admin

# ASPseek.com
User-agent: ASPseek
Allow: /
Disallow: /category
Disallow: /category/aktualnosci
Disallow: /zbiory/katalog/stare
Disallow: /zbiory/katalog/admin
Disallow: /zbiory/adr/admin
Disallow: /zbiory/arch/admin
Disallow: /zbiory/biblio/admin
Disallow: /zbiory/kon/admin
Disallow: /html
Disallow: /html/old
Disallow: /html/generator
Disallow: /html1
Disallow: /html2
Disallow: /admin
Disallow: /test
Disallow: /gen
Disallow: /platnik
Disallow: /html10
Disallow: /html20
Disallow: /tomaszow
Disallow: /zbiory/katalog/include
Disallow: /inw
Disallow: /zbiory/katalog/en0
Disallow: /zbiory/katalog/de0
Disallow: /zbiory/katalog/fr0
Disallow: /zbiory/katalog/pl0
Disallow: /zbiory/katalog/uk0
Disallow:/author/admin

# BDNcentral
User-agent: BDNcentral
Allow: /
Disallow: /category
Disallow: /category/aktualnosci
Disallow: /zbiory/katalog/stare
Disallow: /zbiory/katalog/admin
Disallow: /zbiory/adr/admin
Disallow: /zbiory/arch/admin
Disallow: /zbiory/biblio/admin
Disallow: /zbiory/kon/admin
Disallow: /html
Disallow: /html/old
Disallow: /html/generator
Disallow: /html1
Disallow: /html2
Disallow: /admin
Disallow: /test
Disallow: /gen
Disallow: /platnik
Disallow: /html10
Disallow: /html20
Disallow: /tomaszow
Disallow: /zbiory/katalog/include
Disallow: /inw
Disallow: /zbiory/katalog/en0
Disallow: /zbiory/katalog/de0
Disallow: /zbiory/katalog/fr0
Disallow: /zbiory/katalog/pl0
Disallow: /zbiory/katalog/uk0
Disallow:/author/admin

# Become.com
User-agent: BecomeBot
Allow: /
Disallow: /category
Disallow: /category/aktualnosci
Disallow: /zbiory/katalog/stare
Disallow: /zbiory/katalog/admin
Disallow: /zbiory/adr/admin
Disallow: /zbiory/arch/admin
Disallow: /zbiory/biblio/admin
Disallow: /zbiory/kon/admin
Disallow: /html
Disallow: /html/old
Disallow: /html/generator
Disallow: /html1
Disallow: /html2
Disallow: /admin
Disallow: /test
Disallow: /gen
Disallow: /platnik
Disallow: /html10
Disallow: /html20
Disallow: /tomaszow
Disallow: /zbiory/katalog/include
Disallow: /inw
Disallow: /zbiory/katalog/en0
Disallow: /zbiory/katalog/de0
Disallow: /zbiory/katalog/fr0
Disallow: /zbiory/katalog/pl0
Disallow: /zbiory/katalog/uk0
Disallow:/author/admin

# BigClique
User-agent: BigCliqueBOT
Allow: /
Disallow: /category
Disallow: /category/aktualnosci
Disallow: /zbiory/katalog/stare
Disallow: /zbiory/katalog/admin
Disallow: /zbiory/adr/admin
Disallow: /zbiory/arch/admin
Disallow: /zbiory/biblio/admin
Disallow: /zbiory/kon/admin
Disallow: /html
Disallow: /html/old
Disallow: /html/generator
Disallow: /html1
Disallow: /html2
Disallow: /admin
Disallow: /test
Disallow: /gen
Disallow: /platnik
Disallow: /html10
Disallow: /html20
Disallow: /tomaszow
Disallow: /zbiory/katalog/include
Disallow: /inw
Disallow: /zbiory/katalog/en0
Disallow: /zbiory/katalog/de0
Disallow: /zbiory/katalog/fr0
Disallow: /zbiory/katalog/pl0
Disallow: /zbiory/katalog/uk0
Disallow:/author/admin

# Boitho
User-agent: boitho.com-dc
Allow: /
Disallow: /category
Disallow: /category/aktualnosci
Disallow: /zbiory/katalog/stare
Disallow: /zbiory/katalog/admin
Disallow: /zbiory/adr/admin
Disallow: /zbiory/arch/admin
Disallow: /zbiory/biblio/admin
Disallow: /zbiory/kon/admin
Disallow: /html
Disallow: /html/old
Disallow: /html/generator
Disallow: /html1
Disallow: /html2
Disallow: /admin
Disallow: /test
Disallow: /gen
Disallow: /platnik
Disallow: /html10
Disallow: /html20
Disallow: /tomaszow
Disallow: /zbiory/katalog/include
Disallow: /inw
Disallow: /zbiory/katalog/en0
Disallow: /zbiory/katalog/de0
Disallow: /zbiory/katalog/fr0
Disallow: /zbiory/katalog/pl0
Disallow: /zbiory/katalog/uk0
Disallow:/author/admin

# Convera
User-agent: ConveraCrawler
Allow: /
Disallow: /category
Disallow: /category/aktualnosci
Disallow: /zbiory/katalog/stare
Disallow: /zbiory/katalog/admin
Disallow: /zbiory/adr/admin
Disallow: /zbiory/arch/admin
Disallow: /zbiory/biblio/admin
Disallow: /zbiory/kon/admin
Disallow: /html
Disallow: /html/old
Disallow: /html/generator
Disallow: /html1
Disallow: /html2
Disallow: /admin
Disallow: /test
Disallow: /gen
Disallow: /platnik
Disallow: /html10
Disallow: /html20
Disallow: /tomaszow
Disallow: /zbiory/katalog/include
Disallow: /inw
Disallow: /zbiory/katalog/en0
Disallow: /zbiory/katalog/de0
Disallow: /zbiory/katalog/fr0
Disallow: /zbiory/katalog/pl0
Disallow: /zbiory/katalog/uk0
Disallow:/author/admin

# DailyOrbit.com
User-agent: Orbiter
Allow: /
Disallow: /category
Disallow: /category/aktualnosci
Disallow: /zbiory/katalog/stare
Disallow: /zbiory/katalog/admin
Disallow: /zbiory/adr/admin
Disallow: /zbiory/arch/admin
Disallow: /zbiory/biblio/admin
Disallow: /zbiory/kon/admin
Disallow: /html
Disallow: /html/old
Disallow: /html/generator
Disallow: /html1
Disallow: /html2
Disallow: /admin
Disallow: /test
Disallow: /gen
Disallow: /platnik
Disallow: /html10
Disallow: /html20
Disallow: /tomaszow
Disallow: /zbiory/katalog/include
Disallow: /inw
Disallow: /zbiory/katalog/en0
Disallow: /zbiory/katalog/de0
Disallow: /zbiory/katalog/fr0
Disallow: /zbiory/katalog/pl0
Disallow: /zbiory/katalog/uk0
Disallow:/author/admin

# Daypop
User-agent: Daypopbot
Allow: /
Disallow: /category
Disallow: /category/aktualnosci
Disallow: /zbiory/katalog/stare
Disallow: /zbiory/katalog/admin
Disallow: /zbiory/adr/admin
Disallow: /zbiory/arch/admin
Disallow: /zbiory/biblio/admin
Disallow: /zbiory/kon/admin
Disallow: /html
Disallow: /html/old
Disallow: /html/generator
Disallow: /html1
Disallow: /html2
Disallow: /admin
Disallow: /test
Disallow: /gen
Disallow: /platnik
Disallow: /html10
Disallow: /html20
Disallow: /tomaszow
Disallow: /zbiory/katalog/include
Disallow: /inw
Disallow: /zbiory/katalog/en0
Disallow: /zbiory/katalog/de0
Disallow: /zbiory/katalog/fr0
Disallow: /zbiory/katalog/pl0
Disallow: /zbiory/katalog/uk0
Disallow:/author/admin

# dir.com
User-agent: Pompos
Allow: /
Disallow: /category
Disallow: /category/aktualnosci
Disallow: /zbiory/katalog/stare
Disallow: /zbiory/katalog/admin
Disallow: /zbiory/adr/admin
Disallow: /zbiory/arch/admin
Disallow: /zbiory/biblio/admin
Disallow: /zbiory/kon/admin
Disallow: /html
Disallow: /html/old
Disallow: /html/generator
Disallow: /html1
Disallow: /html2
Disallow: /admin
Disallow: /test
Disallow: /gen
Disallow: /platnik
Disallow: /html10
Disallow: /html20
Disallow: /tomaszow
Disallow: /zbiory/katalog/include
Disallow: /inw
Disallow: /zbiory/katalog/en0
Disallow: /zbiory/katalog/de0
Disallow: /zbiory/katalog/fr0
Disallow: /zbiory/katalog/pl0
Disallow: /zbiory/katalog/uk0
Disallow:/author/admin

# FyberSearch
User-agent: FyberSpider
Allow: /
Disallow: /category
Disallow: /category/aktualnosci
Disallow: /zbiory/katalog/stare
Disallow: /zbiory/katalog/admin
Disallow: /zbiory/adr/admin
Disallow: /zbiory/arch/admin
Disallow: /zbiory/biblio/admin
Disallow: /zbiory/kon/admin
Disallow: /html
Disallow: /html/old
Disallow: /html/generator
Disallow: /html1
Disallow: /html2
Disallow: /admin
Disallow: /test
Disallow: /gen
Disallow: /platnik
Disallow: /html10
Disallow: /html20
Disallow: /tomaszow
Disallow: /zbiory/katalog/include
Disallow: /inw
Disallow: /zbiory/katalog/en0
Disallow: /zbiory/katalog/de0
Disallow: /zbiory/katalog/fr0
Disallow: /zbiory/katalog/pl0
Disallow: /zbiory/katalog/uk0
Disallow:/author/admin

# Galaxy
User-agent: GalaxyBot
Allow: /
Disallow: /category
Disallow: /category/aktualnosci
Disallow: /zbiory/katalog/stare
Disallow: /zbiory/katalog/admin
Disallow: /zbiory/adr/admin
Disallow: /zbiory/arch/admin
Disallow: /zbiory/biblio/admin
Disallow: /zbiory/kon/admin
Disallow: /html
Disallow: /html/old
Disallow: /html/generator
Disallow: /html1
Disallow: /html2
Disallow: /admin
Disallow: /test
Disallow: /gen
Disallow: /platnik
Disallow: /html10
Disallow: /html20
Disallow: /tomaszow
Disallow: /zbiory/katalog/include
Disallow: /inw
Disallow: /zbiory/katalog/en0
Disallow: /zbiory/katalog/de0
Disallow: /zbiory/katalog/fr0
Disallow: /zbiory/katalog/pl0
Disallow: /zbiory/katalog/uk0
Disallow:/author/admin

# Geona
User-agent: GeonaBot
Allow: /
Disallow: /category
Disallow: /category/aktualnosci
Disallow: /zbiory/katalog/stare
Disallow: /zbiory/katalog/admin
Disallow: /zbiory/adr/admin
Disallow: /zbiory/arch/admin
Disallow: /zbiory/biblio/admin
Disallow: /zbiory/kon/admin
Disallow: /html
Disallow: /html/old
Disallow: /html/generator
Disallow: /html1
Disallow: /html2
Disallow: /admin
Disallow: /test
Disallow: /gen
Disallow: /platnik
Disallow: /html10
Disallow: /html20
Disallow: /tomaszow
Disallow: /zbiory/katalog/include
Disallow: /inw
Disallow: /zbiory/katalog/en0
Disallow: /zbiory/katalog/de0
Disallow: /zbiory/katalog/fr0
Disallow: /zbiory/katalog/pl0
Disallow: /zbiory/katalog/uk0
Disallow:/author/admin

# Girafa.com
User-agent: Girafabot
Allow: /
Disallow: /category
Disallow: /category/aktualnosci
Disallow: /zbiory/katalog/stare
Disallow: /zbiory/katalog/admin
Disallow: /zbiory/adr/admin
Disallow: /zbiory/arch/admin
Disallow: /zbiory/biblio/admin
Disallow: /zbiory/kon/admin
Disallow: /html
Disallow: /html/old
Disallow: /html/generator
Disallow: /html1
Disallow: /html2
Disallow: /admin
Disallow: /test
Disallow: /gen
Disallow: /platnik
Disallow: /html10
Disallow: /html20
Disallow: /tomaszow
Disallow: /zbiory/katalog/include
Disallow: /inw
Disallow: /zbiory/katalog/en0
Disallow: /zbiory/katalog/de0
Disallow: /zbiory/katalog/fr0
Disallow: /zbiory/katalog/pl0
Disallow: /zbiory/katalog/uk0
Disallow:/author/admin

# GoForIt
User-agent: Goforitbot
Allow: /
Disallow: /category
Disallow: /category/aktualnosci
Disallow: /zbiory/katalog/stare
Disallow: /zbiory/katalog/admin
Disallow: /zbiory/adr/admin
Disallow: /zbiory/arch/admin
Disallow: /zbiory/biblio/admin
Disallow: /zbiory/kon/admin
Disallow: /html
Disallow: /html/old
Disallow: /html/generator
Disallow: /html1
Disallow: /html2
Disallow: /admin
Disallow: /test
Disallow: /gen
Disallow: /platnik
Disallow: /html10
Disallow: /html20
Disallow: /tomaszow
Disallow: /zbiory/katalog/include
Disallow: /inw
Disallow: /zbiory/katalog/en0
Disallow: /zbiory/katalog/de0
Disallow: /zbiory/katalog/fr0
Disallow: /zbiory/katalog/pl0
Disallow: /zbiory/katalog/uk0
Disallow:/author/admin

# IBM
User-agent: Crawler
Allow: /
Disallow: /category
Disallow: /category/aktualnosci
Disallow: /zbiory/katalog/stare
Disallow: /zbiory/katalog/admin
Disallow: /zbiory/adr/admin
Disallow: /zbiory/arch/admin
Disallow: /zbiory/biblio/admin
Disallow: /zbiory/kon/admin
Disallow: /html
Disallow: /html/old
Disallow: /html/generator
Disallow: /html1
Disallow: /html2
Disallow: /admin
Disallow: /test
Disallow: /gen
Disallow: /platnik
Disallow: /html10
Disallow: /html20
Disallow: /tomaszow
Disallow: /zbiory/katalog/include
Disallow: /inw
Disallow: /zbiory/katalog/en0
Disallow: /zbiory/katalog/de0
Disallow: /zbiory/katalog/fr0
Disallow: /zbiory/katalog/pl0
Disallow: /zbiory/katalog/uk0
Disallow:/author/admin

# Inelegant
User-agent: nelaBot
Allow: /
Disallow: /category
Disallow: /category/aktualnosci
Disallow: /zbiory/katalog/stare
Disallow: /zbiory/katalog/admin
Disallow: /zbiory/adr/admin
Disallow: /zbiory/arch/admin
Disallow: /zbiory/biblio/admin
Disallow: /zbiory/kon/admin
Disallow: /html
Disallow: /html/old
Disallow: /html/generator
Disallow: /html1
Disallow: /html2
Disallow: /admin
Disallow: /test
Disallow: /gen
Disallow: /platnik
Disallow: /html10
Disallow: /html20
Disallow: /tomaszow
Disallow: /zbiory/katalog/include
Disallow: /inw
Disallow: /zbiory/katalog/en0
Disallow: /zbiory/katalog/de0
Disallow: /zbiory/katalog/fr0
Disallow: /zbiory/katalog/pl0
Disallow: /zbiory/katalog/uk0
Disallow:/author/admin

# IRL
User-agent: IRLbot
Allow: /
Disallow: /category
Disallow: /category/aktualnosci
Disallow: /zbiory/katalog/stare
Disallow: /zbiory/katalog/admin
Disallow: /zbiory/adr/admin
Disallow: /zbiory/arch/admin
Disallow: /zbiory/biblio/admin
Disallow: /zbiory/kon/admin
Disallow: /html
Disallow: /html/old
Disallow: /html/generator
Disallow: /html1
Disallow: /html2
Disallow: /admin
Disallow: /test
Disallow: /gen
Disallow: /platnik
Disallow: /html10
Disallow: /html20
Disallow: /tomaszow
Disallow: /zbiory/katalog/include
Disallow: /inw
Disallow: /zbiory/katalog/en0
Disallow: /zbiory/katalog/de0
Disallow: /zbiory/katalog/fr0
Disallow: /zbiory/katalog/pl0
Disallow: /zbiory/katalog/uk0
Disallow:/author/admin

# Local.com
User-agent: LocalcomBot
Allow: /
Disallow: /category
Disallow: /category/aktualnosci
Disallow: /zbiory/katalog/stare
Disallow: /zbiory/katalog/admin
Disallow: /zbiory/adr/admin
Disallow: /zbiory/arch/admin
Disallow: /zbiory/biblio/admin
Disallow: /zbiory/kon/admin
Disallow: /html
Disallow: /html/old
Disallow: /html/generator
Disallow: /html1
Disallow: /html2
Disallow: /admin
Disallow: /test
Disallow: /gen
Disallow: /platnik
Disallow: /html10
Disallow: /html20
Disallow: /tomaszow
Disallow: /zbiory/katalog/include
Disallow: /inw
Disallow: /zbiory/katalog/en0
Disallow: /zbiory/katalog/de0
Disallow: /zbiory/katalog/fr0
Disallow: /zbiory/katalog/pl0
Disallow: /zbiory/katalog/uk0
Disallow:/author/admin

# Loopimprovements
User-agent: NetResearchServer
Allow: /
Disallow: /category
Disallow: /category/aktualnosci
Disallow: /zbiory/katalog/stare
Disallow: /zbiory/katalog/admin
Disallow: /zbiory/adr/admin
Disallow: /zbiory/arch/admin
Disallow: /zbiory/biblio/admin
Disallow: /zbiory/kon/admin
Disallow: /html
Disallow: /html/old
Disallow: /html/generator
Disallow: /html1
Disallow: /html2
Disallow: /admin
Disallow: /test
Disallow: /gen
Disallow: /platnik
Disallow: /html10
Disallow: /html20
Disallow: /tomaszow
Disallow: /zbiory/katalog/include
Disallow: /inw
Disallow:/author/admin


# Majestic-12
User-agent: MJ12bot
Allow: /
Disallow: /category
Disallow: /category/aktualnosci
Disallow: /zbiory/katalog/stare
Disallow: /zbiory/katalog/admin
Disallow: /zbiory/adr/admin
Disallow: /zbiory/arch/admin
Disallow: /zbiory/biblio/admin
Disallow: /zbiory/kon/admin
Disallow: /html
Disallow: /html/old
Disallow: /html/generator
Disallow: /html1
Disallow: /html2
Disallow: /admin
Disallow: /test
Disallow: /gen
Disallow: /platnik
Disallow: /html10
Disallow: /html20
Disallow: /tomaszow
Disallow: /zbiory/katalog/include
Disallow: /inw
Disallow:/author/admin


# Mirago
User-agent: HenryTheMiragoRobot
Allow: /
Disallow: /category
Disallow: /category/aktualnosci
Disallow: /zbiory/katalog/stare
Disallow: /zbiory/katalog/admin
Disallow: /zbiory/adr/admin
Disallow: /zbiory/arch/admin
Disallow: /zbiory/biblio/admin
Disallow: /zbiory/kon/admin
Disallow: /html
Disallow: /html/old
Disallow: /html/generator
Disallow: /html1
Disallow: /html2
Disallow: /admin
Disallow: /test
Disallow: /gen
Disallow: /platnik
Disallow: /html10
Disallow: /html20
Disallow: /tomaszow
Disallow: /zbiory/katalog/include
Disallow: /inw
Disallow: /zbiory/katalog/en0
Disallow: /zbiory/katalog/de0
Disallow: /zbiory/katalog/fr0
Disallow: /zbiory/katalog/pl0
Disallow: /zbiory/katalog/uk0
Disallow:/author/admin

# Nameprotect
User-agent: NPBot
Allow: /
Disallow: /category
Disallow: /category/aktualnosci
Disallow: /zbiory/katalog/stare
Disallow: /zbiory/katalog/admin
Disallow: /zbiory/adr/admin
Disallow: /zbiory/arch/admin
Disallow: /zbiory/biblio/admin
Disallow: /zbiory/kon/admin
Disallow: /html
Disallow: /html/old
Disallow: /html/generator
Disallow: /html1
Disallow: /html2
Disallow: /admin
Disallow: /test
Disallow: /gen
Disallow: /platnik
Disallow: /html10
Disallow: /html20
Disallow: /tomaszow
Disallow: /zbiory/katalog/include
Disallow: /inw
Disallow: /zbiory/katalog/en0
Disallow: /zbiory/katalog/de0
Disallow: /zbiory/katalog/fr0
Disallow: /zbiory/katalog/pl0
Disallow: /zbiory/katalog/uk0
Disallow:/author/admin

# ObjectsSearch
User-agent: ObjectsSearch
Allow: /
Disallow: /category
Disallow: /category/aktualnosci
Disallow: /zbiory/katalog/stare
Disallow: /zbiory/katalog/admin
Disallow: /zbiory/adr/admin
Disallow: /zbiory/arch/admin
Disallow: /zbiory/biblio/admin
Disallow: /zbiory/kon/admin
Disallow: /html
Disallow: /html/old
Disallow: /html/generator
Disallow: /html1
Disallow: /html2
Disallow: /admin
Disallow: /test
Disallow: /gen
Disallow: /platnik
Disallow: /html10
Disallow: /html20
Disallow: /tomaszow
Disallow: /zbiory/katalog/include
Disallow: /inw
Disallow: /zbiory/katalog/en0
Disallow: /zbiory/katalog/de0
Disallow: /zbiory/katalog/fr0
Disallow: /zbiory/katalog/pl0
Disallow: /zbiory/katalog/uk0
Disallow:/author/admin

# Omni-Explorer
User-agent: OmniExplorer_Bot
Allow: /
Disallow: /category
Disallow: /category/aktualnosci
Disallow: /zbiory/katalog/stare
Disallow: /zbiory/katalog/admin
Disallow: /zbiory/adr/admin
Disallow: /zbiory/arch/admin
Disallow: /zbiory/biblio/admin
Disallow: /zbiory/kon/admin
Disallow: /html
Disallow: /html/old
Disallow: /html/generator
Disallow: /html1
Disallow: /html2
Disallow: /admin
Disallow: /test
Disallow: /gen
Disallow: /platnik
Disallow: /html10
Disallow: /html20
Disallow: /tomaszow
Disallow: /zbiory/katalog/include
Disallow: /inw
Disallow: /zbiory/katalog/en0
Disallow: /zbiory/katalog/de0
Disallow: /zbiory/katalog/fr0
Disallow: /zbiory/katalog/pl0
Disallow: /zbiory/katalog/uk0
Disallow:/author/admin

# Picsearch
User-agent: psbot
Allow: /
Disallow: /category
Disallow: /category/aktualnosci
Disallow: /zbiory/katalog/stare
Disallow: /zbiory/katalog/admin
Disallow: /zbiory/adr/admin
Disallow: /zbiory/arch/admin
Disallow: /zbiory/biblio/admin
Disallow: /zbiory/kon/admin
Disallow: /html
Disallow: /html/old
Disallow: /html/generator
Disallow: /html1
Disallow: /html2
Disallow: /admin
Disallow: /test
Disallow: /gen
Disallow: /platnik
Disallow: /html10
Disallow: /html20
Disallow: /tomaszow
Disallow: /zbiory/katalog/include
Disallow: /inw
Disallow: /zbiory/katalog/en0
Disallow: /zbiory/katalog/de0
Disallow: /zbiory/katalog/fr0
Disallow: /zbiory/katalog/pl0
Disallow: /zbiory/katalog/uk0
Disallow:/author/admin

# Pipeline
User-agent: pipeLiner
Allow: /
Disallow: /category
Disallow: /category/aktualnosci
Disallow: /zbiory/katalog/stare
Disallow: /zbiory/katalog/admin
Disallow: /zbiory/adr/admin
Disallow: /zbiory/arch/admin
Disallow: /zbiory/biblio/admin
Disallow: /zbiory/kon/admin
Disallow: /html
Disallow: /html/old
Disallow: /html/generator
Disallow: /html1
Disallow: /html2
Disallow: /admin
Disallow: /test
Disallow: /gen
Disallow: /platnik
Disallow: /html10
Disallow: /html20
Disallow: /tomaszow
Disallow: /zbiory/katalog/include
Disallow: /inw
Disallow: /zbiory/katalog/en0
Disallow: /zbiory/katalog/de0
Disallow: /zbiory/katalog/fr0
Disallow: /zbiory/katalog/pl0
Disallow: /zbiory/katalog/uk0
Disallow:/author/admin

# SEVENtwentyfour
User-agent: LinkWalker
Allow: /
Disallow: /category
Disallow: /category/aktualnosci
Disallow: /zbiory/katalog/stare
Disallow: /zbiory/katalog/admin
Disallow: /zbiory/adr/admin
Disallow: /zbiory/arch/admin
Disallow: /zbiory/biblio/admin
Disallow: /zbiory/kon/admin
Disallow: /html
Disallow: /html/old
Disallow: /html/generator
Disallow: /html1
Disallow: /html2
Disallow: /admin
Disallow: /test
Disallow: /gen
Disallow: /platnik
Disallow: /html10
Disallow: /html20
Disallow: /tomaszow
Disallow: /zbiory/katalog/include
Disallow: /inw
Disallow: /zbiory/katalog/en0
Disallow: /zbiory/katalog/de0
Disallow: /zbiory/katalog/fr0
Disallow: /zbiory/katalog/pl0
Disallow: /zbiory/katalog/uk0
Disallow:/author/admin

# SharewarePlaza.com
User-agent: Agent-SharewarePlazaFileCheckBot
Allow: /
Disallow: /category
Disallow: /category/aktualnosci
Disallow: /zbiory/katalog/stare
Disallow: /zbiory/katalog/admin
Disallow: /zbiory/adr/admin
Disallow: /zbiory/arch/admin
Disallow: /zbiory/biblio/admin
Disallow: /zbiory/kon/admin
Disallow: /html
Disallow: /html/old
Disallow: /html/generator
Disallow: /html1
Disallow: /html2
Disallow: /admin
Disallow: /test
Disallow: /gen
Disallow: /platnik
Disallow: /html10
Disallow: /html20
Disallow: /tomaszow
Disallow: /zbiory/katalog/include
Disallow: /inw
Disallow: /zbiory/katalog/en0
Disallow: /zbiory/katalog/de0
Disallow: /zbiory/katalog/fr0
Disallow: /zbiory/katalog/pl0
Disallow: /zbiory/katalog/uk0
Disallow:/author/admin

# SitiDi.net
User-agent: SitiDiBot
Allow: /
Disallow: /category
Disallow: /category/aktualnosci
Disallow: /zbiory/katalog/stare
Disallow: /zbiory/katalog/admin
Disallow: /zbiory/adr/admin
Disallow: /zbiory/arch/admin
Disallow: /zbiory/biblio/admin
Disallow: /zbiory/kon/admin
Disallow: /html
Disallow: /html/old
Disallow: /html/generator
Disallow: /html1
Disallow: /html2
Disallow: /admin
Disallow: /test
Disallow: /gen
Disallow: /platnik
Disallow: /html10
Disallow: /html20
Disallow: /tomaszow
Disallow: /zbiory/katalog/include
Disallow: /inw
Disallow: /zbiory/katalog/en0
Disallow: /zbiory/katalog/de0
Disallow: /zbiory/katalog/fr0
Disallow: /zbiory/katalog/pl0
Disallow: /zbiory/katalog/uk0
Disallow:/author/admin

# SpiderMonkey
User-agent: SpiderMonkey
Allow: /
Disallow: /category
Disallow: /category/aktualnosci
Disallow: /zbiory/katalog/stare
Disallow: /zbiory/katalog/admin
Disallow: /zbiory/adr/admin
Disallow: /zbiory/arch/admin
Disallow: /zbiory/biblio/admin
Disallow: /zbiory/kon/admin
Disallow: /html
Disallow: /html/old
Disallow: /html/generator
Disallow: /html1
Disallow: /html2
Disallow: /admin
Disallow: /test
Disallow: /gen
Disallow: /platnik
Disallow: /html10
Disallow: /html20
Disallow: /tomaszow
Disallow: /zbiory/katalog/include
Disallow: /inw
Disallow: /zbiory/katalog/en0
Disallow: /zbiory/katalog/de0
Disallow: /zbiory/katalog/fr0
Disallow: /zbiory/katalog/pl0
Disallow: /zbiory/katalog/uk0
Disallow:/author/admin

#Spider32
User-agent: Spider32
Allow: /
Disallow: /category
Disallow: /category/aktualnosci
Disallow: /zbiory/katalog/stare
Disallow: /zbiory/katalog/admin
Disallow: /zbiory/adr/admin
Disallow: /zbiory/arch/admin
Disallow: /zbiory/biblio/admin
Disallow: /zbiory/kon/admin
Disallow: /html
Disallow: /html/old
Disallow: /html/generator
Disallow: /html1
Disallow: /html2
Disallow: /admin
Disallow: /test
Disallow: /gen
Disallow: /platnik
Disallow: /html10
Disallow: /html20
Disallow: /tomaszow
Disallow: /zbiory/katalog/include
Disallow: /inw
Disallow: /zbiory/katalog/en0
Disallow: /zbiory/katalog/de0
Disallow: /zbiory/katalog/fr0
Disallow: /zbiory/katalog/pl0
Disallow: /zbiory/katalog/uk0
Disallow:/author/admin

# Turnitin.com
User-agent: TurnitinBot
Allow: /
Disallow: /category
Disallow: /category/aktualnosci
Disallow: /zbiory/katalog/stare
Disallow: /zbiory/katalog/admin
Disallow: /zbiory/adr/admin
Disallow: /zbiory/arch/admin
Disallow: /zbiory/biblio/admin
Disallow: /zbiory/kon/admin
Disallow: /html
Disallow: /html/old
Disallow: /html/generator
Disallow: /html1
Disallow: /html2
Disallow: /admin
Disallow: /test
Disallow: /gen
Disallow: /platnik
Disallow: /html10
Disallow: /html20
Disallow: /tomaszow
Disallow: /zbiory/katalog/include
Disallow: /inw
Disallow: /zbiory/katalog/en0
Disallow: /zbiory/katalog/de0
Disallow: /zbiory/katalog/fr0
Disallow: /zbiory/katalog/pl0
Disallow: /zbiory/katalog/uk0
Disallow:/author/admin

# TutorGig.com
User-agent: TutorGigBot
Allow: /
Disallow: /category
Disallow: /category/aktualnosci
Disallow: /zbiory/katalog/stare
Disallow: /zbiory/katalog/admin
Disallow: /zbiory/adr/admin
Disallow: /zbiory/arch/admin
Disallow: /zbiory/biblio/admin
Disallow: /zbiory/kon/admin
Disallow: /html
Disallow: /html/old
Disallow: /html/generator
Disallow: /html1
Disallow: /html2
Disallow: /admin
Disallow: /test
Disallow: /gen
Disallow: /platnik
Disallow: /html10
Disallow: /html20
Disallow: /tomaszow
Disallow: /zbiory/katalog/include
Disallow: /inw
Disallow: /zbiory/katalog/en0
Disallow: /zbiory/katalog/de0
Disallow: /zbiory/katalog/fr0
Disallow: /zbiory/katalog/pl0
Disallow: /zbiory/katalog/uk0
Disallow:/author/admin

# Walhello
User-agent: Appie
Allow: /
Disallow: /category
Disallow: /category/aktualnosci
Disallow: /zbiory/katalog/stare
Disallow: /zbiory/katalog/admin
Disallow: /zbiory/adr/admin
Disallow: /zbiory/arch/admin
Disallow: /zbiory/biblio/admin
Disallow: /zbiory/kon/admin
Disallow: /html
Disallow: /html/old
Disallow: /html/generator
Disallow: /html1
Disallow: /html2
Disallow: /admin
Disallow: /test
Disallow: /gen
Disallow: /platnik
Disallow: /html10
Disallow: /html20
Disallow: /tomaszow
Disallow: /zbiory/katalog/include
Disallow: /inw
Disallow: /zbiory/katalog/en0
Disallow: /zbiory/katalog/de0
Disallow: /zbiory/katalog/fr0
Disallow: /zbiory/katalog/pl0
Disallow: /zbiory/katalog/uk0
Disallow:/author/admin

# WebArchive
User-agent: BruinBot
Allow: /
Disallow: /category
Disallow: /category/aktualnosci
Disallow: /zbiory/katalog/stare
Disallow: /zbiory/katalog/admin
Disallow: /zbiory/adr/admin
Disallow: /zbiory/arch/admin
Disallow: /zbiory/biblio/admin
Disallow: /zbiory/kon/admin
Disallow: /html
Disallow: /html/old
Disallow: /html/generator
Disallow: /html1
Disallow: /html2
Disallow: /admin
Disallow: /test
Disallow: /gen
Disallow: /platnik
Disallow: /html10
Disallow: /html20
Disallow: /tomaszow
Disallow: /zbiory/katalog/include
Disallow: /inw
Disallow: /zbiory/katalog/en0
Disallow: /zbiory/katalog/de0
Disallow: /zbiory/katalog/fr0
Disallow: /zbiory/katalog/pl0
Disallow: /zbiory/katalog/uk0
Disallow:/author/admin


# Others
User-agent: *
Disallow: /category
Disallow: /category/aktualnosci
Disallow: /zbiory/katalog/stare
Disallow: /zbiory/katalog/admin
Disallow: /zbiory/adr/admin
Disallow: /zbiory/arch/admin
Disallow: /zbiory/biblio/admin
Disallow: /zbiory/kon/admin
Disallow: /html
Disallow: /html/old
Disallow: /html/generator
Disallow: /html1
Disallow: /html2
Disallow: /admin
Disallow: /test
Disallow: /gen
Disallow: /platnik
Disallow: /html10
Disallow: /html20
Disallow: /tomaszow
Disallow: /zbiory/katalog/include
Disallow: /inw
Disallow: /zbiory/katalog/en0
Disallow: /zbiory/katalog/de0
Disallow: /zbiory/katalog/fr0
Disallow: /zbiory/katalog/pl0
Disallow: /zbiory/katalog/uk0
Disallow:/author/admin

user-agent: sitebot
disallow: /
Disallow: /category
Disallow: /category/aktualnosci
Disallow:/author/admin

#Begin Attracta SEO Tools Sitemap. Do not remove
sitemap: http://cdn.attracta.com/sitemap/2821355.xml.gz
#End Attracta SEO Tools Sitemap. Do not remove

