User-agent: *
Disallow: /common.php
Disallow: /server*.php
Disallow: /sklep.php
Disallow: /notatka.php
Disallow: /menu.php
Disallow: /tarot.php
Disallow: /user.php
Disallow: /todaylog.php
Disallow: /edycja_notatki.php
Disallow: /ankieta.php
Disallow: /daj_st.php
Disallow: /czat.php
Disallow: /avc.inc.php
Disallow: /ekran.php
Disallow: /fotogaleria.php
Disallow: /fotka.php
Disallow: /fotogalerie_mieszkancow.php
Disallow: /functions.php
Disallow: /functions_loc.php
Disallow: /galeria_common.php
Disallow: /global.php
Disallow: /my.php
Disallow: /opis_zdjecia.php
Disallow: /newsletter.php
Disallow: /logo.php
Disallow: /x_avc.js
Disallow: /tarot_opis.php
Disallow: /tarot_lista_kart.php
Disallow: /tarot_txt2mysql.php
Disallow: /index.inc.php
Disallow: /htpasswd.php
Disallow: /ja.php
Disallow: /iq_form.php
Disallow: /audio/
Disallow: /funkcje/
Disallow: /Galeria/
Disallow: /help/
Disallow: /img/
Disallow: /jednorazowe_kod_dostepu/
Disallow: /konta_conf/
Disallow: /Magazyn/
Disallow: /video/
Disallow: /xajax/
Disallow: /konta/0/
Disallow: /konta/1/
Disallow: /konta/11/audio/
Disallow: /konta/11/czaty/
Disallow: /konta/11/obrazki/
Disallow: /konta/11/tmp/
Disallow: /konta/11/video/
Disallow: /konta/11/notatki/
Disallow: /konta/11/global.php
Disallow: /konta/11/kolory.css
Disallow: /konta/21/
