User-agent: *
Disallow: /admin/
Disallow: /faq.php
Disallow: /groupcp.php
Disallow: /login.php
Disallow: /memberlist.php
Disallow: /modcp.php
Disallow: /posting,
Disallow: /posting.php
Disallow: /privmsg,
Disallow: /privmsg.php
Disallow: /profile.php
Disallow: /search.php
Disallow: /viewforum,
Disallow: /viewforum.php
Disallow: /viewonline.php
Disallow: /viewtopic,
Disallow: /viewtopic.php
Disallow: /-vp
