User-agent: *
Disallow: /*?cSEOid
Disallow: /*?sessionid
Disallow: /commerce_seo_url.php
Disallow: /address_book.php
Disallow: /address_book_process.php
Disallow: /account_edit.php
Disallow: /account_edit_process.php
Disallow: /account_history.php
Disallow: /account_history_info.php
Disallow: /checkout_process.php
Disallow: /checkout_address.php
Disallow: /checkout_confirmation.php
Disallow: /checkout_payment.php
Disallow: /checkout_payment_address.php
Disallow: /checkout_shipping.php
Disallow: /checkout_shipping_address.php
Disallow: /checkout_success.php
Disallow: /cookie_usage.php
Disallow: /contact_us.php
Disallow: /create_account_guest.php
Disallow: /create_account_process.php
Disallow: /create_account_success.php
Disallow: /download.php
Disallow: /getCountry.php
Disallow: /gv_redeem.php
Disallow: /gv_send.php
Disallow: /java_functions.js.php
Disallow: /java_main.js.php
Disallow: /popup_image.php
Disallow: /popup_search_help.php
Disallow: /print_order.php
Disallow: /print_pdf.php
Disallow: /privacy.php
Disallow: /product_notifications.php
Disallow: /product_reviews.php
Disallow: /product_reviews_info.php
Disallow: /reviews.php
Disallow: /shipping.php
Disallow: /search_result.php
Disallow: /admin/
Disallow: /callback/
Disallow: /blog_captcha/
Disallow: /cache/
Disallow: /callback/
Disallow: /download/
Disallow: /export/
Disallow: /import/
Disallow: /inc/
Disallow: /includes/
Disallow: /installer/
Disallow: /lang/
Disallow: /pub/
Disallow: /xajax_js/
