User-agent: *
Disallow: /administrator/
Disallow: /login/
Disallow: /verifylogin/
Disallow: /verifyemail/
Disallow: /categories/
Disallow: /posts/administrator/
Disallow: /posts/add_post/
Disallow: /posts/edit_post/
Disallow: /posts/delete_post/
Disallow: /posts/delete_post_form/
Disallow: /posts/survey_answer_form/
Disallow: /posts/survey_answered/
Disallow: /posts/newsletter/
Disallow: /gallery/administrator/
Disallow: /gallery/add_gallery/
Disallow: /gallery/delete_gallery/
Disallow: /gallery/delete_gallery_form/
Disallow: /gallery/edit_gallery/
Disallow: /gallery/edit_images/
Disallow: /gallery/upload_img/
Disallow: /gallery/edit_gallery_image/
Disallow: /gallery/delete_image/
Disallow: /gallery/delete_image_form/
Disallow: /gallery/edit_gallery_order/
Disallow: /gallery/edit_gallery_location/
Disallow: /gallery/update_img/
Disallow: /gallery/delete_image/
Disallow: /gallery/delete_image_form/
Disallow: /gallery/edit_image_location/
Disallow: /gallery/survey_answer_form/
Disallow: /gallery/newsletter/
Disallow: /contact/newsletter/
Disallow: /contact/survey_answer_form/
Disallow: /gallery/newsletter/
Disallow: /file/administrator/
Disallow: /file/add_category/
Disallow: /file/edit_category/
Disallow: /file/delete_category/
Disallow: /file/delete_category_form/
Disallow: /file/add_file/
Disallow: /file/delete_file/
Disallow: /file/delete_file_form/
Disallow: /file/survey_answer_form/
Disallow: /file/download/
Disallow: /newsletter/
Disallow: /surveys/
Disallow: /pages/administrator/
Disallow: /pages/add_page/
Disallow: /pages/edit_page/
Disallow: /pages/survey_answer_form/
Disallow: /pages/newsletter/
Disallow: /pages/administrator/
Disallow: /pages/administrator/
Disallow: /print_description/
Disallow: /Products/print_description/
Disallow: /categories/
