User-agent: *
Crawl-delay: 05
Disallow: /paging/
Disallow: /emailafriend/
Disallow: /catalogue/f/
Disallow: /szukaj/
Disallow: /f/szukaj/
Disallow: /INTERSHOP/web/WFS/NI-NOES-Site/
Disallow: /INTERSHOP/web/WFS/NI-NOIT-Site/
Disallow: /INTERSHOP/web/WFS/NI-NOPT-Site/
Disallow: /INTERSHOP/web/WFS/NI-AUBE-Site/
Disallow: /INTERSHOP/web/WFS/NI-NOFR-Site/
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/-/PLN/ViewFaq-Start
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/-/PLN/ViewBrandPage-Start
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/-/PLN/ViewCarSelectorpage-PopupCarSelector
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/-/PLN/ViewData-Start/
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/-/PLN/ViewMountingCenter-PopupCheckout
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/-/PLN/ViewMountingCenter-PopupHeader
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/-/PLN/ViewMountingCenter-PopupProduct
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/-/PLN/ViewCarSelectorpage-PopupCarteGrise
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/-/PLN/ViewParametricSearch-Browse
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/-/PLN/ViewContent-Start
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/-/PLN/ViewProduct-Start
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/-/PLN/ViewTabContent-Start
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/-/PLN/ViewOrders-SimpleOrderSearch
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/-/PLN/ViewUserAccount-ProcessLogin
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/-/PLN/ViewStandardCatalog-Browse
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/-/PLN/ViewProfileSettings-ViewProfile
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/-/PLN/ViewParametricSearch-SimpleOfferSearch
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/-/PLN/ViewForgotLoginData-Dispatch
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/-/PLN/ViewVehicleOwnershipCertificate-Taxes
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/-/PLN/ViewProductLight-Modal
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/-/PLN/ViewSearchCentres-AjaxSearch
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/-/PLN/IncludeSimpleCaptchaImage-Render
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/-/PLN/URLError-Start/
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/-/PLN/ViewCart-Dispatch
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/-/PLN/ViewMountingCenter-PopupHeader
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/-/PLN/ViewUserAccount-SocialPrivacy
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/-/PLN/GetExternalizedStrings-Start
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/-/PLN/ViewForgotLoginData-ForgotPassword
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/-/PLN/ViewMountingCenter-PopupProduct
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/uas-mobile-b2c-web-shop/PLN/ViewFaq-Start
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/uas-mobile-b2c-web-shop/PLN/ViewBrandPage-Start
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/uas-mobile-b2c-web-shop/PLN/ViewCarSelectorpage-PopupCarSelector
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/uas-mobile-b2c-web-shop/PLN/ViewData-Start/
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/uas-mobile-b2c-web-shop/PLN/ViewMountingCenter-PopupCheckout
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/uas-mobile-b2c-web-shop/PLN/ViewMountingCenter-PopupHeader
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/uas-mobile-b2c-web-shop/PLN/ViewMountingCenter-PopupProduct
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/uas-mobile-b2c-web-shop/PLN/ViewCarSelectorpage-PopupCarteGrise
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/uas-mobile-b2c-web-shop/PLN/ViewParametricSearch-Browse
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/uas-mobile-b2c-web-shop/PLN/ViewContent-Start
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/uas-mobile-b2c-web-shop/PLN/ViewProduct-Start
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/uas-mobile-b2c-web-shop/PLN/ViewTabContent-Start
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/uas-mobile-b2c-web-shop/PLN/ViewOrders-SimpleOrderSearch
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/uas-mobile-b2c-web-shop/PLN/ViewUserAccount-ProcessLogin
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/uas-mobile-b2c-web-shop/PLN/ViewStandardCatalog-Browse
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/uas-mobile-b2c-web-shop/PLN/ViewProfileSettings-ViewProfile
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/uas-mobile-b2c-web-shop/PLN/ViewParametricSearch-SimpleOfferSearch
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/uas-mobile-b2c-web-shop/PLN/ViewForgotLoginData-Dispatch
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/uas-mobile-b2c-web-shop/PLN/ViewVehicleOwnershipCertificate-Taxes
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/uas-mobile-b2c-web-shop/PLN/ViewProductLight-Modal
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/uas-mobile-b2c-web-shop/PLN/ViewSearchCentres-AjaxSearch
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/uas-mobile-b2c-web-shop/PLN/IncludeSimpleCaptchaImage-Render
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/uas-mobile-b2c-web-shop/PLN/URLError-Start/
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/uas-mobile-b2c-web-shop/PLN/ViewCart-Dispatch
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/uas-mobile-b2c-web-shop/PLN/ViewMountingCenter-PopupHeader
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/uas-mobile-b2c-web-shop/PLN/ViewUserAccount-SocialPrivacy
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/uas-mobile-b2c-web-shop/PLN/GetExternalizedStrings-Start
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/uas-mobile-b2c-web-shop/PLN/ViewForgotLoginData-ForgotPassword
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/uas-mobile-b2c-web-shop/PLN/ViewMountingCenter-PopupProduct
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/-/EUR/ViewFaq-Start
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/-/EUR/ViewBrandPage-Start
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/-/EUR/ViewCarSelectorpage-PopupCarSelector
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/-/EUR/ViewData-Start/
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/-/EUR/ViewMountingCenter-PopupCheckout
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/-/EUR/ViewMountingCenter-PopupHeader
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/-/EUR/ViewMountingCenter-PopupProduct
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/-/EUR/ViewCarSelectorpage-PopupCarteGrise
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/-/EUR/ViewParametricSearch-Browse
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/-/EUR/ViewContent-Start
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/-/EUR/ViewProduct-Start
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/-/EUR/ViewTabContent-Start
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/-/EUR/ViewOrders-SimpleOrderSearch
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/-/EUR/ViewUserAccount-ProcessLogin
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/-/EUR/ViewStandardCatalog-Browse
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/-/EUR/ViewProfileSettings-ViewProfile
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/-/EUR/ViewParametricSearch-SimpleOfferSearch
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/-/EUR/ViewForgotLoginData-Dispatch
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/-/EUR/ViewVehicleOwnershipCertificate-Taxes
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/-/EUR/ViewProductLight-Modal
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/-/EUR/ViewSearchCentres-AjaxSearch
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/-/EUR/IncludeSimpleCaptchaImage-Render
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/-/EUR/URLError-Start/
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/-/EUR/ViewCart-Dispatch
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/-/EUR/ViewMountingCenter-PopupHeader
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/-/EUR/ViewUserAccount-SocialPrivacy
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/-/EUR/GetExternalizedStrings-Start
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/-/EUR/ViewForgotLoginData-ForgotPassword
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/-/EUR/ViewMountingCenter-PopupProduct
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/uas-mobile-b2c-web-shop/EUR/ViewFaq-Start
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/uas-mobile-b2c-web-shop/EUR/ViewBrandPage-Start
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/uas-mobile-b2c-web-shop/EUR/ViewCarSelectorpage-PopupCarSelector
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/uas-mobile-b2c-web-shop/EUR/ViewData-Start/
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/uas-mobile-b2c-web-shop/EUR/ViewMountingCenter-PopupCheckout
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/uas-mobile-b2c-web-shop/EUR/ViewMountingCenter-PopupHeader
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/uas-mobile-b2c-web-shop/EUR/ViewMountingCenter-PopupProduct
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/uas-mobile-b2c-web-shop/EUR/ViewCarSelectorpage-PopupCarteGrise
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/uas-mobile-b2c-web-shop/EUR/ViewParametricSearch-Browse
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/uas-mobile-b2c-web-shop/EUR/ViewContent-Start
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/uas-mobile-b2c-web-shop/EUR/ViewProduct-Start
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/uas-mobile-b2c-web-shop/EUR/ViewTabContent-Start
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/uas-mobile-b2c-web-shop/EUR/ViewOrders-SimpleOrderSearch
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/uas-mobile-b2c-web-shop/EUR/ViewUserAccount-ProcessLogin
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/uas-mobile-b2c-web-shop/EUR/ViewStandardCatalog-Browse
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/uas-mobile-b2c-web-shop/EUR/ViewProfileSettings-ViewProfile
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/uas-mobile-b2c-web-shop/EUR/ViewParametricSearch-SimpleOfferSearch
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/uas-mobile-b2c-web-shop/EUR/ViewForgotLoginData-Dispatch
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/uas-mobile-b2c-web-shop/EUR/ViewVehicleOwnershipCertificate-Taxes
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/uas-mobile-b2c-web-shop/EUR/ViewProductLight-Modal
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/uas-mobile-b2c-web-shop/EUR/ViewSearchCentres-AjaxSearch
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/uas-mobile-b2c-web-shop/EUR/IncludeSimpleCaptchaImage-Render
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/uas-mobile-b2c-web-shop/EUR/URLError-Start/
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/uas-mobile-b2c-web-shop/EUR/ViewCart-Dispatch
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/uas-mobile-b2c-web-shop/EUR/ViewMountingCenter-PopupHeader
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/uas-mobile-b2c-web-shop/EUR/ViewUserAccount-SocialPrivacy
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/uas-mobile-b2c-web-shop/EUR/GetExternalizedStrings-Start
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/uas-mobile-b2c-web-shop/EUR/ViewForgotLoginData-ForgotPassword
Disallow: /INTERSHOP/web/WFS/NI-NOPL-Site/pl_PL/uas-mobile-b2c-web-shop/EUR/ViewMountingCenter-PopupProduct
Disallow: /catalog/1_Prestations-atelier.html
Sitemap : https://www.norauto.pl/sitemapindex.xml?SyndicationID=Sitemap_pl
