User-agent: *
Disallow: /*.axd$
Disallow: /protect/
Disallow: /Admin/
Disallow: /AdminManagementPage.aspx
Disallow: /AdminSimpleLogs.aspx
Disallow: /WebResource.axd
Disallow: /Blank.aspx
Disallow: /ChangePassword.aspx
Disallow: /FavouriteFilms.aspx
Disallow: /Invitation.aspx
Disallow: /MyAccount.aspx
Disallow: /MyOpinions.aspx
Disallow: /OpinionNew.aspx
Disallow: /Opinions.aspx
Disallow: /RemFavouriteFilm.aspx
Disallow: /ReportFilmError.aspx
Disallow: /ReportOpinion.aspx
Disallow: /UnderConstruction.aspx
Disallow: /UserSettings.aspx
Disallow: /Rules.aspx
Disallow: /Login.aspx
Disallow: /RemindPass.aspx
Disallow: /BlankNoMasterpage.aspx
Disallow: /MustLogin.aspx
Disallow: /Ranking.aspx
