User-agent: *
Disallow: /szukaj
Disallow: /admin
Disallow: /apple-app-site-association
Disallow: /srs
Disallow: /sklep
Disallow: /felgi
Disallow: /producent
Disallow: /.well-known
Disallow: /MyAccount
Disallow: /blog
Disallow: /tag
Disallow: /wordpress
Disallow: /id_dsa
Disallow: /opony/Diameters
Disallow: /Tire/Diameters
Disallow: /opony/Ratios
Disallow: /Tire/Ratios
Disallow: /Question
Disallow: /TimeTable/TodayTable
Disallow: /sk/
Disallow: /apple-app-site-association/
Disallow: /apple-app-site-association/Index
Disallow: /review/add
Disallow: /c/
Disallow: /q/
Disallow: /p/
Disallow: /r/
Disallow: /s/
Disallow: /cronx/
Disallow: /cronx/tyreinfo
Disallow: /cronx/platformaopon
Disallow: /cronx/hurtopon
Disallow: /cronx/update_exchange_rates
Disallow: /Tire/samochodowe
Disallow: /WebPage/ViewPage
Disallow: /kontakt/kontakt
Disallow: /promocje/Index
Disallow: /poradnik/opis-opon
Disallow: /poradnik/
Disallow: /promocje/
Disallow: /roundcube/Index
