Sitemap: https://panfarmerek.pl/sitemap.xml.gz

### Automatically banned scanners and crawlers section ###
User-agent: 008
Disallow: /
user-agent: AhrefsBot
Disallow: /
User-agent: MJ12bot
Disallow: /
User-agent: metajobbot
Disallow: /
User-agent: Exabot
Disallow: /
User-agent: Ezooms
Disallow: /
User-agent: fyberspider
Disallow: /
User-agent: dotbot
Disallow: /
User-agent: MojeekBot
Disallow: /
User-agent: BLEXBot
Disallow: /
User-agent: wotbox
Disallow: /
### Section end ###

User-agent: TwengaBot-Discover
Disallow: /
User-agent: TwengaBot/2.0
Disallow: /
User-agent: TwengaBot
Disallow: /
User-agent: TwengaBot-2.0
Disallow: /
Sitemap: http://www.panfarmerek.pl/sitemap.xml.gz
User-agent: *
Crawl-delay: 1
Disallow: /basketchange.php
Disallow: /basketedit.php
Disallow: /basket-onchange.php
Disallow: /client-address.php
Disallow: /client-addresses.php
Disallow: /client-new.php
Disallow: /client-orders.php
Disallow: /client-save.php
Disallow: /login.php
Disallow: /loginedit.php
Disallow: /loginonce.php
Disallow: /membership-card.php
Disallow: /order1.php
Disallow: /order2.php
Disallow: /order3.php
Disallow: /ordercancel.php
Disallow: /orderconfirm.php
Disallow: /orderdetails.php
Disallow: /order-document.php
Disallow: /order-newpayment.php
Disallow: /order-payment.php
Disallow: /order-postauction.php
Disallow: /order-wrappers.php
Disallow: /payments-confirm.php
Disallow: /products-bought.php
Disallow: /products-requests.php
Disallow: /przelew.php
Disallow: /rebate-code.php
Disallow: /rma-add.php
Disallow: /rma-list.php
Disallow: /settings.php
Disallow: /Regulamin-cterms-pol-14.html
Disallow: /pol_m_Informacje_Prawo-odstapienia-od-umowy-745.html
Disallow: /pol_m_Informacje_Sposoby-platnosci-i-koszty-dostawy-747.html
Disallow: /Polityka-dotyczaca-cookies-cterms-pol-31.html
Disallow: /sitemap.php
Disallow: /order-open.php
Disallow: /client-new.php?register
Disallow: /signin.php
Disallow: /return.php?status=basket_empty
Disallow: /Produkty-za-punkty-sforpoints-pol.html
Disallow: /search.php*
Disallow: /categories.php
Disallow: /producers.php
Disallow: /stock.php?stock=1
Disallow: /news-pol.phtml*
Disallow: /Polityka-prywatnosci-cinfo-pol-25.html
Disallow: /FAQ-czeste-pytania-cinfo-pol-20.html
Disallow: /Pomoc-cinfo-pol-21.html
Disallow: /Secur-300-news-pol-1341393477.html
Disallow: /Secur-300-zasilacz--news-pol-1341316819.html
Disallow: /checkup.php

