User-agent: *
Disallow: /administration/
Disallow: /locale/
Disallow: /themes/
Disallow: /print.php
Disallow: /galeria/
Disallow: /galeria
Disallow: /phocagallery/
Disallow: /phocagallery
Disallow: /component
Disallow: /component/
Disallow: /modules
Disallow: /?
Disallow: /libraries/
Disallow: /includes
Disallow: /includes/
Disallow: /templates/
Disallow: /index.php/Create-an-account/
Disallow: /component/user/register/
Disallow: /index.php?option=com_users&view=registration/
Disallow: /index.php?option=com_user&view=register/
Disallow: /index.php/Create-an-account
Disallow: /component/user/register
Disallow: /index.php?option=com_users&view=registration
Disallow: /index.php?option=com_user&view=register
