User-agent: *
Disallow: /calendar/action~posterboard/
Disallow: /calendar/action~agenda/
Disallow: /calendar/action~oneday/
Disallow: /calendar/action~month/
Disallow: /calendar/action~week/
Disallow: /calendar/action~stream/
Disallow: /calendar/action~undefined/
Disallow: /calendar/action~http:/
Disallow: /calendar/action~default/
Disallow: /calendar/action~poster/
Disallow: /calendar/action~*/
Disallow: /*controller=ai1ec_exporter_controller*
Disallow: /*/action~*/
Disallow: /strona-startowa/action~posterboard/
Disallow: /strona-startowa/action~agenda/
Disallow: /strona-startowa/action~oneday/
Disallow: /strona-startowa/action~month/
Disallow: /strona-startowa/action~week/
Disallow: /strona-startowa/action~stream/
Disallow: /strona-startowa/action~undefined/
Disallow: /strona-startowa/action~http:/
Disallow: /strona-startowa/action~default/
Disallow: /strona-startowa/action~poster/
Disallow: /strona-startowa/action~*/
Disallow: /kalendarz-szkolen-2018-r/action~posterboard/
Disallow: /kalendarz-szkolen-2018-r/action~agenda/
Disallow: /kalendarz-szkolen-2018-r/action~oneday/
Disallow: /kalendarz-szkolen-2018-r/action~month/
Disallow: /kalendarz-szkolen-2018-r/action~week/
Disallow: /kalendarz-szkolen-2018-r/action~stream/
Disallow: /kalendarz-szkolen-2018-r/action~undefined/
Disallow: /kalendarz-szkolen-2018-r/action~http:/
Disallow: /kalendarz-szkolen-2018-r/action~default/
Disallow: /kalendarz-szkolen-2018-r/action~poster/
Disallow: /kalendarz-szkolen-2018-r/action~*/
