<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<meta name="verify-v1" content="o1YgN5vKUJK0PR3PChcFShHS6ctUWAhLCe5GMSh3SNM=" />
<title>Perkalaba :: </title>
<link rel="stylesheet" type="text/css" href="http://perkalaba.com.ua/css/main.css">
<link rel="stylesheet" href="http://perkalaba.com.ua/css/lightbox.css" type="text/css" media="screen" />
<script src="/js/prototype.js" type="text/javascript"></script>
<script type="text/javascript">

var _gaq = _gaq || [];
_gaq.push(['_setAccount', 'UA-35601904-1']);
_gaq.push(['_trackPageview']);
(function() {
var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
ga.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'stats.g.doubleclick.net/dc.js';
var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
})();

</script>
</head>
<body>
<div id="container">
<div id="header-out"><div id="header">
<div id="top"><a href="mailto:gnativ&#64;yahoo.com"><img src="http://perkalaba.com.ua/img/bt_mail.png" width="12" height="10" alt="Napisat' nam"></a><a href="http://perkalaba.com.ua/ua/"><img src="http://perkalaba.com.ua/img/bt_home.png" width="11" height="10" alt="Pereiti na glavnuiu stranitsu"></a></div>
<p><a href="http://perkalaba.com.ua/ua/"><img src="http://perkalaba.com.ua/img/468x60.gif" width="468" height="60" alt="PERKALABA FEST - diznaisia bil'she"></a></p>
<span><a href="http://perkalaba.com.ua/ua/index.html"><img src="http://perkalaba.com.ua/img/logo.png" width="224" height="32" alt="PERKALABA"></a></span>
<div id="nav">
<table>
<tr>
<td><a href="http://perkalaba.com.ua/ua/index.html">Familia Perkalaba</a></td>
<td><a href="http://perkalaba.com.ua/ua/news/">Novini</a></td>
<td><a href="http://perkalaba.com.ua/ua/cd/">Diskografiia</a></td>
<td><a href="http://perkalaba.com.ua/ua/media.html">Media</a></td>
<td><a href="http://perkalaba.com.ua/ua/photo.html">Svitlini</a></td>
<td><a href="http://perkalaba.com.ua/ua/links.html">Druzhni linki</a></td>
<td><a href="http://perkalaba.com.ua/ua/tech_rider/">Tekh. Raider</a></td>
<td><a href="http://perkalaba.com.ua/ua/guestbook/">Gost'ova</a></td>
<td><a href="http://perkalaba.com.ua/ua/card.html">Perkalabini listivki</a></td>
</tr>
</table>
</div>
</div>
</div>

<div id="left-prepart"><div id="left-part">
<p><img src="http://perkalaba.com.ua/img/manager.png" width="77" height="77" alt="Menedzhers'ki kontakti"></p>
<span>Menedzhers'ki<br>kontakti:<br><strong>+380509482985</strong><br><strong>gnativ&#64;yahoo.com</strong></span>
<div id="lang1"><a href="http://perkalaba.com.ua/ru/"><img src="http://perkalaba.com.ua/img/bt_ru.png" width="53" height="53" alt="Russkii"></a></div>
<div id="lang2"><a href="http://perkalaba.com.ua/en/"><img src="http://perkalaba.com.ua/img/bt_en.png" width="53" height="53" alt="English"></a></div>
<div id="lang3"><a href="http://perkalaba.com.ua/pl/"><img src="http://perkalaba.com.ua/img/bt_pl.png" width="53" height="53" alt="Polski"></a></div>
</div></div>

<div id="content">

<LINK href="http://perkalaba.com.ua/css/message.css" rel="stylesheet" type="text/css">
<div class="error">
<span>&nbsp;<strong>Error 404</strong></span>
<em></em>
Page not found!
<a href="http://perkalaba.com.ua/"><strong>OK</strong> &raquo;</a>
</div>

</div>

<div class="clear"><span>&nbsp;</span></div>

</div>
<div id="foot">
<div id="footer">
<div>
DIZAIN: <strong><a href="http://zsuf.net/">ZSUF</a>, </strong>
KODUVANNIa: <strong><script type="text/javascript">eval(unescape('%64%6f%63%75%6d%65%6e%74%2e%77%72%69%74%65%28%27%3c%61%20%68%72%65%66%3d%22%6d%61%69%6c%74%6f%3a%73%75%6b%61%62%6c%79%61%40%67%6d%61%69%6c%2e%63%6f%6d%22%20%3e%49%6e%76%61%6c%69%64%20%50%72%6f%64%20%54%4d%3c%2f%61%3e%27%29%3b'))</script></strong>
</div>
<p><strong>(s)&nbsp;PERKALABA,</strong>(ts) 1913 - 2007</p>
</div>
</div>
</body>
</html>
