User-agent: *
Sitemap: http://petycja.pracownia.org.pl/default/domain/sitemap
Disallow: /public/js
Disallow: /public/css
Disallow: /public/files
Disallow: /application
Disallow: /library
Disallow: /cache
Disallow: /log
