User-agent: *
Disallow: /calendar/action~posterboard/
Disallow: /calendar/action~agenda/
Disallow: /calendar/action~oneday/
Disallow: /calendar/action~month/
Disallow: /calendar/action~week/
Disallow: /calendar/action~stream/
Disallow: /calendar/action~undefined/
Disallow: /calendar/action~http:/
Disallow: /calendar/action~default/
Disallow: /calendar/action~poster/
Disallow: /calendar/action~*/
Disallow: /*controller=ai1ec_exporter_controller*
Disallow: /*/action~*/
Disallow: /calendar-2/action~posterboard/
Disallow: /calendar-2/action~agenda/
Disallow: /calendar-2/action~oneday/
Disallow: /calendar-2/action~month/
Disallow: /calendar-2/action~week/
Disallow: /calendar-2/action~stream/
Disallow: /calendar-2/action~undefined/
Disallow: /calendar-2/action~http:/
Disallow: /calendar-2/action~default/
Disallow: /calendar-2/action~poster/
Disallow: /calendar-2/action~*/
Disallow: /strona-glowna/action~posterboard/
Disallow: /strona-glowna/action~agenda/
Disallow: /strona-glowna/action~oneday/
Disallow: /strona-glowna/action~month/
Disallow: /strona-glowna/action~week/
Disallow: /strona-glowna/action~stream/
Disallow: /strona-glowna/action~undefined/
Disallow: /strona-glowna/action~http:/
Disallow: /strona-glowna/action~default/
Disallow: /strona-glowna/action~poster/
Disallow: /strona-glowna/action~*/
