User-agent: *
Disallow: /archiwum/
Disallow: /wp-admin
Disallow: /wp-includes
Disallow: /wp-content/plugins
Disallow: /wp-content/cache
Disallow: /wp-content/themes
Disallow: /wp-includes/js
Disallow: /trackback
Disallow: /category/*/*
Disallow: */trackback
Disallow: /*?*
Disallow: /*?
Disallow: /*~*
Disallow: /*~
Disallow: /architekst/administrator/
Disallow: /architekst/cache/
Disallow: /architekst/cgi-bin/
Disallow: /architekst/components/
Disallow: /architekst/editor/
Disallow: /architekst/help/
Disallow: /architekst/images/
Disallow: /architekst/includes/
Disallow: /architekst/language/
Disallow: /architekst/mambots/
Disallow: /architekst/media/
Disallow: /architekst/modules/
Disallow: /architekst/templates/
Disallow: /architekst/parameters/
Disallow: /architekst/uploadfiles/
Disallow: /architekst/installation/
