# www.robotstxt.org/
# www.google.com/support/webmasters/bin/answer.py?hl=en&answer=156449

User-agent: *

# Generated by
# https://pro-sitemaps.com/site/3982463/

sitemap: http://a101935.hostedsitemaps.com/3982463/sitemap.xml.gz

