User-agent: *
Allow: /index.php
Allow: /index_en.php
Allow: /rss.php
Disallow: /!panadd/
Disallow: /download/
Disallow: /F7www/
Disallow: /images/
Disallow: /kalendarz/
Disallow: /mapa/
Disallow: /poczta/
Disallow: /poradnia/
Disallow: /404.php
Disallow: /archiwum.php
Disallow: /baza.php
Disallow: /checkip.php
Disallow: /infpow_apteki.php
Disallow: /infpow_kal_kultura.php
Disallow: /infpow_kal_sport.php
Disallow: /infpow_kal_turystyka.php
Disallow: /infpow_orgpoz.php
Disallow: /infpow_pczk.php
Disallow: /infpow_pinb.php
Disallow: /infpow_piw.php
Disallow: /infpow_policja.php
Disallow: /infpow_psse.php
Disallow: /infpow_straz.php
Disallow: /iso.php
Disallow: /jedorg_pczo.php
Disallow: /jedorg_szkoly.php
Disallow: /jedorg_zdp.php
Disallow: /kanaly_rss.php
Disallow: /multimedia_audycje.php
Disallow: /multimedia_audycje_player.php
Disallow: /multimedia_film.php
Disallow: /multimedia_galeria.php
Disallow: /multimedia_pm.php
Disallow: /news.php
Disallow: /niepelnosprawni.php
Disallow: /powiat_dozynki.php
Disallow: /powiat_gminy.php
Disallow: /powiat_gosp1.php
Disallow: /powiat_gosp2.php
Disallow: /powiat_gosp3.php
Disallow: /powiat_gospodarka.php
Disallow: /powiat_historia.php
Disallow: /powiat_logo.php
Disallow: /powiat_mapa.php
Disallow: /powiat_polozenie.php
Disallow: /powiat_starosta.php
Disallow: /powiat_stats.php
Disallow: /powiat_strategia.php
Disallow: /powiat_tradycja.php
Disallow: /powiat_tur1.php
Disallow: /powiat_tur2.php
Disallow: /powiat_tur3.php
Disallow: /powiat_tur4.php
Disallow: /powiat_tur5.php
Disallow: /powiat_tur6.php
Disallow: /powiat_tur7.php
Disallow: /powiat_tur8.php
Disallow: /powiat_tur9.php
Disallow: /powiat_tur10.php
Disallow: /powiat_tur11.php
Disallow: /powiat_tur12.php
Disallow: /powiat_turystyka.php
Disallow: /print.php
Disallow: /rada_komisje.php
Disallow: /rada_radni.php
Disallow: /rada_zarzad.php
Disallow: /recaptchalib.php
Disallow: /serw_uni.php
Disallow: /switch.php
Disallow: /switch_cookies.php
Disallow: /wez_paragon.php
Disallow: /wydzial_ab.php
Disallow: /wydzial_az.php
Disallow: /wydzial_bh.php
Disallow: /wydzial_br.php
Disallow: /wydzial_fk.php
Disallow: /wydzial_gg.php
Disallow: /wydzial_kt.php
Disallow: /wydzial_og.php
Disallow: /wydzial_pk.php
Disallow: /wydzial_pr.php
Disallow: /wydzial_pz.php
Disallow: /wydzial_rs.php
Disallow: /wydzial_zk.php
