User-agent: *
Disallow: /wp-admin/
Allow: /wp-admin/js/editor.min.js?ver=*
Disallow: /out/*
Disallow: /goto/
Disallow: /goto/*
Disallow: /xmlrpc.php
Disallow: /*action=yith-woocompare-view-table*
Disallow: /?s=*
Disallow: /*?vote=*
Disallow: /slowniczek-pozyczkowy/*
Disallow: /porownaj/*
Disallow: /ywar_reviews/*
Disallow: /lead/*
Disallow: /html5/*
Disallow: /porownywarka*
Disallow: /*?replytocom=*
Disallow: /*?stars=*
Disallow: /*?ans-page=*
Disallow: /*?flag=*
Disallow: /*?order=*
Disallow: /*?orderby=*
Disallow: /*?data-order=*
Disallow: /*?key=*
Disallow: /zadaj-pytanie/
Disallow: /*?_wpnonce=*
Disallow: /*?taxonomy*

Sitemap: https://pozyczkaportal.pl/sitemap_index.xml
