User-agent: *
Crawl-delay: 10
Disallow: /admin/
Disallow: /auth/
Disallow: /profile/
Disallow: /ask/
Disallow: /notify/
Disallow: /basket/
Disallow: /compare/
Disallow: /newsletter/
Disallow: /recommend/
Disallow: /autosuggest/
Disallow: /customize/
Disallow: /comments/
Disallow: /captcha/
Disallow: /polls/
Disallow: /js/
Disallow: /gfx/
Disallow: /css/
Disallow: /images/delivery/
Disallow: /images/shippings/
Disallow: /images/payments/
