User-agent: *
Disallow: /calendar-2/action~posterboard/
Disallow: /calendar-2/action~agenda/
Disallow: /calendar-2/action~oneday/
Disallow: /calendar-2/action~month/
Disallow: /calendar-2/action~week/
Disallow: /calendar-2/action~stream/
Disallow: /calendar-2/action~undefined/
Disallow: /calendar-2/action~http:/
Disallow: /calendar-2/action~default/
Disallow: /calendar-2/action~poster/
Disallow: /calendar-2/action~*/
Disallow: /*controller=ai1ec_exporter_controller*
Disallow: /*/action~*/
Disallow: /calendar-3/action~posterboard/
Disallow: /calendar-3/action~agenda/
Disallow: /calendar-3/action~oneday/
Disallow: /calendar-3/action~month/
Disallow: /calendar-3/action~week/
Disallow: /calendar-3/action~stream/
Disallow: /calendar-3/action~undefined/
Disallow: /calendar-3/action~http:/
Disallow: /calendar-3/action~default/
Disallow: /calendar-3/action~poster/
Disallow: /calendar-3/action~*/
Disallow: /kalendarz-wydarzen/action~posterboard/
Disallow: /kalendarz-wydarzen/action~agenda/
Disallow: /kalendarz-wydarzen/action~oneday/
Disallow: /kalendarz-wydarzen/action~month/
Disallow: /kalendarz-wydarzen/action~week/
Disallow: /kalendarz-wydarzen/action~stream/
Disallow: /kalendarz-wydarzen/action~undefined/
Disallow: /kalendarz-wydarzen/action~http:/
Disallow: /kalendarz-wydarzen/action~default/
Disallow: /kalendarz-wydarzen/action~poster/
Disallow: /kalendarz-wydarzen/action~*/
Disallow: /calendar-4/action~posterboard/
Disallow: /calendar-4/action~agenda/
Disallow: /calendar-4/action~oneday/
Disallow: /calendar-4/action~month/
Disallow: /calendar-4/action~week/
Disallow: /calendar-4/action~stream/
Disallow: /calendar-4/action~undefined/
Disallow: /calendar-4/action~http:/
Disallow: /calendar-4/action~default/
Disallow: /calendar-4/action~poster/
Disallow: /calendar-4/action~*/
