User-agent: *
Disallow: /admin/
Disallow: /cache/
Disallow: /cgi-bin/
Disallow: /components/
Disallow: /dbloader/
Disallow: /editor/
Disallow: /files/
Disallow: /help/
Disallow: /images/
Disallow: /includes/
Disallow: /language/
Disallow: /mambots/
Disallow: /media/
Disallow: /modules/
Disallow: /pafiledb/
Disallow: /templates/
Disallow: /installation/
Disallow: /sprawy_forum/
Disallow: /downloads/
