User-agent: *
Disallow: /user
Disallow: /basket
Disallow: /search
Disallow: /recommend_shop
Disallow: /newsletter
Disallow: /currency
Disallow: /productsCompare
Disallow: /product_options
Disallow: /stNavigationFrontend
Disallow: /producer
Disallow: /navigation
Disallow: /invoice
Disallow: /order
Disallow: /orderPdf/*
Disallow: /invoicePdf/*
Disallow: /stAvailabilityFrontend/showAddOverlay
Disallow: /stQuestionFrontend/showAddOverlay
Disallow: /webpage/polityka-prywatnosci.html
Disallow: /product/recommendProducts/*
Sitemap: http://radosnapolana.pl/sitemap_pl.xml
Disallow: /*.php$
Disallow: /*.php$
User-agent: bingbot
Disallow: /
Disallow: /paypal

