User-agent: *
Allow: /
Disallow: http://sdip.kzkgop.pl/web/ml/timetable/post/
Disallow: http://sdip.kzkgop.pl/web/ml/timetable/journey/
Disallow: http://sdip.kzkgop.pl/web/ml/route/
Disallow: http://sdip.kzkgop.pl/web/ml/messages/bypost/
Disallow: http://sdip.kzkgop.pl/web/ml/messages/byroute/
Disallow: http://sdip.kzkgop.pl/web/ml/map/inline
Disallow: http://sdip.kzkgop.pl/web/ml/map/vehicles/
Disallow: http://sdip.kzkgop.pl/web/ml/map/stops/
Disallow: http://sdip.kzkgop.pl/web/mobile/timetable/journey/
Disallow: http://sdip.kzkgop.pl/web/mobile/route/
Disallow: http://sdip.kzkgop.pl/web/mobile/messages/bypost/
Disallow: http://sdip.kzkgop.pl/web/mobile/messages/byroute/
Disallow: http://sdip.kzkgop.pl/web/mobile/map/inline
Disallow: http://sdip.kzkgop.pl/web/mobile/map/vehicles/
Disallow: http://sdip.kzkgop.pl/web/mobile/map/stops/
Sitemap: http://sdip.kzkgop.pl/web/ml/sitemap.xml
Sitemap: http://sdip.kzkgop.pl/web/mobile/sitemap.xml
