User-agent: *
Allow: /
Disallow: /dev
Disallow: /_ads
Disallow: /actions
Disallow: /admin
Disallow: /batches
Disallow: /cgi-bin
Disallow: /cgi-bin
Disallow: /classes
Disallow: /config
Disallow: /css
Disallow: /dev
Disallow: /goodies
Disallow: /js
Disallow: /newsletter
Disallow: /templates
Disallow: /tools
