# robots.txt automaticaly generated by PrestaShop e-commerce open-source solution
# http://www.prestashop.com - http://www.prestashop.com/forums
# This file is to prevent the crawling and indexing of certain parts
# of your site by web crawlers and spiders run by sites like Yahoo!
# and Google. By telling these "robots" where not to go on your site,
# you save bandwidth and server resources.
# For more information about the robots.txt standard, see:
# http://www.robotstxt.org/robotstxt.html


#User-agent: TwengaBot-Discover
#Disallow: /
#User-agent: TwengaBot/2.0
#Disallow: /
#User-agent: TwengaBot
#Disallow: /



User-agent: *
# Allow Directives
# CHECK ALSO FILE PERMISSION directories are recursive 755 and the banner image is 644 as

#Disallow: /modules/blockcart/ajax-cart.js
#Disallow: /themes/default-bootstrap/js/modules/blockcart/ajax-cart.js

#Allow: */modules/*.css
#Allow: */modules/*.js




#Uwaga blokujemy strone ktorej nie chcemy aby sie pojawiala, bo duplikuje nam tresc!
Disallow: //*?en_contact-us*
Disallow: /blog/wp-admin/
Disallow: /blog/wp-admin/*
#Disallow: /module/mailalerts/actions?process*
#Disallow: /modules/mailalerts/actions?process*

Allow: /modules/*.css
Allow: /modules/*.js
Allow: /modules/*.png
Allow: /modules/*.gif
Allow: /modules/*.jpg
Allow: /modules/*.woff
Allow: /modules/*.ttf
Allow: /modules/*.svg

Disallow: /hxsd/
Disallow: /hxsd/*

Allow: /modules/*/*.css
Allow: /modules/*/*.js
Allow: /modules/*/*.png
Allow: /modules/*/*.gif
Allow: /modules/*/*.jpg

Allow: /themes/*.css
Allow: /themes/*.js
Allow: /themes/*.png
Allow: /themes/*.gif
Allow: /themes/*.jpg

Allow: /themes/*/*.css
Allow: /themes/*/*.js
Allow: /themes/*/*.png
Allow: /themes/*/*.gif
Allow: /themes/*/*.jpg


Allow: /modules/blockbanner/img/*.png
Allow: /modules/themeconfigurator/img/*.png
Allow: /modules/themeconfigurator/img/*.jpg
Allow: /modules/productpaymentlogos/img/*.jpg
Allow: /modules/elevatezoom/css/*.css
Allow: /modules/elevatezoom/js/*.js
Allow: /themes/default-bootstrap/css/modules/homeslider/images/*.gif
Allow: /themes/default-bootstrap/css/modules/homeslider/images/*.jpg
Allow: /themes/default-bootstrap/css/modules/homeslider/images/*.png

#Allow: */modules/themeconfigurator/img
#Allow: */modules/homeslider/images
#Allow /modules/*/css
#Allow /modules/*/js


# Private pages
Disallow: /*?orderby=
Disallow: /*?orderway=
Disallow: /*?tag=
Disallow: /*?id_currency=
Disallow: /*?search_query=
Disallow: /*?back=
Disallow: /*?n=
Disallow: /*&orderby=
Disallow: /*&orderway=
Disallow: /*&tag=
Disallow: /*&id_currency=
Disallow: /*&search_query=
Disallow: /*&back=
Disallow: /*&n=
Disallow: /*controller=addresses
Disallow: /*controller=address
Disallow: /*controller=authentication
Disallow: /*controller=cart
Disallow: /*controller=discount
Disallow: /*controller=footer
Disallow: /*controller=get-file
Disallow: /*controller=header
Disallow: /*controller=history
Disallow: /*controller=identity
Disallow: /*controller=images.inc
Disallow: /*controller=init
Disallow: /*controller=my-account
Disallow: /*controller=order
Disallow: /*controller=order-opc
Disallow: /*controller=order-slip
Disallow: /*controller=order-detail
Disallow: /*controller=order-follow
Disallow: /*controller=order-return
Disallow: /*controller=order-confirmation
Disallow: /*controller=pagination
Disallow: /*controller=password
Disallow: /*controller=pdf-invoice
Disallow: /*controller=pdf-order-return
Disallow: /*controller=pdf-order-slip
Disallow: /*controller=product-sort
Disallow: /*controller=search
Disallow: /*controller=statistics
Disallow: /*controller=attachment
Disallow: /*controller=guest-tracking
# Directories
Disallow: */classes/
Disallow: */config/
Disallow: */download/
Disallow: */mails/
Disallow: */modules/
Disallow: */translations/
Disallow: */tools/
# Files
Disallow: /*pl/odzyskiwanie-hasla
Disallow: /*pl/adres
Disallow: /*pl/adresy
Disallow: /*pl/logowanie
Disallow: /*pl/koszyk
Disallow: /*pl/rabaty
Disallow: /*pl/historia-zamowien
Disallow: /*pl/dane-osobiste
Disallow: /*pl/moje-konto
Disallow: /*pl/sledzenie-zamowienia
Disallow: /*pl/pokwitowania
Disallow: /*pl/zamowienie
Disallow: /*pl/szukaj
Disallow: /*pl/szybkie-zakupy
Disallow: /*pl/sledzenie-zamowienia-gosc
Disallow: /*pl/potwierdzenie-zamowienia
# Sitemap
Sitemap: https://shop.yulihobby.pl/1_index_sitemap.xml

