User-agent: *
Disallow: outsourcing/administrator/
Disallow: outsourcing/bin/
Disallow: outsourcing/cache/
Disallow: outsourcing/cli/
Disallow: outsourcing/components/
Disallow: outsourcing/includes/
Disallow: outsourcing/installation/
Disallow: outsourcing/language/
Disallow: outsourcing/layouts/
Disallow: outsourcing/libraries/
Disallow: outsourcing/logs/
Disallow: outsourcing/modules/
Disallow: outsourcing/plugins/
Disallow: outsourcing/tmp/
Disallow: nieruchomosci/administrator/
Disallow: nieruchomosci/bin/
Disallow: nieruchomosci/cache/
Disallow: nieruchomosci/cli/
Disallow: nieruchomosci/components/
Disallow: nieruchomosci/includes/
Disallow: nieruchomosci/installation/
Disallow: nieruchomosci/language/
Disallow: nieruchomosci/layouts/
Disallow: nieruchomosci/libraries/
Disallow: nieruchomosci/logs/
Disallow: nieruchomosci/modules/
Disallow: nieruchomosci/plugins/
Disallow: nieruchomosci/tmp/
Disallow: rusztowania/administrator/
Disallow: rusztowania/bin/
Disallow: rusztowania/cache/
Disallow: rusztowania/cli/
Disallow: rusztowania/components/
Disallow: rusztowania/includes/
Disallow: rusztowania/installation/
Disallow: rusztowania/language/
Disallow: rusztowania/layouts/
Disallow: rusztowania/libraries/
Disallow: rusztowania/logs/
Disallow: rusztowania/modules/
Disallow: rusztowania/plugins/
Disallow: rusztowania/tmp/
