Sitemap: http://wyrazista-strona.pl/sitemap.xml
User-agent: *
Allow: /*
Disallow: /wp-admin/
Disallow: /wp-includes/
Disallow: /wp-content/plugins/fullscreen-galleria/
User-agent: Googlebot
Allow: /*
Disallow: /wp-admin/
Disallow: /wp-includes/
Disallow: /wp-content/plugins/fullscreen-galleria/
User-agent: Googlebot-Mobile
Allow: /*
Disallow: /wp-admin/
Disallow: /wp-includes/
Disallow: /wp-content/plugins/fullscreen-galleria/
User-agent: Slurp
Allow: /*
Disallow: /wp-admin/
Disallow: /wp-includes/
Disallow: /wp-content/plugins/fullscreen-galleria/
Crawl-delay: 1
User-agent: MSNBot
Allow: /*
Disallow: /wp-admin/
Disallow: /wp-includes/
Disallow: /wp-content/plugins/fullscreen-galleria/
Crawl-delay: 10
User-agent: holmes
Allow: /*
Disallow: /wp-admin/
Disallow: /wp-includes/
Disallow: /wp-content/plugins/fullscreen-galleria/
User-agent: NetSprint
Allow: /*
Disallow: /wp-admin/
Disallow: /wp-includes/
Disallow: /wp-content/plugins/fullscreen-galleria/

