User-agent: *
Disallow: /allegro/
Disallow: /catalog/
Disallow: /admin/
Disallow: /download/
Disallow: /ie6/
Disallow: /system/
Disallow: /vqmod/
Disallow: /*&limit
Disallow: /*&sort
Disallow: /*?route=checkout/
Disallow: /*?route=account/
Disallow: /*?route=product/search
Disallow: /*?route=affiliate/
Disallow: /*?route=product/special/
Disallow: /*?route=product/nowosci/
Disallow: /*?route=product/bestsellers/
Disallow: /*&keyword
Disallow: /*?page=1
Disallow: /czas-dostawy.html
Disallow: /koszty-dostawy.html
Disallow: /reklamacje-i-zwroty.html
Disallow: /regulamin-zakupow.html
Disallow: /bezpieczenstwo-zakupow.html
Disallow: /platnosc.html
Disallow: /jak-kupowac.html
Disallow: /dlaczego-warto-kupowac-w-ehak24pl.html
Disallow: /FAQ.html
Allow: /
