# robots.txt automaticaly generated by PrestaShop e-commerce open-source solution
# http://www.prestashop.com - http://www.prestashop.com/forums
# This file is to prevent the crawling and indexing of certain parts
# of your site by web crawlers and spiders run by sites like Yahoo!
# and Google. By telling these "robots" where not to go on your site,
# you save bandwidth and server resources.
# For more information about the robots.txt standard, see:
# http://www.robotstxt.org/robotstxt.html
User-agent: *
# Allow Directives
Allow: */modules/*.css
Allow: */modules/*.js
# Private pages
Disallow: /*?orderby=
Disallow: /*?orderway=
Disallow: /*?tag=
Disallow: /*?id_currency=
Disallow: /*?search_query=
Disallow: /*?back=
Disallow: /*?n=
Disallow: /*&orderby=
Disallow: /*&orderway=
Disallow: /*&tag=
Disallow: /*&id_currency=
Disallow: /*&search_query=
Disallow: /*&back=
Disallow: /*&n=
Disallow: /*controller=addresses
Disallow: /*controller=address
Disallow: /*controller=authentication
Disallow: /*controller=cart
Disallow: /*controller=discount
Disallow: /*controller=footer
Disallow: /*controller=get-file
Disallow: /*controller=header
Disallow: /*controller=history
Disallow: /*controller=identity
Disallow: /*controller=images.inc
Disallow: /*controller=init
Disallow: /*controller=my-account
Disallow: /*controller=order
Disallow: /*controller=order-opc
Disallow: /*controller=order-slip
Disallow: /*controller=order-detail
Disallow: /*controller=order-follow
Disallow: /*controller=order-return
Disallow: /*controller=order-confirmation
Disallow: /*controller=pagination
Disallow: /*controller=password
Disallow: /*controller=pdf-invoice
Disallow: /*controller=pdf-order-return
Disallow: /*controller=pdf-order-slip
Disallow: /*controller=product-sort
Disallow: /*controller=search
Disallow: /*controller=statistics
Disallow: /*controller=attachment
Disallow: /*controller=guest-tracking
# Directories
Disallow: */classes/
Disallow: */config/
Disallow: */download/
Disallow: */mails/
Disallow: */modules/
Disallow: */translations/
Disallow: */tools/
# Files
Disallow: /*pl/adres
Disallow: /*pl/adresy
Disallow: /*pl/logowanie
Disallow: /*pl/koszyk
Disallow: /*pl/kody-rabatowe
Disallow: /*pl/sledzenie-zamowienia-gosc
Disallow: /*pl/moje-zamowienia
Disallow: /*pl/informacje-osobiste
Disallow: /*pl/moje-konto
Disallow: /*pl/zamowienie
Disallow: /*pl/potwierdzenie-zamowienia
Disallow: /*pl/moje-zwroty
Disallow: /*pl/szybkie-zakupy
Disallow: /*pl/moje-rachunki
Disallow: /*pl/odzyskiwanie-hasla
Disallow: /*pl/szukaj
Disallow: /*en/adres
Disallow: /*en/adresy
Disallow: /*en/logowanie
Disallow: /*en/koszyk
Disallow: /*en/kody-rabatowe
Disallow: /*en/sledzenie-zamowienia-gosc
Disallow: /*en/my-orders
Disallow: /*en/informacje-osobiste
Disallow: /*en/my-account
Disallow: /*en/zamowienie
Disallow: /*en/potwierdzenie-zamowienia
Disallow: /*en/my-returns
Disallow: /*en/szybkie-zakupy
Disallow: /*en/my-bills
Disallow: /*en/odzyskiwanie-hasla
Disallow: /*en/szukaj

