# robots.txt automaticaly generated by PrestaShop e-commerce open-source solution
# http://www.prestashop.com - http://www.prestashop.com/forums

# This file is to prevent the crawling and indexing of certain parts
# of your site by web crawlers and spiders run by sites like Yahoo!
# and Google. By telling these "robots" where not to go on your site,
# you save bandwidth and server resources.

# For more information about the robots.txt standard, see:
# http://www.robotstxt.org/wc/robots.html

User-agent: *

# Directories
Disallow: /presta_shop/classes/
Disallow: /presta_shop/config/
Disallow: /presta_shop/download/
Disallow: /presta_shop/mails/
Disallow: /presta_shop/modules/
Disallow: /presta_shop/translations/
Disallow: /presta_shop/tools/

# Files
Disallow: /presta_shop/addresses.php
Disallow: /presta_shop/address.php
Disallow: /presta_shop/authentication.php
Disallow: /presta_shop/cart.php
Disallow: /presta_shop/contact-form.php
Disallow: /presta_shop/discount.php
Disallow: /presta_shop/footer.php
Disallow: /presta_shop/get-file.php
Disallow: /presta_shop/header.php
Disallow: /presta_shop/history.php
Disallow: /presta_shop/identity.php
Disallow: /presta_shop/images.inc.php
Disallow: /presta_shop/init.php
Disallow: /presta_shop/my-account.php
Disallow: /presta_shop/order.php
Disallow: /presta_shop/order-slip.php
Disallow: /presta_shop/order-detail.php
Disallow: /presta_shop/order-follow.php
Disallow: /presta_shop/order-return.php
Disallow: /presta_shop/order-confirmation.php
Disallow: /presta_shop/pagination.php
Disallow: /presta_shop/password.php
Disallow: /presta_shop/pdf-invoice.php
Disallow: /presta_shop/pdf-order-return.php
Disallow: /presta_shop/pdf-order-slip.php
Disallow: /presta_shop/product-sort.php
Disallow: /presta_shop/search.php
Disallow: /presta_shop/statistics.php
Disallow: /presta_shop/zoom.php


