User-Agent: Yandex
Disallow: /
User-Agent: MJ12bot
Disallow: /
User-agent: Yahoo-Blogs
Disallow: /
User-agent: Yahoo-MMCrawler
Disallow: /
User-agent: AhrefsBot
Disallow: /
User-agent: rogerbot
Disallow: /
User-agent: msnbot
Disallow: /
User-agent: Slurp
Disallow: /
