User-agent: *
Disallow: /*&limit
Disallow: /*&sort
Disallow: /*?route=checkout/
Disallow: /*?route=account/
Disallow: /*?route=product/search
Disallow: /*?route=affiliate/
Disallow: /*?limit
Disallow: /*?sort
Disallow: /*&order
Disallow: /*?order
Disallow: /*?price
Disallow: /*&price
Disallow: /*?manufacturer
Disallow: /*?keyword
Disallow: /*?brand_tabletpc
Disallow: /*&brand_tabletpc
Disallow: /*?color_default
Disallow: /*&color_default
Disallow: /*?filter_tag
Disallow: /*&filter_tag
Disallow: /*?mode
Disallow: /*&mode
Disallow: /*?page=1
Disallow: /index.php?route=product/special
Disallow: /zaplecze-5-x-blox-pl
Disallow: /Sklep%20SEO,%20Sklep%20SiteSEO

Sitemap: https://sklep.siteseo.pl/index.php?route=feed/google_sitemap
