User-agent: *
Disallow: /_stats/
Disallow: /admin/
Disallow: /css/
Disallow: /flash/
Disallow: /images/
Disallow: /img/
Disallow: /inc/
Disallow: /js/
Disallow: /kopie/
Disallow: /modules/
Disallow: /podstrony/
Disallow: /sklep/
Disallow: /tmp/
Disallow: /banery_statystyki.php
Disallow: /drukuj.php
Disallow: /loga.swf
Disallow: /newsletter.php
Disallow: /out_sc.php
Disallow: /znak.php
