User-agent: *
Sitemap: http://sklep.altix.pl/pl/sitemap.xml
Sitemap: http://sklep.altix.pl/en/sitemap.xml
Sitemap: http://sklep.altix.pl/ru/sitemap.xml
Sitemap: http://sklep.altix.pl/ro/sitemap.xml
Sitemap: http://sklep.altix.pl/bg/sitemap.xml
Sitemap: http://sklep.altix.pl/de/sitemap.xml
Disallow: /bin/
Disallow: /content/files/
Disallow: /content/files/exportimport/
Disallow: /country/getstatesbycountryid
Disallow: /install
Disallow: /setproductreviewhelpfulness
Disallow: /addproducttocart/catalog/
Disallow: /addproducttocart/details/
Disallow: /backinstocksubscriptions/manage
Disallow: /boards/forumsubscriptions
Disallow: /boards/forumwatch
Disallow: /boards/postedit
Disallow: /boards/postdelete
Disallow: /boards/postcreate
Disallow: /boards/topicedit
Disallow: /boards/topicdelete
Disallow: /boards/topiccreate
Disallow: /boards/topicmove
Disallow: /boards/topicwatch
Disallow: /cart
Disallow: /checkout
Disallow: /checkout/billingaddress
Disallow: /checkout/completed
Disallow: /checkout/confirm
Disallow: /checkout/shippingaddress
Disallow: /checkout/shippingmethod
Disallow: /checkout/paymentinfo
Disallow: /checkout/paymentmethod
Disallow: /clearcomparelist
Disallow: /compareproducts
Disallow: /compareproducts/add/*
Disallow: /customer/avatar
Disallow: /customer/activation
Disallow: /customer/addresses
Disallow: /customer/changepassword
Disallow: /customer/checkusernameavailability
Disallow: /customer/downloadableproducts
Disallow: /customer/info
Disallow: /deletepm
Disallow: /emailwishlist
Disallow: /inboxupdate
Disallow: /newsletter/subscriptionactivation
Disallow: /onepagecheckout
Disallow: /order/history
Disallow: /orderdetails
Disallow: /passwordrecovery/confirm
Disallow: /poll/vote
Disallow: /privatemessages
Disallow: /returnrequest
Disallow: /returnrequest/history
Disallow: /rewardpoints/history
Disallow: /sendpm
Disallow: /sentupdate
Disallow: /shoppingcart/*
Disallow: /subscribenewsletter
Disallow: /topic/authenticate
Disallow: /viewpm
Disallow: /uploadfileproductattribute
Disallow: /uploadfilecheckoutattribute
Disallow: /wishlist
Disallow: pl/addproducttocart/catalog/
Disallow: pl/addproducttocart/details/
Disallow: pl/backinstocksubscriptions/manage
Disallow: pl/boards/forumsubscriptions
Disallow: pl/boards/forumwatch
Disallow: pl/boards/postedit
Disallow: pl/boards/postdelete
Disallow: pl/boards/postcreate
Disallow: pl/boards/topicedit
Disallow: pl/boards/topicdelete
Disallow: pl/boards/topiccreate
Disallow: pl/boards/topicmove
Disallow: pl/boards/topicwatch
Disallow: pl/cart
Disallow: pl/checkout
Disallow: pl/checkout/billingaddress
Disallow: pl/checkout/completed
Disallow: pl/checkout/confirm
Disallow: pl/checkout/shippingaddress
Disallow: pl/checkout/shippingmethod
Disallow: pl/checkout/paymentinfo
Disallow: pl/checkout/paymentmethod
Disallow: pl/clearcomparelist
Disallow: pl/compareproducts
Disallow: pl/compareproducts/add/*
Disallow: pl/customer/avatar
Disallow: pl/customer/activation
Disallow: pl/customer/addresses
Disallow: pl/customer/changepassword
Disallow: pl/customer/checkusernameavailability
Disallow: pl/customer/downloadableproducts
Disallow: pl/customer/info
Disallow: pl/deletepm
Disallow: pl/emailwishlist
Disallow: pl/inboxupdate
Disallow: pl/newsletter/subscriptionactivation
Disallow: pl/onepagecheckout
Disallow: pl/order/history
Disallow: pl/orderdetails
Disallow: pl/passwordrecovery/confirm
Disallow: pl/poll/vote
Disallow: pl/privatemessages
Disallow: pl/returnrequest
Disallow: pl/returnrequest/history
Disallow: pl/rewardpoints/history
Disallow: pl/sendpm
Disallow: pl/sentupdate
Disallow: pl/shoppingcart/*
Disallow: pl/subscribenewsletter
Disallow: pl/topic/authenticate
Disallow: pl/viewpm
Disallow: pl/uploadfileproductattribute
Disallow: pl/uploadfilecheckoutattribute
Disallow: pl/wishlist
Disallow: en/addproducttocart/catalog/
Disallow: en/addproducttocart/details/
Disallow: en/backinstocksubscriptions/manage
Disallow: en/boards/forumsubscriptions
Disallow: en/boards/forumwatch
Disallow: en/boards/postedit
Disallow: en/boards/postdelete
Disallow: en/boards/postcreate
Disallow: en/boards/topicedit
Disallow: en/boards/topicdelete
Disallow: en/boards/topiccreate
Disallow: en/boards/topicmove
Disallow: en/boards/topicwatch
Disallow: en/cart
Disallow: en/checkout
Disallow: en/checkout/billingaddress
Disallow: en/checkout/completed
Disallow: en/checkout/confirm
Disallow: en/checkout/shippingaddress
Disallow: en/checkout/shippingmethod
Disallow: en/checkout/paymentinfo
Disallow: en/checkout/paymentmethod
Disallow: en/clearcomparelist
Disallow: en/compareproducts
Disallow: en/compareproducts/add/*
Disallow: en/customer/avatar
Disallow: en/customer/activation
Disallow: en/customer/addresses
Disallow: en/customer/changepassword
Disallow: en/customer/checkusernameavailability
Disallow: en/customer/downloadableproducts
Disallow: en/customer/info
Disallow: en/deletepm
Disallow: en/emailwishlist
Disallow: en/inboxupdate
Disallow: en/newsletter/subscriptionactivation
Disallow: en/onepagecheckout
Disallow: en/order/history
Disallow: en/orderdetails
Disallow: en/passwordrecovery/confirm
Disallow: en/poll/vote
Disallow: en/privatemessages
Disallow: en/returnrequest
Disallow: en/returnrequest/history
Disallow: en/rewardpoints/history
Disallow: en/sendpm
Disallow: en/sentupdate
Disallow: en/shoppingcart/*
Disallow: en/subscribenewsletter
Disallow: en/topic/authenticate
Disallow: en/viewpm
Disallow: en/uploadfileproductattribute
Disallow: en/uploadfilecheckoutattribute
Disallow: en/wishlist
Disallow: ru/addproducttocart/catalog/
Disallow: ru/addproducttocart/details/
Disallow: ru/backinstocksubscriptions/manage
Disallow: ru/boards/forumsubscriptions
Disallow: ru/boards/forumwatch
Disallow: ru/boards/postedit
Disallow: ru/boards/postdelete
Disallow: ru/boards/postcreate
Disallow: ru/boards/topicedit
Disallow: ru/boards/topicdelete
Disallow: ru/boards/topiccreate
Disallow: ru/boards/topicmove
Disallow: ru/boards/topicwatch
Disallow: ru/cart
Disallow: ru/checkout
Disallow: ru/checkout/billingaddress
Disallow: ru/checkout/completed
Disallow: ru/checkout/confirm
Disallow: ru/checkout/shippingaddress
Disallow: ru/checkout/shippingmethod
Disallow: ru/checkout/paymentinfo
Disallow: ru/checkout/paymentmethod
Disallow: ru/clearcomparelist
Disallow: ru/compareproducts
Disallow: ru/compareproducts/add/*
Disallow: ru/customer/avatar
Disallow: ru/customer/activation
Disallow: ru/customer/addresses
Disallow: ru/customer/changepassword
Disallow: ru/customer/checkusernameavailability
Disallow: ru/customer/downloadableproducts
Disallow: ru/customer/info
Disallow: ru/deletepm
Disallow: ru/emailwishlist
Disallow: ru/inboxupdate
Disallow: ru/newsletter/subscriptionactivation
Disallow: ru/onepagecheckout
Disallow: ru/order/history
Disallow: ru/orderdetails
Disallow: ru/passwordrecovery/confirm
Disallow: ru/poll/vote
Disallow: ru/privatemessages
Disallow: ru/returnrequest
Disallow: ru/returnrequest/history
Disallow: ru/rewardpoints/history
Disallow: ru/sendpm
Disallow: ru/sentupdate
Disallow: ru/shoppingcart/*
Disallow: ru/subscribenewsletter
Disallow: ru/topic/authenticate
Disallow: ru/viewpm
Disallow: ru/uploadfileproductattribute
Disallow: ru/uploadfilecheckoutattribute
Disallow: ru/wishlist
Disallow: ro/addproducttocart/catalog/
Disallow: ro/addproducttocart/details/
Disallow: ro/backinstocksubscriptions/manage
Disallow: ro/boards/forumsubscriptions
Disallow: ro/boards/forumwatch
Disallow: ro/boards/postedit
Disallow: ro/boards/postdelete
Disallow: ro/boards/postcreate
Disallow: ro/boards/topicedit
Disallow: ro/boards/topicdelete
Disallow: ro/boards/topiccreate
Disallow: ro/boards/topicmove
Disallow: ro/boards/topicwatch
Disallow: ro/cart
Disallow: ro/checkout
Disallow: ro/checkout/billingaddress
Disallow: ro/checkout/completed
Disallow: ro/checkout/confirm
Disallow: ro/checkout/shippingaddress
Disallow: ro/checkout/shippingmethod
Disallow: ro/checkout/paymentinfo
Disallow: ro/checkout/paymentmethod
Disallow: ro/clearcomparelist
Disallow: ro/compareproducts
Disallow: ro/compareproducts/add/*
Disallow: ro/customer/avatar
Disallow: ro/customer/activation
Disallow: ro/customer/addresses
Disallow: ro/customer/changepassword
Disallow: ro/customer/checkusernameavailability
Disallow: ro/customer/downloadableproducts
Disallow: ro/customer/info
Disallow: ro/deletepm
Disallow: ro/emailwishlist
Disallow: ro/inboxupdate
Disallow: ro/newsletter/subscriptionactivation
Disallow: ro/onepagecheckout
Disallow: ro/order/history
Disallow: ro/orderdetails
Disallow: ro/passwordrecovery/confirm
Disallow: ro/poll/vote
Disallow: ro/privatemessages
Disallow: ro/returnrequest
Disallow: ro/returnrequest/history
Disallow: ro/rewardpoints/history
Disallow: ro/sendpm
Disallow: ro/sentupdate
Disallow: ro/shoppingcart/*
Disallow: ro/subscribenewsletter
Disallow: ro/topic/authenticate
Disallow: ro/viewpm
Disallow: ro/uploadfileproductattribute
Disallow: ro/uploadfilecheckoutattribute
Disallow: ro/wishlist
Disallow: bg/addproducttocart/catalog/
Disallow: bg/addproducttocart/details/
Disallow: bg/backinstocksubscriptions/manage
Disallow: bg/boards/forumsubscriptions
Disallow: bg/boards/forumwatch
Disallow: bg/boards/postedit
Disallow: bg/boards/postdelete
Disallow: bg/boards/postcreate
Disallow: bg/boards/topicedit
Disallow: bg/boards/topicdelete
Disallow: bg/boards/topiccreate
Disallow: bg/boards/topicmove
Disallow: bg/boards/topicwatch
Disallow: bg/cart
Disallow: bg/checkout
Disallow: bg/checkout/billingaddress
Disallow: bg/checkout/completed
Disallow: bg/checkout/confirm
Disallow: bg/checkout/shippingaddress
Disallow: bg/checkout/shippingmethod
Disallow: bg/checkout/paymentinfo
Disallow: bg/checkout/paymentmethod
Disallow: bg/clearcomparelist
Disallow: bg/compareproducts
Disallow: bg/compareproducts/add/*
Disallow: bg/customer/avatar
Disallow: bg/customer/activation
Disallow: bg/customer/addresses
Disallow: bg/customer/changepassword
Disallow: bg/customer/checkusernameavailability
Disallow: bg/customer/downloadableproducts
Disallow: bg/customer/info
Disallow: bg/deletepm
Disallow: bg/emailwishlist
Disallow: bg/inboxupdate
Disallow: bg/newsletter/subscriptionactivation
Disallow: bg/onepagecheckout
Disallow: bg/order/history
Disallow: bg/orderdetails
Disallow: bg/passwordrecovery/confirm
Disallow: bg/poll/vote
Disallow: bg/privatemessages
Disallow: bg/returnrequest
Disallow: bg/returnrequest/history
Disallow: bg/rewardpoints/history
Disallow: bg/sendpm
Disallow: bg/sentupdate
Disallow: bg/shoppingcart/*
Disallow: bg/subscribenewsletter
Disallow: bg/topic/authenticate
Disallow: bg/viewpm
Disallow: bg/uploadfileproductattribute
Disallow: bg/uploadfilecheckoutattribute
Disallow: bg/wishlist
Disallow: de/addproducttocart/catalog/
Disallow: de/addproducttocart/details/
Disallow: de/backinstocksubscriptions/manage
Disallow: de/boards/forumsubscriptions
Disallow: de/boards/forumwatch
Disallow: de/boards/postedit
Disallow: de/boards/postdelete
Disallow: de/boards/postcreate
Disallow: de/boards/topicedit
Disallow: de/boards/topicdelete
Disallow: de/boards/topiccreate
Disallow: de/boards/topicmove
Disallow: de/boards/topicwatch
Disallow: de/cart
Disallow: de/checkout
Disallow: de/checkout/billingaddress
Disallow: de/checkout/completed
Disallow: de/checkout/confirm
Disallow: de/checkout/shippingaddress
Disallow: de/checkout/shippingmethod
Disallow: de/checkout/paymentinfo
Disallow: de/checkout/paymentmethod
Disallow: de/clearcomparelist
Disallow: de/compareproducts
Disallow: de/compareproducts/add/*
Disallow: de/customer/avatar
Disallow: de/customer/activation
Disallow: de/customer/addresses
Disallow: de/customer/changepassword
Disallow: de/customer/checkusernameavailability
Disallow: de/customer/downloadableproducts
Disallow: de/customer/info
Disallow: de/deletepm
Disallow: de/emailwishlist
Disallow: de/inboxupdate
Disallow: de/newsletter/subscriptionactivation
Disallow: de/onepagecheckout
Disallow: de/order/history
Disallow: de/orderdetails
Disallow: de/passwordrecovery/confirm
Disallow: de/poll/vote
Disallow: de/privatemessages
Disallow: de/returnrequest
Disallow: de/returnrequest/history
Disallow: de/rewardpoints/history
Disallow: de/sendpm
Disallow: de/sentupdate
Disallow: de/shoppingcart/*
Disallow: de/subscribenewsletter
Disallow: de/topic/authenticate
Disallow: de/viewpm
Disallow: de/uploadfileproductattribute
Disallow: de/uploadfilecheckoutattribute
Disallow: de/wishlist

