User-agent: *
Disallow: /ajax/
Disallow: /api/
Disallow: /csv/
Disallow: /lib/
Disallow: /mail/
Disallow: /media/
Disallow: /site_controller/
Disallow: /site_data/
Disallow: /site_model/
Disallow: /site_pages/
Disallow: /temp/
Disallow: /templates/
Disallow: /templates_c/
Disallow: /config.php
Disallow: /configEx.php
Disallow: /fileUpload.php
Disallow: /foto.php
Disallow: /get_file.php
Disallow: /open_file.php
Disallow: /robot.php
Disallow: /soap.php
Disallow: /subscription_cancel.php
Sitemap: http://***/sitemap.xml
