User-Agent: *
disallow: /fr/
disallow: /it/
disallow: /fi/
disallow: /se/
disallow: /no/
disallow: /de/
disallow: /cs/
disallow: /sk/
disallow: /tr/
disallow: /ch/
disallow: /ru/
disallow: /cn/
disallow: /jp/
disallow: /da/
disallow: /sl/
disallow: /hu/
disallow: /pt/
disallow: /va/
