User-agent: *
Crawl-delay: 2
Request-rate: 1/1s

User-agent: *
Disallow: /application
Disallow: /environment
Allow: /environment/cache/images
Disallow: /libraries
Disallow: /*/fav/add
Disallow: /*/p/comment/add
Disallow: /*/p/mail/recommend
Disallow: /*/p/q
Disallow: /*/reg
Disallow: /*/login
Disallow: /*/basket
Disallow: /*/searchquery
Disallow: /*/p/Kasztanki-luz/77
Disallow: /*/p/Adwokat-luz/78
Disallow: /*/p/Krowkowa-luz/79
Disallow: /*/p/Malaga-luz/80
Disallow: /*/p/Tiki-Taki-luz/81
Disallow: /*/p/Tiramisu-luz/82
Disallow: /*/p/Michalki-biale-luz/84
Disallow: /*/p/Tofflairs-luz/85
Disallow: /*/p/Tofflairs-Czekoladowo-Mleczny-LUZ/86
Disallow: /*/p/Michalki-klasyczne-luz/87
Disallow: /*/p/Michalki-kokosowe-luz/88
Disallow: /*/p/Mieszanka-krakowska-luz/89
Disallow: /*/p/Krowka-mleczna-luz/90
Disallow: /*/p/Trufle-luz/91
Disallow: /*/p/Pastylki-mietowe-zawijane-luz/92
Disallow: /*/p/Mieszanka-krakowska-Nowe-Smaki-luz/93
Disallow: /*/p/Galaretka-FreshFruity-luz/94
Disallow: /*/p/Galaretka-FreshFruity-kwasna-luz/95
Disallow: /*/p/Galaretka-FreshFruity-Multiwitaina-luz/96
Disallow: /*/p/Mietowe-orzezwiajace-luz/97
Disallow: /*/p/Fistaszkowe-luz/98
Disallow: /*/p/Kukulka-zawijana-luz/99
Disallow: /*/p/Raczki-luz/100
Disallow: /*/p/Nut-Break-luz/130
