Sitemap: http://forums.photoartsforum.com/index.php?action=sitemap;xml

User-Agent: *
Request-rate: 1/5
Disallow: /cgi-bin/
Disallow: /forum/attachments/
Disallow: /forum/avatars/
Disallow: /forum/avs/
Disallow: /forum/cache/
Disallow: /forum/chat/
Disallow: /forum/images/
Disallow: /forum/js/
Disallow: /forum/Packages/
Disallow: /forum/site/
Disallow: /forum/site1/
Disallow: /forum/Smileys/
Disallow: /forum/Sources/
Disallow: /forum/steamprofile/
Disallow: /forum/Themes/
Disallow: /forum/tp-downloads/
Disallow: /forum/tp-files/
Disallow: /forum/tp-images/
Disallow: /forum/index.php?action=search
Disallow: /forum/index.php?action=calendar
Disallow: /forum/index.php?action=login
Disallow: /forum/index.php?action=register
Disallow: /forum/index.php?action=profile
Disallow: /forum/index.php?action=stats
Disallow: /forum/index.php?action=activate
Disallow: /forum/index.php?action=help
Disallow: /forum/index.php?action=admin
Disallow: /forum/index.php?action=pm
Disallow: /forum/index.php?action=mlist
Disallow: /forum/index.php?action=notify
Disallow: /forum/index.php?action=post
Disallow: /forum/index.php?action=markasread
Disallow: /forum/index.php?action=sendtopic
Disallow: /forum/index.php?action=printpage
Disallow: /forum/index.php?action=dlattach
Disallow: /forum/index.php?action=reminder
Disallow: /forum/index.php?action=collapse
Disallow: /forum/index.php?action=reporttm
Disallow: /forum/index.php?action=who
Disallow: /forum/index.php?PHPSESSID=*
Disallow: /forum/*topicseen
Disallow: /forum/*sort*
Disallow: /forum/*msg*
Disallow: /forum/*prev_next*
Disallow: /forum/*;all
Disallow: /forum/*;wap
Disallow: /forum/*;wap2
Disallow: /forum/*;imode
Disallow: /forum/*.msg
Disallow: /forum/*.new
Disallow: /forum/*wap2*

User-agent: *
Allow: /forum/index.php?action=sitemap
Allow: /forum/index.php?action=sitemap;xml

