# robots.txt file for http://studio-metamorfoza.pl/
# Generated by SOFTplus GSiteCrawler v1.23 rev. 286 / http://gsitecrawler.com/
# 2015-03-12  00:56

User-agent: *
# No exclusions found, disallow nothing.
Disallow:

# end of file


