User-agent: *
Disallow: /allegro/
Disallow: /historia/
Disallow: /integ_ceneo/
Disallow: /integ_nokaut/
Disallow: /kod_o/
Disallow: /magazyn/
Disallow: /magazyn2/
Disallow: /magazyn3/
Disallow: /pliki/
Disallow: /pliki_aukcje/
Disallow: /sesja/
Disallow: /tmp/
Disallow: /url-test/
Disallow: /zamowienia/
Disallow: /dodaj_opinie.php
Disallow: /porownywarka.php
Disallow: /filtrowane1.php
Disallow: /*kolejnosc
Disallow: /logowanie
Disallow: /prom.php
Disallow: /promocje
Disallow: /nowosc.php
Disallow: /nr_konta
Disallow: /regulamin
Disallow: /pytania.php
Disallow: /koszyk
Disallow: /dane-osobowe
Disallow: /szukaj
Disallow: /*strona-1
Disallow: /*grupa-wag
Disallow: /*opinie
Disallow: /rowerek,6
Disallow: /rowerek,7
Disallow: /rowerek,8
Disallow: /pojazd-na-akumulator,30
Disallow: /pojazd-na-akumulator,31
Disallow: /pojazd-na-akumulator,32
Disallow: /pojazd-na-akumulator,33
Disallow: /pojazd-na-akumulator,34
Disallow: /krzeselko-do-karmienia,14
Disallow: /krzeselko-do-karmienia,13
Disallow: /krzeselko-do-karmienia,35
Disallow: /*,arti$
Disallow: /*,euro-baby$
Disallow: /*,euro-cart$
Disallow: /*,graco$
Disallow: /*,jane$
Disallow: /*,kinderkraft$
Disallow: /*,krasnal$
Disallow: /*,patti$
Disallow: /*,recaro$
Disallow: /*,romer$
Disallow: /*,sena$
Disallow: /*,recaro$
Disallow: /*,romer$
Disallow: /*,sena$
Disallow: /*,adamex$
Disallow: /*,baby-design$
Disallow: /*,babyono$
Disallow: /*,caretero$
Disallow: /*,kees$
Disallow: /*,milly-mally$
Disallow: /*,4baby$
Disallow: /*,adamex$
Disallow: /*,baby-booom$
Disallow: /*,baby-star$
Disallow: /*,babyactive$
Disallow: /*,coletto$
Disallow: /*,elcar$
Disallow: /*,espiro$
Disallow: /*,implast$
Disallow: /*,markas$
Disallow: /*,michelle$
Disallow: /*,palex$
Disallow: /*,quatro$
Disallow: /*,tako$
Disallow: /*,tufi$
Disallow: /*,titiland$
Disallow: /*,uniwersalna$
Disallow: /*,infant$
Disallow: /*,elgrom$
Disallow: /*,feber$
Disallow: /*,elgrom$
Disallow: /*,mm-trend$
Disallow: /*,klups$
Disallow: /*,jardrew$
Disallow: /*,animali$
Disallow: /*,drewex$
Disallow: /*,berber$
Disallow: /*,danpol$
Disallow: /*,lux$
Disallow: /*,baby-raj$
Disallow: /*,baby-mix$
Disallow: /*,babymix$
Disallow: /*,blanca-baby$
Disallow: /*,matex$
Disallow: /*,ceba$
Disallow: /*,coto$
Disallow: /*,britax$
Disallow: /*,canpol-babies$
Disallow: /*,swift$
Disallow: /*,double-horse$
Disallow: /*,poltronic$







