User-agent: *
Crawl-delay: 2
Request-rate: 1/1s

Sitemap: https://tulisie.pl/console/integration/execute/name/GoogleSitemap
User-agent: *
Allow: /environment/cache/images/
Allow: /skins/store_user/*/cache/
Allow: /skins/store_user/*/images/
Allow: /skins/store_user/*/styles/
Allow: /skins/user/rwd_shoper_1/*/*/*.css
Allow: /skins/user/rwd_shoper_1/*/*/*.js
Allow: /skins/user/rwd_shoper_1/*/*/*.ttf
Allow: /skins/user/rwd_shoper_1/*/*/*.woff
Allow: /public/assets/
Allow: /public/scripts/

Disallow: /application/
Disallow: /environment/
Disallow: /libraries/
Disallow: /*/fav/add
Disallow: /*/p/comment/add
Disallow: /*/p/mail/recommend
Disallow: /*/p/q
Disallow: /*/reg
Disallow: /*/login
Disallow: /*/panel
Disallow: /*/promotions
Disallow: /*/panel/edit
Disallow: /*/panel/favourites
Disallow: /*/basket
Disallow: /*/searchquery/*
Disallow: /*/passremind
Disallow: /*/default/*
Disallow: /*/*/default/*
Disallow: /*/*/*/default/*
Disallow: /*/*/*/*/default/*
Disallow: /reklamacje-zwroty
Disallow: /regulamin
Disallow: /polityka-prywatnosci
Disallow: /index
Disallow: /index/*
Disallow: /*/index
Disallow: /*/index/*
Disallow: /*/s/
Disallow: /*/producer/*
Disallow: /login
Disallow: /dzien-dziecka
Disallow: /*/full/*
