User-agent: *
Crawl-delay: 2
Request-rate: 1/1s

User-agent: *
Disallow: /*/p/mail/recommend
Disallow: /*/p/q
Disallow: /admin
Allow: /environment/cache/images
Disallow: /application
Disallow: /environment
Disallow: /libraries
Disallow: /pl/promotions
Disallow: /pl/basket
Disallow: /pl/fav/add
Disallow: /pl/links
Disallow: /pl/passremind
Disallow: /*reg*
Disallow: /mobile
Disallow: /komentarz-
Disallow: /powiadom_znajomego-
Disallow: /pl/banner
Disallow: /pl/p/mail
Disallow: /*login*
Disallow: /panel
Disallow: /*en_US*
Disallow: /pl/new
Disallow: /pl_PL
Disallow: /pl/p/mail/recommend
Disallow: /pl/p/q
Disallow: /links
Disallow: /*mobile*
Disallow: /*fav*
Disallow: /*searchquery*
Disallow: /pl/s*
Disallow: /pl/index/2
Disallow: /*searchquery*
Disallow: /*promotion*
Disallow: /*default*
Disallow: /*full*
Disallow: /*pricefrom*
Disallow: /*news*
Allow: /
Disallow: /*/reg
Disallow: /*/login
Disallow: /*/basket
Disallow: /*/searchquery

