User-agent: MJ12bot
Disallow: /

User-agent: 008
Disallow: /

User-agent: *
Disallow: /blog/wp-admin/
Disallow: /misc/
Disallow: /mobi/
Disallow: /myshortlist.html
Disallow: /shortlistShow/
Disallow: /rentals/shortlistShow.asp
Disallow: /rentals/shortlistRemove.asp
Disallow: /shortlistremove/
Disallow: /rentals/shortlistAdd.asp
Disallow: /shortlistadd/
Disallow: /redirect.asp
Disallow: /ownerwebsiteredirect
Disallow: /preview/
Disallow: /rentals/search-advanced.asp
Disallow: /rentals/searchresult.asp
Disallow: /services/
Allow: /services/VideoService.svc/
Disallow: /PayPalButtonIFrame
Disallow: /ArticleUI/UserControls/
Disallow: /press/photos
Disallow: /api/error
Disallow: /emailOwner/
Disallow: /kontaktejer/
Disallow: /kontakteier/
Disallow: /eigentumer-kontaktieren/
Disallow: /peticion/
Disallow: /contacteer-eigenaar/
Disallow: /emailProprietaire/
Disallow: /emailproprietari/
Disallow: /email-proprietario/
Disallow: /emailagare/
Disallow: /napiszdowlasciciela/
Disallow: /kirjoitaOmistajalle/
Disallow: /myshortlist/
Disallow: /myshortlist
Disallow: /favoritliste/
Disallow: /favoritliste
Disallow: /favorittliste/
Disallow: /favorittliste
Disallow: /hauserliste/
Disallow: /hauserliste
Disallow: /favoritos/
Disallow: /favoritos
Disallow: /favorietenlijst/
Disallow: /favorietenlijst
Disallow: /favoris/
Disallow: /favoris
Disallow: /preferiti/
Disallow: /preferiti
Disallow: /favoritas/
Disallow: /favoritas
Disallow: /favoritlista/
Disallow: /favoritlista
Disallow: /mojeulubione/
Disallow: /mojeulubione
Disallow: /suosikkini/
Disallow: /suosikkini
Disallow: /renter/account
Disallow: /renter/forgotpassword
Disallow: /renter/createuser
Disallow: /lejer/konto
Disallow: /lejer/opretbruger
Disallow: /lejer/glemtkode
Disallow: /leietaker/konto
Disallow: /leietaker/opprettbruker
Disallow: /leietaker/glemtpassord
Disallow: /mieter/konto
Disallow: /mieter/kontoerstellen
Disallow: /mieter/passwortvergessen
Disallow: /huesped/cuenta
Disallow: /huesped/crearusuario
Disallow: /huesped/olvidecontrasena
Disallow: /huurder/account
Disallow: /huurder/aanmakengebruiker
Disallow: /huurder/wachtwoordvergeten
Disallow: /locataire/compte
Disallow: /locataire/nouveaucompte
Disallow: /locataire/motdepasseoublie
Disallow: /affittuario/account
Disallow: /affittuario/creautente
Disallow: /affittuario/passworddimenticata
Disallow: /hyresgast/konto
Disallow: /hyresgast/skapakonto
Disallow: /hyresgast/glomtlosenord
Disallow: /turysta/konto
Disallow: /turysta/utworzkonto
Disallow: /turysta/zapomnialemhasla
Disallow: /vuokraaja/tili
Disallow: /vuokraaja/luouusitili
Disallow: /vuokraaja/salasanaunohtui
Sitemap: https://www.wakacje-hiszpania.pl/VideoSitemap.aspx

