User-agent: *
Disallow: /user
Disallow: /basket
Disallow: /search
Disallow: /recommend_shop
Disallow: /newsletter
Disallow: /currency
Disallow: /productsCompare
Disallow: /product_options
Disallow: /stNavigationFrontend
Disallow: /producer
Disallow: /navigation
Disallow: *.swf
Disallow: *short/price*
Disallow: *short/created_at*
Disallow: *short/name*
Disallow: /basket/
Disallow: /user/
Disallow: /lang/en
Disallow: /group/en/
Disallow: /lang/ru
Disallow: /category/ru/
