User-Agent: *
Disallow: /0/
Disallow: /0_/
Disallow: /0design/
Disallow: /europa/
Disallow: /admin/
Disallow: /akt/
Disallow: /awstats/
Disallow: /bagietkiloss/
Disallow: /default/
Disallow: /down/
Disallow: /download/
Disallow: /galla/
Disallow: /gora/
Disallow: /images/
Disallow: /index_img/
Disallow: /js/
Disallow: /kalkulator/
Disallow: /katalog-stron/
Disallow: /logo/
Disallow: /makro/
Disallow: /mapy/
Disallow: /music/
Disallow: /panoramy/
Disallow: /style/
Disallow: /swieta/
Disallow: /video/
Disallow: /system/
Disallow: /wlink/
Disallow: /zenek/
Disallow: /copyright.php
Disallow: /down.php
Disallow: /downarch.php
Disallow: /global.css
Disallow: /global3.css
Disallow: /google86415c778f9b389b.html
Disallow: /lewy.php
Disallow: /lewybieszczady3.php
Disallow: /losuj.php
Disallow: /losujup.php
Disallow: /losujup.txt
Disallow: /minigalerialewy.txt
Disallow: /pozdrowienia.php
Disallow: /pozdrowienia.txt
Disallow: /pozdrowienia2.php
Disallow: /pozdrowienia4.php
Disallow: /search.php
Disallow: /slideshow.css
Disallow: /strony.txt
Disallow: /cytat.txt
Disallow: /down.txt
Disallow: /szukaj.php
Disallow: /test.php
Disallow: /up.php
Disallow: /up2.php
Disallow: /bieszczady/intro01/
Disallow: /bieszczady/index.php
Disallow: /cytat/
Disallow: /fotografie/
Disallow: /agata/
Disallow: index2.php
Disallow: index3.php
Disallow: /cgi-bin/
Disallow: /bieszczadzka/albums/
Disallow: /bieszczadzka/bridge/
Disallow: /bieszczadzka/images/
Disallow: /bieszczadzka/include/
Disallow: /bieszczadzka/lang/
Disallow: /bieszczadzka/logs/
Disallow: /bieszczadzka/plugins/
Disallow: /bieszczadzka/sql/
Disallow: /bieszczadzka/addfav.php
Disallow: /bieszczadzka/addpic.php
Disallow: /bieszczadzka/admin.php
Disallow: /bieszczadzka/anycontent.php
Disallow: /bieszczadzka/banning.php
Disallow: /bieszczadzka/bridgemgr.php
Disallow: /bieszczadzka/calendar.php
Disallow: /bieszczadzka/catmgr.php
Disallow: /bieszczadzka/charsetmgr.php
Disallow: /bieszczadzka/config.php
Disallow: /bieszczadzka/db_ecard.php
Disallow: /bieszczadzka/db_input.php
Disallow: /bieszczadzka/delete.php
Disallow: /bieszczadzka/displayraport.php
Disallow: /bieszczadzka/editonepic.php
Disallow: /bieszczadzka/exifmgr.php
Disallow: /bieszczadzka/forgot_password.php
Disallow: /bieszczadzka/getland.php
Disallow: /bieszczadzka/groupmgr.php
Disallow: /bieszczadzka/imageprocessor.php
Disallow: /bieszczadzka/keyword_create_dict.php
Disallow: /bieszczadzka/keyword_select.php
Disallow: /bieszczadzka/keywordmgr.php
Disallow: /bieszczadzka/login.php
Disallow: /bieszczadzka/logout.php
Disallow: /bieszczadzka/mode.php
Disallow: /bieszczadzka/minibrowser.php
Disallow: /bieszczadzka/modifyalb.php
Disallow: /bieszczadzka/phpinfo.php
Disallow: /bieszczadzka/picedit.php
Disallow: /bieszczadzka/picmgr.php
Disallow: /bieszczadzka/pluginmgr.php
Disallow: /bieszczadzka/profile.php
Disallow: /bieszczadzka/ratepic.php
Disallow: /bieszczadzka/register.php
Disallow: /bieszczadzka/relocate_serwer.php
Disallow: /bieszczadzka/raport_file.php
Disallow: /bieszczadzka/rwiewcom.php
Disallow: /bieszczadzka/stat_details.php
Disallow: /bieszczadzka/update.php
Disallow: /bieszczadzka/upgrade-1.0-to1.2.php
Disallow: /bieszczadzka/usermgr.php
Disallow: /bieszczadzka/util.php
Disallow: /bieszczadzka/versioncheck.php
Disallow: /bieszczadzka/viewlog.php
Disallow: /bieszczadzka/xp_publish.php
Disallow: /bieszczadzka/zipdownload.php
Disallow: /bieszczadzka/search.php
Disallow: /lukasz/search.php
Disallow: /lukasz/albums/
Disallow: /lukasz/bridge/
Disallow: /lukasz/images/
Disallow: /lukasz/include/
Disallow: /lukasz/lang/
Disallow: /lukasz/logs/
Disallow: /lukasz/plugins/
Disallow: /lukasz/sql/
Disallow: /lukasz/addfav.php
Disallow: /lukasz/addpic.php
Disallow: /lukasz/admin.php
Disallow: /lukasz/anycontent.php
Disallow: /lukasz/banning.php
Disallow: /lukasz/bridgemgr.php
Disallow: /lukasz/calendar.php
Disallow: /lukasz/catmgr.php
Disallow: /lukasz/charsetmgr.php
Disallow: /lukasz/config.php
Disallow: /lukasz/db_ecard.php
Disallow: /lukasz/db_input.php
Disallow: /lukasz/delete.php
Disallow: /lukasz/displayraport.php
Disallow: /lukasz/editonepic.php
Disallow: /lukasz/exifmgr.php
Disallow: /lukasz/forgot_password.php
Disallow: /lukasz/getland.php
Disallow: /lukasz/groupmgr.php
Disallow: /lukasz/imageprocessor.php
Disallow: /lukasz/keyword_create_dict.php
Disallow: /lukasz/keyword_select.php
Disallow: /lukasz/keywordmgr.php
Disallow: /lukasz/login.php
Disallow: /lukasz/logout.php
Disallow: /lukasz/mode.php
Disallow: /lukasz/minibrowser.php
Disallow: /lukasz/modifyalb.php
Disallow: /lukasz/phpinfo.php
Disallow: /lukasz/picedit.php
Disallow: /lukasz/picmgr.php
Disallow: /lukasz/pluginmgr.php
Disallow: /lukasz/profile.php
Disallow: /lukasz/ratepic.php
Disallow: /lukasz/register.php
Disallow: /lukasz/relocate_serwer.php
Disallow: /lukasz/raport_file.php
Disallow: /lukasz/rwiewcom.php
Disallow: /lukasz/stat_details.php
Disallow: /lukasz/update.php
Disallow: /lukasz/upgrade-1.0-to1.2.php
Disallow: /lukasz/usermgr.php
Disallow: /lukasz/util.php
Disallow: /lukasz/versioncheck.php
Disallow: /lukasz/viewlog.php
Disallow: /lukasz/xp_publish.php
Disallow: /lukasz/zipdownload.php
Disallow: /plfotka/search.php
Disallow: /plfotka/albums/
Disallow: /plfotka/bridge/
Disallow: /plfotka/images/
Disallow: /plfotka/include/
Disallow: /plfotka/lang/
Disallow: /plfotka/logs/
Disallow: /plfotka/plugins/
Disallow: /plfotka/sql/
Disallow: /plfotka/addfav.php
Disallow: /plfotka/addpic.php
Disallow: /plfotka/admin.php
Disallow: /plfotka/anycontent.php
Disallow: /plfotka/banning.php
Disallow: /plfotka/bridgemgr.php
Disallow: /plfotka/calendar.php
Disallow: /plfotka/catmgr.php
Disallow: /plfotka/charsetmgr.php
Disallow: /plfotka/config.php
Disallow: /plfotka/db_ecard.php
Disallow: /plfotka/db_input.php
Disallow: /plfotka/delete.php
Disallow: /plfotka/displayraport.php
Disallow: /plfotka/editonepic.php
Disallow: /plfotka/exifmgr.php
Disallow: /plfotka/forgot_password.php
Disallow: /plfotka/getland.php
Disallow: /plfotka/groupmgr.php
Disallow: /plfotka/imageprocessor.php
Disallow: /plfotka/keyword_create_dict.php
Disallow: /plfotka/keyword_select.php
Disallow: /plfotka/keywordmgr.php
Disallow: /plfotka/login.php
Disallow: /plfotka/logout.php
Disallow: /plfotka/mode.php
Disallow: /plfotka/minibrowser.php
Disallow: /plfotka/modifyalb.php
Disallow: /plfotka/phpinfo.php
Disallow: /plfotka/picedit.php
Disallow: /plfotka/picmgr.php
Disallow: /plfotka/pluginmgr.php
Disallow: /plfotka/profile.php
Disallow: /plfotka/ratepic.php
Disallow: /plfotka/register.php
Disallow: /plfotka/relocate_serwer.php
Disallow: /plfotka/raport_file.php
Disallow: /plfotka/rwiewcom.php
Disallow: /plfotka/stat_details.php
Disallow: /plfotka/update.php
Disallow: /plfotka/upgrade-1.0-to1.2.php
Disallow: /plfotka/usermgr.php
Disallow: /plfotka/util.php
Disallow: /plfotka/versioncheck.php
Disallow: /plfotka/viewlog.php
Disallow: /plfotka/xp_publish.php
Disallow: /plfotka/zipdownload.php
Disallow: /pyzdra/search.php
Disallow: /pyzdra/albums/
Disallow: /pyzdra/bridge/
Disallow: /pyzdra/images/
Disallow: /pyzdra/include/
Disallow: /pyzdra/lang/
Disallow: /pyzdra/logs/
Disallow: /pyzdra/plugins/
Disallow: /pyzdra/sql/
Disallow: /pyzdra/addfav.php
Disallow: /pyzdra/addpic.php
Disallow: /pyzdra/admin.php
Disallow: /pyzdra/anycontent.php
Disallow: /pyzdra/banning.php
Disallow: /pyzdra/bridgemgr.php
Disallow: /pyzdra/calendar.php
Disallow: /pyzdra/catmgr.php
Disallow: /pyzdra/charsetmgr.php
Disallow: /pyzdra/config.php
Disallow: /pyzdra/db_ecard.php
Disallow: /pyzdra/db_input.php
Disallow: /pyzdra/delete.php
Disallow: /pyzdra/displayraport.php
Disallow: /pyzdra/editonepic.php
Disallow: /pyzdra/exifmgr.php
Disallow: /pyzdra/forgot_password.php
Disallow: /pyzdra/getland.php
Disallow: /pyzdra/groupmgr.php
Disallow: /pyzdra/imageprocessor.php
Disallow: /pyzdra/keyword_create_dict.php
Disallow: /pyzdra/keyword_select.php
Disallow: /pyzdra/keywordmgr.php
Disallow: /pyzdra/login.php
Disallow: /pyzdra/logout.php
Disallow: /pyzdra/mode.php
Disallow: /pyzdra/minibrowser.php
Disallow: /pyzdra/modifyalb.php
Disallow: /pyzdra/phpinfo.php
Disallow: /pyzdra/picedit.php
Disallow: /pyzdra/picmgr.php
Disallow: /pyzdra/pluginmgr.php
Disallow: /pyzdra/profile.php
Disallow: /pyzdra/ratepic.php
Disallow: /pyzdra/register.php
Disallow: /pyzdra/relocate_serwer.php
Disallow: /pyzdra/raport_file.php
Disallow: /pyzdra/rwiewcom.php
Disallow: /pyzdra/stat_details.php
Disallow: /pyzdra/update.php
Disallow: /pyzdra/upgrade-1.0-to1.2.php
Disallow: /pyzdra/usermgr.php
Disallow: /pyzdra/util.php
Disallow: /pyzdra/versioncheck.php
Disallow: /pyzdra/viewlog.php
Disallow: /pyzdra/xp_publish.php
Disallow: /pyzdra/zipdownload.php
Disallow: /mapa-swiata/
Disallow: /forum/ajax.php
Disallow: /forum/attachment.php
Disallow: /forum/vcalendar.php
Disallow: /forum/converse.php
Disallow: /forum/cron.php
Disallow: /forum/editpost.php
Disallow: /forum/global.php
Disallow: /forum/image.php
Disallow: /forum/inlinemod.php
Disallow: /forum/joinrequests.php
Disallow: /forum/login.php
Disallow: /forum/member.php
Disallow: /forum/memberlist.php
Disallow: /forum/misc.php
Disallow: /forum/moderator.php
Disallow: /forum/newattachment.php
Disallow: /forum/newreply.php
Disallow: /forum/newthread.php
Disallow: /forum/online.php
Disallow: /forum/picture.php
Disallow: /forum/poll.php
Disallow: /forum/postings.php
Disallow: /forum/printthread.php
Disallow: /forum/private.php
Disallow: /forum/profile.php
Disallow: /forum/register.php
Disallow: /forum/report.php
Disallow: /forum/reputation.php
Disallow: /forum/search.php
Disallow: /forum/sendmessage.php
Disallow: /forum/showgroups.php
Disallow: /forum/subscription.php
Disallow: /forum/threadrate.php
Disallow: /forum/usercp.php
Disallow: /forum/usernote.php
Disallow: /forum/visitormessage.php
Disallow: /swf/
Disallow: /pyzdra/galeria-toprated-0-5.html
Disallow: /pyzdra/galeria-toprated-0-4.html
Disallow: /pyzdra/galeria-toprated-0-3.html
Disallow: /pyzdra/galeria-toprated-0-2.html
Disallow: /pyzdra/galeria-toprated-0-11.html
Disallow: /pyzdra/galeria-toprated-0-1.html
Disallow: /pyzdra/galeria-topn-0-8.html
Disallow: /pyzdra/galeria-topn-0-10.html
Disallow: /pyzdra/galeria-topn--7-5.html
Disallow: /lukasz/fotogaleria-6.html
Disallow: /plfotka/displayimage.php?album=75&pos=65
Disallow: /plfotka/displayimage.php?album=75&pos=28
Disallow: /plfotka/displayimage.php?album=74&pos=5
Disallow: /plfotka/displayimage.php?album=71&pos=4
Disallow: /plfotka/displayimage.php?album=51&pos=13
Disallow: /plfotka/displayimage.php?album=47&pos=38
Disallow: /plfotka/displayimage.php?album=46&pos=40
Disallow: /plfotka/displayimage.php?album=46&pos=10
Disallow: /plfotka/displayimage.php?album=40&pos=67
Disallow: /plfotka/displayimage.php?album=40&pos=57
Disallow: /bieszczadzka/widoczek-topn-0-411.html
Disallow: /bieszczadzka/widoczek-topn-0-374.html
Disallow: /bieszczadzka/widoczek-lastup-5-311.html
Disallow: /bieszczadzka/widoczek-lastup-0-362.html
Disallow: /bieszczadzka/widoczek-lastup-0-335.html
Disallow: /bieszczadzka/widoczek-29-8.html
Disallow: /bieszczadzka/widoczek-28-11.html
Disallow: /pyzdra/galeria-toprated-0-0.html
Disallow: /pyzdra/galeria-topn-0-8.html
Disallow: /pyzdra/galeria-topn-0-10.html
Disallow: /dziennik/

User-Agent: *
Sitemap: http://www.widoczek.nets.pl/1sitemap.xml.gz
Sitemap: http://www.widoczek.nets.pl/2sitemap.xml.gz
Sitemap: http://www.widoczek.nets.pl/3sitemap.xml.gz
Sitemap: http://www.widoczek.nets.pl/4sitemap.xml.gz
Sitemap: http://www.widoczek.nets.pl/5sitemap.xml.gz


User-agent: Slurp
Crawl-delay: 20
