# If the Joomla site is installed within a folder such as at
# e.g. www.example.com/joomla/ the robots.txt file MUST be
# moved to the site root at e.g. www.example.com/robots.txt
# AND the joomla folder name MUST be prefixed to the disallowed
# path, e.g. the Disallow rule for the /administrator/ folder
# MUST be changed to read Disallow: /joomla/administrator/
#
# For more information about the robots.txt standard, see:
# http://www.robotstxt.org/orig.html
#
# For syntax checking, see:
# http://tool.motoricerca.info/robots-checker.phtml

User-agent: *
Disallow: /administrator/
Disallow: /bin/
Disallow: /cli/
Disallow: /components/
Disallow: /includes/
Disallow: /installation/
Disallow: /language/
Disallow: /layouts/
Disallow: /libraries/
Disallow: /logs/
Disallow: /modules/
Disallow: /plugins/
Disallow: /templates/
Disallow: /tmp/

Allow: /media/system/css/
Allow: /plugins/system/jcemediabox/js/
Allow: /modules/mod_simpl_fb/plugins/images/follow_btn/
Allow: /media/com_comment/cache/
Allow: /media/system/js/
Allow: /media/jui/js/
Allow: /components/com_comprofiler/plugin/templates/default/images/avatar/
Allow: /components/com_comprofiler/plugin/templates/default/font/
Allow: /plugins/system/jcemediabox/themes/standard/
Allow: /components/com_comprofiler/plugin/templates/default/
Allow: /templates/system/css/
Allow: /components/com_comprofiler/plugin/templates/default/
Allow: /media/juloalib/js/
Allow: /modules/mod_kunenalatest/tmpl/css/
Allow: /plugins/system/jcemediabox/css/
Allow: /media/com_finder/css/
Allow: /media/juloalib/css/
Allow: /media/com_finder/js/
Allow: /media/com_comment/templates/default/css/
Allow: /media/com_comment/images/
Allow: /templates/system/css/
Allow: /media/kunena/cache/crypsisb3/css/
Allow: /components/com_kunena/template/crypsisb3/assets/js/
Allow: /media/kunena/cache/crypsisb3/css/kunena.css
Allow: /components/com_comprofiler/js/jquery/
Allow: /components/com_comprofiler/js/
Allow: /media/kunena/ranks/
Allow: /images/comprofiler/gallery/
Allow: /modules/mod_kunenalatest/tmpl/css/kunenalatest.css
Allow: /images/
Allow: /media/com_comment/templates/default/images/
Allow: /components/com_kunena/template/crypsisb3/assets/css/
Allow: /media/plg_captcha_recaptcha/js/
Allow: /components/com_comprofiler/plugin/templates/default/images/avatar/
Allow: /components/com_comprofiler/plugin/templates/default/fontawesome.css
Allow: /media/kunena/cache/crypsisb3/css/
Allow: /images/stories/
Allow: /media/kunena/emoticons/
Allow: /media/kunena/cache/crypsisb3/css/
Allow: /media/kunena/cache/crypsisb3/css/kunena.css
Allow: /media/kunena/cache/crypsisb3/css/kunena.css
Allow: /components/com_comprofiler/plugin/templates/default/fontawesome.css?v=fcb803716a8aaeb4
Allow: /components/com_comprofiler/plugin/templates/default/template.css?v=fcb803716a8aaeb4
Allow: /media/juloalib/js/jquery.min.js
Allow: /media/juloalib/js/fullnoconflict.js
Allow: /images/stories/dodaj-ogloszenie-bezplatne-norwegia.jpg
Allow: /media/com_dpcalendar/images/site/
Allow: /plugins/content/itpsocialbuttons/images/aquasmall/
Allow: /media/com_dpcalendar/images/site/
Allow: /plugins/content/itpsocialbuttons/images/aquasmall/
Allow: /modules/mod_dpcalendar_upcoming/tmpl/images/
Allow: /media/jui/img/
Allow: /media/jui/fonts/
Allow: /components/com_dpcalendar/libraries/jquery/themes/bootstrap/images/
Allow: /media/com_comment/ubb/
Allow: /media/com_dpcalendar/images/site/
Allow: /plugins/content/itpsocialbuttons/images/aquasmall/
Allow: /media/plg_jchoptimize/assets/gz/1/0/
Allow: /media/plg_jchoptimize/assets/gz/1/1/
Allow: /components/com_contushdvideoshare/images/
Allow: /media/plg_jchoptimize/assets/gz/1/0/
Allow: /templates/shaper_helix3/css/
Allow: /templates/shaper_helix3/js/
Allow: /templates/shaper_helix3/css/presets/
Allow: /components/com_contushdvideoshare/js/
Allow: /components/com_djmediatools/layouts/skitterSlideshow/js/
Allow: /media/djextensions/picturefill/
Allow: /components/com_djmediatools/layouts/slideshow/js/
Allow: /components/com_djmediatools/layouts/mslider/js/
Allow: /media/djmediatools/cache/images/users/1996/
Allow: /components/com_djmediatools/layouts/skitterSlideshow/css/
Allow: /components/com_djclassifieds/themes/clean/css/
Allow: /media/djmediatools/css/
Allow: /components/com_contushdvideoshare/css/
Allow: /modules/mod_dpcalendar_upcoming/tmpl/
Allow: /media/djextensions/jquery-easing/
Allow: /components/com_djmediatools/assets/js/
Allow: /components/com_djclassifieds/assets/images/
Allow: /components/com_djmediatools/assets/images/blank.gif
Allow: /components/com_djmediatools/layouts/slideshow/images/
Allow: /components/com_djclassifieds/themes/clean/images/
Allow: /components/com_djmediatools/layouts/skitterSlideshow/images/
Allow: /media/com_dpcalendar/css/dpcalendar/
Allow: /media/com_dpcalendar/js/dpcalendar/
Allow: /templates/shaper_helix3/fonts/
Allow: /components/com_djmediatools/layouts/mslider/images/
Allow: /media/com_dpcalendar/css/fullcalendar/
Allow: /media/com_dpcalendar/js/fullcalendar/
Allow: /media/kunena/cache/crypsis/css/
Allow: /media/jui/css/
Allow: /components/com_kunena/template/crypsis/assets/css/
Allow: /media/djmediatools/cache/images/users/1996/_320w/
Allow: /components/com_djclassifieds/images/item/
Allow: /components/com_djclassifieds/images/category/
Allow: /components/com_djclassifieds/themes/clean/images/
Allow: /components/com_djclassifieds/themes/clean/images/
Allow: /components/com_comprofiler/plugin/templates/default/font/
Allow: /media/com_dpcalendar/css/jquery/themes/bootstrap/
Allow: /media/com_dpcalendar/js/jquery/ui/
Allow: /media/com_dpcalendar/css/jquery/ext/
Allow: /media/com_dpcalendar/js/jquery/ext/
Allow: /components/com_kunena/template/crypsis/assets/js/
Allow: /components/com_djmediatools/layouts/galleryGrid/images/
Allow: /components/com_djmediatools/layouts/galleryGrid/js/
Allow: /components/com_djclassifieds/assets/picbox/css/
Allow: /modules/mod_onscreen_facebook_likebox_popup/assets/js/
Allow: /modules/mod_onscreen_facebook_likebox_popup/assets/css/
Allow: /modules/mod_djmegamenu/assets/css/
Allow: /media/jui/js/
Allow: /components/com_djclassifieds/themes/clean/css/
Allow: /media/system/js/
Allow: /components/com_djclassifieds/images/category/
Allow: /media/com_dpcalendar/js/md5/
Allow: /media/com_dpcalendar/js/tippy/
Allow: /media/com_dpcalendar/js/moment/
Allow: /media/com_dpcalendar/js/domurl/
Allow: /media/com_dpcalendar/js/md5/
Allow: /media/com_dpcalendar/js/tingle/
Allow: /components/com_djclassifieds/assets/picbox/js/
Allow: /media/djmediatools/cache/images/users/2074/
Allow: /media/kunena/topic_icons/default/system/
Allow: /media/com_dpcalendar/js/popper/
Allow: /media/com_dpcalendar/css/tippy/
Allow: /media/com_dpcalendar/css/tingle/
Allow: /media/com_dpcalendar/js/domurl/
Allow: /components/com_djclassifieds/assets/picbox/js/
Allow: /modules/mod_weather_gk4/style/style.css
Allow: /modules/mod_a4w_infociacho/tmpl/css/style5.css
Allow: /media/sourcecoast/js/jq-bootstrap-1.8.3.js
Allow: /media/sourcecoast/css/sc_bootstrap.css
Allow: /media/sourcecoast/themes/sclogin/default.css
Allow: /media/plg_system_eprivacy/js/eprivacy.class.min.js?368ce9e4b30aa89497c79de203d3eb1f
Allow: /modules/mod_weather_gk4/icons/meteocons_dark/32/partly_cloudy.png
Allow: /modules/mod_weather_gk4/icons/meteocons_dark/32/chance_of_storm.png
Allow: /media/plg_jchoptimize/assets/gz/
Allow: /modules/mod_weather_gk4/icons/meteocons_dark/32/mostly_cloudy.png
Allow: /media/plg_system_eprivacy/js/eprivacy.class.min.js
Allow: /media/sourcecoast/css/common.css
Allow: /media/plg_system_eprivacy/js/base64.min.js?51026168a6a36d90db612af69cd73b65
Allow: /components/com_djclassifieds/themes/clean/css/style.css
Allow: /templates/shaper_helix3/css/bootstrap.min.css
Allow: /templates/shaper_helix3/css/font-awesome.min.css
Allow: /templates/shaper_helix3/css/presets/preset2.css
Allow: /templates/shaper_helix3/css/custom.css
Allow: /templates/shaper_helix3/js/bootstrap.min.js
Allow: /images/stories/radio5Elk_2.png
Allow: /images/planetcinema-elk.jpg
Allow: /templates/shaper_helix3/js/frontend-edit.js
Allow: /templates/shaper_helix3/css/template.css
Allow: /templates/shaper_helix3/css/frontend-edit.css
Allow: /modules/mod_weather_gk4/icons/meteocons_dark/32/
Allow: /components/com_contushdvideoshare/css/
Allow: /components/com_djmediatools/layouts/skitterSlideshow/js/
Allow: /media/djmediatools/cache/images/users/1996/
Allow: /templates/shaper_helix3/fonts/
