User-agent: *
Crawl-delay: 4
Disallow: /css/
Disallow: /js/
Disallow: /fonts/
Disallow: /plugins/
Disallow: /vendor/
Disallow: /video/
Disallow: /forum/sendmessage
Disallow: /forum/search
Disallow: /forum/printthread
Disallow: /*.log$
Disallow: /*.cmd$
Disallow: /*.txt$
Disallow: /*.html$
Allow: /js/*.js$
Allow: /js/*.js?
Allow: /css/*.css$
Allow: /css/*.css?
Allow: /fonts/*.eot$
Allow: /fonts/*.eot?
Allow: /fonts/*.svg$
Allow: /fonts/*.svg?
Allow: /fonts/*.ttf$
Allow: /fonts/*.ttf?
Allow: /fonts/*.woff$
Allow: /fonts/*.woff?
Allow: /fonts/*.woff2$
Allow: /fonts/*.woff2?

Sitemap: https://www.pokerstarsschool.pl/sitemap
