User-agent: *
Disallow: /dall.php
Disallow: /darea.php
Disallow: /data.php
Disallow: /dcontinent.php
Disallow: /dcontnames.php
Disallow: /dcountry.php
Disallow: /dstate.php
Disallow: /darea.php
Disallow: /droute.php
Disallow: /downloadfile.php
Disallow: /iaroute.php
Disallow: /iauth.php
Disallow: /igadvertisers_appv3.php
Disallow: /igroutes.php
Disallow: /igroutes_appv3.php
Disallow: /igrt.php
Disallow: /igroutes_appv3.php
Disallow: /iguser.php
Disallow: /cache/
