User-agent: *
Disallow: /?
Disallow: /content/view/
Disallow: /c/content/view/
Disallow: /content/search
Disallow: /c/content/search
Disallow: /content/download/
Disallow: /user/login
Disallow: /c/user/login
Disallow: /user/forgotpassword
Disallow: /c/user/forgotpassword
Disallow: /search/
Disallow: /switchlanguage/
Disallow: /layout/
Disallow: /Redirect/
Disallow: /*%7B%7B0%7D%7D
Disallow: /*/(offset)/0
Disallow: /*cid=
Disallow: /*_openstat=
Disallow: /*gclid=
Disallow: /*utm_
Disallow: /*utmzi
Disallow: /media/
Host: www.fiskars.pl
Sitemap: http://www.fiskars.pl/sitemap.xml
