User-agent: *
Disallow: /wp-admin
Disallow: /page/2
Disallow: /page/3
Disallow: /page/4
Disallow: /page/5
Disallow: /page/6
Disallow: /page/7
Disallow: /page/8
Disallow: /page/9
Disallow: /page/10
Disallow: /page/11
Disallow: /page/12
Disallow: /page/13
Disallow: /page/14
Disallow: /page/15
Disallow: /page/16
Disallow: /page/17
Disallow: /page/18
Disallow: /page/19
Disallow: /2
Disallow: /3
Disallow: /4
Disallow: /5
Disallow: /6
Disallow: /7
Disallow: /8
Disallow: /9
Disallow: /10
Disallow: /11
Disallow: /12
Disallow: /13
Disallow: /14
Disallow: /15
Disallow: /16
Disallow: /17
Disallow: /18
Disallow: /19
Sitemap: https://agencjanasienna.pl/sitemap.xml

