# robots.txt automaticaly generated by PrestaShop e-commerce open-source solution
# http://www.prestashop.com - http://www.prestashop.com/forums
# This file is to prevent the crawling and indexing of certain parts
# of your site by web crawlers and spiders run by sites like Yahoo!
# and Google. By telling these "robots" where not to go on your site,
# you save bandwidth and server resources.
# For more information about the robots.txt standard, see:
# http://www.robotstxt.org/wc/robots.html
# GoogleBot specific
User-agent: Googlebot
Disallow: /*orderby=
Disallow: /*orderway=
Disallow: /*tag=
Disallow: /*id_currency=
Disallow: /*search_query=
Disallow: /*id_lang=
Disallow: /*back=
Disallow: /*utm_source=
Disallow: /*utm_medium=
Disallow: /*utm_campaign=
Disallow: /*n=
# All bots
User-agent: *
# Directories
Disallow: /*classes/
Disallow: /*config/
Disallow: /*download/
Disallow: /*mails/
Disallow: /*modules/
Disallow: /*translations/
Disallow: /*tools/
# Files
Disallow: /*addresses.php
Disallow: /*address.php
Disallow: /*authentication.php
Disallow: /*cart.php
Disallow: /*discount.php
Disallow: /*footer.php
Disallow: /*get-file.php
Disallow: /*header.php
Disallow: /*history.php
Disallow: /*identity.php
Disallow: /*images.inc.php
Disallow: /*init.php
Disallow: /*my-account.php
Disallow: /*order.php
Disallow: /*order-opc.php
Disallow: /*order-slip.php
Disallow: /*order-detail.php
Disallow: /*order-follow.php
Disallow: /*order-return.php
Disallow: /*order-confirmation.php
Disallow: /*pagination.php
Disallow: /*password.php
Disallow: /*pdf-invoice.php
Disallow: /*pdf-order-return.php
Disallow: /*pdf-order-slip.php
Disallow: /*product-sort.php
Disallow: /*search.php
Disallow: /*statistics.php
Disallow: /*attachment.php
Disallow: /*guest-tracking.php
Disallow: /*en/forgot-your-password
Disallow: /*en/address
Disallow: /*en/addresses
Disallow: /*en/authentication
Disallow: /*en/cart
Disallow: /*en/discount
Disallow: /*en/order-history
Disallow: /*en/identity
Disallow: /*en/my-account
Disallow: /*en/order-follow
Disallow: /*en/order-slip
Disallow: /*en/order
Disallow: /*en/search
Disallow: /*en/quick-order
Disallow: /*en/guest-tracking
Disallow: /*fr/mot-de-passe-oublie
Disallow: /*fr/adresse
Disallow: /*fr/adresses
Disallow: /*fr/authentification
Disallow: /*fr/panier
Disallow: /*fr/bons-de-reduction
Disallow: /*fr/historique-des-commandes
Disallow: /*fr/identite
Disallow: /*fr/mon-compte
Disallow: /*fr/details-de-la-commande
Disallow: /*fr/avoirs
Disallow: /*fr/commande
Disallow: /*fr/recherche
Disallow: /*fr/quick-order
Disallow: /*fr/guest-tracking
Disallow: /*es/olvidaste-tu-contrasena
Disallow: /*es/direccion
Disallow: /*es/direcciones
Disallow: /*es/autenticacion
Disallow: /*es/carro-de-la-compra
Disallow: /*es/descuento
Disallow: /*es/historial-de-pedidos
Disallow: /*es/identidad
Disallow: /*es/mi-cuenta
Disallow: /*es/devolucion-de-productos
Disallow: /*es/vales
Disallow: /*es/carrito
Disallow: /*es/buscar
Disallow: /*es/quick-order
Disallow: /*es/guest-tracking
Disallow: /*pl/zapomniales-hasla
Disallow: /*pl/quick-order
Disallow: /*pl/guest-tracking
# Sitemap


