User-agent: *
Disallow: /admin/
Disallow: /admin2/
Disallow: /download/
Disallow: /includes/
Disallow: /temp/
Disallow: /cennik/
Disallow: /tmp/
Disallow: /images/
Disallow: /img/
Disallow: /install/
Disallow: /account.php
Disallow: /sklep/account.php
Disallow: /advanced_search.php
Disallow: /sklep/advanced_search.php
Disallow: /checkout_shipping.php
Disallow: /sklep/checkout_shipping.php
Disallow: /create_account.php
Disallow: /sklep/create_account.php
Disallow: /login.php
Disallow: /sklep/login/php
Disallow: /password_forgotten.php
Disallow: /sklep/password_forgotten.php
Disallow: /popup_image.php
Disallow: /sklep/popup_image.php
Disallow: /shopping_cart.php
Disallow: /sklep/shipping_cart.php
Disallow: /patch-1-02-b.php
Disallow: /patch-1-02-b.php
Disallow: /product_reviews_write.php
Disallow: /sklep/product_reviews_write.php
Disallow: /osp/
Disallow: /baza/
Disallow: /dane/
Disallow: /protect/
Disallow: /contact_as.php
Disallow: /sklep/contact_as.php
Disallow: /szablony/
Disallow: /phpsysinfo/
Disallow: /nowa/
Disallow: /istat/
Disallow: /sklep/istat/
Disallow: /istats5/
Disallow: /sklep2
Disallow: /sklep2/
Disallow: /sklep/includes
Disallow: /sklep/includes/
Disallow: /sklep1
Disallow: /sklep1/
Disallow: /sklep_rob
Disallow: /sklep_rob/
Disallow: /*buy_now
Disallow: /*add_product
Disallow: /shopping_cart.php
Disallow: /sklep/shopping_cart.php
Disallow: /*?osCsid
Disallow: /sklep/elektro
Disallow: /elektro/
Disallow: /sklep/product_reviews.php
Disallow: /product_reviews.php
Disallow: /sklep/pokaz_plik.php
Disallow: /pokaz_plik.php

# Disallow: /private

