User-agent: *
Disallow: /admin
Disallow: /admin/
Disallow: /css/
Disallow: /img/
Disallow: /xhr/
Disallow: /log/
Disallow: /files/
Disallow: /artpcard
Disallow: /artprintable
Disallow: /artpdf
Disallow: /artgrppdf
Disallow: /barcode
Disallow: /doc
Disallow: /error
Disallow: /random
Disallow: /hqimg
Disallow: /login
Disallow: /logout
Disallow: /customer
Disallow: /customer/
Disallow: /basket
Disallow: /order
Disallow: /nlunsubscribe
Disallow: /favicon.ico
Disallow: /promo_robots.txt
Disallow: /remnantsgrp
Disallow: /remnantsimg
Disallow: /cgi-bin/home.pl
Disallow: /media
Disallow: /tellafriend
Disallow: /vkfmedia
Disallow: /pl

