User-agent: *
Disallow: /gfx/
Disallow: /pdf/
Allow: /*.pdf$
Allow: /*.doc$
Allow: /*.xls$
Allow: /*.rtf$
Allow: /*.js$
Allow: /*.css$
Allow: /*.jpg$
Allow: /*.png$
Allow: /*.gif$
Disallow: /*,filtry.html$
User-agent: Fasterfox
Disallow: /
