User-agent: PowerMapper
Disallow:
User-Agent: *
Disallow: mitnykredit.dk
Disallow: /
Disallow: /*printerfriendly=true
Disallow: /*csref
Disallow: /*intcsref
Disallow: /CampaignFeed/feed.servlet
Disallow: /getOmnivalues.servlet
Disallow: /getProduct.servlet
Disallow: /kursoversigt/KursOvervaagningAction.do
Disallow: /*beskyttede_dokumenter/
Disallow: /CampaignFeed/
Disallow: /svarkort/
Disallow: /ressourcer/
Disallow: /*.txt
Disallow: /fratraedelse
Disallow: /maa-jeg-koebe-min-mobil-ved-fratraedelse
Disallow: /flexvalg-medarejderbredbaand
Disallow: /flexvalg-mobiltelefon
Disallow: /flexvalg-togkortbrobizz
Disallow: /kunden-over-alt
Disallow: /foer-du-starter
Disallow: /overenskomst-og-husaftale
Disallow: /generelle-retningslinjer
Disallow: /finansielle-retningslinjer
Disallow: /faelles-investering
Disallow: /det-bliver-du-en-del-af
Disallow: /nykredits-historie
Disallow: /idegrundlag
Disallow: /strategi
Disallow: /vores-organisation
Disallow: /slet-test
Disallow: /om-os/karriere/din-karriere/ny-i-nykredit
Disallow: /din-virksomhed/bliv-kunde/produkter-til-din-virksomhed/netbank-til-erhverv
Disallow: /om-os/karriere/din-karriere/ny-i-nykredit
Disallow: /tak-hjaelpen
Disallow: /thank-you-your-time
Disallow: /staticcontent/files/retningslinjer_personlige_transaktioner_2.pdf
Disallow: /hjklasdf
Disallow: /erhverv/info/Kundeservice/selvbetjening-faq.xml?infocontentonly=true&disableredirect=true
Disallow: /erhverv/info/bank/Netbankforsikring-for-mindre-erhvervsvirksomheder.xml?infocontentonly=true&disableredirect=true
Disallow: https://www.mitnykredit.dk/leasing
Sitemap: https://www.nykredit.dk/sitemap.xml
