User-agent: TwengaBot
Disallow: /

User-agent: PricecloudBot
Disallow: /

User-agent: *
Disallow: /*?forceFilter*
Disallow: /*?forceDesktop*
Disallow: /*?forceMobile*
Disallow: /*?forceOff*
Disallow: /*?transses*
Disallow: /*category=*
Disallow: /*category=*
Disallow: /*color=*
Disallow: /*fraktland=*
Disallow: /*group=*
Disallow: /*id=*
Disallow: /*keepfilter=*
Disallow: /*lenght=*
Disallow: /*price=*
Disallow: /*sale=*
Disallow: /*setCurrency=*
Disallow: /*setDelivery=*
Disallow: /*shape=*
Disallow: /*similar=*
Disallow: /*siteversion=*
Disallow: /*soldout=*
Disallow: /*subcategory=*
Disallow: /*transses=*
Disallow: /*units=*
Disallow: /*width=*
Disallow: /*nocache=*
Disallow: /*nosticky=*
Disallow: /*noDeferredCss=*
Disallow: /banner.php
Disallow: /cssOld*
Disallow: /flags_allOld*
Disallow: /flagsOld*
Disallow: /galleryOld*
Disallow: /imagesOld*
Disallow: /imgOld*
Disallow: /picsOld*
Disallow: /priceimagesOld*
Disallow: /1*
Disallow: /2*
Disallow: /3*
Disallow: /4*
Disallow: /5*
Disallow: /6*
Disallow: /7*
Disallow: /8*
Disallow: /9*
Disallow: /0*

