User-agent: YandexBot
Disallow: /
User-agent: YandexMobileBot
Disallow: /
User-agent: Yandex
Disallow: /
User-agent: YandexAntivirus
Disallow: /
User-agent: DomainCrawler
Disallow: /
User-agent: AhrefsBot
Disallow: /
User-agent: AhrefsBot/5.2
Disallow: /
User-agent: DotBot
Disallow: /
User-agent: DotBot/1.1
Disallow: /
User-agent: MJ12bot
Disallow: /
User-agent: MJ12bot/v1.4.8
Disallow: /
User-agent: MauiBot
Disallow: /
User-agent: Exabot
Disallow: /
User-agent: Exabot/3.0
Disallow: /
User-agent: *
Disallow: /yii-core/
Disallow: /admin/
Disallow: /fckeditor/
Disallow: /avde/
Disallow: /new/
