User-agent: Googlebot
Noindex: /*/true/$
Noindex: /*/true$
Noindex: /campaign/overlay/
Noindex: /border-banner/
Noindex: /searchresult/0*/
Noindex: /searchresult/1*/
Noindex: /searchresult/2*/
Noindex: /searchresult/3*/
Noindex: /searchresult/4*/
Noindex: /searchresult/5*/
Noindex: /searchresult/6*/
Noindex: /searchresult/7*/
Noindex: /searchresult/8*/
Noindex: /searchresult/9*/
Noindex: /searchresult/*/*/
Noindex: /searchresult/*/?*
Noindex: /searchresult/*%20*/
Noindex: /searchresult/*%C*/
Noindex: /*?page=*/
Noindex: /lokalizacje/sklep-*/*/
Noindex: /shop-the-look/
Allow: /lokalizacje/sklep-*/$
Allow: /searchresult/2-*/$
Allow: /searchresult/3-*/$
Allow: /searchresult/7-*/$
Allow: /searchresult/2er-*/$
Allow: /searchresult/3er-*/$
Allow: /searchresult/kurtki-bomber/*/$
Allow: /fileadmin/
Allow: /*?store=
Allow: /*/?par=*&*
Noindex: /searchresult/2-*/*.*/
Noindex: /searchresult/3-*/*.*/
Noindex: /searchresult/7-*/*.*/
Noindex: /searchresult/2er-*/*.*/
Noindex: /searchresult/3er-*/*.*/
Noindex: /searchresult/kurtki-bomber/*.*/
Noindex: /searchresult/2-*/*/*/
Noindex: /searchresult/3-*/*/*/
Noindex: /searchresult/7-*/*/*/
Noindex: /searchresult/2er-*/*/*/
Noindex: /searchresult/3er-*/*/*/
Noindex: /searchresult/kurtki-bomber/*/*/
Noindex: /shop-the-look/*/?size
Noindex: /*/pricegroup-*/
Noindex: /*/brand-*/?sortby
Noindex: /*/size-*/?sortby
Noindex: /*/colorgroup-*/?sortby
Noindex: /*/brand-*/*-*/
Noindex: /*/size-*/*-*/
Noindex: /*/colorgroup-*/*-*/
Noindex: /?mappedSizes=true
Noindex: /*/?par=*&page
Noindex: /*/?par=*&*&*
Noindex: /_Incapsula_Resource
Noindex: */undefined*
Noindex: /composite_style/
Noindex: /composite_script/
Noindex: /*/*/*/*/*/
Noindex: /*?*.*
Noindex: /*.*
Noindex: /*?*&*
Noindex: /availability/
Noindex: /*pricegroup-*
Noindex: /*store-*
Noindex: /*errors=*
Noindex: /myaccount/*/?url=
Noindex: /recent-products/
Noindex: /suggest/*
Noindex: /*/?cms_paths=
Noindex: /product/*
Noindex: /*oversize-*/*.*
Noindex: /*oversize*/*-*/
Noindex: /*cr=*
Noindex: /*sc=*
Noindex: /*sl=*
Noindex: /*uq=*
Noindex: /*_q=*
Noindex: /*q=*
Noindex: /*af=.*
Noindex: /*mappedSizes=*
Allow: /assets/
Allow: /*oversize*
Allow: /*.xml
Allow: /*.rss
Allow: /*.png
Allow: /*.css
Allow: /*.js
Allow: /*.jpg
Allow: /*.jpeg
Allow: /*.gif
Allow: /*sea_shopping*
Allow: /*?template=productpage&box*
Allow: /media/
Allow: /*wt_mc=*
Allow: /*.svg
Allow: /*.ttf
Allow: /*jsessionid
Allow: /kobiety/sukienki/sukienki-wieczorowe/colorgroup-black/dresslength-maxi/$
Allow: /kobiety/sukienki/colorgroup-black/dresslength-maxi/$
Allow: /kobiety/sukienki/colorgroup-black/dresslength-mini/$
Allow: /kobiety/sukienki/colorgroup-black/sleevelength-langarm/$
Allow: /kobiety/sukienki/colorgroup-red/dresslength-mini/$
Allow: /wyprzedaz/dzieci/dzieci-chlopcy/odziez/kurtki/$
Allow: /wyprzedaz/dzieci/dzieci-chlopcy/odziez/jeansy/$
Allow: /searchresult/kurtki-softshell/brand-wellensteyn/$

User-agent: AdsBot-Google
Allow: /

User-agent: Googlebot-Image
Allow: /

User-agent: *
Disallow: /campaign/overlay/
Disallow: /border-banner/
Disallow: /searchresult/0*/
Disallow: /searchresult/1*/
Disallow: /searchresult/2*/
Disallow: /searchresult/3*/
Disallow: /searchresult/4*/
Disallow: /searchresult/5*/
Disallow: /searchresult/6*/
Disallow: /searchresult/7*/
Disallow: /searchresult/8*/
Disallow: /searchresult/9*/
Disallow: /searchresult/*/*/
Disallow: /searchresult/*/?*
Disallow: /searchresult/*%20*/
Disallow: /searchresult/*%C*/
Disallow: /*?page=*/
Disallow: /lokalizacje/sklep-*/*/
Disallow: /shop-the-look/
Allow: /lokalizacje/sklep-*/$
Allow: /searchresult/2-*/$
Allow: /searchresult/3-*/$
Allow: /searchresult/7-*/$
Allow: /searchresult/2er-*/$
Allow: /searchresult/3er-*/$
Allow: /searchresult/kurtki-bomber/*/$
Allow: /fileadmin/
Allow: /*?store=
Allow: /*/?par=*&*
Disallow: /searchresult/2-*/*.*/
Disallow: /searchresult/3-*/*.*/
Disallow: /searchresult/7-*/*.*/
Disallow: /searchresult/2er-*/*.*/
Disallow: /searchresult/3er-*/*.*/
Disallow: /searchresult/kurtki-bomber/*.*/
Disallow: /searchresult/2-*/*/*/
Disallow: /searchresult/3-*/*/*/
Disallow: /searchresult/7-*/*/*/
Disallow: /searchresult/2er-*/*/*/
Disallow: /searchresult/3er-*/*/*/
Disallow: /searchresult/kurtki-bomber/*/*/
Disallow: /shop-the-look/*/?size
Disallow: /*/pricegroup-*/
Disallow: /*/brand-*/?sortby
Disallow: /*/size-*/?sortby
Disallow: /*/colorgroup-*/?sortby
Disallow: /*/brand-*/*-*/
Disallow: /*/size-*/*-*/
Disallow: /*/colorgroup-*/*-*/
Disallow: /?mappedSizes=true
Disallow: /*/?par=*&page
Disallow: /*/?par=*&*&*
Disallow: /searchresult/kurtki-bomber/*/*/
Disallow: /_Incapsula_Resource
Disallow: */undefined*
Disallow: /composite_style/
Disallow: /composite_script/
Disallow: /*/*/*/*/*/
Disallow: /*?*.*
Disallow: /*.*
Disallow: /*?*&*
Disallow: /availability/
Disallow: /*pricegroup-*
Disallow: /*store-*
Disallow: /*errors=*
Disallow: /myaccount/*/?url=
Disallow: /recent-products/
Disallow: /suggest/*
Disallow: /*/?cms_paths=
Disallow: /product/*
Disallow: /*oversize-*/*.*
Disallow: /*oversize*/*-*/
Disallow: /search/
Disallow: /*af=.*
Disallow: /*mappedSizes=*
Allow: /assets/
Allow: /*oversize*
Allow: /*.xml
Allow: /*.rss
Allow: /*.png
Allow: /*.css
Allow: /*.js
Allow: /*.jpg
Allow: /*.jpeg
Allow: /*.gif
Allow: /*sea_shopping*
Allow: /*?template=productpage&box*
Allow: /media/
Allow: /*wt_mc=*
Allow: /*.svg
Allow: /*.ttf
Allow: /*jsessionid
Allow: /kobiety/sukienki/sukienki-wieczorowe/colorgroup-black/dresslength-maxi/$
Allow: /kobiety/sukienki/colorgroup-black/dresslength-maxi/$
Allow: /kobiety/sukienki/colorgroup-black/dresslength-mini/$
Allow: /kobiety/sukienki/colorgroup-black/sleevelength-langarm/$
Allow: /kobiety/sukienki/colorgroup-red/dresslength-mini/$
Allow: /wyprzedaz/dzieci/dzieci-chlopcy/odziez/kurtki/$
Allow: /wyprzedaz/dzieci/dzieci-chlopcy/odziez/jeansy/$
Allow: /searchresult/kurtki-softshell/brand-wellensteyn/$

Sitemap: https://www.peek-cloppenburg.pl/polen-sitemap.xml

