# Produktive robots.txt
User-agent: gsa-crawler
User-agent: SemrushBot
User-agent: SemrushBot-SA
Disallow: /

User-agent: *
Disallow: /*;
Disallow: /cgi-bin/
Disallow: /eshop/pdfDownload
Disallow: /eshop/b2b/closer_history.jsp
Disallow: /eshop/b2b/fs_start_inner.jsp
Disallow: /eshop/b2b/fs_startworkarea.jsp
Disallow: /eshop/b2b/organizer-nav-doc-search.jsp
Disallow: /eshop/b2b/updateorganizercont.do
Disallow: /eshop/b2b/user_settings_header.jsp
Disallow: /eshop/b2b/user_settings_info.jsp
Disallow: /eshop/ecombase/documentstatus/orderstatusdetail.jsp
Disallow: /eshop/pilz/createorderfromfile.do
Disallow: /eshop/b2b/createdocument/
Disallow: /eshop/pilz/deliverynotestatusdetail.jsp
#Disallow: /eshop/catalog/query/
#Disallow: /eshop/catalog/updateItems/
Disallow: /eshop/feedbackform
Disallow: /eshop/imperia-service/contacts/external/DE
Disallow: /eshop/imperia-service/shopnavigation/de/DE/desktop
Disallow: /eshop/imperia-service/user-data-head/zh/CN/mobile
Disallow: /eshop/openbasket.csv
Disallow: /eshop/pilz/displaybasket/
#Disallow: /eshop/pilz/requestpassword/
Disallow: /eshop/pilz/performrequestpassword/
Disallow: /eshop/pilz/gotoLeaflet/
#Disallow: /eshop/pilz/register/
#Disallow: /eshop/pilz/performregister/
Disallow: /eshop/pilz/showDataChange/
Disallow: /eshop/catalog/catalogEntry/
Disallow: /eshop/order.csv
Disallow: /eshop/pilz/confirmation.do
#Disallow: /eshop/pilz/eshoplogin/
Disallow: /eshop/pilz/eshoplogin.do
Disallow: /eshop/pilz/file.xls
Disallow: /eshop/pilz/login/switchlanguage/
#Disallow: /eshop/pilz/performchangelogin/
Disallow: /eshop/pilz/register.do
Disallow: /eshop/pilz/updateRightNav.do
Disallow: /eshop/pilz/z_error.jsp
Disallow: /eshop/priceatp
Disallow: /eshop/reminder_list.csv
Disallow: /eshop/servlet/addtocompare
Disallow: /eshop/pilz/compareItems/
Disallow: /eshop/servlet/removefromcompare
Disallow: /*/advSearchForward/
#Disallow: /*/support/downloads$
Disallow: /*/services/trainings/seminars/registration-form?

User-agent: *
Sitemap: https://www.pilz.com/de-DE/sitemap.xml
Sitemap: https://www.pilz.com/de-AT/sitemap.xml
Sitemap: https://www.pilz.com/de-CH/sitemap.xml
Sitemap: https://www.pilz.com/en-INT/sitemap.xml
Sitemap: https://www.pilz.com/en-GB/sitemap.xml
Sitemap: https://www.pilz.com/en-US/sitemap.xml
Sitemap: https://www.pilz.com/en-AU/sitemap.xml
Sitemap: https://www.pilz.com/en-IE/sitemap.xml
Sitemap: https://www.pilz.com/en-NZ/sitemap.xml
Sitemap: https://www.pilz.com/en-IN/sitemap.xml
Sitemap: https://www.pilz.com/en-CA/sitemap.xml
Sitemap: https://www.pilz.com/fr-FR/sitemap.xml
Sitemap: https://www.pilz.com/fr-CH/sitemap.xml
Sitemap: https://www.pilz.com/fr-BE/sitemap.xml
Sitemap: https://www.pilz.com/fr-CA/sitemap.xml
Sitemap: https://www.pilz.com/es-ES/sitemap.xml
Sitemap: https://www.pilz.com/es-MX/sitemap.xml
Sitemap: https://www.pilz.com/nl-NL/sitemap.xml
Sitemap: https://www.pilz.com/nl-BE/sitemap.xml
Sitemap: https://www.pilz.com/pt-PT/sitemap.xml
Sitemap: https://www.pilz.com/pt-BR/sitemap.xml
Sitemap: https://www.pilz.com/zh-CN/sitemap.xml
Sitemap: https://www.pilz.com/en-CZ/sitemap.xml
Sitemap: https://www.pilz.com/da-DK/sitemap.xml
Sitemap: https://www.pilz.com/fi-FI/sitemap.xml
Sitemap: https://www.pilz.com/it-IT/sitemap.xml
Sitemap: https://www.pilz.com/ja-JP/sitemap.xml
Sitemap: https://www.pilz.com/ko-KR/sitemap.xml
Sitemap: https://www.pilz.com/pl-PL/sitemap.xml
Sitemap: https://www.pilz.com/ru-RU/sitemap.xml
Sitemap: https://www.pilz.com/sv-SE/sitemap.xml
Sitemap: https://www.pilz.com/tr-TR/sitemap.xml
Sitemap: https://www.pilz.com/tw-TW/sitemap.xml
Sitemap: https://www.pilz.com/en-SG/sitemap.xml

Sitemap: https://www.pilz.com/de-DE/sitemap-shop-level-3.xml
Sitemap: https://www.pilz.com/de-AT/sitemap-shop-level-3.xml
Sitemap: https://www.pilz.com/de-CH/sitemap-shop-level-3.xml
Sitemap: https://www.pilz.com/en-INT/sitemap-shop-level-3.xml
Sitemap: https://www.pilz.com/en-GB/sitemap-shop-level-3.xml
Sitemap: https://www.pilz.com/en-US/sitemap-shop-level-3.xml
Sitemap: https://www.pilz.com/en-AU/sitemap-shop-level-3.xml
Sitemap: https://www.pilz.com/en-IE/sitemap-shop-level-3.xml
Sitemap: https://www.pilz.com/en-NZ/sitemap-shop-level-3.xml
Sitemap: https://www.pilz.com/en-IN/sitemap-shop-level-3.xml
Sitemap: https://www.pilz.com/en-CA/sitemap-shop-level-3.xml
Sitemap: https://www.pilz.com/fr-FR/sitemap-shop-level-3.xml
Sitemap: https://www.pilz.com/fr-CH/sitemap-shop-level-3.xml
Sitemap: https://www.pilz.com/fr-BE/sitemap-shop-level-3.xml
Sitemap: https://www.pilz.com/fr-CA/sitemap-shop-level-3.xml
Sitemap: https://www.pilz.com/es-ES/sitemap-shop-level-3.xml
Sitemap: https://www.pilz.com/es-MX/sitemap-shop-level-3.xml
Sitemap: https://www.pilz.com/nl-NL/sitemap-shop-level-3.xml
Sitemap: https://www.pilz.com/nl-BE/sitemap-shop-level-3.xml
Sitemap: https://www.pilz.com/pt-PT/sitemap-shop-level-3.xml
Sitemap: https://www.pilz.com/pt-BR/sitemap-shop-level-3.xml
Sitemap: https://www.pilz.com/zh-CN/sitemap-shop-level-3.xml
Sitemap: https://www.pilz.com/en-CZ/sitemap-shop-level-3.xml
Sitemap: https://www.pilz.com/da-DK/sitemap-shop-level-3.xml
Sitemap: https://www.pilz.com/fi-FI/sitemap-shop-level-3.xml
Sitemap: https://www.pilz.com/it-IT/sitemap-shop-level-3.xml
Sitemap: https://www.pilz.com/ja-JP/sitemap-shop-level-3.xml
Sitemap: https://www.pilz.com/ko-KR/sitemap-shop-level-3.xml
Sitemap: https://www.pilz.com/pl-PL/sitemap-shop-level-3.xml
Sitemap: https://www.pilz.com/ru-RU/sitemap-shop-level-3.xml
Sitemap: https://www.pilz.com/sv-SE/sitemap-shop-level-3.xml
Sitemap: https://www.pilz.com/tr-TR/sitemap-shop-level-3.xml
Sitemap: https://www.pilz.com/tw-TW/sitemap-shop-level-3.xml
Sitemap: https://www.pilz.com/en-SG/sitemap-shop-level-3.xml

Sitemap: https://www.pilz.com/de-DE/sitemap-shop-level-4.xml
Sitemap: https://www.pilz.com/de-AT/sitemap-shop-level-4.xml
Sitemap: https://www.pilz.com/de-CH/sitemap-shop-level-4.xml
Sitemap: https://www.pilz.com/en-INT/sitemap-shop-level-4.xml
Sitemap: https://www.pilz.com/en-GB/sitemap-shop-level-4.xml
Sitemap: https://www.pilz.com/en-US/sitemap-shop-level-4.xml
Sitemap: https://www.pilz.com/en-AU/sitemap-shop-level-4.xml
Sitemap: https://www.pilz.com/en-IE/sitemap-shop-level-4.xml
Sitemap: https://www.pilz.com/en-NZ/sitemap-shop-level-4.xml
Sitemap: https://www.pilz.com/en-IN/sitemap-shop-level-4.xml
Sitemap: https://www.pilz.com/en-CA/sitemap-shop-level-4.xml
Sitemap: https://www.pilz.com/fr-FR/sitemap-shop-level-4.xml
Sitemap: https://www.pilz.com/fr-CH/sitemap-shop-level-4.xml
Sitemap: https://www.pilz.com/fr-BE/sitemap-shop-level-4.xml
Sitemap: https://www.pilz.com/fr-CA/sitemap-shop-level-4.xml
Sitemap: https://www.pilz.com/es-ES/sitemap-shop-level-4.xml
Sitemap: https://www.pilz.com/es-MX/sitemap-shop-level-4.xml
Sitemap: https://www.pilz.com/nl-NL/sitemap-shop-level-4.xml
Sitemap: https://www.pilz.com/nl-BE/sitemap-shop-level-4.xml
Sitemap: https://www.pilz.com/pt-PT/sitemap-shop-level-4.xml
Sitemap: https://www.pilz.com/pt-BR/sitemap-shop-level-4.xml
Sitemap: https://www.pilz.com/zh-CN/sitemap-shop-level-4.xml
Sitemap: https://www.pilz.com/en-CZ/sitemap-shop-level-4.xml
Sitemap: https://www.pilz.com/da-DK/sitemap-shop-level-4.xml
Sitemap: https://www.pilz.com/fi-FI/sitemap-shop-level-4.xml
Sitemap: https://www.pilz.com/it-IT/sitemap-shop-level-4.xml
Sitemap: https://www.pilz.com/ja-JP/sitemap-shop-level-4.xml
Sitemap: https://www.pilz.com/ko-KR/sitemap-shop-level-4.xml
Sitemap: https://www.pilz.com/pl-PL/sitemap-shop-level-4.xml
Sitemap: https://www.pilz.com/ru-RU/sitemap-shop-level-4.xml
Sitemap: https://www.pilz.com/sv-SE/sitemap-shop-level-4.xml
Sitemap: https://www.pilz.com/tr-TR/sitemap-shop-level-4.xml
Sitemap: https://www.pilz.com/tw-TW/sitemap-shop-level-4.xml
Sitemap: https://www.pilz.com/en-SG/sitemap-shop-level-4.xml

