# robots.txt automaticaly generated by PrestaShop e-commerce open-source solution
# http://www.prestashop.com - http://www.prestashop.com/forums

# This file is to prevent the crawling and indexing of certain parts
# of your site by web crawlers and spiders run by sites like Yahoo!
# and Google. By telling these "robots" where not to go on your site,
# you save bandwidth and server resources.

# For more information about the robots.txt standard, see:
# http://www.robotstxt.org/wc/robots.html

User-agent: *
# Directories
Disallow: /www/wyrobyzdrewna/classes/
Disallow: /www/wyrobyzdrewna/config/
Disallow: /www/wyrobyzdrewna/download/
Disallow: /www/wyrobyzdrewna/mails/
Disallow: /www/wyrobyzdrewna/modules/
Disallow: /www/wyrobyzdrewna/translations/
Disallow: /www/wyrobyzdrewna/tools/
Disallow: /www/wyrobyzdrewna/lang-pl/
# Files
Disallow: /www/wyrobyzdrewna/addresses.php
Disallow: /www/wyrobyzdrewna/address.php
Disallow: /www/wyrobyzdrewna/authentication.php
Disallow: /www/wyrobyzdrewna/cart.php
Disallow: /www/wyrobyzdrewna/discount.php
Disallow: /www/wyrobyzdrewna/footer.php
Disallow: /www/wyrobyzdrewna/get-file.php
Disallow: /www/wyrobyzdrewna/header.php
Disallow: /www/wyrobyzdrewna/history.php
Disallow: /www/wyrobyzdrewna/identity.php
Disallow: /www/wyrobyzdrewna/images.inc.php
Disallow: /www/wyrobyzdrewna/init.php
Disallow: /www/wyrobyzdrewna/my-account.php
Disallow: /www/wyrobyzdrewna/order.php
Disallow: /www/wyrobyzdrewna/order-opc.php
Disallow: /www/wyrobyzdrewna/order-slip.php
Disallow: /www/wyrobyzdrewna/order-detail.php
Disallow: /www/wyrobyzdrewna/order-follow.php
Disallow: /www/wyrobyzdrewna/order-return.php
Disallow: /www/wyrobyzdrewna/order-confirmation.php
Disallow: /www/wyrobyzdrewna/pagination.php
Disallow: /www/wyrobyzdrewna/password.php
Disallow: /www/wyrobyzdrewna/pdf-invoice.php
Disallow: /www/wyrobyzdrewna/pdf-order-return.php
Disallow: /www/wyrobyzdrewna/pdf-order-slip.php
Disallow: /www/wyrobyzdrewna/product-sort.php
Disallow: /www/wyrobyzdrewna/search.php
Disallow: /www/wyrobyzdrewna/statistics.php
Disallow: /www/wyrobyzdrewna/attachment.php
Disallow: /www/wyrobyzdrewna/guest-tracking
Disallow: /www/wyrobyzdrewna/*orderby=
Disallow: /www/wyrobyzdrewna/*orderway=
Disallow: /www/wyrobyzdrewna/*tag=
Disallow: /www/wyrobyzdrewna/*id_currency=
Disallow: /www/wyrobyzdrewna/*search_query=
Disallow: /www/wyrobyzdrewna/*id_lang=
Disallow: /www/wyrobyzdrewna/*back=
Disallow: /www/wyrobyzdrewna/*utm_source=
Disallow: /www/wyrobyzdrewna/*utm_medium=
Disallow: /www/wyrobyzdrewna/*utm_campaign=
Disallow: /www/wyrobyzdrewna/*n=
# Sitemap


