User-agent: *
Allow: /
Disallow: /dolacz-do-nas/c-school/
Disallow: /pl/dolacz-do-nas/c-school/
Disallow: /join-us/c-school/
Disallow: /en/join-us/c-school/
Disallow: /unisciti-a-noi//
Disallow: /it/unisciti-a-noi//
Disallow: /schliess-dich-uns-an/c-school/
Disallow: /de/schliess-dich-uns-an/c-school/
Disallow: /folj-med/c-school/
Disallow: /se/folj-med/c-school/
Disallow: /fb-job-offers/
Disallow: /pl/fb-job-offers/
Disallow: /fb-job-offers/
Disallow: /en/fb-job-offers/
Disallow: /fb-job-offers/
Disallow: /it/fb-job-offers/
Disallow: /fb-job-offers/
Disallow: /de/fb-job-offers/
Disallow: /fb-job-offers/
Disallow: /se/fb-job-offers/
Disallow: /privacy-policy/
Disallow: /pl/privacy-policy/
Disallow: /privacy-policy/
Disallow: /en/privacy-policy/
Disallow: /privacy-policy/
Disallow: /it/privacy-policy/
Disallow: /privacy-policy/
Disallow: /de/privacy-policy/
Disallow: /privacy-policy/
Disallow: /se/privacy-policy/
Disallow: /corobimy-new/
Disallow: /pl/corobimy-new/
Disallow: /corobimy-new/rework-roboczo/
Disallow: /pl/corobimy-new/rework-roboczo/
Disallow: /corobimy-new/c-school-roboczo/
Disallow: /pl/corobimy-new/c-school-roboczo/
Sitemap: https://www.connectis.pl/sitemap.xml
