# robots.txt automaticaly generated by PrestaShop e-commerce open-source solution
# http://www.prestashop.com - http://www.prestashop.com/forums

# This file is to prevent the crawling and indexing of certain parts
# of your site by web crawlers and spiders run by sites like Yahoo!
# and Google. By telling these "robots" where not to go on your site,
# you save bandwidth and server resources.

# For more information about the robots.txt standard, see:
# http://www.robotstxt.org/wc/robots.html

User-agent: *
# Directories
Disallow: /classes/
Disallow: /config/
Disallow: /download/
Disallow: /mails/
Disallow: /modules/
Disallow: /translations/
Disallow: /tools/
Disallow: /lang-pl/
# Files
Disallow: /addresses.php
Disallow: /address.php
Disallow: /authentication.php
Disallow: /cart.php
Disallow: /discount.php
Disallow: /footer.php
Disallow: /get-file.php
Disallow: /header.php
Disallow: /history.php
Disallow: /identity.php
Disallow: /images.inc.php
Disallow: /init.php
Disallow: /my-account.php
Disallow: /order.php
Disallow: /order-opc.php
Disallow: /order-slip.php
Disallow: /order-detail.php
Disallow: /order-follow.php
Disallow: /order-return.php
Disallow: /order-confirmation.php
Disallow: /pagination.php
Disallow: /password.php
Disallow: /pdf-invoice.php
Disallow: /pdf-order-return.php
Disallow: /pdf-order-slip.php
Disallow: /product-sort.php
Disallow: /search.php
Disallow: /statistics.php
Disallow: /attachment.php
Disallow: /guest-tracking
Disallow: /*orderby=
Disallow: /*orderway=
Disallow: /*tag=
Disallow: /*id_currency=
Disallow: /*search_query=
Disallow: /*id_lang=
Disallow: /*back=
Disallow: /*utm_source=
Disallow: /*utm_medium=
Disallow: /*utm_campaign=
Disallow: /*n=
Disallow: /manufacturer-details.php?id_manufacturer=1
Disallow: /manufacturer-details.php?id_manufacturer=2
Disallow: /manufacturer-details.php?id_manufacturer=3
Disallow: /manufacturer-details.php?id_manufacturer=4
Disallow: /manufacturer-details.php?id_manufacturer=5
Disallow: /manufacturer-details.php?id_manufacturer=6
Disallow: /manufacturer-details.php?id_manufacturer=7
Disallow: /manufacturer-details.php?id_manufacturer=8
Disallow: /manufacturer-details.php?id_manufacturer=9
Disallow: /manufacturer-details.php?id_manufacturer=10
Disallow: /manufacturer-details.php?id_manufacturer=11
Disallow: /manufacturer-details.php?id_manufacturer=12
Disallow: /manufacturer-details.php?id_manufacturer=13
Disallow: /manufacturer-details.php?id_manufacturer=14
Disallow: /manufacturer-details.php?id_manufacturer=15
Disallow: /manufacturer-details.php?id_manufacturer=16
Disallow: /manufacturer-details.php?id_manufacturer=17
Disallow: /manufacturer-details.php?id_manufacturer=18
Disallow: /manufacturer-details.php?id_manufacturer=19
Disallow: /manufacturer-details.php?id_manufacturer=20
Disallow: /manufacturer-details.php?id_manufacturer=21
Disallow: /manufacturer-details.php?id_manufacturer=22
Disallow: /manufacturer-details.php?id_manufacturer=23
Disallow: /manufacturer-details.php?id_manufacturer=24
Disallow: /manufacturer-details.php?id_manufacturer=25
Disallow: /manufacturer-details.php?id_manufacturer=26
Disallow: /manufacturer-details.php?id_manufacturer=28
Disallow: /manufacturer-details.php?id_manufacturer=29
Disallow: /manufacturer-details.php?id_manufacturer=30
Disallow: /manufacturer-details.php?id_manufacturer=31
Disallow: /manufacturer-details.php?id_manufacturer=32
Disallow: /manufacturer-details.php?id_manufacturer=33
Disallow: /manufacturer-details.php?id_manufacturer=34
Disallow: /manufacturer-details.php?id_manufacturer=36
Disallow: /manufacturer-details.php?id_manufacturer=37
Disallow: /manufacturer-details.php?id_manufacturer=38
Disallow: /manufacturer-details.php?id_manufacturer=39
Disallow: /manufacturer-details.php?id_manufacturer=40
Disallow: /manufacturer-details.php?id_manufacturer=41
Disallow: /manufacturer-details.php?id_manufacturer=42
Disallow: /manufacturer-details.php?id_manufacturer=43
Disallow: /manufacturer-details.php?id_manufacturer=44
Disallow: /manufacturer-details.php?id_manufacturer=45
Disallow: /manufacturer-details.php?id_manufacturer=46
Disallow: /manufacturer-details.php?id_manufacturer=47
Disallow: /manufacturer-details.php?id_manufacturer=48
Disallow: /manufacturer-details.php?id_manufacturer=49
Disallow: /manufacturer-details.php?id_manufacturer=50
Disallow: /manufacturer-details.php?id_manufacturer=51
Disallow: /manufacturer-details.php?id_manufacturer=52
Disallow: /manufacturer-details.php?id_manufacturer=53

