User-agent: *
Disallow: /user
Disallow: /basket
Disallow: /search
Disallow: /recommend_shop
Disallow: /newsletter
Disallow: /currency
Disallow: /productsCompare
Disallow: /product_options
Disallow: /stNavigationFrontend
Disallow: /producer
Disallow: /navigation
Disallow: /invoice
Disallow: /order
Disallow: /orderPdf/*
Disallow: /invoicePdf/*
Disallow: /stAvailabilityFrontend/showAddOverlay
Disallow: /stQuestionFrontend/showAddOverlay
Disallow: /*.php$
Disallow: /paypal
Disallow: /review/*
Disallow: /plugins/*
Disallow: /c/pl/*
Disallow: /en
Disallow: /at
Disallow: /de
Disallow: /manufacturer/en
Disallow: /lang/de

