User-agent: *
Allow: *
Crawl-delay: 10
Disallow: /admin/
Disallow: /auth/
Disallow: /adult/
Disallow: /profile/
Disallow: /ask/
Disallow: /notify/
Disallow: /basket/
Disallow: /compare/
Disallow: /newsletter/
Disallow: /recommend/
Disallow: /autosuggest/
Disallow: /customize/
Disallow: /comments/
Disallow: /captcha/
Disallow: /polls/
Disallow: /images/delivery/
Disallow: /images/shippings/
Disallow: /images/payments/
Disallow: /images/i18n/
Disallow: /product/print/*
Disallow: /product/reload-price/
Disallow: *filters=
Disallow: *serie=
Disallow: /products/*
Disallow: /cookie/

Sitemap: http://www.przeciwkomonotonii.pl/export/googlesitemap/
