User-agent: Sentibot
Disallow: /
User-Agent: AhrefsBot
Disallow: /mobile/
User-agent: rogerbot
Disallow: /mobile/
User-agent: MJ12bot
Disallow: /mobile/
User-agent: *
Disallow: /administrator/
Disallow: /cache/
Disallow: /includes/
Disallow: /installation/
Disallow: /language/
Disallow: /libraries/
Disallow: /tmp/
Disallow: /xmlrpc/
Disallow: */component/mailto/*
Disallow: *component/user/
