User-agent: *
Disallow: /customer/
Disallow: /checkout/
Disallow: /mevaconewsletter/
Disallow: /products.html?*
Disallow: /*___store=*
Allow: /products.html?productfilter_material=3$
Allow: /products.html?productfilter_type=117$
Allow: /products.html?productfilter_type=117&productfilter_material=3$
Allow: /products.html?productfilter_type=117&productfilter_material=67$
Allow: /products.html?productfilter_type=148$
Allow: /products.html?productfilter_type=148&productfilter_material=63$
Allow: /products.html?productfilter_type=5$
Allow: /products.html?productfilter_type=5&productfilter_material=3$
Allow: /products.html?productfilter_type=148&productfilter_material=3$
Allow: /products.html?productfilter_type=5&productfilter_material=34$
Allow: /products.html?productfilter_type=5&productfilter_material=61$
Allow: /products.html?productfilter_type=117%2C127$
Allow: /products.html?productfilter_type=5&format_filter=412%2C413%2C414$
Sitemap: https://www.mevaco.pl/media/sitemap_pl_pl.xml
