User-agent: *
Disallow: /engine/go.php
Disallow: /lastnews/
Disallow: /filmy/
Disallow: /zwiastun/
Disallow: /telewizja-online/
Disallow: /najlepsze-filmy-2012/
Disallow: /kinoonline/
Disallow: /2012/
Disallow: /user/
Disallow: /statistics.html
Disallow: /*subaction=userinfo
Disallow: /*subaction=newposts
Disallow: /*do=lastcomments
Disallow: /*do=feedback
Disallow: /*do=register
Disallow: /*do=lostpassword
Disallow: /*do=addnews
Disallow: /*do=stats
Disallow: /*do=pm
