User-agent: *
Disallow: /ru/mediakit/$
Disallow: /ru/mediakit/adcampaigns/
Disallow: /ru/mediakit/photos/
Disallow: /ru/popup_view.shtml
Disallow: /ru/products/
Disallow: /ru/wheretobuy/popup_Product_Category.shtml
Disallow: /*?id=kr
Disallow: /*?id=at
Disallow: /*?utm
Host: www.haier.com
Sitemap: http://www.haier.com/cn/sitemap/sitemap.xml
Sitemap: http://www.haier.com/jp/sitemapxml/sitemap.xml
Sitemap: http://www.haier.com/th/sitemap/sitemap.xml
Sitemap: http://www.haier.com/my/sitemap/sitemap.xml
Sitemap: http://www.haier.com/ph/sitemap/sitemap.xml
Sitemap: http://www.haier.com/in/sitemap/sitemap.xml
Sitemap: http://www.haier.com/pk/sitemap/sitemap.xml
Sitemap: http://www.haier.com/uk/sitemap/sitemap.xml
Sitemap: http://www.haier.com/de/sitemap/sitemap.xml
Sitemap: http://www.haier.com/fr/sitemap/sitemap.xml
Sitemap: http://www.haier.com/es/sitemap/sitemap.xml
Sitemap: http://www.haier.com/it/sitemap/sitemap.xml
Sitemap: http://www.haier.com/ru/sitemap/sitemap.xml
Sitemap: http://www.haier.com/nl/sitemap/sitemap.xml
Sitemap: http://www.haier.com/be/sitemap/sitemap.xml
Sitemap: http://www.haier.com/be_fr/sitemap/sitemap.xml
Sitemap: http://www.haier.com/pl/sitemap/sitemap.xml
Sitemap: http://www.haier.com/ve/sitemap/sitemap.xml
Sitemap: http://www.haier.com/ae/sitemap/sitemap.xml

