User-agent: *
Crawl-delay: 30
Request-rate: 1/1s

User-agent: *
Allow: /environment/cache/images/
Disallow: /application/
Disallow: /environment/
Disallow: /libraries/
Disallow: /*/producer/
Disallow: /*/basket
Disallow: /*/fav/add/
Disallow: /*/links/
Disallow: /mobile/
Disallow: /komentarz-
Disallow: /powiadom_znajomego-
Disallow: /pl/banner/
Disallow: /panel
Disallow: /en_US/
Disallow: /*/p/q/
Disallow: /links
Disallow: /*/prices
Disallow: /*/prices/*
Allow: /
Disallow: /*/reg/
Disallow: /*/login/
Disallow: /*/searchquery/
