User-agent: *
Disallow: /zamowienia.php
Disallow: /albumy
Disallow: /dokumenty-grupy
Disallow: /grupy/
Disallow: /group.php
Disallow: /browse_groups.php
Disallow: /pro/regulamin
Disallow: /search.php
Disallow: /indeksy
Disallow: /document-view.seam
Disallow: /logowanie/
Disallow: /regulamin/
Disallow: /pomoc/
Disallow: /rejestracja/
Disallow: /weryfikacja/
Disallow: /przypomnienia-hasla/
Disallow: /wlasna-audioustawa/
Disallow: /polityka-ciasteczek/
Disallow: /reset-hasla/
Disallow: /rabaty/
Disallow: /testy-demo/
Disallow: /moje-zasoby/
Disallow: /newsletter_off/
Disallow: /kontakt/
Disallow: /lexlege/
Disallow: /pro/
