User-agent: *
allow: /
allow: /kontakt.htm
allow: /referencje.htm
allow: /index.htm
Allow: /internet.htm
Allow: /informatyka.htm
Allow: /geomatyka.htm
Allow: /dns/index.htm
Allow: /www/index.htm
Allow: /wizytowki/index.htm
Allow: /e-mail/index.htm
Allow: /domeny/index.htm
allow: /index2.htm
allow: http://www.9669.pl
allow: http://www.taxi-net.pl
allow: /taxi-net/index.html
allow: /phorum-5.1.20/
