User-agent: *
Disallow: /cgi-bin/
Disallow: /blog/wp-content/plugins/
Disallow: /mexican/wp-content/plugins/
Disallow: /user
Disallow: /basket
Disallow: /search
Disallow: /recommend_shop
Disallow: /newsletter
Disallow: /currency
Disallow: /productsCompare
Disallow: /product_options
Disallow: /stNavigationFrontend
Disallow: /producer
Disallow: /navigation
Disallow: /invoice
Disallow: /order
Disallow: /invoicePdf/*
Disallow: /orderPdf/*
Disallow: /stAvailabilityFrontend/showAddOverlay
Disallow: /stQuestionFrontend/showAddOverlay
Disallow: /stAvailabilityFrontend/showAddOverlay
Disallow: /stQuestionFrontend/showAddOverlay
Disallow: /stAvailabilityFrontend/showAddOverlay
Disallow: /stQuestionFrontend/showAddOverlay
Disallow: /product/list/hash
Disallow: /product/recommendProducts
Disallow: /stAccessoriesFrontend/accessoriesList
User-agent: *
Crawl-delay: 5
User-agent: Baiduspider
Disallow: /
User-agent: AhrefsBot
Disallow: /
User-agent: Ezooms
Disallow: /
User-agent: YandexBot
Disallow: /
User-agent: MJ12bot
Disallow: /
User-agent: bingbot
Disallow: /
User-agent: TwengaBot-2.0
Crawl-delay: 100
Disallow: /*.php$
Disallow: /*.php$
Disallow: /paypal

