User-agent: *
Disallow: /fotos/
Disallow: /koparki/photos/
Disallow: /ladkop/photos/
Disallow: /ladowarki/photos/
Disallow: /tv/photos/
Disallow: ankieta.php
Disallow: /ogloszenia/
Disallow: /oskiop/
Disallow: /marmi/
Disallow: /club-swit.pl/
Disallow: /bieganow/
Disallow: /gnomon/
Disallow: /ENG/
Disallow: /rozliczenia/
Disallow: /allegro/
Disallow: /motoallegro/
Disallow: /motosklep/
Disallow: /opony/photos/
Disallow: /tablety/foto/
Disallow: /tv/pytania/
Disallow: /dodaj_pytanie*.html$
Disallow: /sklep/
