User-agent: MJ12bot
disallow: /
User-agent: DomainCrawler
disallow: /
User-agent: Mail.RU_Bot
disallow: /
User-agent: MegaIndex.ru
disallow: /
User-agent: SEOkicks
disallow: /
User-agent: SemrushBot
disallow: /
User-agent: YandexBot
disallow: /

User-agent: DotBot
allow: /SLOFRA/
disallow: /

User-agent: Googlebot, User-agent:Bingbot, User-agent:BingPreview/1.0b, User-agent:MSNBOT, User-agent:DuckDuckGo-Favicons-Bot/1.0, User-agent:DuckDuckBot
disallow: /GENPARAF/
disallow: /genparaf/
disallow: /MET/
disallow: /PHPBB3/memberlist.php
disallow: /PHPBB3/znajdzprzodka.pl_PHPBB3
disallow: /EXMAZTG/memberlist.php
disallow: /EXMAZTG/znajdzprzodka.pl_EXMAZTG
disallow: /GENPARAF7/index.php/Dyskusja
disallow: /GENPARAF7/index.php?title=Dyskusja
disallow: /GENPARAF7/index.php?title=Specjalna:
disallow: /GENPARAF7/index.php/Specjalna:Zmiany_w_linkowanych/
disallow: /GENPARAF7/index.php?diff=
disallow: /GENPARAF7/index.php?title=Help
disallow: /GENPARAF7/index.php?title=Image
disallow: /GENPARAF7/index.php?title=Specjalna
disallow: /GENPARAF7/index.php?title=Template
disallow: /GENPARAF7/index.php?title=MediaWiki
disallow: /WEBTREES/znajdzprzodka.pl_WEBTREES
disallow: /WEBTREES/ancestry.php
disallow: /WEBTREES/branches.php
disallow: /WEBTREES/calendar.php
disallow: /WEBTREES/compact.php
disallow: /WEBTREES/descendancy.php
disallow: /WEBTREES/familybook.php
disallow: /WEBTREES/famlist.php
disallow: /WEBTREES/fanchart.php
disallow: /WEBTREES/hourglass.php
disallow: /WEBTREES/lifespan.php
disallow: /WEBTREES/login.php
disallow: /WEBTREES/medialist.php
disallow: /WEBTREES/notelist.php
disallow: /WEBTREES/pedigree.php
disallow: /WEBTREES/placelist.php
disallow: /WEBTREES/relationship.php
disallow: /WEBTREES/repolist.php
disallow: /WEBTREES/reportengine.php
disallow: /WEBTREES/search.php
disallow: /WEBTREES/search_advanced.php
disallow: /WEBTREES/sourcelist.php
disallow: /WEBTREES/statistics.php
disallow: /WEBTREES/statisticsplot.php
disallow: /WEBTREES/timeline.php
disallow: /BLAB80/
disallow: /DODATKI/
disallow: /SLOWNIK/
disallow: /TOKEN/
disallow: /WYSZUK_OLD/
disallow: /dashboard/
disallow: /Dynamic DNS Update URLs_pliki/
disallow: /include/
disallow: /poszukiwania/
disallow: /webalizer/
disallow: /xampp/
disallow: /analyticstracking.php
disallow: /dodaj_do_php.txt
disallow: /Dynamic DNS Update URLs.html
disallow: /google5da4fdb16dced1d2.html
disallow: /google90d76510a8c601d6.html
disallow: /index.php1
disallow: /phpinfo.php
disallow: /starepow1.html
disallow: /ip-refresh.html
allow: /PHPBB3/
allow: /WEBTREES/
allow: /GENPARAF7/
allow: /EXMAZTG/
allow: /PARAF/
allow: /SLOFRA/
allow: /CMWEB/
allow: /PARAF/HTM/

User-agent: AhrefsBot
disallow: /PHPBB3/memberlist.php
disallow: /EXMAZTG/memberlist.php
disallow: /EXMAZTG/znajdzprzodka.pl_EXMAZTG
disallow: /PHPBB3/znajdzprzodka.pl_PHPBB3
disallow: /GENPARAF/
disallow: /genparaf/
disallow: /GENPARAF7/
disallow: /MET/
disallow: /WEBTREES/
disallow: /webtrees/
disallow: /BLAB80/
disallow: /DODATKI/
disallow: /SLOWNIK/
disallow: /TOKEN/
disallow: /WYSZUK_OLD/
disallow: /dashboard/
disallow: /Dynamic DNS Update URLs_pliki/
disallow: /include/
disallow: /poszukiwania/
disallow: /webalizer/
disallow: /xampp/
disallow: /analyticstracking.php
disallow: /dodaj_do_php.txt
disallow: /Dynamic DNS Update URLs.html
disallow: /google5da4fdb16dced1d2.html
disallow: /google90d76510a8c601d6.html
disallow: /index.php1
disallow: /phpinfo.php
disallow: /ip-refresh.html
allow: /PHPBB3/
allow: /EXMAZTG/
allow: /PARAF/
allow: /SLOFRA/
allow: /CMWEB/
allow: /PARAF/HTM/

User-agent: Nekstbot
disallow: /GENPARAF7/index.php/Dyskusja
disallow: /GENPARAF7/index.php?title=Dyskusja
disallow: /GENPARAF7/index.php/Specjalna:Zmiany_w_linkowanych/
disallow: /GENPARAF7/index.php?diff=
disallow: /GENPARAF7/index.php?title=Help
disallow: /GENPARAF7/index.php?title=Image
disallow: /GENPARAF7/index.php?title=Specjalna
disallow: /GENPARAF7/index.php?title=Template
disallow: /GENPARAF7/index.php?title=MediaWiki
disallow: /WEBTREES/
disallow: /PHPBB3/memberlist.php
disallow: /PHPBB3/znajdzprzodka.pl_PHPBB3
disallow: /EXMAZTG/memberlist.php
disallow: /EXMAZTG/znajdzprzodka.pl_EXMAZTG
disallow: /PARAF/
disallow: /BLAB80/
disallow: /GENPARAF/
disallow: /genparaf/
disallow: /DODATKI/
disallow: /SLOWNIK/
disallow: /TOKEN/
disallow: /WYSZUK_OLD/
disallow: /dashboard/
disallow: /Dynamic DNS Update URLs_pliki/
disallow: /include/
disallow: /poszukiwania/
disallow: /webalizer/
disallow: /xampp/
disallow: /analyticstracking.php
disallow: /dodaj_do_php.txt
disallow: /Dynamic DNS Update URLs.html
disallow: /google5da4fdb16dced1d2.html
disallow: /google90d76510a8c601d6.html
disallow: /index.php1
disallow: /phpinfo.php
disallow: /ip-refresh.html
allow: /SLOFRA/
allow: /CMWEB/
allow: /PHPBB3/
allow: /EXMAZTG/
allow: /GENPARAF7/
