User-agent: *
Allow: *
Crawl-delay: 30
Disallow: /admin/
Disallow: /auth/
Disallow: /adult/
Disallow: /profile/
Disallow: /ask/
Disallow: /notify/
Disallow: /basket/
Disallow: /compare/
Disallow: /newsletter/
Disallow: /recommend/
Disallow: /autosuggest/
Disallow: /customize/
Disallow: /comments/
Disallow: /captcha/
Disallow: /polls/
Disallow: /js/
Disallow: /gfx/
Disallow: /css/
Disallow: /images/delivery/
Disallow: /images/shippings/
Disallow: /images/payments/
Disallow: /images/i18n/
Disallow: /product/print/*
Disallow: /product/reload-price/
Disallow: *filters=
Disallow: *serie=
Disallow: /products/*
Disallow: /cookie/
Disallow: /repository/
Disallow: /search/?attr=*
Disallow: /search/?tag=*
Disallow: /rss/
Disallow: /search/Wysylamy-w-ciagu-24-godzin/?status=1

Sitemap: http://www.ambelucja.pl/export/googlesitemap/
