# robots.txt

User-Agent: *
Allow: /
Crawl-delay: 20

Disallow: /plugins/
Disallow: /libs/
Disallow: /includes/
Disallow: /print*
Disallow: /*?sort_by=
Disallow: /*&sort_by=
Disallow: /*?sort_type=
Disallow: /*&sort_type=

### Rules generated by the Sitemap plugin ###
Sitemap: http://www.gajana.pl/sitemap.xml

# Excluded pages:
Disallow: /*confirm.html*
Disallow: /*listing-details.html*
Disallow: /*print.html*
Disallow: /404.html*
Disallow: /*listing-remove.html*
Disallow: /*newsletter.html*
Disallow: /*excel-import-export.html*
Disallow: /*comparision-tables.html*
Disallow: /*booking-order.html*

