User-agent: *
Sitemap: https://www.monedo.pl/sitemap.xml
Sitemap: https://www.monedo.pl/now/blog/sitemap_index.xml
Allow: /
Disallow: /isItWorking
Disallow: /now?sea=*
Disallow: /now/sea/*
Disallow: /now?migration=true
Disallow: /now/promo/*
Disallow: /now/blog/*/trackback/
Disallow: /now/blog/*/attachment/
Disallow: /now/blog/author/
Disallow: /now/blog/*/page/
Disallow: /now/blog/tag/
Disallow: /now/blog/tag/*/page/
Disallow: /now/blog/page/
Disallow: /now/blog/comments/
Disallow: /now/blog/xmlrpc.php
Disallow: /now/blog/*?s=
Disallow: /now/blog///*/feed.xml
Disallow: /now/blog/?attachment_id*
User-agent: Adsbot-Google
Allow: /
