User-agent: *
Allow: /
User-agent: GoogleBot
Disallow: /k0-2
User-agent: GoogleBot
Disallow: /k3-7
User-agent: GoogleBot
Disallow: /k1-5
User-agent: GoogleBot
Disallow: /k25-6
User-agent: GoogleBot
Disallow: /k4-8
User-agent: GoogleBot
Disallow: /k5-9
User-agent: GoogleBot
Disallow: /k26-11
User-agent: GoogleBot
Disallow: /k9-12
User-agent: GoogleBot
Disallow: /k10-13
User-agent: GoogleBot
Disallow: /k27-14
User-agent: GoogleBot
Disallow: /k12-15
User-agent: GoogleBot
Disallow: /k13-16
User-agent: GoogleBot
Disallow: /k29-17
User-agent: GoogleBot
Disallow: /k15-18
User-agent: GoogleBot
Disallow: /k16-19
User-agent: GoogleBot
Disallow: /k17-20
User-agent: GoogleBot
Disallow: /k18-21
User-agent: GoogleBot
Disallow: /k19-22
User-agent: GoogleBot
Disallow: /k20-23
User-agent: GoogleBot
Disallow: /l1-24
User-agent: GoogleBot
Disallow: /l3-25
User-agent: GoogleBot
Disallow: /l4-26
User-agent: GoogleBot
Disallow: /l5-27
User-agent: GoogleBot
Disallow: /l8-28
User-agent: GoogleBot
Disallow: /l9-29
User-agent: GoogleBot
Disallow: /l10-30
User-agent: GoogleBot
Disallow: /l11-31
User-agent: GoogleBot
Disallow: /mw1-32
User-agent: GoogleBot
Disallow: /mw3-33
User-agent: GoogleBot
Disallow: /mw6-35
User-agent: GoogleBot
Disallow: /mw7-36
User-agent: GoogleBot
Disallow: /mw8-37
User-agent: GoogleBot
Disallow: /mw9-38
User-agent: GoogleBot
Disallow: /mw15-39
User-agent: GoogleBot
Disallow: /mw18-40
User-agent: GoogleBot
Disallow: /mw14-41
User-agent: GoogleBot
Disallow: /sz2-42
User-agent: GoogleBot
Disallow: /sz21-43
User-agent: GoogleBot
Disallow: /sz4-44
User-agent: GoogleBot
Disallow: /sz25-45
User-agent: GoogleBot
Disallow: /sz20-46
User-agent: GoogleBot
Disallow: /sz26-47
User-agent: GoogleBot
Disallow: /sz27-48
User-agent: GoogleBot
Disallow: /sz10-49
User-agent: GoogleBot
Disallow: /sz11-50
User-agent: GoogleBot
Disallow: /sz13-52
User-agent: GoogleBot
Disallow: /sz31-53
User-agent: GoogleBot
Disallow: /sz15-54
User-agent: GoogleBot
Disallow: /sz32-55
User-agent: GoogleBot
Disallow: /sz17-56
User-agent: GoogleBot
Disallow: /sz18-57
User-agent: GoogleBot
Disallow: /sz30-58
User-agent: GoogleBot
Disallow: /sz22-59
User-agent: GoogleBot
Disallow: /sz23-60
User-agent: GoogleBot
Disallow: /sz24-61
User-agent: GoogleBot
Disallow: /wspolpraca-z-firma-lukstol-62
User-agent: GoogleBot
Disallow: /k7-69
User-agent: GoogleBot
Disallow: /k8-70
User-agent: GoogleBot
Disallow: /k12-71
User-agent: GoogleBot
Disallow: /k11-72
User-agent: GoogleBot
Disallow: /l2-73
User-agent: GoogleBot
Disallow: /l6-74
User-agent: GoogleBot
Disallow: /mw2-76
User-agent: GoogleBot
Disallow: /mw3-77
User-agent: GoogleBot
Disallow: /mw4-78
User-agent: GoogleBot
Disallow: /mw11-79
User-agent: GoogleBot
Disallow: /mw13-80
User-agent: GoogleBot
Disallow: /mw9-81
User-agent: GoogleBot
Disallow: /mw10-82
User-agent: GoogleBot
Disallow: /sz19-83
User-agent: GoogleBot
Disallow: /sz6-85
User-agent: GoogleBot
Disallow: /sz7-86
User-agent: GoogleBot
Disallow: /sz3-87
User-agent: GoogleBot
Disallow: /sz28-88
User-agent: GoogleBot
Disallow: /sz13-90
User-agent: GoogleBot
Disallow: /mw12-91
User-agent: GoogleBot
Disallow: /sz8-94
User-agent: GoogleBot
Disallow: /sz9-95
User-agent: GoogleBot
Disallow: /k6-96
User-agent: GoogleBot
Disallow: /sz10-97
User-agent: GoogleBot
Disallow: /sz11-100
User-agent: GoogleBot
Disallow: /mw17-101
User-agent: GoogleBot
Disallow: /mw8-102
User-agent: GoogleBot
Disallow: /sz1-103
User-agent: GoogleBot
Disallow: /k2-104
User-agent: GoogleBot
Disallow: /s1-105
User-agent: GoogleBot
Disallow: /s2-106
User-agent: GoogleBot
Disallow: /s3-107
User-agent: GoogleBot
Disallow: /s4-108
User-agent: GoogleBot
Disallow: /krz1-110
User-agent: GoogleBot
Disallow: /krz2-111
User-agent: GoogleBot
Disallow: /krz3-112
User-agent: GoogleBot
Disallow: /krz4-113
User-agent: GoogleBot
Disallow: /krz5-114
User-agent: GoogleBot
Disallow: /krz6-115
User-agent: GoogleBot
Disallow: /krz7-116
User-agent: GoogleBot
Disallow: /krz8-117
User-agent: GoogleBot
Disallow: /krz9-118
User-agent: GoogleBot
Disallow: /krz10-119
User-agent: GoogleBot
Disallow: /krz11-120
User-agent: GoogleBot
Disallow: /krz12-121
User-agent: GoogleBot
Disallow: /krz13-122
User-agent: GoogleBot
Disallow: /krz14-123
User-agent: GoogleBot
Disallow: /krz15-124
User-agent: GoogleBot
Disallow: /krz16-125
User-agent: GoogleBot
Disallow: /krz17-126
User-agent: GoogleBot
Disallow: /krz18-127
User-agent: GoogleBot
Disallow: /krz19-128
User-agent: GoogleBot
Disallow: /l7-129
User-agent: GoogleBot
Disallow: /l8-130
User-agent: GoogleBot
Disallow: /mw16-131
User-agent: GoogleBot
Disallow: /k14-133
User-agent: GoogleBot
Disallow: /sz14-134
User-agent: GoogleBot
Disallow: /sz16-135
User-agent: GoogleBot
Disallow: /sz29-136
User-agent: GoogleBot
Disallow: /k19-137
User-agent: GoogleBot
Disallow: /k21-138
User-agent: GoogleBot
Disallow: /sz33-139
User-agent: GoogleBot
Disallow: /sz34-140
User-agent: GoogleBot
Disallow: /sz35-141
User-agent: GoogleBot
Disallow: /k22-142
User-agent: GoogleBot
Disallow: /sz36-143
User-agent: GoogleBot
Disallow: /sz37-144
User-agent: GoogleBot
Disallow: /l13-146
User-agent: GoogleBot
Disallow: /sz38-147
User-agent: GoogleBot
Disallow: /l14-148
User-agent: GoogleBot
Disallow: /k23-149
User-agent: GoogleBot
Disallow: /mw19-150
User-agent: GoogleBot
Disallow: /k24-151
User-agent: GoogleBot
Disallow: /mw20-152
User-agent: GoogleBot
Disallow: /k30-153
User-agent: GoogleBot
Disallow: /mw21-154

