User-agent: *
Disallow: /category/en/
Disallow: /product_options/
Disallow: /lang/
Disallow: /invoice
Disallow: /order
Disallow: /invoicePdf/*
Disallow: /orderPdf/*
Disallow: /basket
Disallow: /user
Disallow: /stAvailabilityFrontend/showAddOverlay
Disallow: /stQuestionFrontend/showAddOverlay
User-agent: Yandex
Crawl-delay: 60
User-Agent: bingbot
Crawl-delay: 120
User-Agent: BingPreview
Crawl-delay: 120
User-agent: msnbot
Crawl-Delay: 120
User-agent: msnbot-news
Crawl-Delay: 120
User-agent: msnbot-media
Crawl-Delay: 120
User-agent: msnbot-products
Crawl-Delay: 120
User-agent: TwengaBot-2.0
Crawl-delay: 120
User-agent: TwengaBot
Crawl-delay: 120

