User-agent: *
Disallow: /
Disallow: /public/admin/
Disallow: /public/ajax/
Disallow: /public/cache/
Disallow: /public/captcha/
Disallow: /public/fonts/
Disallow: /public/gfx/
Disallow: /public/images/
Disallow: /public/public/
Disallow: /public/scripts/
Disallow: /public/styles/
User-agent: Googlebot
Allow: /
Disallow: /public/admin/
Disallow: /public/ajax/
Disallow: /public/cache/
Disallow: /public/captcha/
Disallow: /public/fonts/
Disallow: /public/gfx/
Disallow: /public/images/
Disallow: /public/public/
Disallow: /public/scripts/
Disallow: /public/styles/
User-agent: MSNBot
Allow: /
Disallow: /public/admin/
Disallow: /public/ajax/
Disallow: /public/cache/
Disallow: /public/captcha/
Disallow: /public/fonts/
Disallow: /public/gfx/
Disallow: /public/images/
Disallow: /public/public/
Disallow: /public/scripts/
Disallow: /public/styles/
User-agent: Slurp
Allow: /
Disallow: /public/admin/
Disallow: /public/ajax/
Disallow: /public/cache/
Disallow: /public/captcha/
Disallow: /public/fonts/
Disallow: /public/gfx/
Disallow: /public/images/
Disallow: /public/public/
Disallow: /public/scripts/
Disallow: /public/styles/
