User-Agent: *
Disallow: /oldbil/
Allow: /kalendarz/
Allow: /
Allow: /wp-content/uploads/
Allow: /wp-content/uploads/
Allow: /wp-content/uploads/
Allow: /wp-content/uploads/
Allow: /wp-content/uploads/
Disallow: /wp-admin/admin-ajax.php
Disallow: /readme.html
Disallow: /wp-admin/
Disallow: /wp-includes/
Disallow: /wp-content/plugins/
Disallow: /wp-content/cache/
Disallow: /wp-content/themes/
Disallow: /wp-content/
Sitemap: http://bil.bielsko.pl/sitemap.xml
