User-agent: *
Disallow: /.svn/
Disallow: /_index/
Disallow: /admin/
Disallow: /cache/
Disallow: /classes/
Disallow: /dict/
Disallow: /lib/
Disallow: /forums/
Disallow: /templates/
Disallow: /templates_c/
Sitemap: https://www.nicelabel.com/sitemap.xml
Sitemap: https://www.nicelabel.com/sitemap_de.xml
Sitemap: https://www.nicelabel.com/sitemap_fr.xml
Sitemap: https://www.nicelabel.com/sitemap_es.xml
Sitemap: https://www.nicelabel.com/sitemap_pl.xml
Sitemap: https://www.nicelabel.com/sitemap_zh.xml
Sitemap: https://app.wistia.com/sitemaps/27285.xml
