User-agent: *
Disallow: /ru*
Disallow: /en*
Disallow: /*waluta.html
Disallow: /*schowek.html
Disallow: /*podpowiedzi.html
Disallow: /*szukaj.html
Disallow: /*tabela_kolorow.html
Disallow: /*tabela_rozmiarow.html
Disallow: /*produkt_compare_add.html
Disallow: /*produkt_compare_delete.html
Disallow: /*koszyk/
Disallow: /*koszyk.html
Disallow: /*logowanie.html
Disallow: /*rejestracja.html
Disallow: /*odzyskiwanie_hasla.html
Disallow: /*produkt_drukuj.pdf
Disallow: /*porownaj_produkty.html
Disallow: /*banner*
Disallow: /*zoomer2d*
Disallow: /*zoomer3d*
Disallow: /*amf*
Disallow: /*amf/gateway*
Disallow: /*srodki_wirtualne.html
Disallow: /*strefa_projektowania*
Disallow: /*zapytaj_o_zyrandol.html
Disallow: /*zapytaj_o_projekt.html

