# robots.txt file for http://www.zeco.com.pl/
# Generated by SOFTplus GSiteCrawler v1.23 rev. 286 / http://gsitecrawler.com/
# 09-04-2008  02:35

User-agent: *
# No exclusions found, disallow nothing.
Disallow:

# end of file


