# robots.txt automaticaly generated by PrestaShop e-commerce open-source solution
# http://www.prestashop.com - http://www.prestashop.com/forums
# This file is to prevent the crawling and indexing of certain parts
# of your site by web crawlers and spiders run by sites like Yahoo!
# and Google. By telling these "robots" where not to go on your site,
# you save bandwidth and server resources.
# For more information about the robots.txt standard, see:
# http://www.robotstxt.org/wc/robots.html
User-agent: *
# Allow Directives
Allow: */modules/*.css
Allow: */modules/*.js
Allow: */modules/*.png
Allow: */modules/*.jpg
Allow: */themes/*/assets/cache/*.js
Allow: */themes/*/assets/cache/*.css
Allow: */themes/*/assets/css/*
# Private pages
Disallow: /*orderby=
Disallow: /*orderway=
Disallow: /*tag=
Disallow: /*id_currency=
Disallow: /*search_query=
Disallow: /*back=
Disallow: /*n=
Disallow: /*controller=addresses
Disallow: /*controller=address
Disallow: /*controller=authentication
Disallow: /*controller=cart
Disallow: /*controller=discount
Disallow: /*controller=footer
Disallow: /*controller=get-file
Disallow: /*controller=header
Disallow: /*controller=history
Disallow: /*controller=identity
Disallow: /*controller=images.inc
Disallow: /*controller=init
Disallow: /*controller=my-account
Disallow: /*controller=order
Disallow: /*controller=order-opc
Disallow: /*controller=order-slip
Disallow: /*controller=order-detail
Disallow: /*controller=order-follow
Disallow: /*controller=order-return
Disallow: /*controller=order-confirmation
Disallow: /*controller=pagination
Disallow: /*controller=password
Disallow: /*controller=pdf-invoice
Disallow: /*controller=pdf-order-return
Disallow: /*controller=pdf-order-slip
Disallow: /*controller=product-sort
Disallow: /*controller=search
Disallow: /*controller=statistics
Disallow: /*controller=attachment
Disallow: /*controller=guest-tracking
# Directories
Disallow: */classes/
Disallow: */config/
Disallow: */download/
Disallow: */mails/
Disallow: */modules/
Disallow: */translations/
Disallow: */tools/
# Files
Disallow: /odzyskiwanie-hasla
Disallow: /adres
Disallow: /adresy
Disallow: /logowanie
Disallow: /koszyk
Disallow: /rabaty
Disallow: /historia-zamowien
Disallow: /dane-osobiste
Disallow: /moje-konto
Disallow: /sledzenie-zamowienia
Disallow: /pokwitowania
Disallow: /zamowienie
Disallow: /szukaj
Disallow: /szybkie-zakupy
Disallow: /sledzenie-zamowienia-gosc
Disallow: /potwierdzenie-zamowienia

User-agent: mj12bot
Disallow:/
User-agent: MJ12bot
Disallow: /
User-agent: Baiduspider
Disallow: /
User-Agent: AhrefsBot
Disallow: /
User-agent: AhrefsBot/4.0
Disallow: /
User-Agent: TwengaBot
Disallow: /
User-Agent: YandexImages
Disallow: /
User-Agent: SEOkicks
Disallow: /
User-Agent: bingbot
Disallow: /
User-Agent: yandex
Disallow: /
User-Agent: yandexBot
Disallow: /
User-Agent: msnbot
Disallow: /
User-Agent: rogerbot
Disallow: /
User-Agent: Baiduspider/2.0
Disallow: /
User-Agent: bingbot/2.0
Disallow: /
User-Agent: MegaIndex.ru/2.0
Disallow:/
User-Agent: megaindex.com/crawler
Disallow:/
User-Agent: twenga.com/bot.html
Disallow:/
User-Agent: Mail.ru bot
Disallow:/
User-Agent: FavIconizer
Disallow:/
User-Agent: FaceBook
Disallow:/
User-Agent: Yahoo Slurp
Disallow:/
User-Agent: Bing Preview
Disallow:/
User-Agent: Alexa
Disallow:/
User-Agent: SeznamBot
Disallow:/
User-Agent: SemrushBot
Disallow:/
User-Agent: 360spider
Disallow:/
User-Agent: SurveyBot
Disallow:/
User-Agent: yeti
Disallow:/
User-Agent: SEOprofiler
Disallow:/
User-Agent: MSNBot
Disallow:/
User-Agent: SEOprofiler Bot
Disallow:/
User-Agent: archive.org bot
Disallow:/
User-Agent: SemrushBot
Disallow:/
User-Agent: Bing Preview bot
Disallow:/
User-Agent: Proximic Spider
Disallow:/
User-Agent: Grapeshot Crawler
Disallow:/
User-Agent: SEOkicks Webcrawler
Disallow:/
User-Agent: 360spider
Disallow:/
User-Agent: Mail.ru bot
Disallow:/
User-agent: Exabot
Disallow: /
User-agent: CFNetwork
Disallow: /
User-agent: Ask
Disallow: /
User-agent: SurveyBot
Disallow: /
User-agent: BaiDuSpider
Disallow: /
User-agent: Java (Often spam bot)
Disallow: /
User-agent: larbin
Disallow: /
User-agent: Alexa (IA Archiver)
Disallow: /
User-agent: Jakarta commons-httpclient
Disallow: /
User-agent: Python-urllib
Disallow: /
User-agent: larbin
Disallow: /
User-agent: b2w/0.1
Disallow: /
User-agent: Copernic
Disallow: /
User-agent: psbot
Disallow: /
User-agent: Python-urllib
Disallow: /
User-agent: URL_Spider_Pro
Disallow: /
User-agent: CherryPicker
Disallow: /
User-agent: EmailCollector
Disallow: /
User-agent: EmailSiphon
Disallow: /
User-agent: WebBandit
Disallow: /
User-agent: EmailWolf
Disallow: /
User-agent: ExtractorPro
Disallow: /
User-agent: CopyRightCheck
Disallow: /
User-agent: Crescent
Disallow: /
User-agent: SiteSnagger
Disallow: /
User-agent: ProWebWalker
Disallow: /
User-agent: CheeseBot
Disallow: /
User-agent: LNSpiderguy
Disallow: /
User-agent: Alexibot
Disallow: /
User-agent: Teleport
Disallow: /
User-agent: TeleportPro
Disallow: /
User-agent: MIIxpc
Disallow: /
User-agent: Telesoft
Disallow: /
User-agent: Website Quester
Disallow: /
User-agent: WebZip
Disallow: /
User-agent: moget/2.1
Disallow: /
User-agent: WebZip/4.0
Disallow: /
User-agent: WebStripper
Disallow: /
User-agent: WebSauger
Disallow: /
User-agent: WebCopier
Disallow: /
User-agent: NetAnts
Disallow: /
User-agent: Mister PiX
Disallow: /
User-agent: WebAuto
Disallow: /
User-agent: TheNomad
Disallow: /
User-agent: WWW-Collector-E
Disallow: /
User-agent: RMA
Disallow: /
User-agent: libWeb/clsHTTP
Disallow: /
User-agent: asterias
Disallow: /
User-agent: httplib
Disallow: /
User-agent: turingos
Disallow: /
User-agent: spanner
Disallow: /
User-agent: InfoNaviRobot
Disallow: /
User-agent: Harvest/1.5
Disallow: /
User-agent: Bullseye/1.0
Disallow: /
User-agent: Mozilla/4.0 (compatible; BullsEye; Windows 95)
Disallow: /
User-agent: Crescent Internet ToolPak HTTP OLE Control v.1.0
Disallow: /
User-agent: CherryPickerSE/1.0
Disallow: /
User-agent: CherryPickerElite/1.0
Disallow: /
User-agent: WebBandit/3.50
Disallow: /
User-agent: NICErsPRO
Disallow: /
User-agent: Microsoft URL Control - 5.01.4511
Disallow: /
User-agent: Not Your Business!
Disallow: /
User-agent: Hidden-Referrer
Disallow: /
User-agent: DittoSpyder
Disallow: /
User-agent: Foobot
Disallow: /
User-agent: WebmasterWorldForumBot
Disallow: /
User-agent: SpankBot
Disallow: /
User-agent: BotALot
Disallow: /
User-agent: lwp-trivial/1.34
Disallow: /
User-agent: lwp-trivial
Disallow: /
User-agent: BunnySlippers
Disallow: /
User-agent: Microsoft URL Control - 6.00.8169
Disallow: /
User-agent: URLy Warning
Disallow: /
User-agent: Wget/1.6
Disallow: /
User-agent: Wget/1.5.3
Disallow: /
User-agent: Wget
Disallow: /
User-agent: LinkWalker
Disallow: /
User-agent: cosmos
Disallow: /
User-agent: moget
Disallow: /
User-agent: hloader
Disallow: /
User-agent: humanlinks
Disallow: /
User-agent: LinkextractorPro
Disallow: /
User-agent: Offline Explorer
Disallow: /
User-agent: Mata Hari
Disallow: /
User-agent: LexiBot
Disallow: /
User-agent: Web Image Collector
Disallow: /
User-agent: The Intraformant
Disallow: /
User-agent: True_Robot/1.0
Disallow: /
User-agent: True_Robot
Disallow: /
User-agent: BlowFish/1.0
Disallow: /
User-agent: JennyBot
Disallow: /
User-agent: MIIxpc/4.2
Disallow: /
User-agent: BuiltBotTough
Disallow: /
User-agent: ProPowerBot/2.14
Disallow: /
User-agent: BackDoorBot/1.0
Disallow: /
User-agent: toCrawl/UrlDispatcher
Disallow: /
User-agent: WebEnhancer
Disallow: /
User-agent: suzuran
Disallow: /
User-agent: TightTwatBot
Disallow: /
User-agent: VCI WebViewer VCI WebViewer Win32
Disallow: /
User-agent: VCI
Disallow: /
User-agent: Szukacz/1.4
Disallow: /
User-agent: QueryN Metasearch
Disallow: /
User-agent: Openfind data gathere
Disallow: /
User-agent: Openfind
Disallow: /
User-agent: Xenu's Link Sleuth 1.1c
Disallow: /
User-agent: Xenu's
Disallow: /
User-agent: Zeus
Disallow: /
User-agent: RepoMonkey Bait & Tackle/v1.01
Disallow: /
User-agent: RepoMonkey
Disallow: /
User-agent: Microsoft URL Control
Disallow: /
User-agent: Openbot
Disallow: /
User-agent: URL Control
Disallow: /
User-agent: Zeus Link Scout
Disallow: /
User-agent: Zeus 32297 Webster Pro V2.9 Win32
Disallow: /
User-agent: Webster Pro
Disallow: /
User-agent: EroCrawler
Disallow: /
User-agent: LinkScan/8.1a Unix
Disallow: /
User-agent: Keyword Density/0.9
Disallow: /
User-agent: Kenjin Spider
Disallow: /
User-agent: Iron33/1.0.2
Disallow: /
User-agent: Bookmark search tool
Disallow: /
User-agent: GetRight/4.2
Disallow: /
User-agent: FairAd Client
Disallow: /
User-agent: Gaisbot
Disallow: /
User-agent: Aqua_Products
Disallow: /
User-agent: Radiation Retriever 1.1
Disallow: /
User-agent: WebmasterWorld Extractor
Disallow: /
User-agent: Flaming AttackBot
Disallow: /
User-agent: Oracle Ultra Search
Disallow: /
User-agent: MSIECrawler
Disallow: /
User-agent: PerMan
Disallow: /
User-agent: searchpreview
Disallow: /
User-agent: SEOprofiler Bot
Disallow: /
User-agent: FaceBook bot
Disallow: /
User-agent: archive.org bot
Disallow: /
User-agent: Web Core / Roots
Disallow: /
User-agent: Yahoo Slurp
Disallow: /
User-agent: FavIconizer
Disallow: /
User-agent: Linkdex
Disallow: /
User-agent: aiHitBot
Disallow: /
User-agent: aiHitBot/1.0
Disallow: /
User-agent: aiHitBot/1.1
Disallow: /
User-agent: Baiduspider+
Disallow: /
User-agent: Baiduspider+(+http://www.baidu.com/search/spider.htm)
Disallow: /
User-agent: Baiduspider/2.0;+http://www.baidu.com/search/spider.html
Disallow: /
User-agent: +Baiduspider
Disallow: /
User-agent: +Baiduspider/2.0
Disallow: /
User-agent: +Baiduspider/2.0;++http://www.baidu.com/search/spider.html
Disallow: /
User-agent: Mozilla/5.0(compatible; Baiduspider/2.0; +http://www.baidu.com/search/spider.html)
Disallow: /
User-agent: Mail.RU_Bot/2.0
Disallow: /
User-agent: Mail.RU
Disallow: /
User-agent: Mail.RU_Bot/2.0; +http://go.mail.ru/help/robots
Disallow: /
User-agent: Yandex/1.01.001
Disallow: /
User-agent: YandexBot/3.0-MirrorDetector
Disallow: /
User-agent: YandexImages/3.0
Disallow: /
User-agent: YandexSomething/1.
Disallow: /
User-agent: Yandex.com
Disallow: /
User-agent: YandexBot/3.0
Disallow: /
User-agent: SeznamBot
Disallow: /
User-agent: SeznamBot/1.0
Disallow: /
User-agent: SeznamBot/1.1
Disallow: /
#SeznamBot/3.0
User-agent: SeznamBot/3.0
Disallow: /
User-agent: Findxbot
Disallow: /
User-agent: Findxbot/1.0
Disallow: /
User-agent: meanpathbot
Disallow: /
User-agent: MegaIndex.ru
Disallow: /
User-agent: MegaIndex.ru/2.0
Disallow: /
User-agent: Mozilla/4.0 (CMS Crawler: http://www.cmscrawler.com)
Disallow: /
User-agent: Mozilla/4.0 (compatible; MSIE 4.01; Windows NT; MS Search 4.0 Robot)
Disallow: /
User-agent: Mozilla/4.0 (compatible; MSIE 6.0; Windows NT; MS Search 4.0 Robot)
Disallow: /
User-agent: Mozilla/4.0 (compatible; MSIE 4.01; Windows NT; MS Search 5.0 Robot)
Disallow: /
User-agent: Mozilla/4.0 (compatible; MSIE 6.0; Windows NT; MS Search 5.0 Robot)
Disallow: /
User-agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.0 ; ClarityDailyBot)
Disallow: /
User-agent: Mozilla/5.0 (compatible; 200PleaseBot/1.0; +http://www.200please.com/bot)
Disallow: /
User-agent: Mozilla/5.0 (compatible; AhrefsBot/5.0; +http://ahrefs.com/robot/)
Disallow: /
User-agent: Mozilla/5.0 (compatible; AOLbot/4.0; +http://www.aol-soft.com/)
Disallow: /
User-agent: Mozilla/5.0 (compatible; DomainAppender /1.0; +http://www.profound.net/domainappender)
Disallow: /
User-agent: Mozilla/5.0 (compatible; DomainSigmaCrawler/0.1; +http://domainsigma.com/robot)
Disallow: /
User-agent: Mozilla/5.0 (compatible; Findxbot/1.0; +http://www.findxbot.com)
Disallow: /
User-agent: Mozilla/5.0 (compatible; Genieo/1.0 http://www.genieo.com/webfilter.html)
Disallow: /
User-agent: Mozilla/5.0 (compatible; linkdexbot/2.0; +http://www.linkdex.com/bots/)
Disallow: /
User-agent: Mozilla/5.0 (compatible; meanpathbot/1.0; +http://www.meanpath.com/meanpathbot.html)
Disallow: /
User-agent: Mozilla/5.0 (compatible; MJ12bot/v1.4.5; http://www.majestic12.co.uk/bot.php?+)
Disallow: /
User-agent: Mozilla/5.0 (compatible; OpenHoseBot/2.1; +http://www.openhose.org/bot.html)
Disallow: /
User-agent: Mozilla/5.0 (compatible; PAD-bot/9.0; +http://www.descargarprogramagratis.com/)
Disallow: /
User-agent: Mozilla/5.0 (compatible; PaperLiBot/2.1; http://support.paper.li/entries/20023257-what-is-paper-li)
Disallow: /
User-agent: Mozilla/5.0 (compatible; SemrushBot-SI/0.97; +http://www.semrush.com/bot.html)
Disallow: /
User-agent: Mozilla/5.0 (compatible; SoftListBot/2.2; +http://www.softlist.us/)
Disallow: /
User-agent: Mozilla/5.0 (compatible; TweetedTimes Bot/1.0; +http://tweetedtimes.com)
Disallow: /
User-agent: Mozilla/5.0 (compatible; uMBot-LN/1.0; mailto: crawling@ubermetrics-technologies.com)
Disallow: /
User-agent: Mozilla/5.0 (compatible; XoviBot/2.0; +http://www.xovibot.net/)
Disallow: /
User-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:28.0) Gecko/20100101 Firefox/28.0 (FlipboardProxy/1.1; +http://flipboard.com/browserproxy)
Disallow: /
User-agent: Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.8.1.6) Gecko/20070725 Firefox/2.0.0.6 - James BOT - WebCrawler http://cognitiveseo.com/bot.html
Disallow: /
User-agent: Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.9.1.2) Gecko/20090729 Firefox/3.5.2 (.NET CLR 3.5.30729; Diffbot/0.1; +http://www.diffbot.com)
Disallow: /
User-agent: Mozilla/5.0 (Windows NT 6.2) Insitesbot/1.0
Disallow: /
User-agent: Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.2.1)
Disallow: /
User-agent: crawler4j (http://code.google.com/p/crawler4j/)
Disallow: /
User-agent: Mozilla/5.0 (compatible;acapbot/0.1;treat like Googlebot)
Disallow: /
User-agent: Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)
Disallow: /
User-agent: Pinterest/0.2 (+http://www.pinterest.com/bot.html)
Disallow: /
User-agent: Mozilla/5.0 (compatible; DotBot/1.1; http://www.opensiteexplorer.org/dotbot, help@moz.com)
Disallow: /
User-agent: Mozilla/5.0 (compatible; SemrushBot/1.2~bl; +http://www.semrush.com/bot.html)
Disallow: /
User-agent: Mozilla/5.0 (compatible; YandexBot/3.0; +http://yandex.com/bots)
Disallow: /
User-agent: netEstate NE Crawler (+http://www.website-datenbank.de/)
Disallow: /
User-agent: Mozilla/5.0 (compatible; WBSearchBot/1.1; +http://www.warebay.com/bot.html)
Disallow: /
User-agent: WBSearchBot
Disallow: /
User-agent: Mozilla/5.0 (compatible; LinkpadBot/1.07; +http://www.linkpad.ru)
Disallow: /
User-agent: Mozilla/5.0 (compatible; LinkpadBot/1.08; +http://www.linkpad.ru)
Disallow: /
User-agent: Mozilla/5.0 (compatible; LinkpadBot/1.12; +http://www.linkpad.ru)
Disallow: /
User-agent:Mozilla/5.0 (compatible; NetpeakCheckerBot/2.1; +https://netpeaksoftware.com/checker)
Disallow: /
User-agent:Mozilla/5.0 (compatible; adscanner/)
Disallow: /
User-agent:Mozilla/5.0 (compatible; SiteExplorer/1.1b; +http://siteexplorer.info/Backlink-Checker-Spider/)
Disallow: /
User-agent:Mozilla/5.0 (compatible; Cliqzbot/2.0; +http://cliqz.com/company/cliqzbot)
Disallow: /
User-agent: MauiBot
Disallow:/
User-agent: UbiCrawler
Disallow: /
User-agent: Mozilla/5.0 (compatible; SurdotlyBot/1.0; +http://sur.ly/bot.html)
Disallow:/
User-agent: LightspeedSystemsCrawler
Disallow:/
User-agent: facebot
Disallow: /
User-agent: facebookexternalhit/1.1
Disallow: /
User-agent: facebookexternalhit/1.0 (+http://www.facebook.com/externalhit_uatext.php)
Disallow: /
User-agent: facebookexternalhit/1.1 (+http://www.facebook.com/externalhit_uatext.php)
Disallow: /
User-agent: Mozilla/5.0 (compatible; DotBot/1.1; http://www.dotnetdotcom.org/, crawler@dotnetdotcom.org)
Disallow: /
User-agent: DotBot/1.1
Disallow: /
User-agent: BUbiNG
Disallow: /

# Sitemap
Sitemap: http://www.ekoce.pl/1_pl_0_sitemap.xml

