User-agent: *
Disallow: /admin/
Disallow: /auth/
Disallow: /my/
Disallow: /integrations/
Disallow: /ask4price/
Disallow: /notify/
Disallow: /order/
Disallow: /basket/
Disallow: /compare/
Disallow: /newsletter/
Disallow: /recommend/
Disallow: /kontakt/form/
Disallow: /ask4product/
Disallow: /repository/
Disallow: /autosuggest/
Disallow: /js/
Disallow: /images/
Disallow: /gfx/

Sitemap: http://www.dzidziak.pl/sitemap.xml
