User-agent: *
Disallow: /_arch/
Disallow: /admin/
Disallow: /bargraph/
Disallow: /flota/
Disallow: /include/
Disallow: /industry_testowy/
Disallow: /js/
Disallow: /kcounter/
Disallow: /login/
Disallow: /mw/
Disallow: /petersburg_old/
Disallow: /sailing/
Disallow: /search2t/
Disallow: /sessions/
Disallow: /test/
Disallow: /test_bm/
Disallow: /test_dk/
Disallow: /test_mb/
Disallow: /test_sr/
Disallow: /testlyout/
Disallow: /tmp/
Disallow: /wykresy/
Disallow: /events_robo/
Disallow: /kosz/
Disallow: /takeit/
Disallow: /events/indexm_robo.php
Disallow: conn_conf.php
Disallow: cron-daily.php
Disallow: cron-hourly.php

