User-agent: *
Disallow: /*?
Disallow: /*.php*
Disallow: /szczegolyTresciDruk.php
Disallow: /szczegolyDruk.php
Disallow: /przechowalnia.php
Disallow: /zapytaj.php
Disallow: /porownanie.php
Disallow: /powiadomZnajomego.php
Disallow: /koszyk.php
Disallow: /start,0,0.html
Allow: /szczegolyTresci.php?id=*
