User-agent: *
Disallow: /sitecore/
Disallow: /ca/page-not-found/
Disallow: /da/dk/blog/algoritmer-data-back-to-basics-og-kommende-features/
Disallow: /da/dk/losninger/intelligent-content-82d6c/
Disallow: /da/dk/losninger/intelligent-content/
Disallow: /da/dk/vores-arbejde/best-travel/
Disallow: /da/dk/vores-arbejde/bki/
Disallow: /da/dk/vores-arbejde/general-motors/
Disallow: /da/dk/vores-arbejde/jysk/
Disallow: /da/dk/vores-team/dan-hagen/
Disallow: /da/page-not-found/
Disallow: /de/at/unser-team/dan-hagen/
Disallow: /de/ch/ourteam/dan-hagen/
Disallow: /de/ch/solutions/intelligent-content/
Disallow: /de/de/presse/iprospect-setzt-fokus-auf-datengesteuerte-strategien-fur-werbetreibende-und-starkt-das-globale-fuhrungsteam/
Disallow: /de/de/unser-team/dan-hagen/
Disallow: /de/de/unsere-arbeit/coca-cola/
Disallow: /de/page-not-found/
Disallow: /en/ae/careers/available-jobs/senior-account-manager/
Disallow: /en/ae/insights/whitepapers/future-forecast-2016/
Disallow: /en/ae/our-team/dan-hagen/
Disallow: /en/ae/solutions/intelligent-content/
Disallow: /en/ar/insights/whitepapers/future-forecast-2017-741fe/
Disallow: /en/ar/insights/whitepapers/future-forecast-2017/
Disallow: /en/ar/insights/whitepapers/the-rise-of-digital-aisistants-150e0/
Disallow: /en/ar/insights/whitepapers/the-rise-of-digital-aisistants/
Disallow: /en/ar/our-team/dan-hagen/
Disallow: /en/ar/solutions/intelligent-content/
Disallow: /en/at/our-team/dan-hagen/
Disallow: /en/at/solutions/intelligent-content/
Disallow: /en/at/what-we-do/copy-of-solutions/intelligent-content-v2/
Disallow: /en/au/our-team/dan-hagen/
Disallow: /en/au/solutions/intelligent-content/
Disallow: /en/be/our-team/dan-hagen/
Disallow: /en/be/solutions/intelligent-content/
Disallow: /en/bg/insights/whitepapers/future-forecast-2016/
Disallow: /en/bg/our-team/dan-hagen/
Disallow: /en/bg/solutions/intelligent-content/
Disallow: /en/ca/furniture-stores/
Disallow: /en/ca/insights/whitepapers/future-focus-2016/
Disallow: /en/ca/insights/whitepapers/future-focus-2017/
Disallow: /en/ca/lawyers/
Disallow: /en/ca/online-to-offline/
Disallow: /en/ca/press-room/bonlook-partners-with-iprospect-for-its-omni-channel-marketing-strategy/
Disallow: /en/ca/press-room/iprospect-agency-of-the-year-at-bing-agency-awards/
Disallow: /en/ca/press-room/iprospect-canada-appoints-dan-kalinski-as-chief-executive-officer/
Disallow: /en/ca/press-room/iprospect-canada-wins-big-at-the-bing-agency-awards/
Disallow: /en/ca/press-room/iprospect-recognized-as-a-top-company-worldwide-for-millennial-woman-by-mogul/
Disallow: /en/ca/solutions/intelligent-content/
Disallow: /en/ca/team/dan-hagen/
Disallow: /en/ca/terms-of-service/
Disallow: /en/ch/our-team/dan-hagen/
Disallow: /en/ch/solutions/intelligent-content/
Disallow: /en/cl/careers/available-jobs/
Disallow: /en/cl/insights/whitepapers/future-forecast-2017/
Disallow: /en/cl/insights/whitepapers/the-rise-of-digital-aisistants/
Disallow: /en/cl/our-blog/
Disallow: /en/cl/our-team/dan-hagen/
Disallow: /en/cl/solutions/intelligent-content/
Disallow: /en/cn/our-team/dan-hagen/
Disallow: /en/cn/solutions/intelligent-content/
Disallow: /en/co/insights/whitepapers/future-forecast-2017/
Disallow: /en/co/insights/whitepapers/the-rise-of-digital-aisistants/
Disallow: /en/co/our-blog/
Disallow: /en/co/our-team/dan-hagen/
Disallow: /en/co/solutions/intelligent-content/
Disallow: /en/cz/our-team/dan-hagen/
Disallow: /en/cz/solutions/intelligent-content/
Disallow: /en/ee/insights/whitepapers/future-forecast-2016/
Disallow: /en/ee/our-team/dan-hagen/
Disallow: /en/ee/solutions/intelligent-content/
Disallow: /en/es/our-team/dan-hagen/
Disallow: /en/es/solutions/co-op/
Disallow: /en/es/solutions/intelligent-content/
Disallow: /en/female-foundry/resource/ca/hhv-apac-2016/
Disallow: /en/female-foundry/resource/ca/hhv-latam/
Disallow: /en/female-foundry/resource/ca/the-story-so-far/
Disallow: /en/female-foundry/resource/ca/the-voice-of-2000/
Disallow: /en/female-foundry/resource/copy-of-ca/the-story-so-far/
Disallow: /en/female-foundry/resource/copy-of-us/the-story-so-far/
Disallow: /en/female-foundry/resource/mx/hhv-apac-2016/
Disallow: /en/female-foundry/resource/mx/hhv-latam/
Disallow: /en/female-foundry/resource/mx/the-voice-of-2000/
Disallow: /en/female-foundry/resource/sg/hhv-apac-2016/
Disallow: /en/female-foundry/resource/sg/hhv-latam/
Disallow: /en/female-foundry/resource/sg/the-voice-of-2000/
Disallow: /en/female-foundry/resource/us/hhv-apac-2016/
Disallow: /en/female-foundry/resource/us/hhv-latam/
Disallow: /en/female-foundry/resource/us/the-story-so-far/
Disallow: /en/female-foundry/resource/us/the-voice-of-2000/
Disallow: /en/female-foundry/resource/za/hhv-apac-2016/
Disallow: /en/female-foundry/resource/za/hhv-latam/
Disallow: /en/female-foundry/resource/za/the-story-so-far/
Disallow: /en/female-foundry/resource/za/the-voice-of-2000/
Disallow: /en/gb/blog/cross-device-tracking-and-integration/
Disallow: /en/gb/blog/what-does-stories-mean-for-the-future-of-instagram/
Disallow: /en/gb/blog/while-shepherds-watched/
Disallow: /en/gb/landing-page-uk-custom/
Disallow: /en/gb/our-team/dan-hagen/
Disallow: /en/gb/press-room/what-next-for-the-media-industry-2016-revealed-part-2/
Disallow: /en/gb/privacy-notice/
Disallow: /en/gb/solutions/intelligent-content/
Disallow: /en/gb/upcoming-events/
Disallow: /en/gb/what-we-do/services/consult/
Disallow: /en/gb/what-we-do/services/engagement/
Disallow: /en/gb/what-we-do/services/google-analytics-premium/
Disallow: /en/global/insights/
Disallow: /en/global/insights/whitepapers/a-new-era-of-content/
Disallow: /en/global/insights/whitepapers/future-forecast-2016/
Disallow: /en/global/insights/whitepapers/the-international-business-traveler/
Disallow: /en/global/press-room/australia-wins-a-best-content-strategy-award-at-2017-content-marketing-awards/
Disallow: /en/global/press-room/corrected-chris-whitelaw-promoted-to-president-of-emea/
Disallow: /en/global/press-room/discover-iprospect-campaign-release/
Disallow: /en/global/press-room/iprospect-and-isobar-partner-with-diageo-at-cannes/
Disallow: /en/global/press-room/iprospect-enterprise-a-b2b-think-tank/
Disallow: /en/global/press-room/iprospect-given-two-top-awards-at-2017-international-performance-marketing-awards/
Disallow: /en/global/press-room/iprospect-launches-30-x-30-at-cannes-lions-2017/
Disallow: /en/global/press-room/iprospect-most-shorlisted-in-google-premier-partner-awards/
Disallow: /en/global/press-room/iprospect-named-top-global-search-and-activation-agency-a5c6f/
Disallow: /en/global/press-room/iprospect-named-top-global-search-and-activation-agency-e1bf6/
Disallow: /en/global/press-room/iprospect-nl-awarded-with-european-agency-of-the-year-by-bing/
Disallow: /en/global/press-room/iprospect-recognized-as-a-top-company-worldwide-for-millennial-woman-by-mogul/
Disallow: /en/global/press-room/iprospect-reinforces-focus-on-data-driven-client-strategies-strengthens-global-executive-team/
Disallow: /en/global/press-room/iprospect-releases-2018-future-focus-the-new-machine-rules/
Disallow: /en/global/press-room/iprospect-releases-the-future-is-voice-activated-asia-pacific-research/
Disallow: /en/global/press-room/iprospect-valuklik-announcement/
Disallow: /en/global/press-room/iprospect-win-big-at-bing-agency-awards-2018/
Disallow: /en/global/press-room/iprospect-wins-agency-of-the-year-at-inaugural-peak-performance-marketing-awards/
Disallow: /en/global/press-room/iprospect-wins-at-festival-of-media-global-awards/
Disallow: /en/global/press-room/iprospect-wins-big-at-bing-agency-awards/
Disallow: /en/global/press-room/misty-locke-wins-lifetime-achievement-award/
Disallow: /en/global/press-room/mobile-world-congress-2017-barcelona/
Disallow: /en/global/press-room/new-nl-md-saskia/
Disallow: /en/global/press-room/rohan-philips-named-to-iprospect-global-team/
Disallow: /en/global/press-room/ruth-stubbs-promoted-to-global-president-of-iprospect/
Disallow: /en/global/press-room/sxsw-voting/
Disallow: /en/global/press-room/the-global-business-performance-agency/
Disallow: /en/global/press-room/twitter-studio-release/
Disallow: /en/global/team/dan-hagen/
Disallow: /en/global/what-we-do/solutions/intelligent-content/
Disallow: /en/gr/insights/whitepapers/future-forecast-2016/
Disallow: /en/gr/our-team/dan-hagen/
Disallow: /en/gr/our-team/misty-locke/
Disallow: /en/gr/solutions/intelligent-content/
Disallow: /en/hk/insights/whitepapers/future-forecast-2016/
Disallow: /en/hk/our-team/dan-hagen/
Disallow: /en/hk/solutions/intelligent-content/
Disallow: /en/hr/blog/authors/iprospect/
Disallow: /en/hr/our-team/dan-hagen/
Disallow: /en/hr/page-not-found/
Disallow: /en/hr/solutions/intelligent-content/
Disallow: /en/hr/upcoming-events/programmatic-day/
Disallow: /en/id/insights/whitepapers/future-forecast-2016/
Disallow: /en/id/our-team/dan-hagen/
Disallow: /en/id/press-room/
Disallow: /en/id/press-room/read-more/
Disallow: /en/id/solutions/intelligent-content/
Disallow: /en/ie/our-blog/12-eoy-series-cro-in-2016/
Disallow: /en/ie/our-blog/12-seo-and-content-year-in-review/
Disallow: /en/ie/our-team/dan-hagen/
Disallow: /en/ie/solutions/intelligent-content/
Disallow: /en/il/insights/whitepapers/future-forecast-2016/
Disallow: /en/il/our-team/dan-hagen/
Disallow: /en/il/page-not-found/
Disallow: /en/il/solutions/intelligent-content/
Disallow: /en/in/insights/whitepapers/future-forecast-2016/
Disallow: /en/in/insights/whitepapers/golden-geeks-e-book/
Disallow: /en/in/our-team/dan-hagen/
Disallow: /en/in/solutions/intelligent-content/
Disallow: /en/it/insights/whitepapers/future-focus-2019/
Disallow: /en/it/our-team/dan-hagen/
Disallow: /en/it/solutions/intelligent-content/
Disallow: /en/jp/hello-clavis-insight/
Disallow: /en/jp/insights/
Disallow: /en/jp/insights/whitepapers/a-new-era-of-content/
Disallow: /en/jp/insights/whitepapers/future-forecast-2016/
Disallow: /en/jp/insights/whitepapers/the-international-business-traveler/
Disallow: /en/jp/our-team/dan-hagen/
Disallow: /en/jp/press-room/clavis-iprospect-partnership/
Disallow: /en/jp/press-room/sprinklr-iprospect-partnership/
Disallow: /en/jp/products/content-and-creative/
Disallow: /en/jp/products/conversion-optimization/
Disallow: /en/jp/products/data-analytics/
Disallow: /en/jp/products/mobile-strategy/
Disallow: /en/jp/services-agreement/
Disallow: /en/jp/solutions/intelligent-content/
Disallow: /en/jp/what-we-do/
Disallow: /en/jp/what-we-do/copy-of-services/conversion-optimization/
Disallow: /en/jp/what-we-do/copy-of-services/mobile-strategy/
Disallow: /en/jp/who-we-are/
Disallow: /en/ke/furniture-stores/
Disallow: /en/ke/insights/whitepapers/future-focus-2016/
Disallow: /en/ke/insights/whitepapers/future-focus-2017/
Disallow: /en/ke/lawyers/
Disallow: /en/ke/online-to-offline/
Disallow: /en/ke/solutions/intelligent-content/
Disallow: /en/ke/team/dan-hagen/
Disallow: /en/ke/terms-of-service/
Disallow: /en/kr/dan-hagen/
Disallow: /en/kr/our-team/jin-choi/
Disallow: /en/kr/products/display/
Disallow: /en/kr/solutions/intelligent-content/
Disallow: /en/kr/who-we-are/discover/
Disallow: /en/lt/insights/whitepapers/future-focus-2019/
Disallow: /en/lt/insights/whitepapers/future-forecast-2016/
Disallow: /en/lt/our-team/dan-hagen/
Disallow: /en/lt/solutions/intelligent-content/
Disallow: /en/lv/careers/available-jobs/head-of-seo/
Disallow: /en/lv/insights/povs/one-click-social-commerce/
Disallow: /en/lv/our-team/dan-hagen/
Disallow: /en/lv/our-team/linda-konovalova/
Disallow: /en/lv/solutions/intelligent-content/
Disallow: /en/mx/careers/available-jobs/
Disallow: /en/mx/insights/whitepapers/future-forecast-2017/
Disallow: /en/mx/insights/whitepapers/the-rise-of-digital-aisistants/
Disallow: /en/mx/our-blog/
Disallow: /en/mx/our-team/dan-hagen/
Disallow: /en/mx/solutions/intelligent-content/
Disallow: /en/my/insights/whitepapers/future-forecast-2016/
Disallow: /en/my/our-team/dan-hagen/
Disallow: /en/my/solutions/intelligent-content/
Disallow: /en/nl/insights/povs/paid-search-trends-2017-q3/
Disallow: /en/nl/our-team/dan-hagen/
Disallow: /en/nl/press-room/iprospect-given-two-top-awards-at-2017-international-performance-marketing-awards/
Disallow: /en/nl/press-room/iprospect-recognized-as-a-top-company-worldwide-for-millennial-woman-by-mogul/
Disallow: /en/nl/solutions/intelligent-content/
Disallow: /en/nz/insights/whitepapers/future-forecast-2016/
Disallow: /en/nz/our-team/dan-hagen/
Disallow: /en/nz/solutions/intelligent-content/
Disallow: /en/page-not-found/
Disallow: /en/ph/insights/whitepapers/future-forecast-2016/
Disallow: /en/ph/our-team/dan-hagen/
Disallow: /en/ph/solutions/intelligent-content/
Disallow: /en/pt/our-team/dan-hagen/
Disallow: /en/pt/our-team/marta-chaves/
Disallow: /en/pt/our-team/pedro-goncalves/
Disallow: /en/pt/our-team/rita-pereira/
Disallow: /en/pt/our-team/vanessa-reguengos/
Disallow: /en/pt/solutions/intelligent-content/
Disallow: /en/ro/insights/whitepapers/future-forecast-2016/
Disallow: /en/ro/our-team/dan-hagen/
Disallow: /en/ro/solutions/intelligent-content/
Disallow: /en/ru/our-team/dan-hagen/
Disallow: /en/ru/solutions/intelligent-content/
Disallow: /en/sg/our-team/dan-hagen/
Disallow: /en/sg/our-team/omkar-gurjar/
Disallow: /en/sg/press-room/
Disallow: /en/sg/solutions/intelligent-content/
Disallow: /en/sg/who-we-are/discover/
Disallow: /en/sk/our-team/dan-hagen/
Disallow: /en/sk/our-team/jozef-sajdik/
Disallow: /en/sk/our-team/miroslav-filip/
Disallow: /en/sk/solutions/intelligent-content/
Disallow: /en/th/insights/whitepapers/future-forecast-2016/
Disallow: /en/th/our-team/dan-hagen/
Disallow: /en/th/solutions/intelligent-content/
Disallow: /en/tr/
Disallow: /en/tw/our-blog/2016/amp-html/
Disallow: /en/tw/our-blog/2018/facebook-ads-49c4f/
Disallow: /en/tw/our-blog/2018/facebook-ads-5db2d/
Disallow: /en/tw/our-blog/2018/facebook-ads-dbafb/
Disallow: /en/tw/our-blog/2018/facebook-ads/
Disallow: /en/tw/our-blog/facebook-ads/
Disallow: /en/tw/our-team/dan-hagen/
Disallow: /en/tw/our-team/john-ku/
Disallow: /en/tw/press-room/iprospect-recognized-as-a-top-company-worldwide-for-millennial-woman-by-mogul/
Disallow: /en/tw/solutions/intelligent-content/
Disallow: /en/us/2015-forrester-groundswell-award-nomination/
Disallow: /en/us/bank-of-america-and-iprospect-best-seo-campaign/
Disallow: /en/us/chevrolet-and-iprospect-best-seo-campaign/
Disallow: /en/us/hilton-and-iprospect-best-search-campaign/
Disallow: /en/us/insights/infographics/holidays-2012/
Disallow: /en/us/insights/povs/google-elevates-https-from-recommendation-to-ranking-signal/
Disallow: /en/us/insights/povs/google-launches-estimated-cross-device-update/
Disallow: /en/us/insights/povs/paid-search-trends-2017-q3/
Disallow: /en/us/intel-and-iprospect-best-search-campaign/
Disallow: /en/us/iprospect-and-under-armour-best-social-campaign/
Disallow: /en/us/lids-and-iprospect-best-search-campaign/
Disallow: /en/us/media-authorization-terms-and-conditions/
Disallow: /en/us/our-team/dan-hagen/
Disallow: /en/us/our-team/jon-leicht/
Disallow: /en/us/the-limited-and-iprospect-best-search-campaign/
Disallow: /en/us/upcoming-events/2015-client-summit/
Disallow: /en/us/upcoming-events/2018-iprospect-client-summit/
Disallow: /en/za/insights/whitepapers/future-forecast-2016/
Disallow: /en/za/our-team/dan-hagen/
Disallow: /en/za/products/google-analytics-premium/
Disallow: /en/za/solutions/intelligent-content/
Disallow: /en/za/what-we-do/copy-of-services/google-analytics-premium/
Disallow: /es/ar/insights/whitepapers/future-forecast-2017/
Disallow: /es/ar/insights/whitepapers/the-rise-of-digital-aisistants/
Disallow: /es/ar/ourteam/dan-hagen/
Disallow: /es/ar/solutions/intelligent-content/
Disallow: /es/cl/careers/job-list/
Disallow: /es/cl/insights/whitepapers/future-forecast-2017/
Disallow: /es/cl/insights/whitepapers/the-rise-of-digital-aisistants/
Disallow: /es/cl/our-blog/
Disallow: /es/cl/ourteam/dan-hagen/
Disallow: /es/cl/solutions/intelligent-content/
Disallow: /es/co/insights/whitepapers/future-forecast-2017/
Disallow: /es/co/insights/whitepapers/the-rise-of-digital-aisistants/
Disallow: /es/co/our-blog/
Disallow: /es/co/ourteam/dan-hagen/
Disallow: /es/co/solutions/intelligent-content/
Disallow: /es/es/blog/evolucion-del-ecommerce/
Disallow: /es/es/nuestro-equipo/dan-hagen/
Disallow: /es/es/sala-de-prensa/
Disallow: /es/es/soluciones/co-op/
Disallow: /es/es/soluciones/intelligent-content/
Disallow: /es/mx/careers/job-list/
Disallow: /es/mx/insights/whitepapers/future-forecast-2017/
Disallow: /es/mx/insights/whitepapers/the-rise-of-digital-aisistants/
Disallow: /es/mx/our-blog/
Disallow: /es/mx/ourteam/dan-hagen/
Disallow: /es/mx/solutions/intelligent-content/
Disallow: /es/page-not-found/
Disallow: /et/page-not-found/
Disallow: /fi/fi/solutions/intelligent-content/
Disallow: /fi/fi/tiimimme/dan-hagen/
Disallow: /fi/page-not-found/
Disallow: /fr/be/notre-equipe/dan-hagen/
Disallow: /fr/ca/avocats/
Disallow: /fr/ca/detaillants-meubles/
Disallow: /fr/ca/en-ligne-hors-ligne/
Disallow: /fr/ca/equipe/dan-hagen/
Disallow: /fr/ca/ressources/whitepapers/future-focus-2016/
Disallow: /fr/ca/ressources/whitepapers/future-focus-2017/
Disallow: /fr/ca/salle-de-presse/bonlook-sassocie-a-iprospect-pour-sa-strategie-marketing-omnicanale/
Disallow: /fr/ca/salle-de-presse/iprospect-canada-nomme-dan-kalinski-au-poste-de-chef-de-la-direction-de-iprospect-canada/
Disallow: /fr/ca/salle-de-presse/iprospect-canada-nommee-agence-de-lannee-aux-bing-agency-awards/
Disallow: /fr/ca/salle-de-presse/iprospect-canada-remporte-le-prix-de-lagence-de-lannee/
Disallow: /fr/ca/salle-de-presse/iprospect-reconnue-comme-lune-des-meilleures-entreprises-au-monde-pour-les-femmes-millenaires-par-mogul/
Disallow: /fr/ca/solutions/contenu-intelligent/
Disallow: /fr/ca/termes-de-service/
Disallow: /fr/fr/notre-equipe/dan-hagen/
Disallow: /fr/fr/presse/iprospect-renforce-son-equipe-de-direction-monde-pour-delivrer-des-strategies-data-driven-toujours-plus-performantes/
Disallow: /fr/fr/presse/scan-tv/
Disallow: /fr/page-not-found/
Disallow: /hi/page-not-found/
Disallow: /hr/hr/blog/our-authors/iprospect/
Disallow: /hr/hr/solutions/intelligent-content/
Disallow: /hr/hr/tim/dan-hagen/
Disallow: /hu/hu/ourteam/dan-hagen/
Disallow: /hu/page-not-found/
Disallow: /id/page-not-found/
Disallow: /it/it/ilteam/dan-hagen/
Disallow: /it/it/insights/whitepapers/future-focus-2019/
Disallow: /it/it/solutions/intelligent-content/
Disallow: /it/page-not-found/
Disallow: /ja/page-not-found/
Disallow: /ko/kr/dan-hagen/
Disallow: /ko/kr/ourteam/jin-choi/
Disallow: /ko/kr/products/display/
Disallow: /ko/kr/solutions/intelligent-content/
Disallow: /ko/kr/whoweare/discover/
Disallow: /ko/page-not-found/
Disallow: /lt/page-not-found/
Disallow: /lv/lv/jaunumi/povs/one-click-social-commerce/
Disallow: /lv/lv/karjera/vakances/junior-digital-performance-specialist/
Disallow: /lv/lv/karjera/vakances/performance-specialist/
Disallow: /lv/lv/musu-komanda/dan-hagen/
Disallow: /lv/lv/musu-komanda/linda-konovalova/
Disallow: /lv/page-not-found/
Disallow: /ms/page-not-found/
Disallow: /nl/be/ons-team/dan-hagen/
Disallow: /nl/nl/insights/povs/paid-search-trends-2017-q3/
Disallow: /nl/nl/ons-team/dan-hagen/
Disallow: /nl/nl/onze-blog/wat-elke-marketeer-moet-weten-volgens-byron-sharp/
Disallow: /nl/nl/solutions/intelligent-content/
Disallow: /nl/page-not-found/
Disallow: /no/no/blog/2015-video-annonsenes-aar/
Disallow: /no/no/insights/povs/google-elevates-https-from-recommendation-to-ranking-signal/
Disallow: /no/no/konverteringsside-for-kurs/
Disallow: /no/no/our-team/dan-hagen/
Disallow: /no/page-not-found/
Disallow: /pl/page-not-found/
Disallow: /pl/pl/nasz-zespol/dan-hagen/
Disallow: /pl/pl/produktow/data-analytics/
Disallow: /pt/br/blog/autor/andy-edmonds/
Disallow: /pt/br/insights/whitepapers/future-focus-2016/
Disallow: /pt/br/nosso-time/dan-hagen/
Disallow: /pt/br/solutions/intelligent-content/
Disallow: /pt/page-not-found/
Disallow: /pt/pt/a-nossa-equipa/dan-hagen/
Disallow: /pt/pt/a-nossa-equipa/marta-chaves/
Disallow: /pt/pt/a-nossa-equipa/pedro-goncalves/
Disallow: /pt/pt/a-nossa-equipa/rita-pereira/
Disallow: /pt/pt/a-nossa-equipa/vanessa-reguengos/
Disallow: /ro/page-not-found/
Disallow: /ru/page-not-found/
Disallow: /ru/ru/ourteam/dan-hagen/
Disallow: /ru/ru/solutions/intelligent-content/
Disallow: /sk/page-not-found/
Disallow: /sk/sk/ourteam/dan-hagen/
Disallow: /sk/sk/ourteam/jozef-sajdik/
Disallow: /sk/sk/ourteam/miroslav-filip/
Disallow: /sv/page-not-found/
Disallow: /sv/se/blogg/analyticsdagarna-2017/
Disallow: /sv/se/produkter/digital-content-marketing/
Disallow: /th/page-not-found/
Disallow: /tr/page-not-found/
Disallow: /tr/tr/ekibimiz/dan-hagen/
Disallow: /tr/tr/ekibimiz/global-ekibimiz/ruth-stubbs/
Disallow: /tr/tr/page-not-found/
Disallow: /zh/cn/ourteam/dan-hagen/
Disallow: /zh/page-not-found/
Disallow: /zh/tw/our-blog/2016/amp-html-f01a4/
Disallow: /zh/tw/our-blog/2016/amp-html/
Disallow: /zh/tw/our-blog/2018/2018-experience-expo/
Disallow: /zh/tw/our-blog/2018/data-and-machine-learning/
Disallow: /zh/tw/our-blog/2018/facebook-ads/
Disallow: /zh/tw/our-blog/2018/keeping-ahead-in-the-race-of-ai-and-data-competition-49c4f/
Disallow: /zh/tw/our-blog/e-sports-competition/
Disallow: /zh/tw/ourteam/dan-hagen/
Disallow: /zh/tw/ourteam/john-ku/
Disallow: /zh/tw/press-room/2019-iprospect-intern/
Disallow: /zh/tw/press-room/iprospect-recognized-as-a-top-company-worldwide-for-millennial-woman-by-mogul/
Disallow: /zh/tw/press-room/iprospect-tw-and-sg-take-home-4-awards-at-the-drum-digital-trading-awards-apac-2018/
Disallow: /zh/tw/press-room/iprospect-tw-take-home-digital-marketing-award-of-2018-agency-and-advertiser-of-the-year/
Disallow: /zh/tw/press-room/iprospect-tw-take-home-innovation-technology-award-of-the-year-at-digital-singularity-awards/
Disallow: /zh/tw/solutions/intelligent-content/
Disallow: /cs/cz/ourteam/dan-hagen/
Disallow: /cs/page-not-found/

User-agent: CoveoEnterpriseSearch
Disallow: /sitecore/
Disallow: /coveo/
Disallow: /ca/page-not-found/
Disallow: /da/dk/blog/algoritmer-data-back-to-basics-og-kommende-features/
Disallow: /da/dk/losninger/intelligent-content-82d6c/
Disallow: /da/dk/losninger/intelligent-content/
Disallow: /da/dk/vores-arbejde/best-travel/
Disallow: /da/dk/vores-arbejde/bki/
Disallow: /da/dk/vores-arbejde/general-motors/
Disallow: /da/dk/vores-arbejde/jysk/
Disallow: /da/dk/vores-team/dan-hagen/
Disallow: /da/page-not-found/
Disallow: /de/at/unser-team/dan-hagen/
Disallow: /de/ch/ourteam/dan-hagen/
Disallow: /de/ch/solutions/intelligent-content/
Disallow: /de/de/presse/iprospect-setzt-fokus-auf-datengesteuerte-strategien-fur-werbetreibende-und-starkt-das-globale-fuhrungsteam/
Disallow: /de/de/unser-team/dan-hagen/
Disallow: /de/de/unsere-arbeit/coca-cola/
Disallow: /de/page-not-found/
Disallow: /en/ae/careers/available-jobs/senior-account-manager/
Disallow: /en/ae/insights/whitepapers/future-forecast-2016/
Disallow: /en/ae/our-team/dan-hagen/
Disallow: /en/ae/solutions/intelligent-content/
Disallow: /en/ar/insights/whitepapers/future-forecast-2017-741fe/
Disallow: /en/ar/insights/whitepapers/future-forecast-2017/
Disallow: /en/ar/insights/whitepapers/the-rise-of-digital-aisistants-150e0/
Disallow: /en/ar/insights/whitepapers/the-rise-of-digital-aisistants/
Disallow: /en/ar/our-team/dan-hagen/
Disallow: /en/ar/solutions/intelligent-content/
Disallow: /en/at/our-team/dan-hagen/
Disallow: /en/at/solutions/intelligent-content/
Disallow: /en/at/what-we-do/copy-of-solutions/intelligent-content-v2/
Disallow: /en/au/our-team/dan-hagen/
Disallow: /en/au/solutions/intelligent-content/
Disallow: /en/be/our-team/dan-hagen/
Disallow: /en/be/solutions/intelligent-content/
Disallow: /en/bg/insights/whitepapers/future-forecast-2016/
Disallow: /en/bg/our-team/dan-hagen/
Disallow: /en/bg/solutions/intelligent-content/
Disallow: /en/ca/furniture-stores/
Disallow: /en/ca/insights/whitepapers/future-focus-2016/
Disallow: /en/ca/insights/whitepapers/future-focus-2017/
Disallow: /en/ca/lawyers/
Disallow: /en/ca/online-to-offline/
Disallow: /en/ca/press-room/bonlook-partners-with-iprospect-for-its-omni-channel-marketing-strategy/
Disallow: /en/ca/press-room/iprospect-agency-of-the-year-at-bing-agency-awards/
Disallow: /en/ca/press-room/iprospect-canada-appoints-dan-kalinski-as-chief-executive-officer/
Disallow: /en/ca/press-room/iprospect-canada-wins-big-at-the-bing-agency-awards/
Disallow: /en/ca/press-room/iprospect-recognized-as-a-top-company-worldwide-for-millennial-woman-by-mogul/
Disallow: /en/ca/solutions/intelligent-content/
Disallow: /en/ca/team/dan-hagen/
Disallow: /en/ca/terms-of-service/
Disallow: /en/ch/our-team/dan-hagen/
Disallow: /en/ch/solutions/intelligent-content/
Disallow: /en/cl/careers/available-jobs/
Disallow: /en/cl/insights/whitepapers/future-forecast-2017/
Disallow: /en/cl/insights/whitepapers/the-rise-of-digital-aisistants/
Disallow: /en/cl/our-blog/
Disallow: /en/cl/our-team/dan-hagen/
Disallow: /en/cl/solutions/intelligent-content/
Disallow: /en/cn/our-team/dan-hagen/
Disallow: /en/cn/solutions/intelligent-content/
Disallow: /en/co/insights/whitepapers/future-forecast-2017/
Disallow: /en/co/insights/whitepapers/the-rise-of-digital-aisistants/
Disallow: /en/co/our-blog/
Disallow: /en/co/our-team/dan-hagen/
Disallow: /en/co/solutions/intelligent-content/
Disallow: /en/cz/our-team/dan-hagen/
Disallow: /en/cz/solutions/intelligent-content/
Disallow: /en/ee/insights/whitepapers/future-forecast-2016/
Disallow: /en/ee/our-team/dan-hagen/
Disallow: /en/ee/solutions/intelligent-content/
Disallow: /en/es/our-team/dan-hagen/
Disallow: /en/es/solutions/co-op/
Disallow: /en/es/solutions/intelligent-content/
Disallow: /en/female-foundry/resource/ca/hhv-apac-2016/
Disallow: /en/female-foundry/resource/ca/hhv-latam/
Disallow: /en/female-foundry/resource/ca/the-story-so-far/
Disallow: /en/female-foundry/resource/ca/the-voice-of-2000/
Disallow: /en/female-foundry/resource/copy-of-ca/the-story-so-far/
Disallow: /en/female-foundry/resource/copy-of-us/the-story-so-far/
Disallow: /en/female-foundry/resource/mx/hhv-apac-2016/
Disallow: /en/female-foundry/resource/mx/hhv-latam/
Disallow: /en/female-foundry/resource/mx/the-voice-of-2000/
Disallow: /en/female-foundry/resource/sg/hhv-apac-2016/
Disallow: /en/female-foundry/resource/sg/hhv-latam/
Disallow: /en/female-foundry/resource/sg/the-voice-of-2000/
Disallow: /en/female-foundry/resource/us/hhv-apac-2016/
Disallow: /en/female-foundry/resource/us/hhv-latam/
Disallow: /en/female-foundry/resource/us/the-story-so-far/
Disallow: /en/female-foundry/resource/us/the-voice-of-2000/
Disallow: /en/female-foundry/resource/za/hhv-apac-2016/
Disallow: /en/female-foundry/resource/za/hhv-latam/
Disallow: /en/female-foundry/resource/za/the-story-so-far/
Disallow: /en/female-foundry/resource/za/the-voice-of-2000/
Disallow: /en/gb/blog/cross-device-tracking-and-integration/
Disallow: /en/gb/blog/what-does-stories-mean-for-the-future-of-instagram/
Disallow: /en/gb/blog/while-shepherds-watched/
Disallow: /en/gb/landing-page-uk-custom/
Disallow: /en/gb/our-team/dan-hagen/
Disallow: /en/gb/press-room/what-next-for-the-media-industry-2016-revealed-part-2/
Disallow: /en/gb/privacy-notice/
Disallow: /en/gb/solutions/intelligent-content/
Disallow: /en/gb/upcoming-events/
Disallow: /en/gb/what-we-do/services/consult/
Disallow: /en/gb/what-we-do/services/engagement/
Disallow: /en/gb/what-we-do/services/google-analytics-premium/
Disallow: /en/global/insights/
Disallow: /en/global/insights/whitepapers/a-new-era-of-content/
Disallow: /en/global/insights/whitepapers/future-forecast-2016/
Disallow: /en/global/insights/whitepapers/the-international-business-traveler/
Disallow: /en/global/press-room/australia-wins-a-best-content-strategy-award-at-2017-content-marketing-awards/
Disallow: /en/global/press-room/corrected-chris-whitelaw-promoted-to-president-of-emea/
Disallow: /en/global/press-room/discover-iprospect-campaign-release/
Disallow: /en/global/press-room/iprospect-and-isobar-partner-with-diageo-at-cannes/
Disallow: /en/global/press-room/iprospect-enterprise-a-b2b-think-tank/
Disallow: /en/global/press-room/iprospect-given-two-top-awards-at-2017-international-performance-marketing-awards/
Disallow: /en/global/press-room/iprospect-launches-30-x-30-at-cannes-lions-2017/
Disallow: /en/global/press-room/iprospect-most-shorlisted-in-google-premier-partner-awards/
Disallow: /en/global/press-room/iprospect-named-top-global-search-and-activation-agency-a5c6f/
Disallow: /en/global/press-room/iprospect-named-top-global-search-and-activation-agency-e1bf6/
Disallow: /en/global/press-room/iprospect-nl-awarded-with-european-agency-of-the-year-by-bing/
Disallow: /en/global/press-room/iprospect-recognized-as-a-top-company-worldwide-for-millennial-woman-by-mogul/
Disallow: /en/global/press-room/iprospect-reinforces-focus-on-data-driven-client-strategies-strengthens-global-executive-team/
Disallow: /en/global/press-room/iprospect-releases-2018-future-focus-the-new-machine-rules/
Disallow: /en/global/press-room/iprospect-releases-the-future-is-voice-activated-asia-pacific-research/
Disallow: /en/global/press-room/iprospect-valuklik-announcement/
Disallow: /en/global/press-room/iprospect-win-big-at-bing-agency-awards-2018/
Disallow: /en/global/press-room/iprospect-wins-agency-of-the-year-at-inaugural-peak-performance-marketing-awards/
Disallow: /en/global/press-room/iprospect-wins-at-festival-of-media-global-awards/
Disallow: /en/global/press-room/iprospect-wins-big-at-bing-agency-awards/
Disallow: /en/global/press-room/misty-locke-wins-lifetime-achievement-award/
Disallow: /en/global/press-room/mobile-world-congress-2017-barcelona/
Disallow: /en/global/press-room/new-nl-md-saskia/
Disallow: /en/global/press-room/rohan-philips-named-to-iprospect-global-team/
Disallow: /en/global/press-room/ruth-stubbs-promoted-to-global-president-of-iprospect/
Disallow: /en/global/press-room/sxsw-voting/
Disallow: /en/global/press-room/the-global-business-performance-agency/
Disallow: /en/global/press-room/twitter-studio-release/
Disallow: /en/global/team/dan-hagen/
Disallow: /en/global/what-we-do/solutions/intelligent-content/
Disallow: /en/gr/insights/whitepapers/future-forecast-2016/
Disallow: /en/gr/our-team/dan-hagen/
Disallow: /en/gr/our-team/misty-locke/
Disallow: /en/gr/solutions/intelligent-content/
Disallow: /en/hk/insights/whitepapers/future-forecast-2016/
Disallow: /en/hk/our-team/dan-hagen/
Disallow: /en/hk/solutions/intelligent-content/
Disallow: /en/hr/blog/authors/iprospect/
Disallow: /en/hr/our-team/dan-hagen/
Disallow: /en/hr/page-not-found/
Disallow: /en/hr/solutions/intelligent-content/
Disallow: /en/hr/upcoming-events/programmatic-day/
Disallow: /en/id/insights/whitepapers/future-forecast-2016/
Disallow: /en/id/our-team/dan-hagen/
Disallow: /en/id/press-room/
Disallow: /en/id/press-room/read-more/
Disallow: /en/id/solutions/intelligent-content/
Disallow: /en/ie/our-blog/12-eoy-series-cro-in-2016/
Disallow: /en/ie/our-blog/12-seo-and-content-year-in-review/
Disallow: /en/ie/our-team/dan-hagen/
Disallow: /en/ie/solutions/intelligent-content/
Disallow: /en/il/insights/whitepapers/future-forecast-2016/
Disallow: /en/il/our-team/dan-hagen/
Disallow: /en/il/page-not-found/
Disallow: /en/il/solutions/intelligent-content/
Disallow: /en/in/insights/whitepapers/future-forecast-2016/
Disallow: /en/in/insights/whitepapers/golden-geeks-e-book/
Disallow: /en/in/our-team/dan-hagen/
Disallow: /en/in/solutions/intelligent-content/
Disallow: /en/it/insights/whitepapers/future-focus-2019/
Disallow: /en/it/our-team/dan-hagen/
Disallow: /en/it/solutions/intelligent-content/
Disallow: /en/jp/hello-clavis-insight/
Disallow: /en/jp/insights/
Disallow: /en/jp/insights/whitepapers/a-new-era-of-content/
Disallow: /en/jp/insights/whitepapers/future-forecast-2016/
Disallow: /en/jp/insights/whitepapers/the-international-business-traveler/
Disallow: /en/jp/our-team/dan-hagen/
Disallow: /en/jp/press-room/clavis-iprospect-partnership/
Disallow: /en/jp/press-room/sprinklr-iprospect-partnership/
Disallow: /en/jp/products/content-and-creative/
Disallow: /en/jp/products/conversion-optimization/
Disallow: /en/jp/products/data-analytics/
Disallow: /en/jp/products/mobile-strategy/
Disallow: /en/jp/services-agreement/
Disallow: /en/jp/solutions/intelligent-content/
Disallow: /en/jp/what-we-do/
Disallow: /en/jp/what-we-do/copy-of-services/conversion-optimization/
Disallow: /en/jp/what-we-do/copy-of-services/mobile-strategy/
Disallow: /en/jp/who-we-are/
Disallow: /en/ke/furniture-stores/
Disallow: /en/ke/insights/whitepapers/future-focus-2016/
Disallow: /en/ke/insights/whitepapers/future-focus-2017/
Disallow: /en/ke/lawyers/
Disallow: /en/ke/online-to-offline/
Disallow: /en/ke/solutions/intelligent-content/
Disallow: /en/ke/team/dan-hagen/
Disallow: /en/ke/terms-of-service/
Disallow: /en/kr/dan-hagen/
Disallow: /en/kr/our-team/jin-choi/
Disallow: /en/kr/products/display/
Disallow: /en/kr/solutions/intelligent-content/
Disallow: /en/kr/who-we-are/discover/
Disallow: /en/lt/insights/whitepapers/future-focus-2019/
Disallow: /en/lt/insights/whitepapers/future-forecast-2016/
Disallow: /en/lt/our-team/dan-hagen/
Disallow: /en/lt/solutions/intelligent-content/
Disallow: /en/lv/careers/available-jobs/head-of-seo/
Disallow: /en/lv/insights/povs/one-click-social-commerce/
Disallow: /en/lv/our-team/dan-hagen/
Disallow: /en/lv/our-team/linda-konovalova/
Disallow: /en/lv/solutions/intelligent-content/
Disallow: /en/mx/careers/available-jobs/
Disallow: /en/mx/insights/whitepapers/future-forecast-2017/
Disallow: /en/mx/insights/whitepapers/the-rise-of-digital-aisistants/
Disallow: /en/mx/our-blog/
Disallow: /en/mx/our-team/dan-hagen/
Disallow: /en/mx/solutions/intelligent-content/
Disallow: /en/my/insights/whitepapers/future-forecast-2016/
Disallow: /en/my/our-team/dan-hagen/
Disallow: /en/my/solutions/intelligent-content/
Disallow: /en/nl/insights/povs/paid-search-trends-2017-q3/
Disallow: /en/nl/our-team/dan-hagen/
Disallow: /en/nl/press-room/iprospect-given-two-top-awards-at-2017-international-performance-marketing-awards/
Disallow: /en/nl/press-room/iprospect-recognized-as-a-top-company-worldwide-for-millennial-woman-by-mogul/
Disallow: /en/nl/solutions/intelligent-content/
Disallow: /en/nz/insights/whitepapers/future-forecast-2016/
Disallow: /en/nz/our-team/dan-hagen/
Disallow: /en/nz/solutions/intelligent-content/
Disallow: /en/page-not-found/
Disallow: /en/ph/insights/whitepapers/future-forecast-2016/
Disallow: /en/ph/our-team/dan-hagen/
Disallow: /en/ph/solutions/intelligent-content/
Disallow: /en/pt/our-team/dan-hagen/
Disallow: /en/pt/our-team/marta-chaves/
Disallow: /en/pt/our-team/pedro-goncalves/
Disallow: /en/pt/our-team/rita-pereira/
Disallow: /en/pt/our-team/vanessa-reguengos/
Disallow: /en/pt/solutions/intelligent-content/
Disallow: /en/ro/insights/whitepapers/future-forecast-2016/
Disallow: /en/ro/our-team/dan-hagen/
Disallow: /en/ro/solutions/intelligent-content/
Disallow: /en/ru/our-team/dan-hagen/
Disallow: /en/ru/solutions/intelligent-content/
Disallow: /en/sg/our-team/dan-hagen/
Disallow: /en/sg/our-team/omkar-gurjar/
Disallow: /en/sg/press-room/
Disallow: /en/sg/solutions/intelligent-content/
Disallow: /en/sg/who-we-are/discover/
Disallow: /en/sk/our-team/dan-hagen/
Disallow: /en/sk/our-team/jozef-sajdik/
Disallow: /en/sk/our-team/miroslav-filip/
Disallow: /en/sk/solutions/intelligent-content/
Disallow: /en/th/insights/whitepapers/future-forecast-2016/
Disallow: /en/th/our-team/dan-hagen/
Disallow: /en/th/solutions/intelligent-content/
Disallow: /en/tr/
Disallow: /en/tw/our-blog/2016/amp-html/
Disallow: /en/tw/our-blog/2018/facebook-ads-49c4f/
Disallow: /en/tw/our-blog/2018/facebook-ads-5db2d/
Disallow: /en/tw/our-blog/2018/facebook-ads-dbafb/
Disallow: /en/tw/our-blog/2018/facebook-ads/
Disallow: /en/tw/our-blog/facebook-ads/
Disallow: /en/tw/our-team/dan-hagen/
Disallow: /en/tw/our-team/john-ku/
Disallow: /en/tw/press-room/iprospect-recognized-as-a-top-company-worldwide-for-millennial-woman-by-mogul/
Disallow: /en/tw/solutions/intelligent-content/
Disallow: /en/us/2015-forrester-groundswell-award-nomination/
Disallow: /en/us/bank-of-america-and-iprospect-best-seo-campaign/
Disallow: /en/us/chevrolet-and-iprospect-best-seo-campaign/
Disallow: /en/us/hilton-and-iprospect-best-search-campaign/
Disallow: /en/us/insights/infographics/holidays-2012/
Disallow: /en/us/insights/povs/google-elevates-https-from-recommendation-to-ranking-signal/
Disallow: /en/us/insights/povs/google-launches-estimated-cross-device-update/
Disallow: /en/us/insights/povs/paid-search-trends-2017-q3/
Disallow: /en/us/intel-and-iprospect-best-search-campaign/
Disallow: /en/us/iprospect-and-under-armour-best-social-campaign/
Disallow: /en/us/lids-and-iprospect-best-search-campaign/
Disallow: /en/us/media-authorization-terms-and-conditions/
Disallow: /en/us/our-team/dan-hagen/
Disallow: /en/us/our-team/jon-leicht/
Disallow: /en/us/the-limited-and-iprospect-best-search-campaign/
Disallow: /en/us/upcoming-events/2015-client-summit/
Disallow: /en/us/upcoming-events/2018-iprospect-client-summit/
Disallow: /en/za/insights/whitepapers/future-forecast-2016/
Disallow: /en/za/our-team/dan-hagen/
Disallow: /en/za/products/google-analytics-premium/
Disallow: /en/za/solutions/intelligent-content/
Disallow: /en/za/what-we-do/copy-of-services/google-analytics-premium/
Disallow: /es/ar/insights/whitepapers/future-forecast-2017/
Disallow: /es/ar/insights/whitepapers/the-rise-of-digital-aisistants/
Disallow: /es/ar/ourteam/dan-hagen/
Disallow: /es/ar/solutions/intelligent-content/
Disallow: /es/cl/careers/job-list/
Disallow: /es/cl/insights/whitepapers/future-forecast-2017/
Disallow: /es/cl/insights/whitepapers/the-rise-of-digital-aisistants/
Disallow: /es/cl/our-blog/
Disallow: /es/cl/ourteam/dan-hagen/
Disallow: /es/cl/solutions/intelligent-content/
Disallow: /es/co/insights/whitepapers/future-forecast-2017/
Disallow: /es/co/insights/whitepapers/the-rise-of-digital-aisistants/
Disallow: /es/co/our-blog/
Disallow: /es/co/ourteam/dan-hagen/
Disallow: /es/co/solutions/intelligent-content/
Disallow: /es/es/blog/evolucion-del-ecommerce/
Disallow: /es/es/nuestro-equipo/dan-hagen/
Disallow: /es/es/sala-de-prensa/
Disallow: /es/es/soluciones/co-op/
Disallow: /es/es/soluciones/intelligent-content/
Disallow: /es/mx/careers/job-list/
Disallow: /es/mx/insights/whitepapers/future-forecast-2017/
Disallow: /es/mx/insights/whitepapers/the-rise-of-digital-aisistants/
Disallow: /es/mx/our-blog/
Disallow: /es/mx/ourteam/dan-hagen/
Disallow: /es/mx/solutions/intelligent-content/
Disallow: /es/page-not-found/
Disallow: /et/page-not-found/
Disallow: /fi/fi/solutions/intelligent-content/
Disallow: /fi/fi/tiimimme/dan-hagen/
Disallow: /fi/page-not-found/
Disallow: /fr/be/notre-equipe/dan-hagen/
Disallow: /fr/ca/avocats/
Disallow: /fr/ca/detaillants-meubles/
Disallow: /fr/ca/en-ligne-hors-ligne/
Disallow: /fr/ca/equipe/dan-hagen/
Disallow: /fr/ca/ressources/whitepapers/future-focus-2016/
Disallow: /fr/ca/ressources/whitepapers/future-focus-2017/
Disallow: /fr/ca/salle-de-presse/bonlook-sassocie-a-iprospect-pour-sa-strategie-marketing-omnicanale/
Disallow: /fr/ca/salle-de-presse/iprospect-canada-nomme-dan-kalinski-au-poste-de-chef-de-la-direction-de-iprospect-canada/
Disallow: /fr/ca/salle-de-presse/iprospect-canada-nommee-agence-de-lannee-aux-bing-agency-awards/
Disallow: /fr/ca/salle-de-presse/iprospect-canada-remporte-le-prix-de-lagence-de-lannee/
Disallow: /fr/ca/salle-de-presse/iprospect-reconnue-comme-lune-des-meilleures-entreprises-au-monde-pour-les-femmes-millenaires-par-mogul/
Disallow: /fr/ca/solutions/contenu-intelligent/
Disallow: /fr/ca/termes-de-service/
Disallow: /fr/fr/notre-equipe/dan-hagen/
Disallow: /fr/fr/presse/iprospect-renforce-son-equipe-de-direction-monde-pour-delivrer-des-strategies-data-driven-toujours-plus-performantes/
Disallow: /fr/fr/presse/scan-tv/
Disallow: /fr/page-not-found/
Disallow: /hi/page-not-found/
Disallow: /hr/hr/blog/our-authors/iprospect/
Disallow: /hr/hr/solutions/intelligent-content/
Disallow: /hr/hr/tim/dan-hagen/
Disallow: /hu/hu/ourteam/dan-hagen/
Disallow: /hu/page-not-found/
Disallow: /id/page-not-found/
Disallow: /it/it/ilteam/dan-hagen/
Disallow: /it/it/insights/whitepapers/future-focus-2019/
Disallow: /it/it/solutions/intelligent-content/
Disallow: /it/page-not-found/
Disallow: /ja/page-not-found/
Disallow: /ko/kr/dan-hagen/
Disallow: /ko/kr/ourteam/jin-choi/
Disallow: /ko/kr/products/display/
Disallow: /ko/kr/solutions/intelligent-content/
Disallow: /ko/kr/whoweare/discover/
Disallow: /ko/page-not-found/
Disallow: /lt/page-not-found/
Disallow: /lv/lv/jaunumi/povs/one-click-social-commerce/
Disallow: /lv/lv/karjera/vakances/junior-digital-performance-specialist/
Disallow: /lv/lv/karjera/vakances/performance-specialist/
Disallow: /lv/lv/musu-komanda/dan-hagen/
Disallow: /lv/lv/musu-komanda/linda-konovalova/
Disallow: /lv/page-not-found/
Disallow: /ms/page-not-found/
Disallow: /nl/be/ons-team/dan-hagen/
Disallow: /nl/nl/insights/povs/paid-search-trends-2017-q3/
Disallow: /nl/nl/ons-team/dan-hagen/
Disallow: /nl/nl/onze-blog/wat-elke-marketeer-moet-weten-volgens-byron-sharp/
Disallow: /nl/nl/solutions/intelligent-content/
Disallow: /nl/page-not-found/
Disallow: /no/no/blog/2015-video-annonsenes-aar/
Disallow: /no/no/insights/povs/google-elevates-https-from-recommendation-to-ranking-signal/
Disallow: /no/no/konverteringsside-for-kurs/
Disallow: /no/no/our-team/dan-hagen/
Disallow: /no/page-not-found/
Disallow: /pl/page-not-found/
Disallow: /pl/pl/nasz-zespol/dan-hagen/
Disallow: /pl/pl/produktow/data-analytics/
Disallow: /pt/br/blog/autor/andy-edmonds/
Disallow: /pt/br/insights/whitepapers/future-focus-2016/
Disallow: /pt/br/nosso-time/dan-hagen/
Disallow: /pt/br/solutions/intelligent-content/
Disallow: /pt/page-not-found/
Disallow: /pt/pt/a-nossa-equipa/dan-hagen/
Disallow: /pt/pt/a-nossa-equipa/marta-chaves/
Disallow: /pt/pt/a-nossa-equipa/pedro-goncalves/
Disallow: /pt/pt/a-nossa-equipa/rita-pereira/
Disallow: /pt/pt/a-nossa-equipa/vanessa-reguengos/
Disallow: /ro/page-not-found/
Disallow: /ru/page-not-found/
Disallow: /ru/ru/ourteam/dan-hagen/
Disallow: /ru/ru/solutions/intelligent-content/
Disallow: /sk/page-not-found/
Disallow: /sk/sk/ourteam/dan-hagen/
Disallow: /sk/sk/ourteam/jozef-sajdik/
Disallow: /sk/sk/ourteam/miroslav-filip/
Disallow: /sv/page-not-found/
Disallow: /sv/se/blogg/analyticsdagarna-2017/
Disallow: /sv/se/produkter/digital-content-marketing/
Disallow: /th/page-not-found/
Disallow: /tr/page-not-found/
Disallow: /tr/tr/ekibimiz/dan-hagen/
Disallow: /tr/tr/ekibimiz/global-ekibimiz/ruth-stubbs/
Disallow: /tr/tr/page-not-found/
Disallow: /zh/cn/ourteam/dan-hagen/
Disallow: /zh/page-not-found/
Disallow: /zh/tw/our-blog/2016/amp-html-f01a4/
Disallow: /zh/tw/our-blog/2016/amp-html/
Disallow: /zh/tw/our-blog/2018/2018-experience-expo/
Disallow: /zh/tw/our-blog/2018/data-and-machine-learning/
Disallow: /zh/tw/our-blog/2018/facebook-ads/
Disallow: /zh/tw/our-blog/2018/keeping-ahead-in-the-race-of-ai-and-data-competition-49c4f/
Disallow: /zh/tw/our-blog/e-sports-competition/
Disallow: /zh/tw/ourteam/dan-hagen/
Disallow: /zh/tw/ourteam/john-ku/
Disallow: /zh/tw/press-room/2019-iprospect-intern/
Disallow: /zh/tw/press-room/iprospect-recognized-as-a-top-company-worldwide-for-millennial-woman-by-mogul/
Disallow: /zh/tw/press-room/iprospect-tw-and-sg-take-home-4-awards-at-the-drum-digital-trading-awards-apac-2018/
Disallow: /zh/tw/press-room/iprospect-tw-take-home-digital-marketing-award-of-2018-agency-and-advertiser-of-the-year/
Disallow: /zh/tw/press-room/iprospect-tw-take-home-innovation-technology-award-of-the-year-at-digital-singularity-awards/
Disallow: /zh/tw/solutions/intelligent-content/
Disallow: /cs/cz/ourteam/dan-hagen/
Disallow: /cs/page-not-found/

Sitemap: https://www.iprospect.com/sitemap.xml
