User-Agent: *
Allow: /
Disallow: /_admin/
Disallow: /Adder
Disallow: /Cart
Disallow: /Wyszukiwanie
Disallow: /Rejestracja
Disallow: /adder
Disallow: /cart
Disallow: /wyszukiwanie
Disallow: /rejestracja
Disallow: /login
Disallow: /loginerror
Disallow: /szukaj*
Disallow: /cms/regulamin
Disallow: /cms/polityka-prywatnosci
Disallow: /cms/dostawa-i-platnosc
Disallow: /cms/reklamacje
