### nie moze byc adresow wzglednych i odstepow
### adres testera http://www.sxw.org.uk/computing/robots/check.html
#User-agent: *
#Disallow: /
###Crawl-delay: 60
User-agent: *
Crawl-delay: 10
Disallow: /sms/
Disallow: /user/preferences/
Disallow: /krokus/addrelated/
Disallow: /content/edit/
Disallow: /content/browse/
Disallow: /content/tipafriend/
Disallow: /content/pdf/
Disallow: /content/download/
Disallow: /content/new/
Disallow: /email/
Disallow: /user/register
Disallow: /user/forgotpassword
Disallow: /user/login
Disallow: /sklep_pl/sms/
Disallow: /sklep_pl/user/preferences/
Disallow: /sklep_pl/krokus/addrelated/
Disallow: /sklep_pl/content/edit/
Disallow: /sklep_pl/content/browse/
Disallow: /sklep_pl/content/tipafriend/
Disallow: /sklep_pl/content/pdf/
Disallow: /sklep_pl/content/download/
Disallow: /sklep_pl/content/new/
Disallow: /sklep_pl/email/
Disallow: /sklep_pl/layout/
Disallow: /sklep_pl/user/register
Disallow: /sklep_pl/user/forgotpassword
Disallow: /sklep_pl/user/login
Disallow: /sklep_gb/sms/
Disallow: /sklep_gb/user/preferences/
Disallow: /sklep_gb/krokus/addrelated/
Disallow: /sklep_gb/content/edit/
Disallow: /sklep_gb/content/browse/
Disallow: /sklep_gb/content/tipafriend/
Disallow: /sklep_gb/content/pdf/
Disallow: /sklep_gb/content/download/
Disallow: /sklep_gb/content/new/
Disallow: /sklep_gb/email/
Disallow: /sklep_gb/user/register
Disallow: /sklep_gb/user/forgotpassword
Disallow: /sklep_gb/user/login
Disallow: /sklep_es/sms/
Disallow: /sklep_es/user/preferences/
Disallow: /sklep_es/krokus/addrelated/
Disallow: /sklep_es/content/edit/
Disallow: /sklep_es/content/browse/
Disallow: /sklep_es/content/tipafriend/
Disallow: /sklep_es/content/pdf/
Disallow: /sklep_es/content/download/
Disallow: /sklep_es/content/new/
Disallow: /sklep_es/email/
Disallow: /sklep_es/user/register
Disallow: /sklep_es/user/forgotpassword
Disallow: /sklep_es/user/login
Disallow: /*sms/
Disallow: /*user/preferences/
Disallow: /*krokus/addrelated/
Disallow: /*content/edit/
Disallow: /*content/browse/
Disallow: /*content/tipafriend/
Disallow: /*content/pdf/
Disallow: /*content/download/
Disallow: /*content/new/
Disallow: /*email/
Disallow: /*layout/
Disallow: /*user/register
Disallow: /*user/forgotpassword
Disallow: /*user/login
Disallow: /*(year)*
Disallow: /*(re)$
Disallow: /*(comments_offset)*
Disallow: /*(published)*
Disallow: /*(rating)*
Disallow: /*(rating_count)*
Disallow: /*(rating_infocollection)*
Disallow: /*(rating_infocollection_count)*
Disallow: /*(random)*
Disallow: /*(view_top_list)*
Disallow: /*(tipafriend_top_list)*
Disallow: /*tipafriend/

