User-agent: *
Allow: /index.html
Allow: /

User-agent: Mediapartners-Google
Allow: /index.html
Allow: /makijaz.html
Allow: /kriolipoliza.html
Allow: /laserfrakcyjny.html
Allow: /ENdDERMOLOGIA.html
Allow: /pevonia.html
Allow: /firmy.html
Allow: /praca.html
Allow: /zabiegi.html
Allow: /idea.html
Allow: /pracownicy.html
Allow: /galeria/galeria.html
Allow: /galeria.html
Allow: /sauna_Sulechow.html
Allow: /jacuzzi_sulechow_zielona_gora.html
Allow: /hammam.html
Allow: /pakiety.html
Allow: /cennik.html
Allow: /kontakt.html
Allow: /cennik.pdf
Allow: /podologia.html
Allow: /podolog-dla-kobiet.html
Allow: /podolog.html
Allow: /e-light.html
Allow: /bon.html
Allow: /nagrody.html
Allow: /kosmetyka.html
Allow: /rytualy.html
Allow: /masaz.html
Allow: /paznokcie.html
Allow: /piercing.html
Allow: /zabiegi_uzupelniajace.html
Allow: /images/
Allow: /images/banery/
Allow: /images/banery/img05.png
Allow: /images/male/
Allow: /galeria
Allow: /galeria/images
Allow: /galeria/images/male
Allow: /galeria/images/big
Allow: /galeria/css
Allow: /galeria/css/images
Allow: /cennik
Allow: /css/images
Allow: /makijaz
Allow: /images/makijaz_big
Allow: /images/makijaz_male
Allow: /makijaz_premanentny.html
Allow: /mezoterapia_iglowa.html
Allow: /images/maximus
Allow: /images/emerge
Allow: /laser-frakcyjny-emerge.html
Allow: /Maximus-TriLipo-Zielona-Gora.html
Allow: /podolog-sulechow.html
Allow: /cennik/Podolog_Sulechow.pdf
Allow: /zdjecia/cennik_podolog.png
Allow: /zdjecia/podolog_sulechow_piotr_dopierala.png
Allow: / znaczniki.html





User-agent: Googlebot
Allow: /index.html
Allow: /makijaz.html
Allow: /kriolipoliza.html
Allow: /laserfrakcyjny.html
Allow: /ENdDERMOLOGIA.html
Allow: /pevonia.html
Allow: /firmy.html
Allow: /praca.html
Allow: /zabiegi.html
Allow: /idea.html
Allow: /pracownicy.html
Allow: /galeria/galeria.html
Allow: /galeria.html
Allow: /sauna_Sulechow.html
Allow: /jacuzzi_sulechow_zielona_gora.html
Allow: /hammam.html
Allow: /pakiety.html
Allow: /cennik.html
Allow: /kontakt.html
Allow: /cennik.pdf
Allow: /podologia.html
Allow: /podolog-dla-kobiet.html
Allow: /podolog.html
Allow: /e-light.html
Allow: /bon.html
Allow: /nagrody.html
Allow: /kosmetyka.html
Allow: /rytualy.html
Allow: /masaz.html
Allow: /paznokcie.html
Allow: /piercing.html
Allow: /zabiegi_uzupelniajace.html
Allow: /images/
Allow: /images/banery/
Allow: /images/banery/img05.png
Allow: /images/male/
Allow: /galeria
Allow: /galeria/images
Allow: /galeria/images/male
Allow: /galeria/images/big
Allow: /galeria/css
Allow: /galeria/css/images
Allow: /cennik
Allow: /css/images
Allow: /makijaz
Allow: /images/makijaz_big
Allow: /images/makijaz_male
Allow: /makijaz_premanentny.html
Allow: /mezoterapia_iglowa.html
Allow: /images/maximus
Allow: /images/emerge
Allow: /laser-frakcyjny-emerge.html
Allow: /Maximus-TriLipo-Zielona-Gora.html
Allow: /podolog-sulechow.html
Allow: /cennik/Podolog_Sulechow.pdf
Allow: /zdjecia/cennik_podolog.png
Allow: /zdjecia/podolog_sulechow_piotr_dopierala.png
Allow: / znaczniki.html


User-agent: Adsbot-Google
Allow: /index.html
Allow: /makijaz.html
Allow: /kriolipoliza.html
Allow: /laserfrakcyjny.html
Allow: /ENdDERMOLOGIA.html
Allow: /pevonia.html
Allow: /firmy.html
Allow: /praca.html
Allow: /zabiegi.html
Allow: /idea.html
Allow: /pracownicy.html
Allow: /galeria/galeria.html
Allow: /galeria.html
Allow: /sauna_Sulechow.html
Allow: /jacuzzi_sulechow_zielona_gora.html
Allow: /hammam.html
Allow: /pakiety.html
Allow: /cennik.html
Allow: /kontakt.html
Allow: /cennik.pdf
Allow: /podologia.html
Allow: /podolog-dla-kobiet.html
Allow: /podolog.html
Allow: /e-light.html
Allow: /bon.html
Allow: /nagrody.html
Allow: /kosmetyka.html
Allow: /rytualy.html
Allow: /masaz.html
Allow: /paznokcie.html
Allow: /piercing.html
Allow: /zabiegi_uzupelniajace.html
Allow: /images/
Allow: /images/banery/
Allow: /images/banery/img05.png
Allow: /images/male/
Allow: /galeria
Allow: /galeria/images
Allow: /galeria/images/male
Allow: /galeria/images/big
Allow: /galeria/css
Allow: /galeria/css/images
Allow: /cennik
Allow: /css/images
Allow: /makijaz
Allow: /images/makijaz_big
Allow: /images/makijaz_male
Allow: /makijaz_premanentny.html
Allow: /mezoterapia_iglowa.html
Allow: /images/maximus
Allow: /images/emerge
Allow: /laser-frakcyjny-emerge.html
Allow: /Maximus-TriLipo-Zielona-Gora.html
Allow: /podolog-sulechow.html
Allow: /cennik/Podolog_Sulechow.pdf
Allow: /zdjecia/cennik_podolog.png
Allow: /zdjecia/podolog_sulechow_piotr_dopierala.png
Allow: / znaczniki.html


User-agent: Googlebot-Image
Allow: /index.html
Allow: /makijaz.html
Allow: /kriolipoliza.html
Allow: /laserfrakcyjny.html
Allow: /ENdDERMOLOGIA.html
Allow: /pevonia.html
Allow: /firmy.html
Allow: /praca.html
Allow: /zabiegi.html
Allow: /idea.html
Allow: /pracownicy.html
Allow: /galeria/galeria.html
Allow: /galeria.html
Allow: /sauna_Sulechow.html
Allow: /jacuzzi_sulechow_zielona_gora.html
Allow: /hammam.html
Allow: /pakiety.html
Allow: /cennik.html
Allow: /kontakt.html
Allow: /cennik.pdf
Allow: /podologia.html
Allow: /podolog-dla-kobiet.html
Allow: /podolog.html
Allow: /e-light.html
Allow: /bon.html
Allow: /nagrody.html
Allow: /kosmetyka.html
Allow: /rytualy.html
Allow: /masaz.html
Allow: /paznokcie.html
Allow: /piercing.html
Allow: /zabiegi_uzupelniajace.html
Allow: /images/
Allow: /images/banery/
Allow: /images/banery/img05.png
Allow: /images/male/
Allow: /galeria
Allow: /galeria/images
Allow: /galeria/images/male
Allow: /galeria/images/big
Allow: /galeria/css
Allow: /galeria/css/images
Allow: /cennik
Allow: /css/images
Allow: /makijaz
Allow: /images/makijaz_big
Allow: /images/makijaz_male
Allow: /makijaz_premanentny.html
Allow: /mezoterapia_iglowa.html
Allow: /images/maximus
Allow: /images/emerge
Allow: /laser-frakcyjny-emerge.html
Allow: /Maximus-TriLipo-Zielona-Gora.html
Allow: /podolog-sulechow.html
Allow: /cennik/Podolog_Sulechow.pdf
Allow: /zdjecia/cennik_podolog.png
Allow: /zdjecia/podolog_sulechow_piotr_dopierala.png
Allow: / znaczniki.html



User-agent: Googlebot-Mobile
Allow: /index.html
Allow: /makijaz.html
Allow: /kriolipoliza.html
Allow: /laserfrakcyjny.html
Allow: /ENdDERMOLOGIA.html
Allow: /pevonia.html
Allow: /firmy.html
Allow: /praca.html
Allow: /zabiegi.html
Allow: /idea.html
Allow: /pracownicy.html
Allow: /galeria/galeria.html
Allow: /galeria.html
Allow: /sauna_Sulechow.html
Allow: /jacuzzi_sulechow_zielona_gora.html
Allow: /hammam.html
Allow: /pakiety.html
Allow: /cennik.html
Allow: /kontakt.html
Allow: /cennik.pdf
Allow: /podologia.html
Allow: /podolog-dla-kobiet.html
Allow: /podolog.html
Allow: /e-light.html
Allow: /bon.html
Allow: /nagrody.html
Allow: /kosmetyka.html
Allow: /rytualy.html
Allow: /masaz.html
Allow: /paznokcie.html
Allow: /piercing.html
Allow: /zabiegi_uzupelniajace.html
Allow: /images/
Allow: /images/banery/
Allow: /images/banery/img05.png
Allow: /images/male/
Allow: /galeria
Allow: /galeria/images
Allow: /galeria/images/male
Allow: /galeria/images/big
Allow: /galeria/css
Allow: /galeria/css/images
Allow: /cennik
Allow: /css/images
Allow: /makijaz
Allow: /images/makijaz_big
Allow: /images/makijaz_male
Allow: /makijaz_premanentny.html
Allow: /mezoterapia_iglowa.html
Allow: /images/maximus
Allow: /images/emerge
Allow: /laser-frakcyjny-emerge.html
Allow: /Maximus-TriLipo-Zielona-Gora.html
Allow: /podolog-sulechow.html
Allow: /cennik/Podolog_Sulechow.pdf
Allow: /zdjecia/cennik_podolog.png
Allow: /zdjecia/podolog_sulechow_piotr_dopierala.png
Allow: / znaczniki.html
