# robots.txt automaticaly generated by PrestaShop e-commerce open-source solution
# http://www.prestashop.com - http://www.prestashop.com/forums
# This file is to prevent the crawling and indexing of certain parts
# of your site by web crawlers and spiders run by sites like Yahoo!
# and Google. By telling these "robots" where not to go on your site,
# you save bandwidth and server resources.
# For more information about the robots.txt standard, see:
# http://www.robotstxt.org/wc/robots.html
User-agent: Googlebot
# Private pages
allow: /*orderby=
allow: /*orderway=
allow: /*tag=
allow: /*id_currency=
allow: /*search_query=
allow: /*back=
allow: /*n=
allow: /*controller=addresses
allow: /*controller=address
allow: /*controller=authentication
allow: /*controller=cart
allow: /*controller=discount
allow: /*controller=footer
allow: /*controller=get-file
allow: /*controller=header
allow: /*controller=history
allow: /*controller=identity
allow: /*controller=images.inc
allow: /*controller=init
allow: /*controller=my-account
allow: /*controller=order
allow: /*controller=order-opc
allow: /*controller=order-slip
allow: /*controller=order-detail
allow: /*controller=order-follow
allow: /*controller=order-return
allow: /*controller=order-confirmation
allow: /*controller=pagination
Disallow: /*controller=password
Disallow: /*controller=pdf-invoice
Disallow: /*controller=pdf-order-return
Disallow: /*controller=pdf-order-slip
Disallow: /*controller=product-sort
Disallow: /*controller=search
Disallow: /*controller=statistics
Disallow: /*controller=attachment
Disallow: /*controller=guest-tracking
User-agent: Googlebot
# Directories
allow: */classes/
allow: */config/
allow: */download/
allow: */mails/
allow: */translations/
allow: */tools/
# Files
allow: /*pl/odzyskiwanie-hasla
allow: /*pl/adres
allow: /*pl/adresy
allow: /*pl/logowanie
Disallow: /*pl/koszyk
Disallow: /*pl/rabaty
Disallow: /*pl/historia-zamowien
Disallow: /*pl/dane-osobiste
Disallow: /*pl/moje-konto
Disallow: /*pl/sledzenie-zamowienia
Disallow: /*pl/pokwitowania
allow: /*pl/zamowienie
allow: /*pl/szukaj
allow: /*pl/szybkie-zakupy
Disallow: /*pl/sledzenie-zamowienia-gosc
Disallow: /*pl/potwierdzenie-zamowienia
Sitemap: http://elmetsa.pl/1_index_sitemap.xml
