User-agent: *
Crawl-delay: 10
Disallow: /tmp/
Disallow: /temp/
Disallow: /cache/
Disallow: /admin/
Disallow: /administration/
Disallow: /root/
Disallow: /private/
Disallow: /install/
Sitemap: http://www.goganet.com/dat/sitemap.xml.gz
