User-agent: *
Allow: /
Disallow: /ajax/
Disallow: /pl/ajax/
Disallow: /ajax/
Disallow: /en/ajax/
Disallow: /ajax/wyslij-link/
Disallow: /pl/ajax/wyslij-link/
Disallow: /ajax/send-link/
Disallow: /en/ajax/send-link/
Disallow: /ajax/zglos-blad/
Disallow: /pl/ajax/zglos-blad/
Disallow: /ajax/bug-raport/
Disallow: /en/ajax/bug-raport/
Disallow: /ajax/kalendarz/
Disallow: /pl/ajax/kalendarz/
Disallow: /ajax/kalendarzmini/
Disallow: /en/ajax/kalendarzmini/
Disallow: /ajax/kalendarz-strony/
Disallow: /pl/ajax/kalendarz-strony/
Disallow: /ajax/kalendarzmini_strony/
Disallow: /en/ajax/kalendarzmini_strony/
Disallow: /dodaj/
Disallow: /pl/dodaj/
Disallow: /dodaj/
Disallow: /en/dodaj/
Sitemap: http://www.muzeum.krosno.pl/sitemap.xml
