User-agent: *
Disallow: /Czyszczenie_zabezpieczanie_anty_graffiti_elewacji.php
Disallow: /mapa_strony_clean_bruk.php
Disallow: /o_kostce_brukowej_bruku.php
Disallow: /Czyszczenie_renowacja_malowanie_impregnacja_dachow.php
Disallow: /kostka_brukowa_zdjecia.php
Disallow: /Usuwanie_Zmywanie_Graffiti_Zabezpieczanie_Powierzchni.php
Allow: /
Disallow: /zdjecia_czyszczenia_kostki_elewacji_dachu.php
Disallow: /Wysokocisnieniowe_czyszczenie_techniczne.php
Disallow: /Wysokocisnieniowe_czyszczenie_odswiezanie_renowacja_impregnacja_kostki_brukowej.php
Disallow: /preparaty_do_czyszczenia_i_impregnacji.php
Disallow: /kontakt_clean_bruk.php
Disallow: /kreator/
Disallow: /Czyszczenie-zabezpieczanie-anty-graffiti-elewacji.php
Disallow: /mapa-strony-clean-bruk.php
Disallow: /o-kostce-brukowej-bruku.php
Disallow: /Czyszczenie-renowacja-malowanie-impregnacja-dachow.php
Disallow: /kostka-brukowa-zdjecia.php
Disallow: /Usuwanie-Zmywanie-Graffiti-Zabezpieczanie-Powierzchni.php
Disallow: /zdjecia-czyszczenia-kostki-elewacji-dachu.php
Disallow: /Wysokocisnieniowe-czyszczenie-techniczne.php
Disallow: /Wysokocisnieniowe-czyszczenie-odswiezanie-renowacja-impregnacja-kostki-brukowej.php
Disallow: /preparaty-do-czyszczenia-i-impregnacji.php
Disallow: /kontakt-clean-bruk.php
Disallow: /init.php
Disallow: /config.php
Disallow: /indexdo5IV2012.php
Disallow: /publication_list.xml
Disallow: /menu.xml
Sitemap: http://www.clean-bruk.pl/sitemap.xml
Sitemap: http://www.clean-bruk.pl/image-sitemap.xml
