# robots.txt automaticaly generated by PrestaShop e-commerce open-source solution
# http://www.prestashop.com - http://www.prestashop.com/forums
# This file is to prevent the crawling and indexing of certain parts
# of your site by web crawlers and spiders run by sites like Yahoo!
# and Google. By telling these "robots" where not to go on your site,
# you save bandwidth and server resources.
# For more information about the robots.txt standard, see:
# http://www.robotstxt.org/wc/robots.html
User-agent: *
# Directories
Disallow: */classes/
Disallow: */config/
Disallow: */download/
Disallow: */mails/
Disallow: */modules/
Disallow: */translations/
Disallow: */tools/
# Files
Disallow: /*en/address
Disallow: /*en/addresses
Disallow: /*en/discount
Disallow: /*en/order-history
Disallow: /*en/identity
Disallow: /*en/my-account
Disallow: /*en/order-follow
Disallow: /*en/order-slip
Disallow: /*en/order
Disallow: /*en/guest-tracking
Disallow: /*pl/address
Disallow: /*pl/addresses
Disallow: /*pl/discount
Disallow: /*pl/order-history
Disallow: /*pl/identity
Disallow: /*pl/my-account
Disallow: /*pl/order-follow
Disallow: /*pl/order-slip
Disallow: /*pl/order
Disallow: /*pl/guest-tracking


