# robotstxt.org/

User-agent: *
Disallow: /k1/
Disallow: /k2/
Disallow: /k3/
Disallow: /k4/
Disallow: /k5/
Disallow: /k6/
Disallow: /k7/
Disallow: /k8/
Disallow: /k9/
Disallow: /ka/
Disallow: /kb/
Disallow: /o1/
Disallow: /o2/
Disallow: /o3/
Disallow: /o4/
Disallow: /o5/
Disallow: /o6/
Disallow: /o7/
Disallow: /o8/
Disallow: /b1/
Disallow: /b2/
Disallow: /b3/
Disallow: /b4/
Disallow: /b5/
Disallow: /b6/
Disallow: /b7/
Disallow: /b8/
Disallow: /p1/
Disallow: /p2/
Disallow: /p3/
Disallow: /p4/
Disallow: /p5/
Disallow: /p6/
Disallow: /p7/
Disallow: /p8/
Disallow: /p9/
Disallow: /pa/
Disallow: /pb/
Disallow: /t1/
Disallow: /t2/
Disallow: /t3/
Disallow: /t4/
Disallow: /t5/
Disallow: /t6/
Disallow: /t7/
Disallow: /t8/
Disallow: /t9/
Disallow: /ta/
Disallow: /tb/
Disallow: /f1/
Disallow: /f2/
Disallow: /f3/
Disallow: /f4/
Disallow: /f5/
Disallow: /f6/
Disallow: /f7/
Disallow: /f8/
Disallow: /att/

