User-agent: *
Disallow: /AdminKa/
Disallow: /GPMazowsza/
Disallow: /GPW/
Disallow: /GPW2002/
Disallow: /GPW2003/
Disallow: /GPW2004/
Disallow: /GPW2005/
Disallow: /GPW2006/
Disallow: /info/
Disallow: /infoturnieje/
Disallow: /kalbar/
Disallow: /kalendarz/
Disallow: /kk2005/
Disallow: /ligi/
Disallow: /mpj/
Disallow: /mpj1920_03/
Disallow: /mpj1920_04/
Disallow: /mpj1920_05/
Disallow: /mpj1920_06/
Disallow: /obrazy/
Disallow: /obrazy_index/
Disallow: /PHP/
Disallow: /rankingi/
Disallow: /regulaminy/
Disallow: /rejestr/
Disallow: /swf/
Disallow: /SZL/
Disallow: /tmp/
Disallow: /turnieje/
Disallow: /udm-resources/
Disallow: /undermain/
Disallow: /upload/
Disallow: /wyniki/
Disallow: /xml/
