User-agent: *
Allow: /*
Disallow: /application/
Disallow: /libraries/
Disallow: /*/fav/add/
Disallow: /*/p/comment/add/
Disallow: /*/p/mail/recommend/
Disallow: /*/p/q/
Disallow: /*/reg/
Disallow: /*/login/
Disallow: /*/basket/
Disallow: /*/searchquery
