User-agent: *
Disallow: http://www.microaqua.pl/c/
Disallow: http://www.microaqua.pl/protected/
Disallow: /meduzy/
Disallow: /meduzy/akwaria/
Disallow: /meduzy/akwaria/cubic/
Disallow: /meduzy/akwaria/jellyfish-art/
Disallow: /meduzy/akwaria/eon/
Disallow: /meduzy/akwaria/walce-akrylowe/
Disallow: /meduzy/akwaria/pod-zabudowe/
Disallow: /meduzy/akwaria/hodowlane/
Disallow: /meduzy/akwaria/wszystkie-akwaria/
Disallow: /meduzy/akwaria/juz-wkrotce/
Disallow: /meduzy/meduzy-hodowlane/
Disallow: /meduzy/akcesoria/
Disallow: /meduzy/karmienie-i-pielegnacja/
Disallow: /meduzy/uslugi/
Disallow: /meduzy/hotel-dla-meduz/
Disallow: /poradnik/salifert-testy/test-ca/
Disallow: /poradnik/salifert-testy/test-mg/
Disallow: /poradnik/salifert-testy/test-kh/
Disallow: /poradnik/salifert-testy/test-no3/
Disallow: /poradnik/salifert-testy/test-po4/
Disallow: /poradnik/salifert-testy/test-ph/
Disallow: /poradnik/salifert-testy/test-nh4/
Disallow: /wydarzenia/interzoo-2012-w-norymberdze/video-1/
Disallow: /wydarzenia/interzoo-2012-w-norymberdze/video-2/
Disallow: /wydarzenia/interzoo-2012-w-norymberdze/video-3/
Sitemap: http://www.microaqua.pl/sitemap.xml

