<!doctype html> <html ng-app="vitesseApp"> <head> <base href="/"> <script src="https://use.typekit.net/jnu5zoj.js"></script> <script>try {
Typekit.load({async: true});
} catch (e) {
}</script> <meta charset="utf-8"> <title data-ng-bind="($root.title[lang].length > 0 ? $root.title[lang] + ' - ' : '') + 'VITESSE'">VITESSE</title> <meta name="Description" content="Jestesmy rodzinna firma z okolic Warszawy, ktora robi dobre ubrania kolarskie."> <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no"/> <link rel="apple-touch-icon-precomposed" sizes="57x57" href="images/favicons/apple-touch-icon-57x57.661f9365.png"/> <link rel="apple-touch-icon-precomposed" sizes="114x114" href="images/favicons/apple-touch-icon-114x114.04a082ad.png"/> <link rel="apple-touch-icon-precomposed" sizes="72x72" href="images/favicons/apple-touch-icon-72x72.fabb2a29.png"/> <link rel="apple-touch-icon-precomposed" sizes="144x144" href="images/favicons/apple-touch-icon-144x144.19666bf9.png"/> <link rel="apple-touch-icon-precomposed" sizes="60x60" href="images/favicons/apple-touch-icon-60x60.e1594db9.png"/> <link rel="apple-touch-icon-precomposed" sizes="120x120" href="images/favicons/apple-touch-icon-120x120.21e5a073.png"/> <link rel="apple-touch-icon-precomposed" sizes="76x76" href="images/favicons/apple-touch-icon-76x76.20c7c7e4.png"/> <link rel="apple-touch-icon-precomposed" sizes="152x152" href="images/favicons/apple-touch-icon-152x152.52aaf239.png"/> <link rel="icon" type="image/png" href="images/favicons/favicon-196x196.9872329d.png" sizes="196x196"/> <link rel="icon" type="image/png" href="images/favicons/favicon-96x96.269b00f5.png" sizes="96x96"/> <link rel="icon" type="image/png" href="images/favicons/favicon-32x32.443930d4.png" sizes="32x32"/> <link rel="icon" type="image/png" href="images/favicons/favicon-16x16.9ab00e54.png" sizes="16x16"/> <link rel="icon" type="image/png" href="images/favicons/favicon-128.c580d9b6.png" sizes="128x128"/> <meta name="application-name" content="&nbsp;"/> <meta name="msapplication-TileColor" content="#FFFFFF"/> <meta name="msapplication-TileImage" content="images/favicons/mstile-144x144.19666bf9.png"/> <meta name="msapplication-square70x70logo" content="images/favicons/mstile-70x70.c580d9b6.png"/> <meta name="msapplication-square150x150logo" content="images/favicons/mstile-150x150.ffcfa070.png"/> <meta name="msapplication-wide310x150logo" content="images/favicons/mstile-310x150.8a8956e9.png"/> <meta name="msapplication-square310x310logo" content="images/favicons/mstile-310x310.fc0f87ff.png"/> <meta property="og:title" content="Vitesse Sportswear"/> <meta property="og:type" content="website"/> <meta property="og:url" content="http://vitesse.pl/"/> <meta property="og:description" content="Jestesmy rodzinna firma z okolic Warszawy, ktora robi dobre ubrania kolarskie."/> <meta property="og:image" content="http://vitesse.pl/api/og-image.jpg"/> <link rel="stylesheet" href="styles/vendor.ffec62c8.css"> <link rel="stylesheet" href="styles/main.a34b10d5.css"> </head> <body ng-controller="MainCtrl" ng-class="{'menuOpen': menuOpen, 'showCookies': showCookies}"> <!--[if lte IE 8]>
<p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade
your browser</a> to improve your experience.</p>
<![endif]--> <div id="loading" ng-show="showLoading"> </div> <div id="loadingFirst" ng-show="showFirstLoading"></div> <div id="cookies" ng-show="showCookies"> <div class="content"> <div class="text-center"> Ta strona wykorzystuje pliki cookie dla lepszego dzialania serwisu. Mozesz zablokowac pliki cookie w ustawieniach przegladarki. WIecej informacji w Polityce Prywatnosci tej strony. </div> <button class="btn btn-with-arrow" ng-click="closeCookies()"> OK, ROZUMIEM </button> </div> </div> <div ui-view id="ui-view-main"></div> <!-- Google Analytics: change UA-XXXXX-X to be your site's ID --> <script>!function (A, n, g, u, l, a, r) {
A.GoogleAnalyticsObject = l, A[l] = A[l] || function () {
(A[l].q = A[l].q || []).push(arguments)
}, A[l].l = +new Date, a = n.createElement(g),
r = n.getElementsByTagName(g)[0], a.src = u, r.parentNode.insertBefore(a, r)
}(window, document, 'script', 'https://www.google-analytics.com/analytics.js', 'ga');

ga('create', 'UA-83058404-1');
/*ga('send', 'pageview');*/</script> <script src="scripts/vendor.61be8015.js"></script> <script src="scripts/scripts.1c218a9a.js"></script> </body> </html>
