User-agent: AdsBot-Google-Mobile
Disallow:

User-agent: AdsBot-Google
Disallow:

user-agent: AhrefsBot
disallow: /

# robots.txt - Inhalte freigegeben
User-agent: *
# Sperrung eines bestimmten Bereiches
Disallow: /*linkgenerator=
Disallow: /*popup=
Disallow: /*nocache=
Disallow: /*?code=
Disallow: /*&code=
Disallow: /*?offer=
Disallow: /*&offer=
Disallow: /*?fix-occupation-offer=
Disallow: /*&fix-occupation-offer=
Disallow: /*?subcode=
Disallow: /*&subcode=
Disallow: /logs/
Disallow: /control/
Disallow: /umfrage/
Disallow: /templ/
Disallow: /buchen/
Disallow: /tmp/
Disallow: /ini/
Disallow: /infx/
Disallow: /sql/
Disallow: /scripts/
Disallow: /layout/
Disallow: /styles/
Disallow: /doc/
Disallow: /data/
Disallow: /admin/
Disallow: /flash/
Disallow: /xml/
Disallow: /images/
Disallow: /index/popup.php
Disallow: /callcenter/
Disallow: /info/
Disallow: /new/
Disallow: /pictures/67924
# Sperrung des Buchungsvorgangs
Disallow: /devis-sans-engagement.html?*
Disallow: /pedido-personal.html?*
Disallow: /specpredlozhenie.html?*
Disallow: /nabidka_pro_vas.html?*
Disallow: /individuelt_tilbud.html?*
Disallow: /persoenliches_angebot.html?*
Disallow: /oferta_personal.html?*
Disallow: /simulation_sans_engagement.html?*
Disallow: /personalised_offer.html?*
Disallow: /offerta_individuale.html?*
Disallow: /persoonlijke_aanbieding.html?*
Disallow: /oferta_osobista.html?*
Disallow: /proposta_pessoal.html?*
Disallow: /oferta_personalizata.html?*
Disallow: /osebna_ponudba.html?*
Disallow: /ponuka_pre_vas.html?*
Disallow: /personligt_erbjudande.html?*
Disallow: /nabidka-pro-vas.html?*
Disallow: /individuelt-tilbud.html?*
Disallow: /persoenliches-angebot.html?*
Disallow: /oferta-personal.html?*
Disallow: /simulation-sans-engagement.html?*
Disallow: /personalised-offer.html?*
Disallow: /offerta-individuale.html?*
Disallow: /persoonlijke-aanbieding.html?*
Disallow: /oferta-osobista.html?*
Disallow: /proposta-pessoal.html?*
Disallow: /oferta-personalizata.html?*
Disallow: /osebna-ponudba.html?*
Disallow: /ponuka-pre-vas.html?*
Disallow: /personligt-erbjudande.html?*
Disallow: /buchung.html
Disallow: /boeking.html
Disallow: /objednavka.html
Disallow: /booking.html
Disallow: /reserva.html
Disallow: /reservation.html
Disallow: /prenotazione.html
Disallow: /foglalas.html
Disallow: /boeking.html
Disallow: /buchung.html
Disallow: /rezerwuj.html
Disallow: /rezervare.html
Disallow: /rezervacija.html
Disallow: /buchung.html
Disallow: /objednavka.html
Disallow: /bokning.html
# sonstiger content
Disallow: /index/index.php?sei_id=16
Disallow: /index/index.php?sei_id=216
Disallow: /index/index.php?sei_id=404
Disallow: /beispielhaus/
Disallow: /lcc.html
Disallow: /crazy_booking_newsletter.html
Disallow: /reiseinformationen/*.pdf
Disallow: /index/index.php?sei_id=219
Disallow: /sandbox/formy.html
Disallow: /sandbox.html
Disallow: /sandbox/
Disallow: /pojisteni.html
# Partner content
Disallow: /unternehmen/*
Disallow: /het_bedrijf/*
Disallow: /firma/*
Disallow: /firmaet/*
Disallow: /nuestra_empresa/*
Disallow: /entreprise/*
Disallow: /company/*
Disallow: /chi_siamo/*
Disallow: /ceguenk/*
Disallow: /het_bedrijf/*
Disallow: /%D0%9A%D0%BE%D0%BC%D0%BF%D0%B0%D0%BD%D0%B8%D1%8F/*
Disallow: /firma/*
Disallow: /empresa/*
Disallow: /compania/*
Disallow: /unternehmen/*
Disallow: /podjetje/*
Disallow: /firma/*
Disallow: /foeretag/*
Disallow: /company/*
Disallow: /wintertrex_partners/*
Disallow: /snowtrex_partner/*
Disallow: /socio_snowtrex/*
Disallow: /partenaire_snowtrex/*
Disallow: /snowtrex_affiliates/*
Disallow: /partner_snowtrex/*
Disallow: /%D0%9F%D0%B0%D1%80%D1%82%D0%BD%D1%91%D1%80%D1%8B_snowtrex/*
Disallow: /partnerzy_snowtrex/*
Disallow: /parceiros_snowtrex/*
Disallow: /parteneri_snowtrex/*
Disallow: /snowtrex_partneri/*
Disallow: /snowtrex_affiliates/*
Disallow: /unternehmen/partnerbereich/ihre_daten.html
Disallow: /unternehmen/partnerbereich/ihre_statistiken.html
Disallow: /partnerprogramm/einstellungen.html
Disallow: /unternehmen/partnerbereich/werbemedien.html
Disallow: /unternehmen/partnerbereich/linkgenerator.html
Disallow: /partnerprogramm/styles_aendern.html
Disallow: /partnerprogramm/xml.html

