User-agent: *
Disallow: /admin
Disallow: /download
Disallow: /includes
Disallow: /temp
Disallow: /tmp
Allow: /images/produkty/*
Disallow: /odblokuj
Disallow: /img
Disallow: /install
Disallow: /account.php
Disallow: /advanced_search.php
Disallow: /checkout_shipping.php
Disallow: /checkout_payment.php
Disallow: /checkout_process.php
Disallow: /create_account.php
Disallow: /contact_us1.php*
Disallow: /product_info.php/cPath/*
Disallow: /product_info.php/products_id/*
Disallow: /login.php
Disallow: /password_forgotten.php
Disallow: /popup_image.php
Disallow: /shopping_cart.php
Disallow: /patch-1-02-b.php
Disallow: /product_reviews_write.php
Disallow: /account.html
Disallow: /advanced_search.html
Disallow: /checkout_shipping.html
Disallow: /checkout_payment.html
Disallow: /checkout_shipping.html
Disallow: /checkout_process.html
Disallow: /create_account.html
Disallow: /login.html
Disallow: /password_forgotten.html
Disallow: /popup_image.html
Disallow: /shopping_cart.html
Disallow: /product_reviews_write.html
Disallow: /contact_us.php?
Disallow: /advanced_search_result.php?
Disallow: /szukaj-*
Disallow: /wyprzedaze-c-554.html?sort
Disallow: /*?sort=
Disallow: /*?search_in_description=
Sitemap: /sitemap.xml

