# robots.txt automaticaly generated by PrestaShop e-commerce open-source solution
# http://www.prestashop.com - http://www.prestashop.com/forums
# This file is to prevent the crawling and indexing of certain parts
# of your site by web crawlers and spiders run by sites like Yahoo!
# and Google. By telling these "robots" where not to go on your site,
# you save bandwidth and server resources.
# For more information about the robots.txt standard, see:
# http://www.robotstxt.org/wc/robots.html
User-agent: *

# Allow dla Googlebot
Allow: /themes/muza/css/global.css
Allow: /modules/blockbestsellers/blockbestsellers.css
Allow: /modules/blockpermanentlinks/blockpermanentlinks.css
Allow: /themes/muza/css/modules/blockuserinfo/blockuserinfo.css
Allow: /modules/blockcontact/blockcontact.css
Allow: /themes/muza/css/modules/blocksearch/blocksearch.css
Allow: /themes/muza/css/modules/favoriteproducts/favoriteproducts.css
Allow: /themes/muza/css/modules/blocknewsletter/blocknewsletter.css
Allow: /modules/cscatalogmenu/cscatalogmenu.css
Allow: /themes/muza/css/modules/blockmyaccountfooter/blockmyaccount.css
Allow: /themes/muza/css/modules/blockcart/blockcart.css
Allow: /modules/csaddtocartextend/css/jquery.ambiance.css
Allow: /modules/csquickview/css/cs_quickview.css
Allow: /modules/csmegamenu/css/csmegamenu_front.css
Allow: /modules/csthemeeditor/css/colorpicker.css
Allow: /modules/csheaderlink/csheaderlink.css
Allow: /modules/cshometab/css/cshometab.css
Allow: /modules/checkoutfields/checkoutfields.css
Allow: /modules/mailalerts/mailalerts.css
Allow: /themes/muza/css/modules/productcomments/productcomments.css
Allow: /modules/favoriteproducts/favoriteproducts.js
Allow: /modules/csaddtocartextend/js/jquery.ambiance.min.js
Allow: /modules/csquickview/js/cs_quickview.min.js
Allow: /modules/csmegamenu/js/csmegamenu_front.js
Allow: /modules/csmegamenu/js/csmegamenu_addmore.js
Allow: /themes/muza/js/tools/treeManagement.js


# Private pages
Disallow: /*orderby=
Disallow: /*orderway=
Disallow: /*tag=
Disallow: /*id_currency=
Disallow: /*search_query=
Disallow: /*back=
Disallow: /*n=
Disallow: /*controller=addresses
Disallow: /*controller=address
Disallow: /*controller=authentication
Disallow: /*controller=cart
Disallow: /*controller=discount
Disallow: /*controller=footer
Disallow: /*controller=get-file
Disallow: /*controller=header
Disallow: /*controller=history
Disallow: /*controller=identity
Disallow: /*controller=images.inc
Disallow: /*controller=init
Disallow: /*controller=my-account
Disallow: /*controller=order
Disallow: /*controller=order-opc
Disallow: /*controller=order-slip
Disallow: /*controller=order-detail
Disallow: /*controller=order-follow
Disallow: /*controller=order-return
Disallow: /*controller=order-confirmation
Disallow: /*controller=pagination
Disallow: /*controller=password
Disallow: /*controller=pdf-invoice
Disallow: /*controller=pdf-order-return
Disallow: /*controller=pdf-order-slip
Disallow: /*controller=product-sort
Disallow: /*controller=search
Disallow: /*controller=statistics
Disallow: /*controller=attachment
Disallow: /*controller=guest-tracking
# Directories
Disallow: */classes/
Disallow: */config/
Disallow: */download/
Disallow: */mails/
# Disallow: */modules/
Disallow: */translations/
Disallow: */tools/
Disallow: */elibri/
# Files
Disallow: /*pl/odzyskiwanie-hasla
Disallow: /*pl/adres
Disallow: /*pl/adresy
Disallow: /*pl/logowanie
Disallow: /*pl/koszyk
Disallow: /*pl/rabaty
Disallow: /*pl/historia-zamowien
Disallow: /*pl/dane-osobiste
Disallow: /*pl/moje-konto
Disallow: /*pl/sledzenie-zamowienia
Disallow: /*pl/pokwitowania
Disallow: /*pl/zamowienie
Disallow: /*pl/szukaj
Disallow: /*pl/szybkie-zakupy
Disallow: /*pl/sledzenie-zamowienia-gosc
Disallow: /*pl/potwierdzenie-zamowienia

