User-agent: *
Allow: /
Disallow: /career*
Disallow: /recruitment_form*
Disallow: /create_account*
Disallow: /login*
Disallow: /password_forgotten*
Disallow: /and/
Sitemap: https://www.prooffice.waw.pl/sitemap.xml
