User-agent: *
Allow: /
Disallow: /wp-admin/
Disallow: /wp-includes/
Disallow: /wp-content/plugins/
Disallow: /wp-content/cache/
Disallow: /wp-content/themes/
Allow: /wp-admin/admin-ajax.php

Host: https://www.aspa.pl

User-agent: *
Disallow: /wp-admin/*
Disallow: /wp-login/*
Disallow: /wp-includes/
Allow: /wp-admin/admin-ajax.php
Allow: /wp-includes/js/
Allow: /wp-includes/images/
Disallow: /wp-login.php
Disallow: /wp-register.php
Disallow: /trackback/
Disallow: /t/*
Disallow: *wordfence_logHuman=*
Disallow: *hid=*
Disallow: *page_id=*
Disallow: *id=*
Disallow: *.pdf
Disallow: *orderby=*
Disallow: *filter_typ=*
Disallow: *s=*
Disallow: *id=*
Disallow: *template=print
Disallow: /typ*
Disallow: /ilosc-programow*
Disallow: /maksymalny-prad*
Disallow: /czestotliwosc/
Disallow: /makswtop*
Disallow: /przedzialy-czasowe/
Disallow: /sila-docisku-el*
Disallow: /czu-pra-wto-zg/
Disallow: /narastanie-pradu/
Disallow: /praznazalodzaselebloty/
Disallow: /stopien-ochrony-obudowy/
Disallow: /tol-nap-zas/
Disallow: /dop-tem-pra/
Disallow: /parametry-twarde/
Disallow: /wymciswodchl/
Disallow: /moc-znamionowa-p5*
Disallow: /stal-wysokoweglowa/
Disallow: /z-pomiarem-pradu/
Disallow: /stal-niskoweglowa*
Disallow: /wtoprazwa/
Disallow: /prety-na-krzyz/
Disallow: /nap-zas-el-wyk/
Disallow: /wysieg-ramion/
Disallow: /znam-pra-100/
Disallow: /zabzwlo/
Disallow: /stop-reg/
Disallow: /zasilanie/
Disallow: /wymcissprepow/
Disallow: /parametry-pracy/
Disallow: /wysieg-ramion/
Disallow: /predkosc-liniowa-elektrod/
Disallow: /zabezpieczenie-glowne/
Disallow: /moc-znamionowa-p50kva/
Disallow: /zuzycie-wody-chlodzacej/
Disallow: /moc-przylaczeniowa/
Disallow: /zuzyspre/
Disallow: /aluminium/
Disallow: /moc-przylaczeniowa/
Disallow: /stal-stopowa/
Disallow: /napiecia-znamionowe/
Disallow: /rozstaw-ramion/
Disallow: /parametry-miekkie/
Disallow: /predkosc-liniowa-elektrod/
Disallow: /napiecie/
Disallow: /ilosc-przedzialow/
Disallow: /miedz/
Disallow: /wysieg-ramion/
Disallow: /praznazalodzaselebloty/
Disallow: /maksymalny-prad-zgrzewania/
Disallow: /srednica-elektrod/
Disallow: /srejakzgrzew/
Disallow: /wysjakzgrz/
Disallow: /znam-moc-100/
Disallow: /chlodzenie-wody/
Disallow: /zuzyspre/
Disallow: /liczba-stopni-regulacji/
Disallow: /pily-tasmowe/
Disallow: /wysjakzgrz/
Disallow: /stal-stopowa-blachy/
Disallow: /srejakzgrzew/
Disallow: /sila-speczajaca/
Disallow: /mosiadz-blachy/
Disallow: /stalnipretnakr/
Disallow: /ilo-imp-dla-zgr-imp/
Disallow: /chlodzenie/
Disallow: /znam-moc-zgrze/
Disallow: /wykrywane-stany-awaryjne/
Disallow: /ilosc-programow-zgrzewania/
Disallow: /rozstaw-ramion/
Disallow: /dop-tem-pra/
Disallow: /3-zmi-pra/
Disallow: /skok-elektrod/
Disallow: /stalnipretnakr/
Disallow: /napiecia-znamionowe/
Disallow: /zdolnosc-zgrzewania/
Disallow: /rodzaj-docisku/
Disallow: /maksymalna-sila-docisku/
Disallow: /pozostale-przedzialy/
Disallow: /srednica-ramion/
Disallow: /zak-reg-pra/
Disallow: /funkcja-stepper/
Disallow: /makswtoprazwa/
Disallow: /czas-narostu-pradu-slope/
Disallow: /zak-nas-pra-zgr/
Disallow: /ilosc-odczepow/
Disallow: /pra-obc-obw-el-wyk/
Disallow: /na-kazdym-stopniu/




# This robots.txt file was created by Robots.txt Rewrite plugin: https://wordpress.org/plugins/robotstxt-rewrite/

