User-agent: *
Disallow: /check/
Disallow: /contao/
Disallow: /system/
Disallow: /templates/
Disallow: /vendor/
Disallow: /share/index.php
Disallow: /build.xml
Disallow: /composer.json
Disallow: /composer.lock
Disallow: /README.md
Allow: /system/cron/cron.txt
Allow: /system/modules/*/assets/
Allow: /system/modules/*/html/
sitemap:  https://www.ppb-infolounge.de/share/sitemap-de-de.xml
sitemap:  https://www.ppb-infolounge.de/share/sitemap-en-de.xml
sitemap:  https://www.ppb-infolounge.at/share/sitemap-de-at.xml
sitemap:  https://www.ppb-infolounge.at/share/sitemap-en-at.xml
sitemap:  https://www.ppb-infolounge.com/share/sitemap-en-gb.xml
sitemap:  https://www.ppb-infolounge.com/share/sitemap-en-francebenelux.xml
sitemap:  https://www.ppb-infolounge.com/share/sitemap-fr-francebenelux.xml
sitemap:  https://www.ppb-infolounge.com/share/sitemap-en-it.xml
sitemap:  https://www.ppb-infolounge.com/share/sitemap-it-it.xml
sitemap:  https://www.ppb-infolounge.com/share/sitemap-en-scand.xml
sitemap:  https://www.ppb-infolounge.com/share/sitemap-en-cee.xml
sitemap:  https://www.ppb-infolounge.com/share/sitemap-en-fi.xml
sitemap:  https://www.ppb-infolounge.com/share/sitemap-en-pl.xml
sitemap:  https://www.ppb-infolounge.com/share/sitemap-pl-pl.xml
sitemap:  https://www.ppb-infolounge.com/share/sitemap-en-pt.xml
sitemap:  https://www.ppb-infolounge.com/share/sitemap-pt-pt.xml
sitemap:  https://www.ppb-infolounge.com/share/sitemap-en-es.xml
sitemap:  https://www.ppb-infolounge.com/share/sitemap-es-es.xml
sitemap:  https://www.ppb-infolounge.com/share/sitemap-ru-contact.xml
sitemap:  https://www.ppb-infolounge.com/share/sitemap-en-contact.xml
sitemap:  https://www.ppb-infolounge.com/share/sitemap-el-gr.xml
sitemap:  https://www.ppb-infolounge.com/share/sitemap-en-gr.xml
sitemap:  https://www.ppb-infolounge.com/share/sitemap-tr-gr.xml
sitemap:  https://www.ppb-infolounge.com/share/sitemap-de-ch.xml
sitemap:  https://www.ppb-infolounge.com/share/sitemap-en-ch.xml
sitemap:  https://www.ppb-infolounge.com/share/sitemap-fr-ch.xml
sitemap:  https://www.ppb-infolounge.com/share/sitemap-fr-tn.xml
sitemap:  https://www.ppb-infolounge.com/share/sitemap-en-tn.xml
sitemap:  https://www.ppb-infolounge.com/share/sitemap-fr-ng.xml
sitemap:  https://www.ppb-infolounge.com/share/sitemap-en-ng.xml
sitemap:  https://www.ppb-infolounge.com/share/sitemap-en-ae.xml
sitemap:  https://www.ppb-infolounge.com/share/sitemap-he-gr.xml
