User-agent: *
Disallow: /user
Disallow: /basket
Disallow: /search
Disallow: /recommend_shop
Disallow: /newsletter
Disallow: /currency
Disallow: /productsCompare
Disallow: /product_options
Disallow: /stNavigationFrontend
Disallow: /producer
Disallow: /navigation
Disallow: /webpage/regulamin.html
Disallow: /en
Disallow: /invoice
Disallow: /order
Disallow: /invoicePdf/*
Disallow: /orderPdf/*
Disallow: /stAvailabilityFrontend/showAddOverlay
Disallow: /stQuestionFrontend/showAddOverlay
Disallow: /stAvailabilityFrontend/showAddOverlay
Disallow: /stQuestionFrontend/showAddOverlay
Disallow: /*.php$
Disallow: /*.php$
Disallow: /paypal
Disallow: /webpage/witamy-ponownie.html
Disallow: /webpage/regulamin-obowiazujacy-od-dnia-25-12-2014-r.html
