User-agent: *
Disallow: /xmlrpc.php
Disallow: /*wpmp_switcher*
Disallow: /wp-admin/
Disallow: /wp-includes/
Disallow: /*wptouch*
Disallow: /?s=*
Disallow: /page/1/
Disallow: /page/2/
Disallow: /page/3/
Disallow: /page/4/
Disallow: /page/5/
Disallow: /page/6/
Disallow: /page/7/
Disallow: /page/8/
Disallow: /page/9/
Disallow: /page/10/
Disallow: /page/11/
Disallow: /page/12/
Disallow: /page/*
