User-Agent: *
Allow: /
Allow: /about-sports-medicine.html
Allow: /history.html
Allow: /honorary-members.html
Allow: /presidents.html
Allow: /executive-board.html
Allow: /committees.html
Allow: /regional-divisions-of-ptms.html
Allow: /o-ptms.html
Allow: /o-medycynie-sportowej.html
Allow: /statut-ptms.html
Allow: /regulamin-sadu-kolezenskiego.html
Allow: /regulamin-przyznawania-wyroznien-i-odznaczen.html
Allow: /historia.html
Allow: /honorowi-czlonkowie.html
Allow: /zasady-czlonkostwa.html
Allow: /zarzad-glowny.html
Allow: /komisje.html
Allow: /sekcje.html
Allow: /oddzialy.html
Allow: /walne-zebranie-czlonkow-ptms-14-11-2013-wroclaw.html
Allow: /walne-zebranie-czlonkow-ptms-14-10-2011-bydgoszcz.html
Allow: /statut-przyjety-na-walnym-zebraniu-czlonkow-ptms-w-dniu-14-10-2011-w-bydgoszczy.html
Allow: /materialy-na-walne-zebranie-czlonkow-ptms-14-10-2011-bydgoszcz.html
Allow: /udzial-w-efsma.html
Allow: /sports-medicine-speciality-training-core-curriculum-for-european-countries.html
Allow: /sports-medicine-speciality-training-core-curriculum-in-poland.html
Allow: /efsma-accredited-sports-medicine-centers.html
Allow: /recommendations.html
Allow: /stanowiska-ptms.html
Allow: /materialy-edukacyjne.html
Allow: /certyfikat-ptms.html
Allow: /regulamin-uzyskiwania-certyfikatu-ptms.html
Allow: /obowiazujacy-wzor-pieczatki.html
Allow: /regulamin-egzaminu-abc-medycyny-sportowej.html
Allow: /oplaty.html
Allow: /biuro-certyfikatow.html
Allow: /regulamin-biura-certyfikatow.html
Allow: /kursy-do-certyfikatu-ptms.html
Allow: /specjalizacja-w-medycynie-sportowej-w-polsce.html
Allow: /specjalizacja-w-medycynie-sportowej-w-ue-projekt.html
Allow: /konsultanci-wojewodzcy.html
Allow: /zjazdy-i-kongresy-ptms.html
Allow: /zjazdy-ptms-w-latach-1937-2013.html
Allow: /inne-kongresy.html
Allow: /congresses-of-polish-society-of-sports-medicine.html
Allow: /czasopisma.html
Allow: /ksiazki.html
Allow: /journals.html
Allow: /books.html
Allow: /legislacja.html
Allow: /linki.html
Allow: /kontakt.html
Allow: /contact.html


