User-agent: *
Disallow: /config/
Disallow: /functions/
Disallow: /tools/
Disallow: /download/
Disallow: /ftp/
Disallow: /help/
Disallow: /tmp/
Disallow: /banery/
Disallow: /banners/
Disallow: /bannersOK/
Disallow: /tmpx/
Disallow: /modules/
Disallow: /classes/
Disallow: /stopki/
Disallow: /manual/
Disallow: /include/
Disallow: /theme/
Disallow: /block/
Disallow: /block_top/
Disallow: /cronOLD/
Disallow: /cron/
Disallow: /images/
Disallow: /ico/
Disallow: /swf/
Disallow: /theme/
Disallow: /proftp/
Disallow: /lib/
Disallow: /stopki/
Disallow: /libjs/
Disallow: /adm/
Disallow: /edit/
Disallow: /ImageManager/
Disallow: confadd.php
Disallow: edit_dzialy.php
Disallow: edit_gminy.php
Disallow: read_config.php
Disallow: edit.php
Disallow: functions.php
Disallow: configure.php
Disallow: config.php
Disallow: login.php
Disallow: cron.php
Disallow: mainfile.php
Disallow: firma.php
Disallow: explorer.php
Disallow: header.php
Disallow: he.js
Disallow: mapa.php
Disallow: footer.php
Disallow: popupradio.php
Disallow: cron2.php

