User-agent: *
Disallow: /user
Disallow: /basket
Disallow: /search
Disallow: /recommend_shop
Disallow: /newsletter
Disallow: /currency
Disallow: /productsCompare
Disallow: /product_options
Disallow: /stNavigationFrontend
Disallow: /producer
Disallow: /navigation
Disallow: /value.html
Disallow: */showAddOverlay
Disallow: /invoice
Disallow: /order
Disallow: /invoicePdf/*
Disallow: /orderPdf/*
Disallow: /stAvailabilityFrontend/showAddOverlay
Disallow: /stQuestionFrontend/showAddOverlay
Disallow: /stAvailabilityFrontend/showAddOverlay
Disallow: /stQuestionFrontend/showAddOverlay
User-agent: Googlebot
User-agent: Googlebot-image
Disallow: /*.php$
Disallow: /paypal

Sitemap: https://medyczny.pl/sitemap_pl.xml
