User-agent: *
Disallow: /_borders/
Disallow: /_fpclass/
Disallow: /_frontlook/
Disallow: /_images/
Disallow: /_private/
Disallow: /_styles/
Disallow: /_overlay/
Disallow: /_themes/
Disallow: /images/
Disallow: /old/
Disallow: /libs/
Disallow: /robocze/
Disallow: /kids/
Disallow: /rodzina/
Disallow: /rodzina/rod
Disallow: /isia/
Disallow: /wicio/
Disallow: /julek/
Disallow: /rodzina/rod/
Disallow: /nepomuk/bractwo
Disallow: _rodzinaArrays.js
Disallow: Isia*.*
Disallow: Wicio*.*
Disallow: Julek*.*
Disallow: ASW*.*
Disallow: TW*.*
Disallow: BW*.*
Disallow: KW*.*
