User-agent: *
Disallow: /administrator
Disallow: /cache
Disallow: /eres
Disallow: /includes
Disallow: /language
Disallow: /libraries
Disallow: /logs
Disallow: /jovy2017
Disallow: /jovy2018
Disallow: /modules
Disallow: /plugins
Disallow: /portal
Disallow: /reklamacje
Disallow: /templates/hotair1
Disallow: /templates/system
Disallow: /tmp
Disallow: /xmlrpc
Disallow: /components/com_annonces
Disallow: /components/com_banners
Disallow: /components/com_contact
Disallow: /components/com_content
Disallow: /components/com_easycomments
Disallow: /components/com_joomdoc
Disallow: /components/com_joomfish
Disallow: /components/com_joomlapack
Disallow: /components/com_mailto
Disallow: /components/com_media
Disallow: /components/com_newsfeeds
Disallow: /components/com_nowe_haslo
Disallow: /components/com_poll
Disallow: /components/com_redj
Disallow: /components/com_reklamacje
Disallow: /components/com_search
Disallow: /components/com_serwisreklamacji
Disallow: /components/com_ssvirtuecsv
Disallow: /components/com_synchronizacja
Disallow: /components/com_test
Disallow: /components/com_user
Disallow: /components/com_vmsef
Disallow: /components/com_waticketsystem
Disallow: /components/com_weblinks
Disallow: /components/com_wrappercom_xmap
Disallow: /components/com_virtuemart/js
Disallow: /components/com_virtuemart/themes
Allow: /components/com_virtuemart/shop_image
Allow: /components/com_virtuemart/shop_image/product
Allow: /modules/mod_djimageslider
Allow: /resources/js/*.js$
Allow: /resources/css/*.css$
Allow: /widget/*
Sitemap:http://www.hotair.pl/index.php?option=com_xmap&sitemap=1&view=xml

User-agent: bingbot
Disallow: /

