User-agent: *
Crawl-delay: 30
Request-rate: 1/1s

User-agent: *
Allow: /environment/cache/images/
Allow: Pufy-tapicerowane/13/1/default/1/f_ov_1_13/1
Allow: Pufy-tapicerowane/13/1/default/1/f_ov_6_10/1
Disallow: /application/
Disallow: /environment/
Disallow: /libraries/
Disallow: /*/fav/add/
Disallow: /*/p/comment/add/
Disallow: /*/p/mail/recommend/
Disallow: /*/p/q/
Disallow: /*/reg/
Disallow: /*/login/
Disallow: /*/basket/
Disallow: /*/searchquery/
Disallow: /*/new/*/default/*
Disallow: /*/promotions/*/default/*
Disallow: /*/i/Regulamin/3
Disallow: /*/i/Polityka-prywatnosci/11
Disallow: /*/basket/add/
Disallow: /*/new/*/full/*
Disallow: /*/promotions/*/phot/*
Disallow: /*/new/*/phot/*
Disallow: /*/promotions/*/full/*
Disallow: /*/index/*
Disallow: /*/i/Polityka-prywatnosci-i-Cookies/11

User-agent: Googlebot
Allow: /environment/cache/images/
Allow: Pufy-tapicerowane/13/1/default/1/f_ov_1_13/1
Allow: Pufy-tapicerowane/13/1/default/1/f_ov_6_10/1
Disallow: /application/
Disallow: /environment/
Disallow: /libraries/
Disallow: /*/fav/add/
Disallow: /*/basket/add/
Disallow: /*/p/comment/add/
Disallow: /*/p/mail/recommend/
Disallow: /*/p/q/
Disallow: /*/reg
Disallow: /*/login
Disallow: /*/i/Regulamin/3
Disallow: /*/basket
Disallow: /*/searchquery/*
Disallow: /*/basket/add/
Disallow: /*/i/Polityka-prywatnosci/11
Disallow: /*/new/*/default/*
Disallow: /*/promotions/*/default/*
Disallow: /*/new/*/full/*
Disallow: /*/promotions/*/phot/*
Disallow: /*/new/*/phot/*
Disallow: /*/promotions/*/full/*
Disallow: /*/index/*
Disallow: /*/i/Polityka-prywatnosci-i-Cookies/11


