User-agent: *
Disallow: /admin/
Disallow: /compare
Disallow: /include/language.js.php
Disallow: /themes/js/cs_info.php
Disallow: /themes/js/cs_info.php
Disallow: /question_*
Disallow: /notify_*
Disallow: /recommend_*
Disallow: /index.php?do=comment*
Disallow: /contact
Disallow: /artykuly-sg-g10003
Disallow: /alba-710-c17446
Disallow: /antic-1873-c17439
Disallow: /sabiaduo-2963-c17430
Disallow: /storage
Disallow: /registration
Disallow: /login
Disallow: /terms_and_conditions
Disallow: /shopcart
Disallow: /include/:url_login
Disallow: /include/%5B%base_url%%5Dregistration
Disallow: /include/%5B%base_url%%5Dterms_and_conditions
Disallow: /include/search
Disallow: /include/www.facebook.com/aquasanita24
Disallow: /themes/js/cs_info.php
Disallow: /include/language.js.php
User-agent: *
Disallow: /
User-agent: Googlebot
Allow: /
User-agent: Slurp
Allow: /
User-Agent: msnbot
Disallow:
