User-agent: *
Allow: /
Disallow: /administrator/
Disallow: /cache/
Disallow: /cgi-bin/
Disallow: /components/
Disallow: /images/
Disallow: /includes/
Disallow: /installation/
Disallow: /language/
Disallow: /libraries/
Disallow: /media/
Disallow: /modules/
Disallow: /plugins/
Disallow: /templates/
Disallow: /tmp/
Disallow: /xmlrpc/
Disallow: /component/
Sitemap: http://www.smerfiki.waw.pl/index.php?option=com_xmap&sitemap=1&view=xml
