User-agent: *
Disallow: /www/administrator/
Disallow: /www/cache/
Disallow: /www/components/
Disallow: /www/editor/
Disallow: /www/help/
Disallow: /www/images/
Disallow: /www/includes/
Disallow: /www/language/
Disallow: /www/mambots/
Disallow: /www/media/
Disallow: /www/modules/
Disallow: /www/templates/
Disallow: /www/installation/
Disallow: /forum/latarki/
Disallow: /www/forum/
Disallow: /forum/Themes/
Disallow: /Themes
Disallow: /migracja/
Disallow: /attachments/
Disallow: /avatars/
Disallow: /FCKeditor/
Disallow: /forum_old/
Disallow: /gallery/
Disallow: /Packages/
Disallow: /Smileys/
Disallow: /Sources/
Disallow: /Themes/
Disallow: /tp-downloads/
Disallow: /tp-images/
Disallow: /wysiwyg/
