User-agent: *
Disallow: /galeria/
Disallow: /recenzje/
Disallow: /forum/admin/
Disallow: /forum/files/
Disallow: /forum/cache/
Disallow: /forum/templates/
Disallow: /administrator/
Disallow: /cache/
Disallow: /components/
Disallow: /editor/
Disallow: /help/
Disallow: /images/
Disallow: /includes/
Disallow: /language/
Disallow: /mambots/
Disallow: /media/
Disallow: /modules/
Disallow: /templates/
Disallow: /installation/
Disallow: /virtual/raporty/

