User-agent: *
Disallow: /arch/
Disallow: /csubskrypcja/
Disallow: /nowy/
Disallow: /pub/
Disallow: /temp/
Disallow: /test/
Disallow: /work/
Disallow: /rsi013/
Disallow: /kalendarz/
Disallow: /konf013/
Disallow: /upload/
Disallow: /sender/
Disallow: /pub_xc132as/
Disallow: /fotolab/
Disallow: /fotv/
Disallow: /main/
Disallow: /dd/
