# In ANY CASE, you are NOT ALLOWED to train Machine Translation Systems
# on data crawled on Linguee.
#
# Linguee contains fake entries - changes in the wording of sentences,
# complete fake entries.
# These entries can be used to identify even small parts of our material
# if you try to copy it without our permission.
# Machine Translation systems trained on these data will learn these errors
# and can be identified easily. We will take all legal measures against anyone
# training Machine Translation systems on data crawled from this website.

User-agent: Ask Jeeves/Teoma
Disallow: /page/forward.php
Allow: /

User-agent: Googlebot/2.1
Disallow: /*.html=$
Disallow: /*identifier=$
Disallow: /*identifyer=$
Disallow: /*bid=*
Disallow: /*moreResults=1*

Allow: /english-polish/sitemap
Allow: /polish-english/sitemap
Allow: /english-polish/top
Allow: /polish-english/top
Disallow: /translation
Disallow: /german-english
Disallow: /english-german
Disallow: /french-english
Disallow: /english-french
Disallow: /spanish-english
Disallow: /english-spanish
Disallow: /portuguese-english
Disallow: /english-portuguese
Disallow: /english-polish
Disallow: /english-russian
Disallow: /english-italian
Disallow: /english-dutch
Disallow: /english-chinese
Disallow: /english-japanese
Disallow: /polish-english
Disallow: /russian-english
Disallow: /italian-english
Disallow: /dutch-english
Disallow: /chinese-english
Disallow: /japanese-english
Disallow: /uebersetzung
Disallow: /deutsch-englisch
Disallow: /englisch-deutsch
Disallow: /spanisch-englisch
Disallow: /englisch-spanisch
Disallow: /franzoesisch-englisch
Disallow: /englisch-franzoesisch
Disallow: /portugiesisch-englisch
Disallow: /englisch-portugiesisch
Disallow: /deutsch-franzoesisch
Disallow: /franzoesisch-deutsch
Disallow: /deutsch-spanisch
Disallow: /spanisch-deutsch
Disallow: /deutsch-portugiesisch
Disallow: /portugiesisch-deutsch
Disallow: /francais-anglais
Disallow: /anglais-francais
Disallow: /francais-allemand
Disallow: /allemand-francais
Disallow: /francais-espagnol
Disallow: /espagnol-francais
Disallow: /francais-portugais
Disallow: /portugais-francais
Disallow: /ingles-espanol
Disallow: /espanol-ingles
Disallow: /aleman-espanol
Disallow: /espanol-aleman
Disallow: /frances-espanol
Disallow: /espanol-frances
Disallow: /portugues-espanol
Disallow: /espanol-portugues
Disallow: /ingles-portugues
Disallow: /portugues-ingles
Disallow: /alemao-portugues
Disallow: /portugues-alemao
Disallow: /espanhol-portugues
Disallow: /portugues-espanhol
Disallow: /frances-portugues
Disallow: /portugues-frances
Disallow: /russkii-angliiskii
Disallow: /angliiskii-russkii
Disallow: /italiano-inglese
Disallow: /inglese-italiano
Disallow: /nederlands-engels
Disallow: /engels-nederlands
Disallow: /Zhong Wen -Ying Yu 
Disallow: /Ying Yu -Zhong Wen 
Disallow: /Ri Ben Yu -Ying Yu 
Disallow: /Ying Yu -Ri Ben Yu 
Disallow: /page/forward.php
Allow: /

User-agent: Googlebot
Disallow: /*.html=$
Disallow: /*identifier=$
Disallow: /*identifyer=$
Disallow: /*bid=*
Disallow: /*moreResults=1*
Allow: /english-polish/sitemap
Allow: /polish-english/sitemap
Allow: /english-polish/top
Allow: /polish-english/top
Disallow: /translation
Disallow: /german-english
Disallow: /english-german
Disallow: /french-english
Disallow: /english-french
Disallow: /spanish-english
Disallow: /english-spanish
Disallow: /portuguese-english
Disallow: /english-portuguese
Disallow: /english-polish
Disallow: /english-russian
Disallow: /english-italian
Disallow: /english-dutch
Disallow: /english-chinese
Disallow: /english-japanese
Disallow: /polish-english
Disallow: /russian-english
Disallow: /italian-english
Disallow: /dutch-english
Disallow: /chinese-english
Disallow: /japanese-english
Disallow: /uebersetzung
Disallow: /deutsch-englisch
Disallow: /englisch-deutsch
Disallow: /spanisch-englisch
Disallow: /englisch-spanisch
Disallow: /franzoesisch-englisch
Disallow: /englisch-franzoesisch
Disallow: /portugiesisch-englisch
Disallow: /englisch-portugiesisch
Disallow: /deutsch-franzoesisch
Disallow: /franzoesisch-deutsch
Disallow: /deutsch-spanisch
Disallow: /spanisch-deutsch
Disallow: /deutsch-portugiesisch
Disallow: /portugiesisch-deutsch
Disallow: /francais-anglais
Disallow: /anglais-francais
Disallow: /francais-allemand
Disallow: /allemand-francais
Disallow: /francais-espagnol
Disallow: /espagnol-francais
Disallow: /francais-portugais
Disallow: /portugais-francais
Disallow: /ingles-espanol
Disallow: /espanol-ingles
Disallow: /aleman-espanol
Disallow: /espanol-aleman
Disallow: /frances-espanol
Disallow: /espanol-frances
Disallow: /portugues-espanol
Disallow: /espanol-portugues
Disallow: /ingles-portugues
Disallow: /portugues-ingles
Disallow: /alemao-portugues
Disallow: /portugues-alemao
Disallow: /espanhol-portugues
Disallow: /portugues-espanhol
Disallow: /frances-portugues
Disallow: /portugues-frances
Disallow: /russkii-angliiskii
Disallow: /angliiskii-russkii
Disallow: /italiano-inglese
Disallow: /inglese-italiano
Disallow: /nederlands-engels
Disallow: /engels-nederlands
Disallow: /Zhong Wen -Ying Yu 
Disallow: /Ying Yu -Zhong Wen 
Disallow: /Ri Ben Yu -Ying Yu 
Disallow: /Ying Yu -Ri Ben Yu 
Disallow: /page/forward.php
Disallow: /linkPartToTranslation*
Allow: /

User-agent: Mediapartners-Google*
Disallow: /*.html=$
Disallow: /*identifier=$
Disallow: /*identifyer=$
Disallow: /*bid=*
Disallow: /*moreResults=1*
Allow: /english-polish/sitemap
Allow: /polish-english/sitemap
Allow: /english-polish/top
Allow: /polish-english/top
Disallow: /translation
Disallow: /german-english
Disallow: /english-german
Disallow: /french-english
Disallow: /english-french
Disallow: /spanish-english
Disallow: /english-spanish
Disallow: /portuguese-english
Disallow: /english-portuguese
Disallow: /english-polish
Disallow: /english-russian
Disallow: /english-italian
Disallow: /english-dutch
Disallow: /english-chinese
Disallow: /english-japanese
Disallow: /polish-english
Disallow: /russian-english
Disallow: /italian-english
Disallow: /dutch-english
Disallow: /chinese-english
Disallow: /japanese-english
Disallow: /uebersetzung
Disallow: /deutsch-englisch
Disallow: /englisch-deutsch
Disallow: /spanisch-englisch
Disallow: /englisch-spanisch
Disallow: /franzoesisch-englisch
Disallow: /englisch-franzoesisch
Disallow: /portugiesisch-englisch
Disallow: /englisch-portugiesisch
Disallow: /deutsch-franzoesisch
Disallow: /franzoesisch-deutsch
Disallow: /deutsch-spanisch
Disallow: /spanisch-deutsch
Disallow: /deutsch-portugiesisch
Disallow: /portugiesisch-deutsch
Disallow: /francais-anglais
Disallow: /anglais-francais
Disallow: /francais-allemand
Disallow: /allemand-francais
Disallow: /francais-espagnol
Disallow: /espagnol-francais
Disallow: /francais-portugais
Disallow: /portugais-francais
Disallow: /ingles-espanol
Disallow: /espanol-ingles
Disallow: /aleman-espanol
Disallow: /espanol-aleman
Disallow: /frances-espanol
Disallow: /espanol-frances
Disallow: /portugues-espanol
Disallow: /espanol-portugues
Disallow: /ingles-portugues
Disallow: /portugues-ingles
Disallow: /alemao-portugues
Disallow: /portugues-alemao
Disallow: /espanhol-portugues
Disallow: /portugues-espanhol
Disallow: /frances-portugues
Disallow: /portugues-frances
Disallow: /russkii-angliiskii
Disallow: /angliiskii-russkii
Disallow: /italiano-inglese
Disallow: /inglese-italiano
Disallow: /nederlands-engels
Disallow: /engels-nederlands
Disallow: /Zhong Wen -Ying Yu 
Disallow: /Ying Yu -Zhong Wen 
Disallow: /Ri Ben Yu -Ying Yu 
Disallow: /Ying Yu -Ri Ben Yu 
Disallow: /page/forward.php
Allow: /

User-agent: Yahoo! Slurp
Allow: /english-polish/sitemap
Allow: /polish-english/sitemap
Allow: /english-polish/top
Allow: /polish-english/top
Disallow: /translation
Disallow: /german-english
Disallow: /english-german
Disallow: /french-english
Disallow: /english-french
Disallow: /spanish-english
Disallow: /english-spanish
Disallow: /portuguese-english
Disallow: /english-portuguese
Disallow: /english-polish
Disallow: /english-russian
Disallow: /english-italian
Disallow: /english-dutch
Disallow: /english-chinese
Disallow: /english-japanese
Disallow: /polish-english
Disallow: /russian-english
Disallow: /italian-english
Disallow: /dutch-english
Disallow: /chinese-english
Disallow: /japanese-english
Disallow: /uebersetzung
Disallow: /deutsch-englisch
Disallow: /englisch-deutsch
Disallow: /spanisch-englisch
Disallow: /englisch-spanisch
Disallow: /franzoesisch-englisch
Disallow: /englisch-franzoesisch
Disallow: /portugiesisch-englisch
Disallow: /englisch-portugiesisch
Disallow: /deutsch-franzoesisch
Disallow: /franzoesisch-deutsch
Disallow: /deutsch-spanisch
Disallow: /spanisch-deutsch
Disallow: /deutsch-portugiesisch
Disallow: /portugiesisch-deutsch
Disallow: /francais-anglais
Disallow: /anglais-francais
Disallow: /francais-allemand
Disallow: /allemand-francais
Disallow: /francais-espagnol
Disallow: /espagnol-francais
Disallow: /francais-portugais
Disallow: /portugais-francais
Disallow: /ingles-espanol
Disallow: /espanol-ingles
Disallow: /aleman-espanol
Disallow: /espanol-aleman
Disallow: /frances-espanol
Disallow: /espanol-frances
Disallow: /portugues-espanol
Disallow: /espanol-portugues
Disallow: /ingles-portugues
Disallow: /portugues-ingles
Disallow: /alemao-portugues
Disallow: /portugues-alemao
Disallow: /espanhol-portugues
Disallow: /portugues-espanhol
Disallow: /frances-portugues
Disallow: /portugues-frances
Disallow: /russkii-angliiskii
Disallow: /angliiskii-russkii
Disallow: /italiano-inglese
Disallow: /inglese-italiano
Disallow: /nederlands-engels
Disallow: /engels-nederlands
Disallow: /Zhong Wen -Ying Yu 
Disallow: /Ying Yu -Zhong Wen 
Disallow: /Ri Ben Yu -Ying Yu 
Disallow: /Ying Yu -Ri Ben Yu 
Disallow: /page/forward.php
Allow: /

User-agent: Yahoo!
Allow: /english-polish/sitemap
Allow: /polish-english/sitemap
Allow: /english-polish/top
Allow: /polish-english/top
Disallow: /translation
Disallow: /german-english
Disallow: /english-german
Disallow: /french-english
Disallow: /english-french
Disallow: /spanish-english
Disallow: /english-spanish
Disallow: /portuguese-english
Disallow: /english-portuguese
Disallow: /english-polish
Disallow: /english-russian
Disallow: /english-italian
Disallow: /english-dutch
Disallow: /english-chinese
Disallow: /english-japanese
Disallow: /polish-english
Disallow: /russian-english
Disallow: /italian-english
Disallow: /dutch-english
Disallow: /chinese-english
Disallow: /japanese-english
Disallow: /uebersetzung
Disallow: /deutsch-englisch
Disallow: /englisch-deutsch
Disallow: /spanisch-englisch
Disallow: /englisch-spanisch
Disallow: /franzoesisch-englisch
Disallow: /englisch-franzoesisch
Disallow: /portugiesisch-englisch
Disallow: /englisch-portugiesisch
Disallow: /deutsch-franzoesisch
Disallow: /franzoesisch-deutsch
Disallow: /deutsch-spanisch
Disallow: /spanisch-deutsch
Disallow: /deutsch-portugiesisch
Disallow: /portugiesisch-deutsch
Disallow: /francais-anglais
Disallow: /anglais-francais
Disallow: /francais-allemand
Disallow: /allemand-francais
Disallow: /francais-espagnol
Disallow: /espagnol-francais
Disallow: /francais-portugais
Disallow: /portugais-francais
Disallow: /ingles-espanol
Disallow: /espanol-ingles
Disallow: /aleman-espanol
Disallow: /espanol-aleman
Disallow: /frances-espanol
Disallow: /espanol-frances
Disallow: /portugues-espanol
Disallow: /espanol-portugues
Disallow: /ingles-portugues
Disallow: /portugues-ingles
Disallow: /alemao-portugues
Disallow: /portugues-alemao
Disallow: /espanhol-portugues
Disallow: /portugues-espanhol
Disallow: /frances-portugues
Disallow: /portugues-frances
Disallow: /russkii-angliiskii
Disallow: /angliiskii-russkii
Disallow: /italiano-inglese
Disallow: /inglese-italiano
Disallow: /nederlands-engels
Disallow: /engels-nederlands
Disallow: /Zhong Wen -Ying Yu 
Disallow: /Ying Yu -Zhong Wen 
Disallow: /Ri Ben Yu -Ying Yu 
Disallow: /Ying Yu -Ri Ben Yu 
Disallow: /page/forward.php
Allow: /

User-agent: msnbot/1.1
Allow: /english-polish/sitemap
Allow: /polish-english/sitemap
Allow: /english-polish/top
Allow: /polish-english/top
Disallow: /translation
Disallow: /german-english
Disallow: /english-german
Disallow: /french-english
Disallow: /english-french
Disallow: /spanish-english
Disallow: /english-spanish
Disallow: /portuguese-english
Disallow: /english-portuguese
Disallow: /english-polish
Disallow: /english-russian
Disallow: /english-italian
Disallow: /english-dutch
Disallow: /english-chinese
Disallow: /english-japanese
Disallow: /polish-english
Disallow: /russian-english
Disallow: /italian-english
Disallow: /dutch-english
Disallow: /chinese-english
Disallow: /japanese-english
Disallow: /uebersetzung
Disallow: /deutsch-englisch
Disallow: /englisch-deutsch
Disallow: /spanisch-englisch
Disallow: /englisch-spanisch
Disallow: /franzoesisch-englisch
Disallow: /englisch-franzoesisch
Disallow: /portugiesisch-englisch
Disallow: /englisch-portugiesisch
Disallow: /deutsch-franzoesisch
Disallow: /franzoesisch-deutsch
Disallow: /deutsch-spanisch
Disallow: /spanisch-deutsch
Disallow: /deutsch-portugiesisch
Disallow: /portugiesisch-deutsch
Disallow: /francais-anglais
Disallow: /anglais-francais
Disallow: /francais-allemand
Disallow: /allemand-francais
Disallow: /francais-espagnol
Disallow: /espagnol-francais
Disallow: /francais-portugais
Disallow: /portugais-francais
Disallow: /ingles-espanol
Disallow: /espanol-ingles
Disallow: /aleman-espanol
Disallow: /espanol-aleman
Disallow: /frances-espanol
Disallow: /espanol-frances
Disallow: /portugues-espanol
Disallow: /espanol-portugues
Disallow: /ingles-portugues
Disallow: /portugues-ingles
Disallow: /alemao-portugues
Disallow: /portugues-alemao
Disallow: /espanhol-portugues
Disallow: /portugues-espanhol
Disallow: /frances-portugues
Disallow: /portugues-frances
Disallow: /russkii-angliiskii
Disallow: /angliiskii-russkii
Disallow: /italiano-inglese
Disallow: /inglese-italiano
Disallow: /nederlands-engels
Disallow: /engels-nederlands
Disallow: /Zhong Wen -Ying Yu 
Disallow: /Ying Yu -Zhong Wen 
Disallow: /Ri Ben Yu -Ying Yu 
Disallow: /Ying Yu -Ri Ben Yu 
Disallow: /page/forward.php
Allow: /

User-agent: bingbot
Allow: /english-polish/sitemap
Allow: /polish-english/sitemap
Allow: /english-polish/top
Allow: /polish-english/top
Disallow: /translation
Disallow: /german-english
Disallow: /english-german
Disallow: /french-english
Disallow: /english-french
Disallow: /spanish-english
Disallow: /english-spanish
Disallow: /portuguese-english
Disallow: /english-portuguese
Disallow: /english-polish
Disallow: /english-russian
Disallow: /english-italian
Disallow: /english-dutch
Disallow: /english-chinese
Disallow: /english-japanese
Disallow: /polish-english
Disallow: /russian-english
Disallow: /italian-english
Disallow: /dutch-english
Disallow: /chinese-english
Disallow: /japanese-english
Disallow: /uebersetzung
Disallow: /deutsch-englisch
Disallow: /englisch-deutsch
Disallow: /spanisch-englisch
Disallow: /englisch-spanisch
Disallow: /franzoesisch-englisch
Disallow: /englisch-franzoesisch
Disallow: /portugiesisch-englisch
Disallow: /englisch-portugiesisch
Disallow: /deutsch-franzoesisch
Disallow: /franzoesisch-deutsch
Disallow: /deutsch-spanisch
Disallow: /spanisch-deutsch
Disallow: /deutsch-portugiesisch
Disallow: /portugiesisch-deutsch
Disallow: /francais-anglais
Disallow: /anglais-francais
Disallow: /francais-allemand
Disallow: /allemand-francais
Disallow: /francais-espagnol
Disallow: /espagnol-francais
Disallow: /francais-portugais
Disallow: /portugais-francais
Disallow: /ingles-espanol
Disallow: /espanol-ingles
Disallow: /aleman-espanol
Disallow: /espanol-aleman
Disallow: /frances-espanol
Disallow: /espanol-frances
Disallow: /portugues-espanol
Disallow: /espanol-portugues
Disallow: /ingles-portugues
Disallow: /portugues-ingles
Disallow: /alemao-portugues
Disallow: /portugues-alemao
Disallow: /espanhol-portugues
Disallow: /portugues-espanhol
Disallow: /frances-portugues
Disallow: /portugues-frances
Disallow: /russkii-angliiskii
Disallow: /angliiskii-russkii
Disallow: /italiano-inglese
Disallow: /inglese-italiano
Disallow: /nederlands-engels
Disallow: /engels-nederlands
Disallow: /Zhong Wen -Ying Yu 
Disallow: /Ying Yu -Zhong Wen 
Disallow: /Ri Ben Yu -Ying Yu 
Disallow: /Ying Yu -Ri Ben Yu 
Disallow: /page/forward.php
Allow: /

User-agent: msnbot
Allow: /english-polish/sitemap
Allow: /polish-english/sitemap
Allow: /english-polish/top
Allow: /polish-english/top
Disallow: /translation
Disallow: /german-english
Disallow: /english-german
Disallow: /french-english
Disallow: /english-french
Disallow: /spanish-english
Disallow: /english-spanish
Disallow: /portuguese-english
Disallow: /english-portuguese
Disallow: /english-polish
Disallow: /english-russian
Disallow: /english-italian
Disallow: /english-dutch
Disallow: /english-chinese
Disallow: /english-japanese
Disallow: /polish-english
Disallow: /russian-english
Disallow: /italian-english
Disallow: /dutch-english
Disallow: /chinese-english
Disallow: /japanese-english
Disallow: /uebersetzung
Disallow: /deutsch-englisch
Disallow: /englisch-deutsch
Disallow: /spanisch-englisch
Disallow: /englisch-spanisch
Disallow: /franzoesisch-englisch
Disallow: /englisch-franzoesisch
Disallow: /portugiesisch-englisch
Disallow: /englisch-portugiesisch
Disallow: /deutsch-franzoesisch
Disallow: /franzoesisch-deutsch
Disallow: /deutsch-spanisch
Disallow: /spanisch-deutsch
Disallow: /deutsch-portugiesisch
Disallow: /portugiesisch-deutsch
Disallow: /francais-anglais
Disallow: /anglais-francais
Disallow: /francais-allemand
Disallow: /allemand-francais
Disallow: /francais-espagnol
Disallow: /espagnol-francais
Disallow: /francais-portugais
Disallow: /portugais-francais
Disallow: /ingles-espanol
Disallow: /espanol-ingles
Disallow: /aleman-espanol
Disallow: /espanol-aleman
Disallow: /frances-espanol
Disallow: /espanol-frances
Disallow: /portugues-espanol
Disallow: /espanol-portugues
Disallow: /ingles-portugues
Disallow: /portugues-ingles
Disallow: /alemao-portugues
Disallow: /portugues-alemao
Disallow: /espanhol-portugues
Disallow: /portugues-espanhol
Disallow: /frances-portugues
Disallow: /portugues-frances
Disallow: /russkii-angliiskii
Disallow: /angliiskii-russkii
Disallow: /italiano-inglese
Disallow: /inglese-italiano
Disallow: /nederlands-engels
Disallow: /engels-nederlands
Disallow: /Zhong Wen -Ying Yu 
Disallow: /Ying Yu -Zhong Wen 
Disallow: /Ri Ben Yu -Ying Yu 
Disallow: /Ying Yu -Ri Ben Yu 
Disallow: /page/forward.php
Allow: /

User-agent: msnbot-media/1.0
Allow: /english-polish/sitemap
Allow: /polish-english/sitemap
Allow: /english-polish/top
Allow: /polish-english/top
Disallow: /translation
Disallow: /german-english
Disallow: /english-german
Disallow: /french-english
Disallow: /english-french
Disallow: /spanish-english
Disallow: /english-spanish
Disallow: /portuguese-english
Disallow: /english-portuguese
Disallow: /english-polish
Disallow: /english-russian
Disallow: /english-italian
Disallow: /english-dutch
Disallow: /english-chinese
Disallow: /english-japanese
Disallow: /polish-english
Disallow: /russian-english
Disallow: /italian-english
Disallow: /dutch-english
Disallow: /chinese-english
Disallow: /japanese-english
Disallow: /uebersetzung
Disallow: /deutsch-englisch
Disallow: /englisch-deutsch
Disallow: /spanisch-englisch
Disallow: /englisch-spanisch
Disallow: /franzoesisch-englisch
Disallow: /englisch-franzoesisch
Disallow: /portugiesisch-englisch
Disallow: /englisch-portugiesisch
Disallow: /deutsch-franzoesisch
Disallow: /franzoesisch-deutsch
Disallow: /deutsch-spanisch
Disallow: /spanisch-deutsch
Disallow: /deutsch-portugiesisch
Disallow: /portugiesisch-deutsch
Disallow: /francais-anglais
Disallow: /anglais-francais
Disallow: /francais-allemand
Disallow: /allemand-francais
Disallow: /francais-espagnol
Disallow: /espagnol-francais
Disallow: /francais-portugais
Disallow: /portugais-francais
Disallow: /ingles-espanol
Disallow: /espanol-ingles
Disallow: /aleman-espanol
Disallow: /espanol-aleman
Disallow: /frances-espanol
Disallow: /espanol-frances
Disallow: /portugues-espanol
Disallow: /espanol-portugues
Disallow: /ingles-portugues
Disallow: /portugues-ingles
Disallow: /alemao-portugues
Disallow: /portugues-alemao
Disallow: /espanhol-portugues
Disallow: /portugues-espanhol
Disallow: /frances-portugues
Disallow: /portugues-frances
Disallow: /russkii-angliiskii
Disallow: /angliiskii-russkii
Disallow: /italiano-inglese
Disallow: /inglese-italiano
Disallow: /nederlands-engels
Disallow: /engels-nederlands
Disallow: /Zhong Wen -Ying Yu 
Disallow: /Ying Yu -Zhong Wen 
Disallow: /Ri Ben Yu -Ying Yu 
Disallow: /Ying Yu -Ri Ben Yu 
Disallow: /page/forward.php
Allow: /

User-agent: msnbot-media
Allow: /english-polish/sitemap
Allow: /polish-english/sitemap
Allow: /english-polish/top
Allow: /polish-english/top
Disallow: /translation
Disallow: /german-english
Disallow: /english-german
Disallow: /french-english
Disallow: /english-french
Disallow: /spanish-english
Disallow: /english-spanish
Disallow: /portuguese-english
Disallow: /english-portuguese
Disallow: /english-polish
Disallow: /english-russian
Disallow: /english-italian
Disallow: /english-dutch
Disallow: /english-chinese
Disallow: /english-japanese
Disallow: /polish-english
Disallow: /russian-english
Disallow: /italian-english
Disallow: /dutch-english
Disallow: /chinese-english
Disallow: /japanese-english
Disallow: /uebersetzung
Disallow: /deutsch-englisch
Disallow: /englisch-deutsch
Disallow: /spanisch-englisch
Disallow: /englisch-spanisch
Disallow: /franzoesisch-englisch
Disallow: /englisch-franzoesisch
Disallow: /portugiesisch-englisch
Disallow: /englisch-portugiesisch
Disallow: /deutsch-franzoesisch
Disallow: /franzoesisch-deutsch
Disallow: /deutsch-spanisch
Disallow: /spanisch-deutsch
Disallow: /deutsch-portugiesisch
Disallow: /portugiesisch-deutsch
Disallow: /francais-anglais
Disallow: /anglais-francais
Disallow: /francais-allemand
Disallow: /allemand-francais
Disallow: /francais-espagnol
Disallow: /espagnol-francais
Disallow: /francais-portugais
Disallow: /portugais-francais
Disallow: /ingles-espanol
Disallow: /espanol-ingles
Disallow: /aleman-espanol
Disallow: /espanol-aleman
Disallow: /frances-espanol
Disallow: /espanol-frances
Disallow: /portugues-espanol
Disallow: /espanol-portugues
Disallow: /ingles-portugues
Disallow: /portugues-ingles
Disallow: /alemao-portugues
Disallow: /portugues-alemao
Disallow: /espanhol-portugues
Disallow: /portugues-espanhol
Disallow: /frances-portugues
Disallow: /portugues-frances
Disallow: /russkii-angliiskii
Disallow: /angliiskii-russkii
Disallow: /italiano-inglese
Disallow: /inglese-italiano
Disallow: /nederlands-engels
Disallow: /engels-nederlands
Disallow: /Zhong Wen -Ying Yu 
Disallow: /Ying Yu -Zhong Wen 
Disallow: /Ri Ben Yu -Ying Yu 
Disallow: /Ying Yu -Ri Ben Yu 
Disallow: /page/forward.php
Allow: /

User-agent: YandexBot
Allow: /english-polish/sitemap
Allow: /polish-english/sitemap
Allow: /english-polish/top
Allow: /polish-english/top
Disallow: /translation
Disallow: /german-english
Disallow: /english-german
Disallow: /french-english
Disallow: /english-french
Disallow: /spanish-english
Disallow: /english-spanish
Disallow: /portuguese-english
Disallow: /english-portuguese
Disallow: /english-polish
Disallow: /english-russian
Disallow: /english-italian
Disallow: /english-dutch
Disallow: /english-chinese
Disallow: /english-japanese
Disallow: /polish-english
Disallow: /russian-english
Disallow: /italian-english
Disallow: /dutch-english
Disallow: /chinese-english
Disallow: /japanese-english
Disallow: /uebersetzung
Disallow: /deutsch-englisch
Disallow: /englisch-deutsch
Disallow: /spanisch-englisch
Disallow: /englisch-spanisch
Disallow: /franzoesisch-englisch
Disallow: /englisch-franzoesisch
Disallow: /portugiesisch-englisch
Disallow: /englisch-portugiesisch
Disallow: /deutsch-franzoesisch
Disallow: /franzoesisch-deutsch
Disallow: /deutsch-spanisch
Disallow: /spanisch-deutsch
Disallow: /deutsch-portugiesisch
Disallow: /portugiesisch-deutsch
Disallow: /francais-anglais
Disallow: /anglais-francais
Disallow: /francais-allemand
Disallow: /allemand-francais
Disallow: /francais-espagnol
Disallow: /espagnol-francais
Disallow: /francais-portugais
Disallow: /portugais-francais
Disallow: /ingles-espanol
Disallow: /espanol-ingles
Disallow: /aleman-espanol
Disallow: /espanol-aleman
Disallow: /frances-espanol
Disallow: /espanol-frances
Disallow: /portugues-espanol
Disallow: /espanol-portugues
Disallow: /ingles-portugues
Disallow: /portugues-ingles
Disallow: /alemao-portugues
Disallow: /portugues-alemao
Disallow: /espanhol-portugues
Disallow: /portugues-espanhol
Disallow: /frances-portugues
Disallow: /portugues-frances
Disallow: /russkii-angliiskii
Disallow: /angliiskii-russkii
Disallow: /italiano-inglese
Disallow: /inglese-italiano
Disallow: /nederlands-engels
Disallow: /engels-nederlands
Disallow: /Zhong Wen -Ying Yu 
Disallow: /Ying Yu -Zhong Wen 
Disallow: /Ri Ben Yu -Ying Yu 
Disallow: /Ying Yu -Ri Ben Yu 
Disallow: /page/forward.php
Allow: /

User-agent: Baiduspider
Allow: /english-polish/sitemap
Allow: /polish-english/sitemap
Allow: /english-polish/top
Allow: /polish-english/top
Disallow: /translation
Disallow: /german-english
Disallow: /english-german
Disallow: /french-english
Disallow: /english-french
Disallow: /spanish-english
Disallow: /english-spanish
Disallow: /portuguese-english
Disallow: /english-portuguese
Disallow: /english-polish
Disallow: /english-russian
Disallow: /english-italian
Disallow: /english-dutch
Disallow: /english-chinese
Disallow: /english-japanese
Disallow: /polish-english
Disallow: /russian-english
Disallow: /italian-english
Disallow: /dutch-english
Disallow: /chinese-english
Disallow: /japanese-english
Disallow: /uebersetzung
Disallow: /deutsch-englisch
Disallow: /englisch-deutsch
Disallow: /spanisch-englisch
Disallow: /englisch-spanisch
Disallow: /franzoesisch-englisch
Disallow: /englisch-franzoesisch
Disallow: /portugiesisch-englisch
Disallow: /englisch-portugiesisch
Disallow: /deutsch-franzoesisch
Disallow: /franzoesisch-deutsch
Disallow: /deutsch-spanisch
Disallow: /spanisch-deutsch
Disallow: /deutsch-portugiesisch
Disallow: /portugiesisch-deutsch
Disallow: /francais-anglais
Disallow: /anglais-francais
Disallow: /francais-allemand
Disallow: /allemand-francais
Disallow: /francais-espagnol
Disallow: /espagnol-francais
Disallow: /francais-portugais
Disallow: /portugais-francais
Disallow: /ingles-espanol
Disallow: /espanol-ingles
Disallow: /aleman-espanol
Disallow: /espanol-aleman
Disallow: /frances-espanol
Disallow: /espanol-frances
Disallow: /portugues-espanol
Disallow: /espanol-portugues
Disallow: /ingles-portugues
Disallow: /portugues-ingles
Disallow: /alemao-portugues
Disallow: /portugues-alemao
Disallow: /espanhol-portugues
Disallow: /portugues-espanhol
Disallow: /frances-portugues
Disallow: /portugues-frances
Disallow: /russkii-angliiskii
Disallow: /angliiskii-russkii
Disallow: /italiano-inglese
Disallow: /inglese-italiano
Disallow: /nederlands-engels
Disallow: /engels-nederlands
Disallow: /Zhong Wen -Ying Yu 
Disallow: /Ying Yu -Zhong Wen 
Disallow: /Ri Ben Yu -Ying Yu 
Disallow: /Ying Yu -Ri Ben Yu 
Disallow: /page/forward.php
Allow: /

User-agent: Applebot
Allow: /english-polish/sitemap
Allow: /polish-english/sitemap
Allow: /english-polish/top
Allow: /polish-english/top
Disallow: /translation
Disallow: /german-english
Disallow: /english-german
Disallow: /french-english
Disallow: /english-french
Disallow: /spanish-english
Disallow: /english-spanish
Disallow: /portuguese-english
Disallow: /english-portuguese
Disallow: /english-polish
Disallow: /english-russian
Disallow: /english-italian
Disallow: /english-dutch
Disallow: /english-chinese
Disallow: /english-japanese
Disallow: /polish-english
Disallow: /russian-english
Disallow: /italian-english
Disallow: /dutch-english
Disallow: /chinese-english
Disallow: /japanese-english
Disallow: /uebersetzung
Disallow: /deutsch-englisch
Disallow: /englisch-deutsch
Disallow: /spanisch-englisch
Disallow: /englisch-spanisch
Disallow: /franzoesisch-englisch
Disallow: /englisch-franzoesisch
Disallow: /portugiesisch-englisch
Disallow: /englisch-portugiesisch
Disallow: /deutsch-franzoesisch
Disallow: /franzoesisch-deutsch
Disallow: /deutsch-spanisch
Disallow: /spanisch-deutsch
Disallow: /deutsch-portugiesisch
Disallow: /portugiesisch-deutsch
Disallow: /francais-anglais
Disallow: /anglais-francais
Disallow: /francais-allemand
Disallow: /allemand-francais
Disallow: /francais-espagnol
Disallow: /espagnol-francais
Disallow: /francais-portugais
Disallow: /portugais-francais
Disallow: /ingles-espanol
Disallow: /espanol-ingles
Disallow: /aleman-espanol
Disallow: /espanol-aleman
Disallow: /frances-espanol
Disallow: /espanol-frances
Disallow: /portugues-espanol
Disallow: /espanol-portugues
Disallow: /ingles-portugues
Disallow: /portugues-ingles
Disallow: /alemao-portugues
Disallow: /portugues-alemao
Disallow: /espanhol-portugues
Disallow: /portugues-espanhol
Disallow: /frances-portugues
Disallow: /portugues-frances
Disallow: /russkii-angliiskii
Disallow: /angliiskii-russkii
Disallow: /italiano-inglese
Disallow: /inglese-italiano
Disallow: /nederlands-engels
Disallow: /engels-nederlands
Disallow: /Zhong Wen -Ying Yu 
Disallow: /Ying Yu -Zhong Wen 
Disallow: /Ri Ben Yu -Ying Yu 
Disallow: /Ying Yu -Ri Ben Yu 
Disallow: /page/forward.php
Allow: /

User-agent: *
Disallow: /

Sitemap: http://www.linguee.pl/sitemap.xml
