User-agent: *
Disallow: /administrator/
Disallow: /cache/
Disallow: /components/
Disallow: /images/
Disallow: /includes/
Disallow: /installation/
Disallow: /language/
Disallow: /libraries/
Disallow: /media/
Disallow: /modules/
Disallow: /plugins/
Disallow: /templates/
Disallow: /tmp/
Disallow: /xmlrpc/
Disallow: /normcar/cookie
Disallow: /normcar/zamowienia
Disallow: /normcar/koszyk/editpayment
Disallow: /normcar/koszyk/edit_shipment
Disallow: /sklep/odzyskiwanie-hasla
Disallow: /normcar/component/content/
Disallow: /sklep/szukaj
Disallow: /sklep/logowanie
Disallow: /normcar/component/users
Disallow: /normcar/imprezy/8-wiesci
Disallow: /normcar/imprezy/galerie/8-wiesci
Disallow: /normcar/imprezy/relacje/8-wiesc
Disallow: /normcar/administrator/index.php
Disallow: /normcar/imprezy/galerie/8-vasteras-galeria
Disallow: /normcar/imprezy/relacje/7-onas
Disallow: /normcar/imprezy/relacje/9-imprezy
Disallow: /normcar/imprezy/12-imprezy/galerie
Disallow: /normcar/imprezy/relacje/9-imprezy
Disallow: /normcar/imprezy/12-imprezy/galerie
Disallow: /normcar/imprezy/galerie/14-nasze-rumaki
Disallow: /normcar/imprezy/galerie/12-imprezy/galerie
Disallow: /normcar/imprezy/relacje/12-imprezy/galerie
Disallow: /normcar/component/content/category/17-news
Disallow: /normcar/imprezy/relacje/13-imprezy/relacje
Disallow: /normcar/imprezy/relacje/18-sklep-wyprzedaz/46-opel-cadet-skrzynia-biegow
Disallow: /normcar/imprezy/13-imprezy/content/view/79/46/
Disallow: /normcar/index.php?option=com_virtuemart&view=manufacturer&virtuemart_manufacturer_id=2&tmpl=component
Disallow: /normcar/imprezy/relacje/13-imprezy/imprezy/galerie/8-vasteras-galeria
Disallow: /normcar/warsztat/na-warsztacie?task=entry.add&sid=56
Disallow: /normcar/index.php?option=com_weblinks&catid=20&Itemid=8
Disallow: /normcar/imprezy/galerie/13-imprezy/content/view/79/46/
Disallow: *component*
Disallow: *user*
Disallow: *adres-uzytkownika*
Disallow: *sklep*

