Sitemap: http://www.krampa.pl/sitemap.xml
User-agent: *
Allow: o_firmie
Allow: oferta
Allow: projekty
Allow: promocja
Allow: kontakt
Allow: domki
Allow: dom
Allow: projekty_indywidualne
Allow: domki_w_trojmiescie
Allow: trojmiasto
Allow: pracownia_projektowa
Allow: biuro_projektowe
Allow: wejherowo
Allow: gdynia
Allow: gdansk
Allow: sopot
Allow: reda
Allow: rumia
Allow: puck
Allow: wladyslawowo
Allow: lubiatowo
Allow: kopalino
Allow: gowino
Allow: gniewino
Allow: lebork
Allow: kaszuby
Allow: powiat_wejherowski
Allow: wyszukaj_projekt
Allow: adaptacje
Allow: geodezja
Allow: adaptacje
Allow: wykonawstwo
Allow: gotowe_projekty
Allow: bolszewo
Allow: kartuzy
Allow: szemud
Allow: zukowo
Allow: luzino
Allow: goscicino
Allow: bojano
Allow: chwaszczyno
Allow: stezyca
Allow: chmielno
Allow: orle
Allow: index2.html
Allow: dom_parterowy_budynek_budowa_geodeta_geodezja_pomorskie_wejherowo_kartuzy_puck_luzino_goscicino.html
Allow: wejherowo_dom_biuro_projektowe_projekty_inwentaryzacje_materialy_bowa_budowlane.html
Allow: trojmiasto_projekty_dom_biuro_projektowe_projekty_inwentaryzacje_materialy_bowa_budowlane.html
Allow: index.php

