User-agent: *
Disallow: /5F/
Disallow: /aads/
Disallow: /adm/
Disallow: /adodb/
Disallow: /alpaki/
Disallow: /configs/
Disallow: /css/
Disallow: /cytaty/
Disallow: /data/
Disallow: /edit/
Disallow: /emile/
Disallow: /engine/
Disallow: /eshop/
Disallow: /flags/
Disallow: /flavon/
Disallow: /HTML/
Disallow: /ibox/
Disallow: /images/
Disallow: /jk/
Disallow: /jk/
Disallow: /kb/
Disallow: /keys/
Disallow: /m/
Disallow: /maria/
Disallow: /mod/
Disallow: /moskwa/
Disallow: /MQ/
Disallow: /newsletter/
Disallow: /portfolio/
Disallow: /ray/
Disallow: /serwis/
Disallow: /shop/
Disallow: /spotkania/
Disallow: /spotkold/
Disallow: /subdomeny/
Disallow: /templates/
Disallow: /templates_c/
Disallow: /vf/
Disallow: /xpu/
Disallow: /z/
