User-agent: *
Disallow: /administrator/
Disallow: /cache/
Disallow: /cli/
Disallow: /components/
Allow: /components/com_jfbconnect/includes/*.js$
Allow: /components/com_k2/css/*.css$
Allow: /components/com_k2/images/placeholder/*.png$
Disallow: /includes/
Disallow: /installation/
Disallow: /language/
Disallow: /libraries/
Disallow: /logs/
Disallow: /modules/
Allow: /modules/mod_yj_live_search/css/*.css$
Allow: /modules/mod_yj_live_search/script/*.js$
Allow: /modules/mod_yj_live_search/images/*.png$
Allow: /modules/mod_yj_media_slider/css/*.css$
Allow: /modules/mod_yj_media_slider/src/*.js$
Allow: /modules/mod_yj_media_slider/images/*.gif$
Allow: /modules/mod_yjme/css/*.css$
Allow: /modules/mod_yjtt30/css/*.css$
Allow: /modules/mod_yjtt30/src/*.js$
Disallow: /plugins/
Allow: /plugins/system/jcemediabox/css/*.css$
Allow: /plugins/system/jcemediabox/js/*.js$
Allow: /plugins/system/jcemediabox/themes/squeeze/*.html$
Allow: /plugins/system/jcemediabox/themes/squeeze/css/*.css$
Allow: /plugins/system/yjsg/assets/css/*.css$
Allow: /plugins/system/yjsg/assets/src/magnific/*.js$
Allow: /plugins/system/yjsg/assets/src/mediaelement/*.js$
Allow: /plugins/system/yjsg/assets/src/mediaelement/*.css$
Allow: /plugins/system/yjsg/assets/src/*.js$
Allow: /plugins/system/yjsg/assets/fonts/fontawesome/
Disallow: /tmp/

