User-agent: *
Disallow: /application/
Disallow: /design/
Disallow: /doc/
Disallow: /cache/
Disallow: /min/
Disallow: /upload/
Disallow: /serialization/
Disallow: /design/_css_frontend/
Disallow: /design/_css_panel/
Disallow: /design/_data_frontend/
Disallow: /design/_data_panel/
Disallow: /design/_images_common/
Disallow: /design/_images_frontend/
Disallow: /design/_images_installer/
Disallow: /design/_images_panel/
Disallow: /design/_js_frontend/
Disallow: /design/_js_libs/
Disallow: /design/_js_panel/
Disallow: /design/_tpl/
Disallow: /design/_virtualproduct/
Disallow: /design/admin/
Disallow: /design/frontend/
Disallow: /informacja/*
