User-agent: *
Crawl-delay: 10

Disallow: /*/fr/
Disallow: /fr/
Disallow: /*/nl/
Disallow: /nl/
Disallow: /*/jp/
Disallow: /jp/
Disallow: /*/cn/
Disallow: /cn/
Disallow: /*/pt/
Disallow: /pt/
Disallow: /*/es/
Disallow: /es/
Disallow: /*/tw/
Disallow: /tw/
Disallow: /*/it/
Disallow: /it/
Disallow: /*/no/
Disallow: /no/
Disallow: /*/gr/
Disallow: /gr/
Disallow: /*/de/
Disallow: /de/
Disallow: /*/cz/
Disallow: /cz/

Disallow: /horloge_mock-up.php
Disallow: /cron/*
Disallow: /includes/*

Disallow: /horloge-nieuws/
Disallow: /watch-news/
Disallow: /*/shoppingcart/
Disallow: /*/checkout/
Disallow: /*/ordertracking/
Disallow: /*/contact/
Disallow: /*/receipt/
Disallow: /*/*/receipt/
Disallow: /*/my-account/
Disallow: /*/*/my-account/
Disallow: /*/wishlist/
Disallow: /*/*/wishlist/
Disallow: /*/mailing/
Disallow: /*/*/mailing/
Disallow: /*/add-new-review/
Disallow: /*/*/add-new-review/

User-agent: Googlebot
Disallow: /*/fr/
Disallow: /fr/
Disallow: /*/nl/
Disallow: /nl/
Disallow: /*/jp/
Disallow: /jp/
Disallow: /*/cn/
Disallow: /cn/
Disallow: /*/pt/
Disallow: /pt/
Disallow: /*/es/
Disallow: /es/
Disallow: /*/tw/
Disallow: /tw/
Disallow: /*/it/
Disallow: /it/
Disallow: /*/no/
Disallow: /no/
Disallow: /*/gr/
Disallow: /gr/
Disallow: /*/de/
Disallow: /de/
Disallow: /*/cz/
Disallow: /cz/

Disallow: /horloge_mock-up.php
Disallow: /cron/*
Disallow: /includes/*

Disallow: /horloge-nieuws/
Disallow: /watch-news/
Disallow: /*/shoppingcart/
Disallow: /*/checkout/
Disallow: /*/ordertracking/
Disallow: /*/contact/
Disallow: /*/receipt/
Disallow: /*/*/receipt/
Disallow: /*/my-account/
Disallow: /*/*/my-account/
Disallow: /*/wishlist/
Disallow: /*/*/wishlist/
Disallow: /*/mailing/
Disallow: /*/*/mailing/
Disallow: /*/add-new-review/
Disallow: /*/*/add-new-review/

User-agent: Googlebot-image
Disallow: /*/fr/
Disallow: /fr/
Disallow: /*/nl/
Disallow: /nl/
Disallow: /*/jp/
Disallow: /jp/
Disallow: /*/cn/
Disallow: /cn/
Disallow: /*/pt/
Disallow: /pt/
Disallow: /*/es/
Disallow: /es/
Disallow: /*/tw/
Disallow: /tw/
Disallow: /*/it/
Disallow: /it/
Disallow: /*/no/
Disallow: /no/
Disallow: /*/gr/
Disallow: /gr/
Disallow: /*/de/
Disallow: /de/
Disallow: /*/cz/
Disallow: /cz/

Disallow: /horloge_mock-up.php
Disallow: /cron/*
Disallow: /includes/*

Disallow: /horloge-nieuws/
Disallow: /watch-news/
Disallow: /*/shoppingcart/
Disallow: /*/checkout/
Disallow: /*/ordertracking/
Disallow: /*/contact/
Disallow: /*/receipt/
Disallow: /*/*/receipt/
Disallow: /*/my-account/
Disallow: /*/*/my-account/
Disallow: /*/wishlist/
Disallow: /*/*/wishlist/
Disallow: /*/mailing/
Disallow: /*/*/mailing/
Disallow: /*/add-new-review/
Disallow: /*/*/add-new-review/
