User-agent: *
Disallow: /administrar/
Disallow: /modulos/actualizacionesBD/
Disallow: /modulos/AccionesBD/
Disallow: /modulos/Comun/
Disallow: /extranet/
Disallow: /conf/
Disallow: /bin/
Disallow: /imagenes/
Disallow: /includes/
Disallow: /WAI/
Disallow: /*.txt$
Disallow: /geka-cnc_es/FlogP/
Disallow: /geka-cnc_es/usuariosftp/
Disallow: /geka-cnc_com/FlogP/
Disallow: /geka-cnc_com/usuariosftp/
Disallow: /geka-cnc_de/FlogP/
Disallow: /geka-cnc_de/usuariosftp/
Disallow: /geka-cnc_fr/FlogP/
Disallow: /geka-cnc_fr/usuariosftp/
Disallow: /geka-cnc_pl/FlogP/
Disallow: /geka-cnc_pl/usuariosftp/
Disallow: /geka-cnc_ru/FlogP/
Disallow: /geka-cnc_ru/usuariosftp/
Disallow: /geka-group_es/FlogP/
Disallow: /geka-group_es/usuariosftp/
Disallow: /geka-group_com/FlogP/
Disallow: /geka-group_com/usuariosftp/
Disallow: /geka-group_de/FlogP/
Disallow: /geka-group_de/usuariosftp/
Disallow: /geka-group_fr/FlogP/
Disallow: /geka-group_fr/usuariosftp/
Disallow: /geka-group_pl/FlogP/
Disallow: /geka-group_pl/usuariosftp/
Disallow: /geka-group_ru/FlogP/
Disallow: /geka-group_ru/usuariosftp/
Disallow: /geka-ironworkers_es/FlogP/
Disallow: /geka-ironworkers_es/usuariosftp/
Disallow: /geka-ironworkers_com/FlogP/
Disallow: /geka-ironworkers_com/usuariosftp/
Disallow: /geka-ironworkers_de/FlogP/
Disallow: /geka-ironworkers_de/usuariosftp/
Disallow: /geka-ironworkers_fr/FlogP/
Disallow: /geka-ironworkers_fr/usuariosftp/
Disallow: /geka-ironworkers_pl/FlogP/
Disallow: /geka-ironworkers_pl/usuariosftp/
Disallow: /geka-ironworkers_ru/FlogP/
Disallow: /geka-ironworkers_ru/usuariosftp/
Disallow: /geka-tools_es/FlogP/
Disallow: /geka-tools_es/usuariosftp/
Disallow: /geka-tools_com/FlogP/
Disallow: /geka-tools_com/usuariosftp/

