User-agent: BLEXBot
Crawl-Delay: 10
Disallow: /facebook-nemazat/
Disallow: /teplicke-skaly/souteze/soutez-2016/
Disallow: /teplicke-skaly/souteze/soutez-2015/
Disallow: /teplicke-skaly/souteze/soutez-2014/
Disallow: /teplicke-skaly/souteze/soutez-2013/
Disallow: /teplicke-skaly/souteze/soutez-2012/
Disallow: /teplicke-skaly/souteze/soutez-2011/
Disallow: /teplicke-skaly/souteze/
Disallow: /ski-kamenec-2/price-list/
Disallow: /ski-kamenec-2/opening-hours/
Disallow: /ski-kamenec-2/ski-rental/
Disallow: /ski-kamenec-2/ski-school/
Disallow: /ski-kamenec-2/photogallery/
Disallow: /ski-kamenec-2/webcam/
Disallow: /ski-kamenec-2/operator/
Disallow: /ski-kamenec-2/
Disallow: /ski-kamenec-4/cennik/
Disallow: /ski-kamenec-4/godziny-otwarcia/
Disallow: /ski-kamenec-4/wypozyczalnia-sprzetu/
Disallow: /ski-kamenec-4/fotogaleria/
Disallow: /ski-kamenec-4/kamera-internetowa/
Disallow: /ski-kamenec-4/administrator/
Disallow: /ski-kamenec-4/

User-agent: *
Crawl-Delay: 3
Disallow: /facebook-nemazat/
Disallow: /teplicke-skaly/souteze/soutez-2016/
Disallow: /teplicke-skaly/souteze/soutez-2015/
Disallow: /teplicke-skaly/souteze/soutez-2014/
Disallow: /teplicke-skaly/souteze/soutez-2013/
Disallow: /teplicke-skaly/souteze/soutez-2012/
Disallow: /teplicke-skaly/souteze/soutez-2011/
Disallow: /teplicke-skaly/souteze/
Disallow: /ski-kamenec-2/price-list/
Disallow: /ski-kamenec-2/opening-hours/
Disallow: /ski-kamenec-2/ski-rental/
Disallow: /ski-kamenec-2/ski-school/
Disallow: /ski-kamenec-2/photogallery/
Disallow: /ski-kamenec-2/webcam/
Disallow: /ski-kamenec-2/operator/
Disallow: /ski-kamenec-2/
Disallow: /ski-kamenec-4/cennik/
Disallow: /ski-kamenec-4/godziny-otwarcia/
Disallow: /ski-kamenec-4/wypozyczalnia-sprzetu/
Disallow: /ski-kamenec-4/fotogaleria/
Disallow: /ski-kamenec-4/kamera-internetowa/
Disallow: /ski-kamenec-4/administrator/
Disallow: /ski-kamenec-4/
Sitemap: http://www.teplickeskaly.com/sitemap.xml

