User-agent: *
Disallow: /wp-admin/
Disallow: /xmlrpc.php
Disallow: /test/
Disallow: /wala_logow/
Disallow: /wala_logob-2/
Disallow: /wala_logo2/
Disallow: /wala_logo/
Disallow: /podgorska26/
Disallow: /wydarzenia/lokalizacje/
Disallow: /wydarzenia/kategorie/
Disallow: /wydarzenia/tagi/
Disallow: /wydarzenia/moje-rezerwacje/
Disallow: /wydarzenia/
Disallow: /wala-sl-01-2/
Disallow: /slider2-2/
Disallow: /pit/
Disallow: /kalk/
Disallow: /4-1/
Disallow: /4/
Disallow: /3/
Disallow: /2/
Disallow: /1/
Disallow: /favicon-2/
Disallow: /wala-sl-01/
Disallow: /slider2/
Disallow: /favicon/
Disallow: /wala_logob/
