User-agent: *
Disallow: /_stats/
Disallow: /admin/
Disallow: /alpanet_pliki_worek/
Disallow: /ckeditor/
Disallow: /classes/
Disallow: /cookies/
Disallow: /css/
Disallow: /flash/
Disallow: /grafiki/
Disallow: /images/
Disallow: /img/
Disallow: /inc/
Disallow: /js/
Disallow: /kopie/
Disallow: /logi/
Disallow: /mini/
Disallow: /modules/
Disallow: /mpdf/
Disallow: /nivoslider/
Disallow: /player/
Disallow: /podstrony/
Disallow: /restore/
Disallow: /script/
Disallow: /tmp/
Disallow: /vote_map/
Disallow: /wtyczki/
Disallow: /xls_reader/
Disallow: /captcha.php
Disallow: /cron.php
Disallow: /csv.php
Disallow: /drukuj.php
Disallow: /get_calendar_list.php
Disallow: /newsletter.php
Disallow: /pdf.php
Disallow: /polec.php
Disallow: /reload.php
Disallow: /znak.php
