User-agent: *
Allow: /lang/en
Allow: /lang/de
Allow: /lang/se
Allow: /lang/no
Allow: /lang/de
Allow: /lang/ru
Allow: /lang/lt
Allow: /lang/it
Allow: /lang/zh
Allow: /lang/lt
Allow: /lang/ru
Disallow: /user
Disallow: /basket
Disallow: /search
Disallow: /recommend_shop
Disallow: /newsletter
Disallow: /currency
Disallow: /productsCompare
Disallow: /product_options
Disallow: /stNavigationFrontend
Disallow: /producer
Disallow: /navigation
Disallow: /invoice
Disallow: /order
Disallow: /invoicePdf/*
Disallow: /orderPdf/*
Disallow: /stAvailabilityFrontend/showAddOverlay
Disallow: /stQuestionFrontend/showAddOverlay
Disallow: /stAvailabilityFrontend/showAddOverlay
Disallow: /stQuestionFrontend/showAddOverlay
Disallow: /*.php$
Disallow: /*.php$
Disallow: /paypal

