# robots.txt automaticaly generated by PrestaShop e-commerce open-source solution
# http://www.prestashop.com - http://www.prestashop.com/forums

# This file is to prevent the crawling and indexing of certain parts
# of your site by web crawlers and spiders run by sites like Yahoo!
# and Google. By telling these "robots" where not to go on your site,
# you save bandwidth and server resources.

# For more information about the robots.txt standard, see:
# http://www.robotstxt.org/wc/robots.html

User-agent: GSiteCrawler/v1.23 rev. 286
Disallow: /order/
Disallow: /cart/
Disallow: /quick-order/
Disallow: /sklep/console/
Disallow: /kalkulator/
Disallow: /_sqldump_/
Disallow: /kamera/
Disallow: /console.php

User-agent: GSiteCrawler/v1.23 rev. 286 (http://gsitecrawler.com/)
Disallow: /order/
Disallow: /cart/
Disallow: /quick-order/
Disallow: /sklep/console/
Disallow: /kalkulator/
Disallow: /_sqldump_/
Disallow: /console.php
Disallow: /kamera/

User-agent: Adsbot-Google
Disallow: /sklep/order/
Disallow: /sklep/cart/
Disallow: /sklep/quick-order/
Disallow: /sklep/console/
Disallow: /kalkulator/
Disallow: /_sqldump_/
Disallow: /console.php
Disallow: /kamera/

User-agent: *
Disallow: /sklep/order/
Disallow: /sklep/cart/
Disallow: /sklep/quick-order/
Disallow: /sklep/console/
Disallow: /kamera/

User-agent: *
# Directories
Disallow: /_sqldump_/
Disallow: /programy/
Disallow: /banery/
Disallow: /projekty/
Disallow: /kalkulator/
Disallow: /file_przejscie/
Disallow: /reklama/
Disallow: /web/
Disallow: /sklep/console/
Disallow: /sklep/classes/
Disallow: /sklep/config/
Disallow: /sklep/download/
Disallow: /sklep/mails/
Disallow: /sklep/modules/
Disallow: /sklep/translations/
Disallow: /sklep/tools/
Disallow: /sklep/lang-pl/
Disallow: /sklep/cart/
Disallow: /sklep/quick-order/
Disallow: /kamera/
Allow: /sklep/img/m/
Disallow: /sklep/img/admin/
Allow: /sklep/img/c/
Allow: /sklep/img/cms/
Allow: /sklep/img/co/
Disallow: /sklep/img/jquery-ui/
Allow: /sklep/img/l/
Allow: /sklep/img/os/
Allow: /sklep/img/s/
Allow: /sklep/img/scenes/
Allow: /sklep/img/st/
Allow: /sklep/img/su/
Allow: /sklep/img/t/
Disallow: /sklep/img/tmp/
Allow: /sklep/
Allow: /sklep/img/
Allow: /sklep/img/p/
Allow: /sklep/modules/maofree_askmoreinfo/
Allow: /sklep/themes/prestashop/img/
Allow: /biuletyny/

# Files
Disallow: /sklep/addresses.php
Disallow: /sklep/address.php
Disallow: /sklep/authentication.php
Disallow: /sklep/cart.php
Disallow: /sklep/discount.php
Disallow: /sklep/footer.php
Disallow: /sklep/get-file.php
Disallow: /sklep/header.php
Disallow: /sklep/history.php
Disallow: /sklep/identity.php
Disallow: /sklep/images.inc.php
Disallow: /sklep/init.php
Disallow: /sklep/my-account.php
Disallow: /sklep/order.php
Disallow: /sklep/order-slip.php
Disallow: /sklep/order-detail.php
Disallow: /sklep/order-follow.php
Disallow: /sklep/order-return.php
Disallow: /sklep/order-confirmation.php
Disallow: /sklep/pagination.php
Disallow: /sklep/password.php
Disallow: /sklep/pdf-invoice.php
Disallow: /sklep/pdf-order-return.php
Disallow: /sklep/pdf-order-slip.php
Disallow: /sklep/product-sort.php
Disallow: /sklep/search.php
Disallow: /sklep/statistics.php
Disallow: /sklep/img/logo.jpg
Disallow: /sklep/img/logo_invoice.jpg
Disallow: /sklep/img/logo_mail.jpg
Disallow: /sklep/img/logo_stores.gif
Disallow: /sklep/console/index.php
Allow: /sklep/sitemap.xml
Allow: /sklep/pl_pln_googlebase.xml
Allow: /sklep/modules/ps_cumulus/ps_cumulus.css
Allow: /sklep/themes/prestashop/css/modules/blockmya-ccount/blockmyaccount.css
Allow: /sklep/themes/prestashop/css/modules/editorial/edit-orial.css
Allow: /sklep/themes/prestashop/css/modules/blockbes-tsellers/blockbestsellers.css
Allow: /sklep/themes/prestashop/css/modules/blockcat-egories/blockcategories.css
Allow: /sklep/themes/prestashop/css/modules/blockrss/bl-ockrss.css
Allow: /sklep/modules/productscategory/productscateg-ory.css
Allow: /sklep/themes/prestashop/css/product_list.css
Allow: ^blog/all-post.html$ /sklep/modules/plblog/frontent/all-post.php
Allow: ^blog/([a-zA-Z0-9-]*)/([0-9]*)-([a-zA-Z0-9-]*).html$ /sklep/modules/plblog/frontent/details.php?plcn=$1&plidp=$2&plpn=$3&.php
Allow: ^blog/([0-9]*)_([a-zA-Z0-9-]*).html$ /sklep/modules/plblog/frontent/list-post.php?plidc=$1&plcn=$2&.php
Allow: ^blog/tag/([a-zA-Z0-9-]*)_([0-9]*).html$ /sklep/modules/plblog/frontent/list-tags.php?pltn=$1&plidt=$2&.php
Sitemap: http://www.kkp-gezler.pl/sitemap.xml
sitemap: http://www.kkp-gezler.pl/sklep/sitemap.xml
