User-agent: *
Disallow: /*print*
Disallow: /*.swf$
Disallow: /R_S_S%0tze_deu.htm
Disallow: /id-772-fds_glosario.html
Disallow: /id-771-msds_glossary.html
Disallow: /kateg-94-1-regulation.html
Disallow: /kateg-226-1-eu_regulations_on_chemical_safety.html
Disallow: /kateg-64-1-pravni_pravidla.html
Disallow: /kateg-235-1-narizeni_eu_chemicke_bezpecnosti.html
Disallow: /kateg-82-1-reglamentos.html
Disallow: /kateg-233-1-principales_normas_legales_de_la_union_e.html
Disallow: /msds_download_search/request_download.html
Disallow: /kateg-202-1-msdocs.html
Disallow: /msds_download_search/index.php?action=request_data_sheet&lang=it
Disallow: /organiczna/preparatyka/id-277-ceginformaciok.html
Disallow: /kateg-193-1-ghs_clp_information.htmlhttp:/www.msds-europe.com/kateg-193-1-ghs_clp_information.html
Disallow: /kateg-193-1-ghs_clp_information.htmlhttp:/www.msds-europe.com/kateg-34-1-reach.html
Disallow: /id-733-zm_ny_narizeni_reach_2011.html
Disallow: /id-684-system_deskriptor_pouziti_esds.html
Disallow: /id-1006-mobilni_aplikace_msdocs_2_0_pro_operacni.html
Disallow: /id-531-ktere_latky_musim_oznamovat_do_seznamu.html
Disallow: /id-971-la_aplicacion_movil_msdocs_2_0_ahora_dis.html
Disallow: /id-972-aplicacion_movil_msdocs_para_dispositivo.html
Disallow: /msds_download_search/index.php?action=request_data_sheet&lang=it
Disallow: /msds_download_search/request_download.html
Disallow: /id-1029-servicii_speciale.html
Disallow: /id-517-avantajele_i_dezavantajele_produselor.html
Disallow: /id-518-metoda_noastr_de_lucru_practica.html
Disallow: /id-574-ce_informa_ii_trebuie_s_prezint_in.html
Disallow: /id-575-cum_pot_s_creez_notificare.html
Disallow: /id-688-sistemul_de_descriptori_ai_utiliz_rii.html
Disallow: /id-985-aplica_ie_mobil_msdocs_pentru_dispozitiv.html
Disallow: /kateg-230-1-prinicipalele_legisla_ii_ue_in_leg_tur_c.html
Disallow: /id-1011-cosmetic_product_safety_report_sample.html
Disallow: /id-462-vyhody_nevyhody_softverov_na.html
Disallow: /id-463-nas_pracovny_postup_spravna_metoda.html
Disallow: /id-489-the_advantages_and_disadvantages_of_the.html
Disallow: /id-581-ako_mozem_vytvori_oznamenie.html
Disallow: /id-933-registration_on_the_cpnp_portal.html
Disallow: /id-14-fichas _de_ datos_ de_ seguridad_clp_rea.html
Disallow: /id-1036-clp_einstufung_nachgeschaltete_anwender.html
Disallow: /id-475-unsere_arbeitsmethode_die_korrekte.html
Disallow: /id-476-die_vorteile_und_nachteile_von_software.html
Disallow: /id-539-wie_kann_ich_eine_meldung_erstellen.html
Disallow: /id-620-aktualisierung_der.html
Disallow: /id-621-kennzeichnungen_des.html
Disallow: /id-680-esds_die_verwendungssektor_kategorie.html
Disallow: /id-713-allgemeine_informationen_uber_das.html
Disallow: /id-714-ein_kurzer_uberblick_von_reach_fur.html
Disallow: /id-715-die_hauptaufgaben_der_nachgeschalteten.html
Disallow: /id-719-elemente_des_etiketts_gemass.html
Disallow: /id-728-anderungen_der_reach_verordnung_2011.html
Disallow: /id-936-cpnp_onlineberatung.html
Disallow: /id-937-anfertigung_und_ubersetzung_von_etikette.html
Disallow: /id-938-notifizierung_von_kosmetischen_mitteln_u.html
Disallow: /id-940-anfertigung_der_produktinformationsdatei.html
Disallow: /id-943-kosmetische_mittel_definizionen.html
Disallow: /id-944-registrierung_cpnp.html
Disallow: /id-278-nas_nacin_dela_pravilni_proces.html
Disallow: /id-279-dobre_in_slabe_lastnosti_softverjev_za.html
Disallow: /id-283-priprava_varnostne_ocene_kozmeticnih.html
Disallow: /id-689-seznam_deskriptorjev_za_sektorje_uporabe.html
Disallow: /kateg-202-1-msdocs.html
Disallow: /kateg-108-1-karty_bezpecnostnych_udajov_preklad.html
Disallow: /kateg-58-1-bezpecnostni_list.html
Disallow: /id-352-przygotowanie_karty_charakterystyki_do.html
Disallow: /id-464-zwroty_r_s.html
Disallow: /id-465-zwroty_h_p_ghs_clp.html
Disallow: /id-466-symbol_zagrozenia_reach.html
Disallow: /id-467-piktogramy_wskazujace_rodzaj_zagrozenia.html
Disallow: /id-509-nasza_metoda_pracy_nale_yta_praktyka.html
Disallow: /id-569-jaki_sposob_mog_przygotowa.html
Disallow: /id-599-karta_charakterystyki_sk_ada_si_16.html
Disallow: /id-686-system_deskryptorow_dla_zastosowa.html
Disallow: /id-776-msds_s_ownik.html
Disallow: /id-804-wymiary_etykiet.html
Disallow: /id-980-aplikacja_mobilna_msdocs_2_0_jest_dost_p.html
Disallow: /kateg-157-1-msds_informacje.html
Disallow: /kateg-187-1-udost_pnianie_kart_charakterystyki.html
Disallow: /id-490-our_work_method_the_appropriate.html
Disallow: /id-577-ktore_latky_je_potrebne_oznamova_do.html
Disallow: /id-642-the_msdocs_logo_as_communication_tool.html
Disallow: /id-643-legislative_background_reach_clp.html
Disallow: /id-685-system_deskriptorov_pouzitia_esds.html
Disallow: /id-766-label_elements_regarding_clp_regulation.html
Disallow: /id-802-rozmery_etikiet.html
Disallow: /id-820-list_of_svhc_substances.html
Disallow: /id-885-introduction_ghs_united_states.html
Disallow: /id-899-sastavljanje_oznaka_koje_su_skladu_clp_o.html
Disallow: /id-903-predregistracija_reach.html
Disallow: /id-904-sastavljanje_visejezicnih_oznaka.html
Disallow: /id-910-nas_nacin_rada_odgovaraju_e_prakse_pripr.html
Disallow: /id-911-prednosti_nedostaci_softvera_za_odobrenj.html
Disallow: /id-927-consultancy_on_manufacturing_distributio.html
Disallow: /id-929-requirements_of_article_13_of_regulation.html
Disallow: /id-932-cosmetics_key_terms.html
Disallow: /id-965-msdocs_2_0_application_for_mobile_device.html
Disallow: /id-996-msdocs_2_0_mobilna_aplikacija_je_dostupn.html
Disallow: /hazard_symbol.htm
Disallow: /jog/jog_nemet/67_548_EWG.pdf
Disallow: /cimke-1-1907%2F2006.html
Disallow: /cimke-1-98%2F8%2FEG.html
Disallow: /jog/jog_spanyol/91_155_CEE.htm
Disallow: /kateg-268-1-descargar_traducir
Disallow: /sitemap.htm
Disallow: /msds_inform%E1ci%F3.htm
Disallow: /msds_information_fr.htm
Disallow: /msds_informazioni.htm
Disallow: /msds_information.htm
Disallow: /msds_wissenswertes.htm
Disallow: /id-523-reglement_ue_no_453_2010_
Disallow: /images/msds_europa.swf
Disallow: /data/files/125_2012_eu_EvxlsN.pdf
Disallow: /data/files/348_2013_eu_hX1Ghe.pdf
Disallow: /msds_preparation_translation.htm.
Disallow: /cimke-3-sds.html
Disallow: /cimke-3-SDS.html
Disallow: /cimke-2-sds.html
Disallow: /cimke-1-mention%20de%20danger.html
Disallow: /cimke-1-indicaci%C3%B3n%20de%20peligro.html
Disallow: /cimke-1-indicaci%C3%B3n%20de%20peligro.html
Disallow: /cimke-1-consejo%20de%20prudencia.html
Disallow: /cimke-1-Preparaci%C3%B3n.html
Disallow: /cimke-1-PICTOGRAM%20DE%20PERICOL.html
Disallow: /cimke-1-2015.html
Disallow: /id-96-.html
Disallow: /kateg-13-2-de.html
Disallow: /id-575-cum_pot_s_creez_notificare.html
Disallow: /id-985-aplica_ie_mobil_msdocs_pentru_dispozitiv.html
Disallow: /id-581-ako_mozem_vytvori_oznamenie.html
Disallow: /id-643-legislative_background_reach_clp.html
Disallow: /id-899-sastavljanje_oznaka_koje_su_skladu_clp_o.html
Disallow: /id-929-requirements_of_article_13_of_regulation.html
Disallow: /id-14-fichas _de_ datos_ de_ seguridad_clp_rea.html
Disallow: /id-1020-kiemelt_szolgaltatasaink.html
Disallow: /cimke-1-(symboly.html
Disallow: /cimke-1-e-SDB.html
Disallow: /cimke-3-SDS.html
Disallow: /id-885-introduction_ghs_united_states.html
Disallow: /id-927-consultancy_on_manufacturing_distributio.html
Disallow: /id-932-cosmetics_key_terms.html
Disallow: /kateg-255-1-usluge_stl_ova.html
Disallow: /kateg-5-1-news.html
Disallow: /organiczna/preparatyka/id-62-jognyilatkozat.html
Disallow: /id-119-vantaggi_svantaggi_dei_software_per_la.html
Disallow: /id-120-il_nostro_metodo_di_lavoro_esperienze.html
Disallow: /id-563-come_si_predispone_una_notifica.html
Disallow: /id-681-il_sistema_dei_descrittori_degli_usi.html
Disallow: /id-810-dimensioni_delle_etichette.html
Disallow: /id-891-registrazione_cpnp.html
Disallow: /id-892-categorie_di_prodotti_cosmetici.html
Disallow: /id-992-ora_disponibile_l_applicazione_mobile_ms.html
Disallow: /kateg-26-1-notizie.html
Disallow: /organiczna/preparatyka/oldalterkep.html
Disallow: /organiczna/preparatyka/referenciak.html
Disallow: /organiczna/preparatyka/index.php?action=bid&page=online_info
Disallow: /cimke-1-1272%2F2008%2FCE.html
Disallow: /jog/jog_olasz/67_548_CEE.pdf
Allow: /
Allow: /kateg-162-1-ghs_clp_informaciok.html
