User-Agent: *
Disallow: /root*
Disallow: /regulamin
Disallow: /jakosc
Disallow: /pytania-i-odpowiedzi
Disallow: /zaloguj
Disallow: /konto
Disallow: /zarejestruj
Disallow: /wyszukaj
Disallow: /zresetuj-haslo
Disallow: /extra
Disallow: /recenzja
Disallow: /ocena
Disallow: /blog/ocena/dodaj
Disallow: /produkt/udostepnij
Disallow: /koszyk
Disallow: /zamowienie
Disallow: /newsletter
Disallow: /polityka-prywatnosci
Disallow: /polityka-plikow-cookies
Disallow: /oferta-dla-agencji-reklamowych
Disallow: /kontakt
Disallow: /nasi-klienci-i-referencje
Disallow: /polityka-jakosci
Disallow: /uslugi-graficzne
Disallow: /terminy-realizacji
Disallow: /koszty-dostawy

Disallow: /index.php/regulamin
Disallow: /index.php/jakosc
Disallow: /index.php/pytania-i-odpowiedzi
Disallow: /index.php/zaloguj
Disallow: /index.php/konto
Disallow: /index.php/zarejestruj
Disallow: /index.php/wyszukaj
Disallow: /index.php/zresetuj-haslo
Disallow: /index.php/extra
Disallow: /index.php/recenzja
Disallow: /index.php/ocena
Disallow: /index.php/blog/ocena/dodaj
Disallow: /index.php/produkt/udostepnij
Disallow: /index.php/koszyk
Disallow: /index.php/zamowienie
Disallow: /index.php/newsletter
Disallow: /index.php/polityka-prywatnosci
Disallow: /index.php/polityka-plikow-cookies
Disallow: /index.php/oferta-dla-agencji-reklamowych
Disallow: /index.php/kontakt
Disallow: /index.php/nasi-klienci-i-referencje
Disallow: /index.php/polityka-jakosci
Disallow: /index.php/uslugi-graficzne
Disallow: /index.php/terminy-realizacji
Disallow: /index.php/koszty-dostawy
