User-agent: *
Disallow: /application/
Disallow: /design/
Disallow: /doc/
Disallow: /cache/
Disallow: /min/
Disallow: /upload/
Disallow: /serialization/
Disallow: /wyszukiwarka/*
Disallow: /kontakt/*
Disallow: /productprintbox/*
Disallow: /kategoria/zarowki-led-gu10,*
Disallow: /kategoria/zarowki-led-gu10/zarowki-led-cob,*
Disallow: /kategoria/zarowki-led-gu10/zarowki-led-smd,*
Disallow: /kategoria/zarowki-led-gu10/zarowki-led-hi-power,*
Disallow: /kategoria/zarowki-led-mr16,*
Disallow: /kategoria/zarowki-led-mr16/zarowki-led-cob,*
Disallow: /kategoria/zarowki-led-mr16/zarowki-led-smd,*
Disallow: /kategoria/zarowki-led-mr16/zarowki-led-hi-power,*
Disallow: /kategoria/zarowki-led-mr11,*
Disallow: /kategoria/zarowki-led-e14,*
Disallow: /kategoria/zarowki-led-e27,*
Disallow: /kategoria/zarowki-led-g4,*
Disallow: /kategoria/zarowki-led-g9,*
Disallow: /kategoria/zarowki-led-ar111,*
Disallow: /kategoria/tasmy-led,*
Disallow: /kategoria/tasmy-led-3528,*
Disallow: /kategoria/tasmy-led-5050,*
Disallow: /kategoria/tasmy-led-5050-rgb,*
Disallow: /kategoria/naswietlacze-led,*
Disallow: /kategoria/moduly-led,*
Disallow: /kategoria/oprawy-led,*
Disallow: /kategoria/akcesoria-led,*
Disallow: /kategoria/zasilacze-led,*
Disallow: /kategoria/samochodowe-led,*
Disallow: /kategoria/lampy-led,*
Disallow: /kategoria/profile-led,*
