User-agent: AdsBot-Google-Mobile
Disallow:

User-agent: AdsBot-Google
Disallow:

user-agent: AhrefsBot
disallow: /

# robots.txt - Inhalte freigegeben
User-agent: *
# Sperrung eines bestimmten Bereiches
Disallow: /admin/
Disallow: /*?bel_erw
Disallow: /*&bel_erw
Disallow: /buchen/
Disallow: /callcenter/
Disallow: /*?code=
Disallow: /*&code=
Disallow: /control/
Disallow: /data/
Disallow: /*?dauer
Disallow: /*&dauer
Disallow: /*?design
Disallow: /*&design
Disallow: /doc/
Disallow: /*?fix-occupation-offer=
Disallow: /*&fix-occupation-offer=
Disallow: /flash/
Disallow: /*?gclid
Disallow: /*&gclid
Disallow: /*?id
Disallow: /*&id
Disallow: /images/
Disallow: /index/popup.php
Disallow: /info/
Disallow: /infx/
Disallow: /ini/
Disallow: /*?kwtype
Disallow: /*&kwtype
Disallow: /*?lay
Disallow: /*&lay
Disallow: /layout/
Disallow: /*linkgenerator=
Disallow: /logs/
Disallow: /new/
Disallow: /*nocache=
Disallow: /*?offer=
Disallow: /*&offer=
Disallow: /pictures/67924
Disallow: /*?pop
Disallow: /*&pop
Disallow: /*popup=
Disallow: /*?schritt
Disallow: /*&schritt
Disallow: /scripts/
Disallow: /*?sei_id
Disallow: /*&sei_id
Disallow: /*?site_mode
Disallow: /*&site_mode
Disallow: /sql/
Disallow: /styles/
Disallow: /*?subcode=
Disallow: /*&subcode=
Disallow: /templ/
Disallow: /tmp/
Disallow: /umfrage/
Disallow: /*?unterkunft
Disallow: /*&unterkunft
Disallow: /*?week
Disallow: /*&week
Disallow: /xml/
Disallow: /*?ziel
Disallow: /*&ziel
#Sperrung des Buchungsvorgangs
Disallow: /boeking.html
Disallow: /bokning.html
Disallow: /booking.html
Disallow: /buchung.html
Disallow: /devis-sans-engagement.html?*
Disallow: /foglalas.html
Disallow: /individuelt_tilbud.html?*
Disallow: /individuelt-tilbud.html?*
Disallow: /nabidka_pro_vas.html?*
Disallow: /nabidka-pro-vas.html?*
Disallow: /objednavka.html
Disallow: /oferta_osobista.html?*
Disallow: /oferta-osobista.html?*
Disallow: /oferta_personal.html?*
Disallow: /oferta-personal.html?*
Disallow: /oferta_personalizata.html?*
Disallow: /oferta-personalizata.html?*
Disallow: /offerta_individuale.html?*
Disallow: /offerta-individuale.html?*
Disallow: /osebna_ponudba.html?*
Disallow: /osebna-ponudba.html?*
Disallow: /pedido-personal.html?*
Disallow: /persoenliches_angebot.html?*
Disallow: /persoenliches-angebot.html?*
Disallow: /personalised_offer.html?*
Disallow: /personalised-offer.html?*
Disallow: /personligt_erbjudande.html?*
Disallow: /personligt-erbjudande.html?*
Disallow: /persoonlijke_aanbieding.html?*
Disallow: /persoonlijke-aanbieding.html?*
Disallow: /ponuka_pre_vas.html?*
Disallow: /ponuka-pre-vas.html?*
Disallow: /prenotazione.html
Disallow: /proposta_pessoal.html?*
Disallow: /proposta-pessoal.html?*
Disallow: /reserva.html
Disallow: /reservation.html
Disallow: /rezervacija.html
Disallow: /rezervare.html
Disallow: /rezerwuj.html
Disallow: /simulation_sans_engagement.html?*
Disallow: /simulation-sans-engagement.html?*
Disallow: /specpredlozhenie.html?*
#Sonstiger Content
Disallow: /beispielhaus/
Disallow: /crazy_booking_newsletter.html
Disallow: /index/index.php?sei_id=16
Disallow: /index/index.php?sei_id=216
Disallow: /index/index.php?sei_id=219
Disallow: /index/index.php?sei_id=404
Disallow: /lcc.html
Disallow: /pojisteni.html
Disallow: /reiseinformationen/*.pdf
Disallow: /sandbox/
Disallow: /sandbox/formy.html
Disallow: /sandbox.html
#temp. Disallow Partnerprogramm
Disallow: /affiliate_area/greeting.html
Disallow: /affiliate_programme.html
Disallow: /affiliates_programme.html
Disallow: /area_partner/saluti.html
Disallow: /espace_partenaire/accueil.html
Disallow: /o_programie_partnerskim.html
Disallow: /partnerafdeling/begroeting.html
Disallow: /partneralue/tervehdys.html
Disallow: /partnerbereich/begruessung.html
Disallow: /partner-ohjelma.html
Disallow: /partneromraade/velkomst.html
Disallow: /partnerprogram.html
Disallow: /partnerprogramma.html
Disallow: /partnerprogramm/einstellungen.html
Disallow: /partnerprogrammet.html
Disallow: /partnerprogramm.html
Disallow: /partnerprogramm/partnerprogramm.html
Disallow: /partnerprogramm/partnerprogramm/werbemedien.html
Disallow: /partnerprogramm/styles_aendern.html
Disallow: /partnerprogramm/xml.html
Disallow: /partnerprogram/reklamemedier.html
Disallow: /partnerprogram/reklammedier.html
Disallow: /partnerreszleg/udvozles.html
Disallow: /partnersidor/valkommen.html
Disallow: /partnerska_oblast/pozdravenie.html
Disallow: /partnersky_program.html
Disallow: /partnjorsko_pole/dobre_doshli.html
Disallow: /pentru_parteneri/salut.html
Disallow: /programa_de_parceiros.html
Disallow: /_programa_de_parceiros/publicidade_e_media.html
Disallow: /programa_de_socios.html
Disallow: /_programa_de_socios/publicidad_y_medios.html
Disallow: /program_de_afiliere.html
Disallow: /programma_di_affiliazione.html
Disallow: /programme_de_partenaires.html
Disallow: /program_partnerski.html
Disallow: /program_partnerski/powitanie.html
Disallow: /program_partnerski/reklama.html
Disallow: /program_pro_partnery.html
Disallow: /program_pro_partnery/privitani.html
Disallow: /program_pro_partnery/reklamni_prostredky.html
Disallow: /unternehmen/partnerbereich/ihre_daten.html
Disallow: /unternehmen/partnerbereich/ihre_statistiken.html
Disallow: /unternehmen/partnerbereich/linkgenerator.html
Disallow: /unternehmen/partnerbereich/werbemedien.html
Disallow: /zz/werbemedien.html

