User-agent: *
Disallow: /404/
Disallow: /app/
Disallow: /cgi-bin/
Disallow: /downloader/
Disallow: /includes/
Disallow: /lib/
Disallow: /magento/
Disallow: /pkginfo/
Disallow: /report/
Disallow: /stats/
Disallow: /var/
Disallow: /catalog/product_compare/
Disallow: /catalogsearch/
Disallow: /checkout/
Disallow: /control/
Disallow: /contacts/
Disallow: /customer/
Disallow: /customize/
Disallow: /newsletter/
Disallow: /poll/
Disallow: /sept/
Disallow: /xml/
Disallow: /sendfriend/
Disallow: /wishlist/
Disallow: /cron.php
Disallow: /cron.sh
Disallow: /error_log
Disallow: /install.php
Disallow: /LICENSE.html
Disallow: /LICENSE.txt
Disallow: /LICENSE_AFL.txt
Disallow: /STATUS.txt
Disallow: /index.php$
Disallow: /cron.php$
Disallow: /ups.php$
Disallow: /repairtable.php$
Disallow: /install.php$
Disallow: /phpinfo.php$
Disallow: /stest.php$
Disallow: /test.php$
Disallow: /test_md.php$
Disallow: /test2.php$
Disallow: /testo.php$
Disallow: /testwebapi.php$
Disallow: /testwebapi2.php$
Disallow: /uallegro.php$
Disallow: /adminer.php$
Disallow: /all2mage.php$
Disallow: /all2mage_kod.php$
Disallow: /api.php$
Disallow: /baselinker.php$
Disallow: /get.php$
Disallow: /getdata.php$
Disallow: /all2mage.php$
Disallow: /*?p=*&
Disallow: /*?*&p=
Disallow: /*?SID=
Disallow: /*?*&SID=
Disallow: /*?dir=
Disallow: /*?*&dir=
Disallow: /*?order=
Disallow: /*?*&order=
Disallow: /*?cat=
Disallow: /*?*&cat=
Disallow: /*?price=
Disallow: /*?*&price=
Disallow: /*?mode=
Disallow: /*?*&mode=
Disallow: /*?limit=
Disallow: /*?*&limit=
Disallow: /*?*___store=
Disallow: /*?*___from_store=
Disallow: /productalert
Disallow: /productquestion
Disallow: /*?*frontend=
Disallow: /*?*&*&*&

Sitemap: https://www.e-klosz.pl/sitemap/mapa_google.xml

##

