User-agent: *
noindex: /allgemeine_geschaeftsbedingungen
noindex: /datenschutz
noindex: /widerruf
noindex: /merkzettel
noindex: /warenkorb
noindex: /mein-konto
noindex: /Newsletter
noindex: /Sitemap
noindex: /versand_und_lieferung
noindex: /ruecksendungen
noindex: /customer/login?ReturnUrl=%2Fmein-konto
noindex: /Article?s=*
noindex: /*?Page=*
noindex: /*?Items=*
noindex: /*?Filter=*
noindex: /*?sort=*
noindex: /article?s=*
noindex: /*?page=*
noindex: /*?items=*
noindex: /*?filter=*
noindex: /*?sort=*
noindex: /artikel/*
noindex: /Artikel/*
noindex: /landingpage
noindex: /Landingpage
noindex: /Leaflet
noindex: /ShippingInfo
noindex: /customer/*
noindex: /Customer/*

