Disallow: /xmlrpc.php
Disallow: /wp-
Disallow: /trackback/
Disallow: ?wptheme=
Disallow: ?comments=
Disallow: ?replytocom
Disallow: /comment-page-
Disallow: /?s=
Disallow: /wp-content/
Allow: /wp-content/uploads/
