User-agent: *
Disallow: /admin/
Disallow: /pytanie-do-sprzedawcy/
Disallow: /dodaj-nowe-powiadomienie-exapro/
Disallow: /aktywuj-konto/
Disallow: /ajax_remove_product_from_wishlist/
Disallow: /ajax_add_product_to_wishlist/
Disallow: /ajax_check_existing_email/
Disallow: /ajax_check_minimal_price/
Disallow: /ajax_load_related_machines/
Disallow: /ajax_commission_calculate/
Disallow: /ajax_filter_search_results/
Disallow: /ajax_filter_list_results/
Disallow: /ajax_autocomplete_search_results/
Disallow: /ajax_make_inquiry/
Disallow: /ajax_autocomplete_manufacturers/
Disallow: /ajax_translate/
Disallow: /ajax_rate_product/
Disallow: /ajax_log_trans_request/
Disallow: /ajax_load_select_by_country/
Disallow: /ajax_load_select_by_parent_category/
Disallow: /ajax_change_expiry/
Disallow: /ajax_change_currency/
Disallow: /ajax_change_measures/
Disallow: /ajax_product_alert_de_activate/
Disallow: /ajax_product_alert_delete/
Disallow: /ajax_product_delete/
Disallow: /ajax_product_attributes_product_category/
Disallow: /ajax_product_attributes_product/
Disallow: /ajax_product_attributes/
Disallow: /ajax_product_list_view_mode/
Disallow: /ajax_thumbnail_preview/

