User-agent: *
Sitemap: https://queer.pl/sitemap
Allow: /data/article/
Allow: /data/rssPost/
Allow: /data/wiki/
Allow: /data/top/
Disallow: /cache/
Disallow: /tmp/
Disallow: /app/
Disallow: /admin/
Disallow: /private/
Disallow: /test/
Disallow: /lib/
Disallow: /msg/
Disallow: /epub/
Disallow: /ebook/
Disallow: /user/
Disallow: /data/pic/
Disallow: /info/terms
Disallow: /info/privacy
Disallow: /info/cookies
Disallow: /info/partners
