# robots.txt file for http://www.wkrainieksiazki.pl/
# Generated by SOFTplus GSiteCrawler v1.23 rev. 286 / http://gsitecrawler.com/
# 2013-01-22  16:36

User-agent: *
# No exclusions found, disallow nothing.
Disallow:

# end of file


