# nie ma tu nic ciekawego
Sitemap: http://www.poezje.hdwao.pl/sitemap.xml
Sitemap: http://www.poezje.hdwao.pl/sitemap2.xml
Sitemap: http://www.poezje.hdwao.pl/sitemap3.xml
Sitemap: http://www.poezje.hdwao.pl/sitemap4.xml
User-agent: *
Disallow: /admin/
Disallow: /ads/
Disallow: /banery/
Disallow: /download/
Disallow: /ekartka/
Disallow: /fadmin/
Disallow: /forum/
Disallow: /images/
Disallow: /js/
Disallow: /jsr/
Disallow: /kartki/
Disallow: /logs/
Disallow: /mail/
Disallow: /online/
Disallow: /online_f/
Disallow: /online_g/
Disallow: /partnerzy/
Disallow: /phpmailer/
Disallow: /reklama/
Disallow: /seo/
Disallow: /theme/
Disallow: /tmp/
Disallow: /uploads/
