# robots.txt automatically generated by PrestaShop e-commerce open-source solution
# http://www.prestashop.com - http://www.prestashop.com/forums
# This file is to prevent the crawling and indexing of certain parts
# of your site by web crawlers and spiders run by sites like Yahoo!
# and Google. By telling these "robots" where not to go on your site,
# you save bandwidth and server resources.
# For more information about the robots.txt standard, see:
# http://www.robotstxt.org/robotstxt.html
User-agent: *
# Allow Directives
Allow: */modules/*.css
Allow: */modules/*.js
Allow: */modules/*.png
Allow: */modules/*.jpg
Allow: /js/jquery/*
# Private pages
Disallow: /*?order=
Disallow: /*?tag=
Disallow: /*?id_currency=
Disallow: /*?search_query=
Disallow: /*?back=
Disallow: /*?n=
Disallow: /*&order=
Disallow: /*&tag=
Disallow: /*&id_currency=
Disallow: /*&search_query=
Disallow: /*&back=
Disallow: /*&n=
Disallow: /*controller=addresses
Disallow: /*controller=address
Disallow: /*controller=authentication
Disallow: /*controller=cart
Disallow: /*controller=discount
Disallow: /*controller=footer
Disallow: /*controller=get-file
Disallow: /*controller=header
Disallow: /*controller=history
Disallow: /*controller=identity
Disallow: /*controller=images.inc
Disallow: /*controller=init
Disallow: /*controller=my-account
Disallow: /*controller=order
Disallow: /*controller=order-slip
Disallow: /*controller=order-detail
Disallow: /*controller=order-follow
Disallow: /*controller=order-return
Disallow: /*controller=order-confirmation
Disallow: /*controller=pagination
Disallow: /*controller=password
Disallow: /*controller=pdf-invoice
Disallow: /*controller=pdf-order-return
Disallow: /*controller=pdf-order-slip
Disallow: /*controller=product-sort
Disallow: /*controller=search
Disallow: /*controller=statistics
Disallow: /*controller=attachment
Disallow: /*controller=guest-tracking
# Directories for www.aura.szczecin.pl
Disallow: /_sklep_1.7.5.0/app/
Disallow: /_sklep_1.7.5.0/cache/
Disallow: /_sklep_1.7.5.0/classes/
Disallow: /_sklep_1.7.5.0/config/
Disallow: /_sklep_1.7.5.0/controllers/
Disallow: /_sklep_1.7.5.0/download/
Disallow: /_sklep_1.7.5.0/js/
Disallow: /_sklep_1.7.5.0/localization/
Disallow: /_sklep_1.7.5.0/log/
Disallow: /_sklep_1.7.5.0/mails/
Disallow: /_sklep_1.7.5.0/modules/
Disallow: /_sklep_1.7.5.0/override/
Disallow: /_sklep_1.7.5.0/pdf/
Disallow: /_sklep_1.7.5.0/src/
Disallow: /_sklep_1.7.5.0/tools/
Disallow: /_sklep_1.7.5.0/translations/
Disallow: /_sklep_1.7.5.0/upload/
Disallow: /_sklep_1.7.5.0/var/
Disallow: /_sklep_1.7.5.0/vendor/
Disallow: /_sklep_1.7.5.0/webservice/
Disallow: /pl/app/
Disallow: /pl/cache/
Disallow: /pl/classes/
Disallow: /pl/config/
Disallow: /pl/controllers/
Disallow: /pl/download/
Disallow: /pl/js/
Disallow: /pl/localization/
Disallow: /pl/log/
Disallow: /pl/mails/
Disallow: /pl/modules/
Disallow: /pl/override/
Disallow: /pl/pdf/
Disallow: /pl/src/
Disallow: /pl/tools/
Disallow: /pl/translations/
Disallow: /pl/upload/
Disallow: /pl/var/
Disallow: /pl/vendor/
Disallow: /pl/webservice/
# Files
Disallow: /*pl/odzyskiwanie-hasla
Disallow: /*pl/adres
Disallow: /*pl/adresy
Disallow: /*pl/logowanie
Disallow: /*pl/koszyk
Disallow: /*pl/rabaty
Disallow: /*pl/historia-zamowien
Disallow: /*pl/dane-osobiste
Disallow: /*pl/moje-konto
Disallow: /*pl/sledzenie-zamowienia
Disallow: /*pl/potwierdzenie-zwrotu
Disallow: /*pl/zamowienie
Disallow: /*pl/szukaj
Disallow: /*pl/sledzenie-zamowien-gosci
Disallow: /*pl/potwierdzenie-zamowienia
# Sitemap
Sitemap: http://www.aura.szczecin.pl/_sklep_1.7.5.0/1_index_sitemap.xml

