User-agent: *
allow: /
Disallow: /_devinprogress/
Disallow: /_devinprogressPOOLL/
Disallow: /_live_www/
Disallow: /_livingroom_usunac/
Disallow: /_mailing/
Disallow: /_nieruchomosci/
Disallow: /_strony_www/
Disallow: /_szablony/
Disallow: /_vti_pvt/
Disallow: /_vti_txt/
Disallow: /2018_akademiamilpl/
Disallow: /allegro/
Disallow: /autoinstalator/
Disallow: /bodyfitness/
Disallow: /commercium/
Disallow: /config/
Disallow: /copy/
Disallow: /cover/
Disallow: /cyrk/
Disallow: /dejniak/
Disallow: /domeny/
Disallow: /e-kolekcje/
Disallow: /faroma/
Disallow: /gobit/
Disallow: /hidden/
Disallow: /italia-shop/
Disallow: /kantorbay/
Disallow: /kbs/
Disallow: /makeup/
Disallow: /mar-bruk/
Disallow: /mobilese/
Disallow: /nestor/
Disallow: /p4/
Disallow: /pagerank/
Disallow: /pfron_ecri/
Disallow: /pfron1/
Disallow: /pfron2/
Disallow: /pfron2txt/
Disallow: /pfron3/
Disallow: /pfron3txt/
Disallow: /pfron4/
Disallow: /pfron4txt/
Disallow: /pfron5/
Disallow: /pfron5txt/
Disallow: /pfrontxt/
Disallow: /polkraft/
Disallow: /private/
Disallow: /przedszkole1/
Disallow: /psr/
Disallow: /pub/
Disallow: /strony-martwe/
Disallow: /tmp/
Disallow: /toz/
Disallow: /validate/
Disallow: /winb/
Disallow: /wydra-done/
Disallow: /zppp-gorzow/
Disallow: /zsz/
Disallow: /zubowicz/
Disallow: /adn
Disallow: /download
