User-agent: *
Allow: /
Disallow: /fileadmin/user_upload/Downloads/Produkte/
Disallow: /ako-article-code/
Disallow: /ako-artikelcode/
Disallow: /downloads/
Disallow: /produkte/
Disallow: /wissenswertes/
Disallow: /videos/
Disallow: /informations/
Disallow: /wetenswaardigheden/
Disallow: /vaert-att-veta/
Disallow: /vaerd-at-vide/
Disallow: /useful-information/
Disallow: /polezno-znat/
Disallow: /erdemes-tudni/
Disallow: /da-sapere/
Disallow: /curiosidades/
Disallow: /bilinmesi-gerekenler/
Disallow: /utils/
Disallow: /robots/
Disallow: /nc/
Sitemap: https://www.zawory-zaciskowe.pl/index.php?eID=dd_googlesitemap&L=7
