User-agent: *
Disallow: /administrator/
Disallow: /cache/
Disallow: /components/
Disallow: /images/
Disallow: /includes/
Disallow: /installation/
Disallow: /language/
Disallow: /libraries/
Disallow: /media/
Disallow: /modules/
Disallow: /plugins/
Disallow: /templates/
Disallow: /tmp/
Disallow: /xmlrpc/
Disallow: /Productos/Mastiles.html
Disallow: /Productos/Banderas-Publicitarias.html
Disallow: /Productos/Banderas-Institucionales.html
Disallow: /Productos/Fly-banner.html
Disallow: /Productos/Banderas-de-Manifestaciones.html
Disallow: /Productos/Banner-Pop-Up-230x100m.html
Disallow: /Productos/Mastiles-Telescopicos.html
Disallow: /Productos.html
Disallow: /Productos/Accesorios-para-Mastiles.html
Disallow: /Productos/Fabricacion-de-Mastiles.html
Disallow: /General/Plantillas.html
Disallow: Productos/Instrucciones-de-montaje-de-Fly-banner.html

Sitemap: http://www.adivin.com/sitemap-xml.html?sitemap=1
