#As more sites are added, this file should be updated with new Sitemap urls

Sitemap: https://www.dynafleethelp.volvotrucks.com/es-ar/sitemap.xml
Sitemap: https://www.dynafleethelp.volvotrucks.com/en-au/sitemap.xml
Sitemap: https://www.dynafleethelp.volvotrucks.com/de-at/sitemap.xml
Sitemap: https://www.dynafleethelp.volvotrucks.com/ru-by/sitemap.xml
Sitemap: https://www.dynafleethelp.volvotrucks.com/fr-be/sitemap.xml
Sitemap: https://www.dynafleethelp.volvotrucks.com/nl-be/sitemap.xml
Sitemap: https://www.dynafleethelp.volvotrucks.com/pt-br/sitemap.xml
Sitemap: https://www.dynafleethelp.volvotrucks.com/bg-bg/sitemap.xml
Sitemap: https://www.dynafleethelp.volvotrucks.com/es-cl/sitemap.xml
Sitemap: https://www.dynafleethelp.volvotrucks.com/zh-cn/sitemap.xml
Sitemap: https://www.dynafleethelp.volvotrucks.com/hr-hr/sitemap.xml
Sitemap: https://www.dynafleethelp.volvotrucks.com/cs-cz/sitemap.xml
Sitemap: https://www.dynafleethelp.volvotrucks.com/da-dk/sitemap.xml
Sitemap: https://www.dynafleethelp.volvotrucks.com/et-ee/sitemap.xml
Sitemap: https://www.dynafleethelp.volvotrucks.com/fi-fi/sitemap.xml
Sitemap: https://www.dynafleethelp.volvotrucks.com/fr-fr/sitemap.xml
Sitemap: https://www.dynafleethelp.volvotrucks.com/de-de/sitemap.xml
Sitemap: https://www.dynafleethelp.volvotrucks.com/en-hk/sitemap.xml
Sitemap: https://www.dynafleethelp.volvotrucks.com/zh-hk/sitemap.xml
Sitemap: https://www.dynafleethelp.volvotrucks.com/hu-hu/sitemap.xml
Sitemap: https://www.dynafleethelp.volvotrucks.com/en-in/sitemap.xml
Sitemap: https://www.dynafleethelp.volvotrucks.com/id-id/sitemap.xml
Sitemap: https://www.dynafleethelp.volvotrucks.com/he-il/sitemap.xml
Sitemap: https://www.dynafleethelp.volvotrucks.com/ko-kr/sitemap.xml
Sitemap: https://www.dynafleethelp.volvotrucks.com/lv-lv/sitemap.xml
Sitemap: https://www.dynafleethelp.volvotrucks.com/lt-lt/sitemap.xml
Sitemap: https://www.dynafleethelp.volvotrucks.com/mk-mk/sitemap.xml
Sitemap: https://www.dynafleethelp.volvotrucks.com/en-my/sitemap.xml
Sitemap: https://www.dynafleethelp.volvotrucks.com/ms-my/sitemap.xml
Sitemap: https://www.dynafleethelp.volvotrucks.com/fr-ma/sitemap.xml
Sitemap: https://www.dynafleethelp.volvotrucks.com/nl-nl/sitemap.xml
Sitemap: https://www.dynafleethelp.volvotrucks.com/en-nz/sitemap.xml
Sitemap: https://www.dynafleethelp.volvotrucks.com/no-no/sitemap.xml
Sitemap: https://www.dynafleethelp.volvotrucks.com/es-pe/sitemap.xml
Sitemap: https://www.dynafleethelp.volvotrucks.com/pl-pl/sitemap.xml
Sitemap: https://www.dynafleethelp.volvotrucks.com/pt-pt/sitemap.xml
Sitemap: https://www.dynafleethelp.volvotrucks.com/ro-ro/sitemap.xml
Sitemap: https://www.dynafleethelp.volvotrucks.com/ru-ru/sitemap.xml
Sitemap: https://www.dynafleethelp.volvotrucks.com/sr-rs/sitemap.xml
Sitemap: https://www.dynafleethelp.volvotrucks.com/en-sg/sitemap.xml
Sitemap: https://www.dynafleethelp.volvotrucks.com/sk-sk/sitemap.xml
Sitemap: https://www.dynafleethelp.volvotrucks.com/sl-si/sitemap.xml
Sitemap: https://www.dynafleethelp.volvotrucks.com/en-za/sitemap.xml
Sitemap: https://www.dynafleethelp.volvotrucks.com/es-es/sitemap.xml
Sitemap: https://www.dynafleethelp.volvotrucks.com/sv-se/sitemap.xml
Sitemap: https://www.dynafleethelp.volvotrucks.com/de-ch/sitemap.xml
Sitemap: https://www.dynafleethelp.volvotrucks.com/fr-ch/sitemap.xml
Sitemap: https://www.dynafleethelp.volvotrucks.com/zh-tw/sitemap.xml
Sitemap: https://www.dynafleethelp.volvotrucks.com/th-th/sitemap.xml
Sitemap: https://www.dynafleethelp.volvotrucks.com/tr-tr/sitemap.xml
Sitemap: https://www.dynafleethelp.volvotrucks.com/en-ae/sitemap.xml
Sitemap: https://www.dynafleethelp.volvotrucks.com/uk-ua/sitemap.xml
Sitemap: https://www.dynafleethelp.volvotrucks.com/en-gb/sitemap.xml
Sitemap: https://www.dynafleethelp.volvotrucks.com/it-it/sitemap.xml


User-agent: *
Disallow: /content/volvo/
