User-agent: *
Disallow: /_stats/
Disallow: /admin/
Disallow: /changelog/
Disallow: /cookies/
Disallow: /ckeditor/
Disallow: /css/
Disallow: /flash/
Disallow: /grafiki/
Disallow: /images/
Disallow: /img/
Disallow: /inc/
Disallow: /js/
Disallow: /kopie/
Disallow: /mini/
Disallow: /modules/
Disallow: /mpdf/
Disallow: /nivoslider/
Disallow: /podstrony/
Disallow: /scripts/
Disallow: /tmp/
Disallow: /wtyczki/
Disallow: /zapytanie/
Disallow: /banery_statystyki.php
Disallow: /captcha.php
Disallow: /drukuj.php
Disallow: /drukuj_produkt.php
Disallow: /faktura.php
Disallow: /mail_style.inc.php
Disallow: /ostrzezenie.php
Disallow: /pdf.php
Disallow: /pdf_produkt.php
Disallow: /piece.php
Disallow: /piecemaker.css
Disallow: /piecemaker.swf
Disallow: /polec.php
Disallow: /wyszukiwarka.php
