User-agent: *
Disallow: /administrator/
Disallow: /bin/
Disallow: /cache/
Disallow: /cli/
Disallow: /components/
Disallow: /images/
Disallow: /includes/
Disallow: /installation/
Disallow: /language/
Disallow: /libraries/
Disallow: /logs/
Disallow: /media/
Disallow: /modules/
Disallow: /pic/
Disallow: /picsel/
Disallow: /plugins/
Disallow: /templates/
Disallow: /tmp/
Disallow: /xmlrpc/
Disallow: /projekt/
Disallow: /rettpolmail/
Disallow: /szablon-allegro/
Disallow: /allegro/
Disallow: /serwis
Disallow: /formularz-serwisowy
Disallow: /bdump/
Disallow: /api/
Crawl-Delay: 10
