User-agent: *
Disallow: /administrator/
Disallow: /cache/
Disallow: /components/
Disallow: /images/
Disallow: /includes/
Disallow: /installation/
Disallow: /language/
Disallow: /libraries/
Disallow: /media/
Disallow: /modules/
Disallow: /plugins/
Disallow: /templates/
Disallow: /tmp/
Disallow: /xmlrpc/
Allow: /plugins/system/jceutilities/themes/standard/css/
Allow: /plugins/system/jceutilities/css/
Allow: /modules/mod_djimageslider/assets/
Allow: /media/system/js/
Allow: /plugins/system/jceutilities/js/
Allow: /templates/system/css/
Allow: /templates/www/css/
Allow: /images/stories/photo_strona/
Allow: /images/stories/top_baner/
Allow: /images/stories/pliki_strony/
Allow: /templates/www/img/
