User-agent: *
Disallow: /basket/
Disallow: /user/
Disallow: /review/
Disallow: /stAccessoriesFrontend/
Disallow: /product/
Disallow: /productsCompare/
Disallow: /category/meble-ogrodowe/2/long
Disallow: /category/meble-ogrodowe/2/short
Disallow: /category/meble-ogrodowe/2/other
Disallow: /category/meble-ogrodowe/1/long
Disallow: /category/meble-ogrodowe/1/short
Disallow: /category/meble-ogrodowe/1/other
Disallow: /category/deski-tarasowe/1/long
Disallow: /category/deski-tarasowe/1/short
Disallow: /category/deski-tarasowe/1/other
Disallow: /category/narzedzia-ogrodnicze/2/long
Disallow: /category/narzedzia-ogrodnicze/2/short
Disallow: /category/narzedzia-ogrodnicze/2/other
Disallow: /category/narzedzia-ogrodnicze/1/long
Disallow: /category/narzedzia-ogrodnicze/1/short
Disallow: /category/narzedzia-ogrodnicze/1/other
Disallow: /manufacturer/ogrody-leandro/1/long
Disallow: /manufacturer/ogrody-leandro/1/short
Disallow: /manufacturer/ogrody-leandro/1/other
Disallow: /manufacturer/ogrody-leandro/2/long
Disallow: /manufacturer/ogrody-leandro/2/short
Disallow: /manufacturer/ogrody-leandro/2/other
Disallow: /manufacturer/ogrody-leandro/3/long
Disallow: /manufacturer/ogrody-leandro/3/short
Disallow: /manufacturer/ogrody-leandro/3/other
Disallow: /manufacturer/ogrody-leandro/4/long
Disallow: /manufacturer/ogrody-leandro/4/short
Disallow: /manufacturer/ogrody-leandro/4/other
Disallow: /manufacturer/lucy-ray/1/long
Disallow: /manufacturer/lucy-ray/1/short
Disallow: /manufacturer/lucy-ray/1/other
Disallow: /manufacturer/lucy-ray/2/long
Disallow: /manufacturer/lucy-ray/2/short
Disallow: /manufacturer/lucy-ray/2/other
Disallow: /manufacturer/lucy-ray/3/long
Disallow: /manufacturer/lucy-ray/3/short
Disallow: /manufacturer/lucy-ray/3/other
Disallow: /category/oslonki-na-doniczki/1/long
Disallow: /category/oslonki-na-doniczki/1/short
Disallow: /category/oslonki-na-doniczki/1/other
Disallow: /category/donice-ceramiczne/1/long
Disallow: /category/donice-ceramiczne/1/short
Disallow: /category/donice-ceramiczne/1/other
Disallow: /category/doniczki-kwietniki/1/long
Disallow: /category/doniczki-kwietniki/1/short
Disallow: /category/doniczki-kwietniki/1/other
Disallow: /category/narzedzia-ogrodnicze-zima-odsniezanie/1/long
Disallow: /category/narzedzia-ogrodnicze-zima-odsniezanie/1/short
Disallow: /category/narzedzia-ogrodnicze-zima-odsniezanie/1/other
Disallow: /category/deski-tarasowe-akacja-taras/1/long
Disallow: /category/deski-tarasowe-akacja-taras/1/short
Disallow: /category/deski-tarasowe-akacja-taras/1/other
Disallow: /invoice
Disallow: /order
Disallow: /invoicePdf/*
Disallow: /orderPdf/*
Disallow: /stAvailabilityFrontend/showAddOverlay
Disallow: /stQuestionFrontend/showAddOverlay
Disallow: /stAvailabilityFrontend/showAddOverlay
Disallow: /stQuestionFrontend/showAddOverlay
Disallow: /*.php$
Disallow: /paypal

