# robots.txt automaticaly generated by PrestaShop e-commerce open-source solution
# http://www.prestashop.com - http://www.prestashop.com/forums
# This file is to prevent the crawling and indexing of certain parts
# of your site by web crawlers and spiders run by sites like Yahoo!
# and Google. By telling these "robots" where not to go on your site,
# you save bandwidth and server resources.
# For more information about the robots.txt standard, see:
# http://www.robotstxt.org/robotstxt.html
User-agent: *
# Allow Directives
Allow: */modules/*.css
Allow: */modules/*.js
# Directories
Disallow: */classes/
Disallow: */config/
Disallow: */download/
Disallow: */mails/
Disallow: */modules/
Disallow: */translations/
Disallow: */tools/
# Files
Disallow: /*pl/adres
Disallow: /*pl/adresy
Disallow: /*pl/logowanie
Disallow: /*pl/koszyk
Disallow: /*pl/rabaty
Disallow: /*pl/sledzenie-zamowienia-gosc
Disallow: /*pl/historia-zamowien
Disallow: /*pl/dane-osobiste
Disallow: /*pl/moje-konto
Disallow: /*pl/zamowienie
Disallow: /*pl/potwierdzenie-zamowienia
Disallow: /*pl/sledzenie-zamowienia
Disallow: /*pl/szybkie-zakupy
Disallow: /*pl/pokwitowania
Disallow: /*pl/odzyskiwanie-hasla
Disallow: /*pl/szukaj
# Sitemap
Sitemap: https://www.forhim.pl/1_pl_0_sitemap.xml

