# robots.txt automaticaly generated by PrestaShop e-commerce open-source solution
# http://www.prestashop.com - http://www.prestashop.com/forums
# This file is to prevent the crawling and indexing of certain parts
# of your site by web crawlers and spiders run by sites like Yahoo!
# and Google. By telling these "robots" where not to go on your site,
# you save bandwidth and server resources.
# For more information about the robots.txt standard, see:
# http://www.robotstxt.org/wc/robots.html
# GoogleBot specific
User-agent: Googlebot
Disallow: /page/*orderby=
Disallow: /page/*orderway=
Disallow: /page/*tag=
Disallow: /page/*id_currency=
Disallow: /page/*search_query=
Disallow: /page/*id_lang=
Disallow: /page/*back=
Disallow: /page/*utm_source=
Disallow: /page/*utm_medium=
Disallow: /page/*utm_campaign=
Disallow: /page/*n=
# All bots
User-agent: *
# Directories
Disallow: /page/classes/
Disallow: /page/config/
Disallow: /page/download/
Disallow: /page/mails/
Disallow: /page/modules/
Disallow: /page/translations/
Disallow: /page/tools/
# Files
Disallow: /page/addresses.php
Disallow: /page/address.php
Disallow: /page/authentication.php
Disallow: /page/cart.php
Disallow: /page/discount.php
Disallow: /page/footer.php
Disallow: /page/get-file.php
Disallow: /page/header.php
Disallow: /page/history.php
Disallow: /page/identity.php
Disallow: /page/images.inc.php
Disallow: /page/init.php
Disallow: /page/my-account.php
Disallow: /page/order.php
Disallow: /page/order-opc.php
Disallow: /page/order-slip.php
Disallow: /page/order-detail.php
Disallow: /page/order-follow.php
Disallow: /page/order-return.php
Disallow: /page/order-confirmation.php
Disallow: /page/pagination.php
Disallow: /page/password.php
Disallow: /page/pdf-invoice.php
Disallow: /page/pdf-order-return.php
Disallow: /page/pdf-order-slip.php
Disallow: /page/product-sort.php
Disallow: /page/search.php
Disallow: /page/statistics.php
Disallow: /page/attachment.php
Disallow: /page/guest-tracking.php
Disallow: /page/password-recovery
Disallow: /page/odzyskiwanie-hasla
Disallow: /page/address
Disallow: /page/adres
Disallow: /page/addresses
Disallow: /page/adresy
Disallow: /page/authentication
Disallow: /page/rejestracja
Disallow: /page/cart
Disallow: /page/rezerwuj
Disallow: /page/discount
Disallow: /page/bony-rabatowe
Disallow: /page/order-history
Disallow: /page/history
Disallow: /page/identity
Disallow: /page/identyfikacja
Disallow: /page/my-account
Disallow: /page/moje-konto
Disallow: /page/order-follow
Disallow: /page/sledzenie
Disallow: /page/order-slip
Disallow: /page/zwroty
Disallow: /page/order
Disallow: /page/rezerwacje
Disallow: /page/search
Disallow: /page/szukaj
Disallow: /page/quick-order
Disallow: /page/Rezerwowanie
Disallow: /page/guest-tracking
Disallow: /page/guest-tracking
# Sitemap
Sitemap: http://www.welter.com.pl/page/sitemap.xml


