Disallow: /xmlrpc/User-agent: *
Disallow: /administrator/
Disallow: /cache/
Disallow: /components/
Disallow: /images/
Disallow: /includes/
Disallow: /installation/
Disallow: /language/
Disallow: /libraries/
Disallow: /media/
Disallow: /modules/
Disallow: /plugins/
Disallow: /stats/
Disallow: /templates/
Disallow: /tmp/
Disallow: /xmlrpc/
Disallow: /new/
User-agent: bingbot
Crawl-delay: 1
User-agent: MSNbot
Crawl-delay: 1
User-agent: MSNbot / Bingbot
Crawl-delay: 1
