# robots.txt automaticaly generated by PrestaShop e-commerce open-source solution
# http://www.prestashop.com - http://www.prestashop.com/forums

# This file is to prevent the crawling and indexing of certain parts
# of your site by web crawlers and spiders run by sites like Yahoo!
# and Google. By telling these "robots" where not to go on your site,
# you save bandwidth and server resources.

# For more information about the robots.txt standard, see:
# http://www.robotstxt.org/wc/robots.html

User-agent: *
# Directories
Disallow: /prestashop2/classes/
Disallow: /prestashop2/config/
Disallow: /prestashop2/download/
Disallow: /prestashop2/mails/
Disallow: /prestashop2/modules/
Disallow: /prestashop2/translations/
Disallow: /prestashop2/tools/
Disallow: /prestashop2/lang-pl/
# Files
Disallow: /prestashop2/addresses.php
Disallow: /prestashop2/address.php
Disallow: /prestashop2/authentication.php
Disallow: /prestashop2/cart.php
Disallow: /prestashop2/discount.php
Disallow: /prestashop2/footer.php
Disallow: /prestashop2/get-file.php
Disallow: /prestashop2/header.php
Disallow: /prestashop2/history.php
Disallow: /prestashop2/identity.php
Disallow: /prestashop2/images.inc.php
Disallow: /prestashop2/init.php
Disallow: /prestashop2/my-account.php
Disallow: /prestashop2/order.php
Disallow: /prestashop2/order-opc.php
Disallow: /prestashop2/order-slip.php
Disallow: /prestashop2/order-detail.php
Disallow: /prestashop2/order-follow.php
Disallow: /prestashop2/order-return.php
Disallow: /prestashop2/order-confirmation.php
Disallow: /prestashop2/pagination.php
Disallow: /prestashop2/password.php
Disallow: /prestashop2/pdf-invoice.php
Disallow: /prestashop2/pdf-order-return.php
Disallow: /prestashop2/pdf-order-slip.php
Disallow: /prestashop2/product-sort.php
Disallow: /prestashop2/search.php
Disallow: /prestashop2/statistics.php
Disallow: /prestashop2/attachment.php
Disallow: /prestashop2/guest-tracking
Disallow: /prestashop2/*orderby=
Disallow: /prestashop2/*orderway=
Disallow: /prestashop2/*tag=
Disallow: /prestashop2/*id_currency=
Disallow: /prestashop2/*search_query=
Disallow: /prestashop2/*id_lang=
Disallow: /prestashop2/*back=
Disallow: /prestashop2/*utm_source=
Disallow: /prestashop2/*utm_medium=
Disallow: /prestashop2/*utm_campaign=
Disallow: /prestashop2/*n=
# Sitemap


