User-agent: *
Disallow: /administrator/
Disallow: /bin/
Disallow: /cache/
Disallow: /cli/
Disallow: /components/
Disallow: /includes/
Disallow: /installation/
Disallow: /language/
Disallow: /layouts/
Disallow: /libraries/
Disallow: /logs/
Disallow: /tmp/

Allow: /plugins/*.css
Allow: /plugins/*.js
Allow: /templates/*.css
Allow: /templates/*.js
Allow: /templates/*.png
Allow: /templates/*.gif
Allow: /templates/*.woff
Allow: /media/*.css
Allow: /media/*.js
Allow: /media/*.png
Allow: /media/*.gif
Allow: /modules/*.css
Allow: /modules/*.js
Allow: /modules/*.png
Allow: /cache/*.jpg
Allow: /
