# robots.txt automaticaly generated by PrestaShop e-commerce open-source solution
# http://www.prestashop.com - http://www.prestashop.com/forums
# This file is to prevent the crawling and indexing of certain parts
# of your site by web crawlers and spiders run by sites like Yahoo!
# and Google. By telling these "robots" where not to go on your site,
# you save bandwidth and server resources.
# For more information about the robots.txt standard, see:
# http://www.robotstxt.org/robotstxt.html
User-agent: *
# Allow Directives
Allow: */modules/*.css
Allow: */modules/*.js
# Private pages
Disallow: /*?orderby=
Disallow: /*?orderway=
Disallow: /*?tag=
Disallow: /*?id_currency=
Disallow: /*?search_query=
Disallow: /*?back=
Disallow: /*?n=
Disallow: /*&orderby=
Disallow: /*&orderway=
Disallow: /*&tag=
Disallow: /*&id_currency=
Disallow: /*&search_query=
Disallow: /*&back=
Disallow: /*&n=
Disallow: /*controller=addresses
Disallow: /*controller=address
Disallow: /*controller=authentication
Disallow: /*controller=cart
Disallow: /*controller=discount
Disallow: /*controller=footer
Disallow: /*controller=get-file
Disallow: /*controller=header
Disallow: /*controller=history
Disallow: /*controller=identity
Disallow: /*controller=images.inc
Disallow: /*controller=init
Disallow: /*controller=my-account
Disallow: /*controller=order
Disallow: /*controller=order-opc
Disallow: /*controller=order-slip
Disallow: /*controller=order-detail
Disallow: /*controller=order-follow
Disallow: /*controller=order-return
Disallow: /*controller=order-confirmation
Disallow: /*controller=pagination
Disallow: /*controller=password
Disallow: /*controller=pdf-invoice
Disallow: /*controller=pdf-order-return
Disallow: /*controller=pdf-order-slip
Disallow: /*controller=product-sort
Disallow: /*controller=search
Disallow: /*controller=statistics
Disallow: /*controller=attachment
Disallow: /*controller=guest-tracking
# Directories
Disallow: */classes/
Disallow: */config/
Disallow: */download/
Disallow: */mails/
Disallow: */translations/
Disallow: */tools/
# Files
Disallow: /*odzyskiwanie-hasla
Disallow: /*odzyskiwanie-hasla
Disallow: /*adres
Disallow: /*adres
Disallow: /*adresy
Disallow: /*adresy
Disallow: /*logowanie
Disallow: /*logowanie
Disallow: /*koszyk
Disallow: /*koszyk
Disallow: /*rabaty
Disallow: /*rabaty
Disallow: /*historia-zamowien
Disallow: /*historia-zamowien
Disallow: /*dane-osobiste
Disallow: /*dane-osobiste
Disallow: /*moje-konto
Disallow: /*moje-konto
Disallow: /*sledzenie-zamowienia
Disallow: /*sledzenie-zamowienia
Disallow: /*pokwitowania
Disallow: /*pokwitowania
Disallow: /*zamowienie
Disallow: /*zamowienie
Disallow: /*szukaj
Disallow: /*szukaj
Disallow: /*szybkie-zakupy
Disallow: /*szybkie-zakupy
Disallow: /*sledzenie-zamowienia-gosc
Disallow: /*sledzenie-zamowienia-gosc
Disallow: /*potwierdzenie-zamowienia
Disallow: /*potwierdzenie-zamowienia

Disallow: /content/9-zgoda-na-przetwarzanie-danych-
Disallow: /content/10-polityka-prywatnosci
Disallow: /content/3-regulamin
Disallow: /content/5-platnosci
Disallow: /content/1-dostawa
Disallow: /historia-zamowien
Disallow: /dane-osobiste
Disallow: /pokwitowania
Disallow: /adresy

Disallow: /0-home_default/okulary-astrospec.jpg
Disallow: /0-home_default/rekawice-nitrylowe--a100-niebieskie-ideall-nitrille.jpg
Disallow: /0-home_default/spodnie-ogrodniczki-tartak-lis.jpg
Disallow: /0-home_default/tristep-kombinezon-roboczy-planam--chabrowy.jpg
Disallow: /0-home_default/znaki-bhp.jpg

# Sitemap
Sitemap: https://mado.com.pl/1_index_sitemap.xml

