User-agent: *
Disallow: /admin
Disallow: /download
Disallow: /tmp
Disallow: /account.php
Disallow: /advanced_search.php
Disallow: /checkout_shipping.php
Disallow: /checkout_payment.php
Disallow: /checkout_process.php
Disallow: /cookie_usage.php
Disallow: /create_account.php
Disallow: /login.php
Disallow: /password_forgotten.php
Disallow: /shopping_cart.php
Disallow: /product_reviews_write.php
Disallow: /ask_a_question.php
