User-agent: *
Disallow: /administrator/
Disallow: /cache/
Disallow: /components/
Disallow: /component/
Disallow: /images/
Disallow: /includes/
Disallow: /installation/
Disallow: /language/
Disallow: /libraries/
Disallow: /media/
Disallow: /modules/
Disallow: /plugins/
Disallow: /templates/
Disallow: /tmp/
Disallow: /xmlrpc/
Disallow: *layout*
Disallow: *start=5
Disallow: *option
Disallow: *kromapl
Disallow: *pliki-do-pobrania
Disallow: *rss
Disallow: *12-kroma
Disallow: *kontakt/administrator
Disallow: *pdf
Disallow: /component/aicontactsafe/
Disallow: /component/user/reset
Disallow: /component/user/remind
