User-agent: *
Disallow: /banery/
Disallow: /foto/
Disallow: /googlemaps/
Disallow: /incl/
Disallow: /kris/
Disallow: /phpBB2/
Disallow: /projekty/
Disallow: /tmp/
Disallow: /fpdf.php
Disallow: /ankieta_form.php
Disallow: /baner_mbank.php
Disallow: /baza_search2.php
Disallow: /baza_search3.php
Disallow: /baza_search4.php
Disallow: /baza_wpis2.php
Disallow: /baza_wpis3.php
Disallow: /baza_wpis4.php
Disallow: /bilety.php
Disallow: /czcionka.php
Disallow: /organizatorzy_test.php
Disallow: /polec2.php
Disallow: /polec3.php
Disallow: /profil_add2.php
Disallow: /profil_del.php
Disallow: /profil_edit2.php
Disallow: /profil_search2.php
Disallow: /reklama_form.php
Disallow: /reklama2.php
Disallow: /reklamawserwisie.php
Disallow: /test.php
Disallow: /thx.php
Disallow: /wypisz.php

Disallow: /board/style_images/
Disallow: /board/lofiversion/
Disallow: /board/index.php?act=idx
Disallow: /board/index.php?act=Login
Disallow: /board/index.php?act=Search
Disallow: /board/index.php?act=Shoutbox
Disallow: /board/index.php?act=Reg
Disallow: /board/index.php?act=Msg
Disallow: /board/index.php?act=Mail
Disallow: /board/index.php?act=Forward
Disallow: /board/index.php?act=Track
Disallow: /board/index.php?act=Post
Disallow: /board/index.php?act=post
Disallow: /board/index.php?act=Print
Disallow: /board/index.php?act=ST
Disallow: /board/index.php?act=boardrules
Disallow: /board/?act=boardrules
Disallow: /board/index.php?act=Help
Disallow: /board/index.php?act=Stats
Disallow: /board/index.php?act=stats
Disallow: /board/index.php?act=Members
Disallow: /board/index.php?act=Online
Disallow: /board/index.php?act=calendar
Disallow: /board/index.php?act=SR
Disallow: /board/index.php?act=SF
Disallow: /board/index.php?act=ICQ
Disallow: /board/index.php?act=MSN
Disallow: /board/index.php?act=AOL
Disallow: /board/index.php?act=AIM
Disallow: /board/index.php?act=SC
Disallow: /board/index.php?act=task
Disallow: /board/index.php?act=findpost
Disallow: /board/index.php?act=UserCP
Disallow: /board/index.php?act=usercp
Disallow: /board/index.php?&act=
Disallow: /board/index.php?act=report
Disallow: /board/index.php?act=buddy
Disallow: /board/index.php?act=legends
Disallow: /board/index.php?CODE=
Disallow: /board/index.php?act=attach
Disallow: /board/index.php?act=Attach
Disallow: /board/index.php?&&CODE=
Disallow: /board/index.php?&debug=1
Disallow: /board/index.php?act=Profile
Disallow: /board/index.php?showuser
Disallow: /board/index.php?s=
Disallow: /*&view=getnewpost$
Disallow: /*&view=getlastpost$
Disallow: /*&view=old$
Disallow: /*&view=new$
Disallow: /*mode=linear
Disallow: /*mode=threaded
Disallow: /*mode=linearplus
Disallow: /*&p=
Disallow: /*&pid=
Disallow: /*&gopid=
Disallow: /*&hl=
Disallow: /*&start=
Disallow: /*gallery&req=stats
Disallow: /*gallery&req=user
Disallow: /*gallery&req=slideshow
Disallow: /*reportimage


