User-agent: *
Disallow: /wp-admin/
Disallow: /wp-includes/
Disallow: /agents/
Disallow: /listings/
Disallow: /agents/kontakt/
Disallow: /property_category/magazyny/
Disallow: /property_city/inne/
Disallow: /property_city/poznan/
Disallow: /property_city/swarzedz/
Disallow: /property_area/wielkopolska/
Disallow: /property_action_category/do-wynajecia/
Disallow: /property_action_category/na-sprzedaz/
Disallow: /kontakt/
Disallow: /oferta/
Disallow: /galeria/
Disallow: /property-search/
Disallow: /advanced-search/
Disallow: /o-nas/
Disallow: /city/warszawa/
Disallow: /neighborhood/mazowieckie/
Disallow: /author/admin/
Disallow: /compare-pages/
Disallow: /state/masovian-voivodeship/
Disallow: /properties/page/2/
