User-agent: *
Disallow: /administrator/
Disallow: /cache/
Disallow: /cli/
Disallow: /components/
Disallow: /includes/
Disallow: /installation/
Disallow: /language/
Disallow: /libraries/
Disallow: /logs/
Disallow: /modules/
Disallow: /templates/atomic/
Disallow: /templates/beez5/
Disallow: /templates/beez_20/
Disallow: /templates/roger-old/
Disallow: /tmp/
Allow: *.css
Allow: *.js
Allow: /components/com_chronoforms/css/
Allow: /components/com_chronoforms/js/
Allow: /modules/mod_jse_megamenu/assets/js/
