User-agent: *
Disallow: /administrator/
Disallow: /cache/
Disallow: /cli/
Disallow: /components/
Disallow: /images/
Disallow: /includes/
Disallow: /installation/
Disallow: /language/
Disallow: /libraries/
Disallow: /logs/
Disallow: /media/
Disallow: /modules/
Disallow: /plugins/
Disallow: /templates/
Disallow: /tmp/
Disallow: /xmlrpc/
Disallow: /index.php/pl/home$
Disallow: /index.php/en/home$
Disallow: /index.php/en/tarczynski/aboutourcompany$
Disallow: /index.php/en/tarczynski/awardsandcertificates$
Disallow: /index.php/en/tarczynski/awardsandcertificates?start=*
Disallow: /index.php/en/tarczynski/spot-reklamowy$
Disallow: /index.php/en/tarczynski/formularz$
Disallow: /index.php/en/products/produkty-tarczyski/linia-po-wiejsku$
Disallow: /index.php/en/products/produkty-tarczyski/pieczone-z-podbeskidzia-starpeck$
Disallow: /index.php/en/products/produkty-tarczyski/duopack$
Disallow: /index.php/en/products/produkty-dobrosawa/linia-geesowska$
Disallow: /index.php/en/products/produkty-dobrosawa/wdliny-z-wiejskiej-chaty$
Disallow: /index.php/en/products/katalog2012$
Disallow: /index.php/en/for-the-media*
Disallow: /index.php/en/tarczynski-kabanos-extra$
Disallow: /index.php/en/linia-geesowska$
Disallow: /index.php/en/wdliny-z-wiejskiej-chaty$
Disallow: /index.php/en/produkty-dobroslawa$
Disallow: /index.php/en/oak-tradition$
Disallow: /index.php/en/tajemnicekuchni$
Disallow: /index.php/en/premium-cold-cuts$
Disallow: /index.php/en/meat-preparations-in-jars$
Disallow: /index.php/en/fillet-products$
Disallow: /index.php/en/to-go-line$
Disallow: /index.php/en/wdliny-po-wiejsku$
Disallow: /index.php/en/products/smoked-cold-cuts$
Disallow: /index.php/en/products/thin-sausages$
Disallow: /index.php/en/products/bars-and-pressed-products$
Disallow: /index.php/en/products/offal-and-delicatessen-meats$
Disallow: /index.php/en/products/miesomielone$
Disallow: /index.php/en/products/thick-sausages$
Disallow: /index.php/en/duopak$
Disallow: /index.php/en/pieczonezpodbeskidziastarpeck-$
Disallow: /pl/tarczyski/spot-reklamowy
Disallow: /index.php/pl/tarczyski/formularz
Disallow: /index.php/pl/kabanosy-extra
Disallow: /index.php?option=*
Disallow: /podstrona.php?str=*
Disallow: /en/index.php?option=*
Disallow: /index.php/*
Disallow: /index.php?*
Disallow: /en/index.php/*
