User-agent: *
Disallow: /cyklotrasy/mapa/
Disallow: /turistika/mapa/
Disallow: /bezecke-trasy/mapa/
Disallow: /in-line/mapa/
Disallow: /objekty/hotelclient
Disallow: /objekty/hotelmisto.php
Disallow: /objekty/hotel3.php
Disallow: /objekty/hotel2.php
Disallow: /ubytovani-na-horach/
Disallow: /share/licence.php
Disallow: /share/countJS.php
Disallow: /?from=
Disallow: /share/cam.php
Disallow: /objekty/skimain
Disallow: /objekty/skiprint
Disallow: /objekty/hotelimage
Disallow: /objekty/hledamkontakt
Disallow: /objekty/objekt.php
Disallow: /lanovka/doporucit/
Disallow: /lanovka/email/
Disallow: /lanovka/tisk/
Disallow: /lanovka/video/
Disallow: /ski-areal/doporucit/
Disallow: /ski-areal/email/
Disallow: /ski-areal/tisk/
Disallow: /ski-areal/video/
Disallow: /ski-centre/recommend/
Disallow: /ski-centre/email/
Disallow: /ski-centre/print/
Disallow: /ski-centre/video/
Disallow: /funicular/recommend/
Disallow: /funicular/email/
Disallow: /funicular/print/
Disallow: /funicular/video/
Disallow: /skizentrum/empfehlen/
Disallow: /skizentrum/email/
Disallow: /skizentrum/druck/
Disallow: /skizentrum/video/
Disallow: /seilbahn/empfehlen/
Disallow: /seilbahn/email/
Disallow: /seilbahn/druck/
Disallow: /seilbahn/video/
Disallow: /osrodek-narciarski/polecic/
Disallow: /osrodek-narciarski/email/
Disallow: /osrodek-narciarski/druk/
Disallow: /osrodek-narciarski/video/
Disallow: /kolejka-linowa/polecic/
Disallow: /kolejka-linowa/email/
Disallow: /kolejka-linowa/druk/
Disallow: /kolejka-linowa/video/
Disallow: /ubytovani/email/
Disallow: /ubytovani/doporucit/
Disallow: /ubytovani/tisk/
Disallow: /unterkunft/empfehlen/
Disallow: /unterkunft/email/
Disallow: /unterkunft/druck/
Disallow: /accommodation/recommend/
Disallow: /accommodation/email/
Disallow: /accommodation/print/
Disallow: /zakwaterowanie/polecic/
Disallow: /zakwaterowanie/email/
Disallow: /zakwaterowanie/druk/
Disallow: /cyklotrasy/cyklotrasa.asp
Disallow: /soutez/
Disallow: /briefcase/?i=n&
Disallow: /share/image.php
Disallow: /reklama/reklama2_server.php
Disallow: /objekty/map
Disallow: /share/map
Disallow: /profil/login.php
Disallow: /profil/logout.php
Disallow: /profil/ajax_nick.php
Disallow: /profil/ajax_nickauto.php
Disallow: /profil/aktivace.php
Disallow: /profil/foto.php
Disallow: /profil/index.php
Disallow: /profil/register.php
Disallow: /profil/removeitem.php
Disallow: /profil/additem.php
Disallow: /profil/upload_image.php
Disallow: /profil/zapomenute_heslo.php

