User-agent: *
Disallow: /*.CVS
Disallow: /*.Idea$
Disallow: /*.php$
Disallow: /*.Sql$
Disallow: /*.Svn$
Disallow: /*.Tgz$
Disallow: /*.Zip$
Disallow: /*?
Disallow: /*?*product_list_dir=
Disallow: /*?*product_list_limit=
Disallow: /*?*product_list_mode=
Disallow: /*?*product_list_order=
Disallow: /*?dir*
Disallow: /*?dir=asc
Disallow: /*?dir=desc
Disallow: /*?limit=all
Disallow: /*?mode*
Disallow: /*?SID=
Disallow: /*SID=
Disallow: /admin/
Disallow: /app/
Disallow: /bin/
Disallow: /catalog/category/view/
Disallow: /catalog/product/view/
Disallow: /catalog/product_compare/
Disallow: /catalogsearch/
Disallow: /checkout/
Disallow: /composer.json
Disallow: /composer.lock
Disallow: /contacts/
Disallow: /CONTRIBUTING.md
Disallow: /CONTRIBUTOR_LICENSE_AGREEMENT.html
Disallow: /control/
Disallow: /COPYING.txt
Disallow: /customer/
Disallow: /customer/account/
Disallow: /customer/account/login/
Disallow: /customize/
Disallow: /dev/
Disallow: /directory/
Disallow: /enable-cookies/
Disallow: /Gruntfile.js
Disallow: /index.php/
Disallow: /js/
Disallow: /lib/
Disallow: /LICENSE.html
Disallow: /LICENSE.txt
Disallow: /LICENSE_AFL.txt
Disallow: /newsletter/
Disallow: /nginx.conf.sample
Disallow: /onestepcheckout/
Disallow: /package.json
Disallow: /php.ini.sample
Disallow: /phpserver/
Disallow: /pkginfo/
Disallow: /RELEASE_NOTES.txt
Disallow: /report/
Disallow: /review/
Disallow: /review/product/
Disallow: /sendfriend/
Disallow: /setup/
Disallow: /skin/
Disallow: /tag/
Disallow: /update/
Disallow: /var/
Disallow: /vendor/
Disallow: /wishlist/

User-agent: Googlebot-image
Disallow:
