User-agent:*
Disallow:/administrator/
Disallow:/bin/
Disallow:/cache/
Disallow:/cli/
Disallow:/components/
Disallow:/images/
Disallow:/includes/
Disallow:/installation/
Disallow:/language/
Disallow:/layouts/
Disallow:/libraries/
Disallow:/logs/
Disallow:/modules/
Disallow:/plugins/
Disallow:/searchGR26zst/
Disallow:/tmp/
Disallow:/planLekcji/
Disallow:/planTelefon/
Disallow:/pdf/
