User-agent: GoogleBot
Allow: /*.css
Allow: /*.js
Allow: /*.jpg
Allow: /*.jpeg
Allow: /*.png
Allow: /*.gif
Allow: /*.doc
Disallow: /*?s=*
Disallow: /*/author/
Disallow: /*/tag/
Disallow: /wp-admin/
Disallow: */system/files/
Disallow: */files/
Disallow: /ru/ekaterinburg/
Disallow: /ru/moscow/
Disallow: /ru/kazan/
Disallow: /ru/nizhnij-novgorod/
Disallow: /ru/rostov-na-donu/
Disallow: /ru/samara/
Disallow: /ru/sankt-peterburg/
Disallow: /ru/togliatti/
Noindex: */system/files/
Noindex: */files/

User-agent: *
Allow: /*.css
Allow: /*.js
Allow: /*.jpg
Allow: /*.jpeg
Allow: /*.png
Allow: /*.gif
Allow: /*.pdf
Allow: /*.doc
Disallow: /*?s=*
Disallow: /*/author/
Disallow: /*/tag/
Disallow: /wp-admin/
Disallow: */system/files/
Disallow: */files/
Noindex: */system/files/
Noindex: */files/
Host: https://lindstromgroup.com
Sitemap: https://lindstromgroup.com/sitemap_index.xml
Sitemap: https://lindstromgroup.com/fi/sitemap_index.xml
Sitemap: https://lindstromgroup.com/uk/sitemap_index.xml
Sitemap: https://lindstromgroup.com/ru/sitemap_index.xml
Sitemap: https://lindstromgroup.com/rs/sitemap_index.xml
Sitemap: https://lindstromgroup.com/ro/sitemap_index.xml
Sitemap: https://lindstromgroup.com/bg/sitemap_index.xml
Sitemap: https://lindstromgroup.com/in/sitemap_index.xml
Sitemap: https://lindstromgroup.com/hr/sitemap_index.xml
Sitemap: https://lindstromgroup.com/rs/sitemap_index.xml
Sitemap: https://lindstromgroup.com/lv/sitemap_index.xml
Sitemap: https://lindstromgroup.com/se/sitemap_index.xml
Sitemap: https://lindstromgroup.com/ko/sitemap_index.xml
Sitemap: https://lindstromgroup.com/cn-en/sitemap_index.xml
Sitemap: https://lindstromgroup.com/cn/sitemap_index.xml
Sitemap: https://lindstromgroup.com/tr/sitemap_index.xml
Sitemap: https://lindstromgroup.com/hu/sitemap_index.xml
Sitemap: https://lindstromgroup.com/cz/sitemap_index.xml
Sitemap: https://lindstromgroup.com/po/sitemap_index.xml
Sitemap: https://lindstromgroup.com/kz/sitemap_index.xml
Sitemap: https://lindstromgroup.com/ua-ru/sitemap_index.xml
Sitemap: https://lindstromgroup.com/ua/sitemap_index.xml
Sitemap: https://lindstromgroup.com/ee/sitemap_index.xml
Sitemap: https://lindstromgroup.com/lt/sitemap_index.xml
Sitemap: https://lindstromgroup.com/by/sitemap_index.xml
Sitemap: https://lindstromgroup.com/si/sitemap_index.xml
Sitemap: https://lindstromgroup.com/sk/sitemap_index.xml
