User-agent: *
Disallow: /sophia_loren_bio.htm
Disallow: /tefal/img/common/spacer.gifwidth=
Disallow: /collections/Autocuiseurs/maga/
Disallow: /collections/Autocuiseurs/Pratica/
Disallow: /collections/Articles-culinaires-fixes/Melodia/
Disallow: /collections/Articles-culinaires-fixes/Pandora/
Disallow: /collections/Articles-culinaires-fixes/novia/
Disallow: /collections/Articles-culinaires-amovibles/salvaspazio/
Disallow: /collections/Autocuiseurs/maga/autocuiseur-maga.htm
Disallow: /index.html.htm
Disallow: /collections/Les-couverts/Ellix/ellix.htm
Disallow: /philosophie/test+lien+home+philo.htm
Disallow: /collections/Articles-culinaires-fixes/Novia/Novia.htm
Disallow: /collections/Les-couverts/Cube/couverts-cube.htm
Disallow: /collections/Articles-culinaires-fixes/Pandora/sauteuse-pandora.htm
Disallow: /collections/Articles-culinaires-fixes/Pandora/poele-pandora.htm
Disallow: /collections/Articles-culinaires-fixes/venere/sauteuse-venere.htm
Disallow: /collections/Articles-culinaires-fixes/venere/marmite-venere.htm
Disallow: /collections/Articles-culinaires-fixes/venere/cuit-vapeur.htm
Disallow: /collections/Articles-culinaires-fixes/venere/casserole-venere.htm
Disallow: /collections/Articles-culinaires-fixes/novia/sauteuse-novia.htm
Disallow: /collections/Articles-culinaires-fixes/venere/poele-venere.htm
Disallow: /collections/Articles-culinaires-fixes/venere/faitout-venere.htm
Disallow: /collections/Articles-culinaires-fixes/Pandora/cuit-pates.htm
Disallow: /collections/Articles-culinaires-fixes/novia/poele-novia.htm
Disallow: /collections/Articles-culinaires-fixes/venere/saucier-venere.htm
Disallow: /collections/Articles-culinaires-fixes/Pandora/faitout-pandora.htm
Disallow: /collections/Articles-culinaires-fixes/novia/casserole-novia.htm
Disallow: /collections/Articles-de-table/Cube/set-antipasti.htm
Disallow: /collections/Articles-de-table/Cube/plat-cube.htm
Disallow: /collections/Articles-de-table/Ellix/huilier-ellix.htm
Disallow: /collections/Articles-de-table/Cube/plateau-cube.htm
Disallow: /collections/Articles-de-table/Cube/bocal-cube.htm
Disallow: /collections/Articles-culinaires-fixes/Collezione-Rossa/faitout-rouge.htm
Disallow: /collections/Articles-culinaires-fixes/Inox-Meteorite/casserole-rev%C3%AAtue.htm
Disallow: /collections/Articles-culinaires-fixes/Inox-Meteorite/casserole-rev%C3%AAtue.htm
Disallow: /collections/Articles-culinaires-fixes/Pandora/cuit-vapeur-pandora.htm
Disallow: /collections/Articles-culinaires-fixes/gran-ghisa/marmite-ovale.htm
Disallow: /collections/Articles-culinaires-fixes/novia/faitout-inox-novia.htm
Disallow: /collections/Articles-culinaires-fixes/Inox-Meteorite/sauteuse-meteorite.htm
Disallow: /collections/Articles-culinaires-fixes/novia/cuit-vapeur-novia.htm
Disallow: /collections/Articles-de-table/Cube/panier-a-pain.htm
Disallow: /collections/Articles-culinaires-fixes/Inox-Meteorite/poele-revetue.htm
Disallow: /collections/Articles-culinaires-fixes/Collezione-Rossa/marmite-rossa.htm
Disallow: /collections/Articles-culinaires-fixes/novia/panier-pastaiola-novia.htm
Disallow: /collections/Articles-culinaires-fixes/Collezione-Rossa/casserole-rossa.htm
Disallow: /collections/Articles-culinaires-fixes/gran-ghisa/marmite-carree.htm
Disallow: /collections/Articles-culinaires-fixes/Collezione-Rossa/set-cuiseur-pates.htm
Disallow: /collections/Articles-culinaires-amovibles/Collezione-Rossa/poele-rossa-amovible.htm
Disallow: /collections/Articles-culinaires-amovibles/Collezione-Rossa/casserole-manche-amovible.htm
Disallow: /Template/Philosophy/Spirit/Spirit.aspx?NRMODE=Published&NRNODEGUID=%7B543F89F8-0B14-4671-9B73-C9260AF6F8F3%7D&NRORIGINALURL=%2Fphilosophie%2FHistoire%2F&NRCACHEHINT=NoModifyGuest
Disallow: /*WSRetailer.asmx$
Disallow: /*PrintProduct09.aspx$
Disallow: /collections/Articles-culinaires-amovibles/Collezione-Rossa/sauteuse-manche-amovible.htm
Disallow: /collections/Articles-culinaires-fixes/Collezione-Rossa/sauteuse-rossa.htm
Disallow: /collections/Articles-culinaires-amovibles/salvaspazio/Every-lid09.htm
Disallow: /collections/Articles-culinaires-fixes/Pandora/sauteuse-anses-pandora.htm
Disallow: /collections/Articles-culinaires-fixes/novia/cuit-vapeur-novia.htm
Disallow: /collections/Articles-culinaires-fixes/Pandora/Casseruola+fonda+a+manico+lungo+con+coperchio+a+parte09.htm
Disallow: /Template/philosophy/xml/FR-savoir-faire.xml$
Disallow: /NR/rdonlyres/DEE2B1AF-CD1D-4D2A-A183-2C8AFCA90287/0/Lescoursdecuisine.pdf$
Disallow: /NR/rdonlyres/9E5F068A-71E6-4DE9-AA5F-F7222B3D4F67/0/BULLETINLAGOSTINA.pdf$
Disallow: /Template/Philosophy/Spirit/Spirit.aspx?NRMODE=Published&NRNODEGUID=%7B543F89F8-0B14-4671-9B73-C9260AF6F8F3%7D&NRORIGINALURL=%2Fphilosophie%2FHistoire%2F&NRCACHEHINT=NoModifyGuest$
Disallow: /service/services.htm$

