# robots txt for bitiba
# created 22.06.2016
#
User-agent: *
Disallow: /ask?*
Disallow: /checkout/
Disallow: /myzooplus/
Disallow: /pictureupload*
Disallow: /stockreminder
Disallow: /web/
Disallow: /feedback/form/
Disallow: /petofday*
Disallow: */topten$
Disallow: /customerpicturedisplay/
Disallow: /feedback/0/1/
Disallow: /feedback/1/0/
Disallow: /feedback/1/1/
Disallow: /*page
Disallow: /affiliate/
Disallow: /passwordreminder*
Disallow: /?petId*
Disallow: /account*
Disallow: /askdetail?*
Disallow: /ov?
Disallow: /bewertung
Disallow: /m/
Disallow: /mobile/

User-agent: bingbot
Disallow: /ask?*
Disallow: /checkout/
Disallow: /myzooplus/
Disallow: /pictureupload*
Disallow: /stockreminder
Disallow: /web/
Disallow: /feedback/form/
Disallow: /petofday*
Disallow: */topten$
Disallow: /customerpicturedisplay/
Disallow: /feedback/0/1/
Disallow: /feedback/1/0/
Disallow: /feedback/1/1/
Disallow: /*page
Disallow: /affiliate/
Disallow: /passwordreminder*
Disallow: /?petId*
Disallow: /account*
Disallow: /askdetail?*
Disallow: /ov?
Disallow: /bewertung
Disallow: /m/
Disallow: /mobile/
Crawl-delay: 5

User-agent: msnbot
Disallow: /ask?*
Disallow: /checkout/
Disallow: /myzooplus/
Disallow: /pictureupload*
Disallow: /stockreminder
Disallow: /web/
Disallow: /feedback/form/
Disallow: /petofday*
Disallow: */topten$
Disallow: /customerpicturedisplay/
Disallow: /feedback/0/1/
Disallow: /feedback/1/0/
Disallow: /feedback/1/1/
Disallow: /*page
Disallow: /affiliate/
Disallow: /passwordreminder*
Disallow: /?petId*
Disallow: /account*
Disallow: /askdetail?*
Disallow: /ov?
Disallow: /bewertung
Disallow: /m/
Disallow: /mobile/
Crawl-delay: 5

User-agent: msnbot-media
Disallow: /ask?*
Disallow: /checkout/
Disallow: /myzooplus/
Disallow: /pictureupload*
Disallow: /stockreminder
Disallow: /web/
Disallow: /feedback/form/
Disallow: /petofday*
Disallow: */topten$
Disallow: /customerpicturedisplay/
Disallow: /feedback/0/1/
Disallow: /feedback/1/0/
Disallow: /feedback/1/1/
Disallow: /*page
Disallow: /affiliate/
Disallow: /passwordreminder*
Disallow: /?petId*
Disallow: /account*
Disallow: /askdetail?*
Disallow: /ov?
Disallow: /bewertung
Disallow: /m/
Disallow: /mobile/
Crawl-delay: 5
