User-agent: *
Disallow: /imprezy/action~posterboard/
Disallow: /imprezy/action~agenda/
Disallow: /imprezy/action~oneday/
Disallow: /imprezy/action~month/
Disallow: /imprezy/action~week/
Disallow: /imprezy/action~stream/
Disallow: /calendar/action~posterboard/
Disallow: /calendar/action~agenda/
Disallow: /calendar/action~oneday/
Disallow: /calendar/action~month/
Disallow: /calendar/action~week/
Disallow: /calendar/action~stream/
Disallow: /calendar/action~undefined/
Disallow: /calendar/action~http:/
Disallow: /calendar/action~default/
Disallow: /calendar/action~poster/
Disallow: /calendar/action~*/
Disallow: /*controller=ai1ec_exporter_controller*
Disallow: /*/action~*/
Disallow: /calendar-2/action~posterboard/
Disallow: /calendar-2/action~agenda/
Disallow: /calendar-2/action~oneday/
Disallow: /calendar-2/action~month/
Disallow: /calendar-2/action~week/
Disallow: /calendar-2/action~stream/
Disallow: /calendar-2/action~undefined/
Disallow: /calendar-2/action~http:/
Disallow: /calendar-2/action~default/
Disallow: /calendar-2/action~poster/
Disallow: /calendar-2/action~*/
Disallow: /wydarzenia/action~posterboard/
Disallow: /wydarzenia/action~agenda/
Disallow: /wydarzenia/action~oneday/
Disallow: /wydarzenia/action~month/
Disallow: /wydarzenia/action~week/
Disallow: /wydarzenia/action~stream/
Disallow: /wydarzenia/action~undefined/
Disallow: /wydarzenia/action~http:/
Disallow: /wydarzenia/action~default/
Disallow: /wydarzenia/action~poster/
Disallow: /wydarzenia/action~*/
