User-agent: *
Disallow: /projekt1/
Disallow: /projekt2/
Disallow: /projekt3/
Disallow: /projekt4/
Disallow: /projekt5/
Disallow: /projekt6/
Disallow: /projekt7/
Disallow: /projekt8/
Disallow: /projekt9/
Disallow: /projekt10/
Disallow: /projekt11/
Disallow: /projekt12/
Disallow: /projekt13/
Disallow: /projekt14/
Disallow: /projekt15/
Disallow: /projekt16/
Disallow: /projekt17/
Disallow: /projekt18/
Disallow: /projekt19/
Disallow: /projekt20/
