User-agent: *
Disallow: /wp-admin/
Disallow: /wp-includes/
Disallow: /calendar/action~posterboard/
Disallow: /calendar/action~agenda/
Disallow: /calendar/action~oneday/
Disallow: /calendar/action~month/
Disallow: /calendar/action~week/
Disallow: /calendar/action~stream/
Disallow: /kalendarz-imprez/action~posterboard/
Disallow: /kalendarz-imprez/action~agenda/
Disallow: /kalendarz-imprez/action~oneday/
Disallow: /kalendarz-imprez/action~month/
Disallow: /kalendarz-imprez/action~week/
Disallow: /kalendarz-imprez/action~stream/
