User-agent: *
Disallow: /admin
Disallow: /cache
Disallow: /download
Disallow: /includes
Disallow: /temp
Disallow: /tmp
Disallow: /install
Disallow: /system
Disallow: /catalog
Disallow: /account.php
Disallow: /checkout_shipping.php
Disallow: /checkout_payment.php
Disallow: /checkout_process.php
Disallow: /contact_us.php
Disallow: /cookie_usage.php
Disallow: /create_account.php
Disallow: /login.php
Disallow: /password_forgotten.php
Disallow: /popup_image.php
Disallow: /shopping_cart.php
Disallow: /patch.php
Disallow: /product_reviews_write.php
Disallow: /account.html
Disallow: /advanced_search.html
Disallow: /checkout_shipping.html
Disallow: /checkout_payment.html
Disallow: /checkout_shipping.html
Disallow: /checkout_process.html
Disallow: /contact_us.html
Disallow: /cookie_usage.html
Disallow: /create_account.html
Disallow: /login.html
Disallow: /password_forgotten.html
Disallow: /popup_image.html
Disallow: /shopping_cart.html
Disallow: /product_reviews_write.html
Disallow: /information.php?info_id=3
Disallow: /information.php?info_id=4
Disallow: /regulamin
Disallow: /wysylka-i-zwroty
Disallow: /*&sort=*
Disallow: /*&route=*
Disallow: /*.html?sort=*&dostepnosc=*
Disallow: /gry-uzywane*.html?page=*&sort=*
Disallow: /gry-uzywane*.html?sort=*&dostepnosc=*
Disallow: /index.php?route=product/search&search=*
Disallow: /index.php?route=account/login
Disallow: /index.php?route=account/register
Disallow: /index.php?route=checkout/cart
