User-agent: *
Allow: */modules/*.css
Allow: */modules/*.js
Disallow: /*?orderby=
Disallow: /*?orderway=
Disallow: /*?tag=
Disallow: /*?id_currency=
Disallow: /*?search_query=
Disallow: /*?back=
Disallow: /*?n=
Disallow: /*&orderby=
Disallow: /*&orderway=
Disallow: /*&tag=
Disallow: /*&id_currency=
Disallow: /*&search_query=
Disallow: /*&back=
Disallow: /*&n=
Disallow: /*controller=addresses
Disallow: /*controller=address
Disallow: /*controller=authentication
Disallow: /*controller=cart
Disallow: /*controller=discount
Disallow: /*controller=footer
Disallow: /*controller=get-file
Disallow: /*controller=header
Disallow: /*controller=history
Disallow: /*controller=identity
Disallow: /*controller=images.inc
Disallow: /*controller=init
Disallow: /*controller=my-account
Disallow: /*controller=order
Disallow: /*controller=order-opc
Disallow: /*controller=order-slip
Disallow: /*controller=order-detail
Disallow: /*controller=order-follow
Disallow: /*controller=order-return
Disallow: /*controller=order-confirmation
Disallow: /*controller=pagination
Disallow: /*controller=password
Disallow: /*controller=pdf-invoice
Disallow: /*controller=pdf-order-return
Disallow: /*controller=pdf-order-slip
Disallow: /*controller=product-sort
Disallow: /*controller=search
Disallow: /*controller=statistics
Disallow: /*controller=attachment
Disallow: /*controller=guest-tracking
Disallow: */classes/
Disallow: */config/
Disallow: */download/
Disallow: */mails/
Disallow: */modules/
Disallow: */translations/
Disallow: */tools/
Disallow: /*pl/odzyskiwanie-hasla
Disallow: /*pl/adres
Disallow: /*pl/adresy
Disallow: /*pl/logowanie
Disallow: /*pl/koszyk
Disallow: /*pl/rabaty
Disallow: /*pl/historia-zamowien
Disallow: /*pl/dane-osobiste
Disallow: /*pl/moje-konto
Disallow: /*pl/sledzenie-zamowienia
Disallow: /*pl/pokwitowania
Disallow: /*pl/zamowienie
Disallow: /*pl/szukaj
Disallow: /*pl/szybkie-zakupy
Disallow: /*pl/sledzenie-zamowienia-gosc
Disallow: /*pl/potwierdzenie-zamowienia
Disallow: /*en/odzyskiwanie-hasla
Disallow: /*en/adres
Disallow: /*en/adresy
Disallow: /*en/logowanie
Disallow: /*en/koszyk
Disallow: /*en/rabaty
Disallow: /*en/historia-zamowien
Disallow: /*en/dane-osobiste
Disallow: /*en/moje-konto
Disallow: /*en/sledzenie-zamowienia
Disallow: /*en/pokwitowania
Disallow: /*en/zamowienie
Disallow: /*en/szukaj
Disallow: /*en/szybkie-zakupy
Disallow: /*en/sledzenie-zamowienia-gosc
Disallow: /*en/potwierdzenie-zamowienia

Sitemap: https://www.bikers-shop.pl/1_index_sitemap.xml

