User-agent:*
Disallow:/_js/
Disallow:/_css/
Disallow:/_images/
Disallow:/nbproject/
Disallow:/fancybox/
Disallow:/tipuesearch/
Disallow:/en/
Disallow:/pl/Galeria/
Disallow:/pl/Kontakt/
Disallow:/pl/Oferta/
Disallow:/pl/PRODUKTY/
Disallow:/pl/PrzygotowanieDoDruku/
Disallow:/pl/StrefaKlienta/
Disallow:/pl/StronaStartowa/
Disallow:/pl/_js_cookies/
Disallow:/pl/home/
Disallow:/de/_js/
Disallow:/pl/check.php
Disallow:/pl/check_ftp.php
Disallow:logoDA.ico
