User-agent: *
Disallow: /admin/
Disallow: /actions/
Disallow: /libs/
Disallow: /img/
Disallow: /css/
Disallow: /media/
Disallow: /tmp/
Disallow: /js/
Disallow: /flash/
Disallow: /swf/
Disallow: /templates/
Disallow: /templates_c/
Disallow: /_newsletter/
Disallow: /_galeria/
Disallow: /pdf/
Disallow: /allegro/
Disallow: /cache/
Disallow: /_boxes/
Disallow: /_breadcrumbs/
Disallow: /_buttons/
Disallow: /_calendar/
Disallow: /_citations/
Disallow: /_common/
Disallow: /_files/
Disallow: /_galeria/
Disallow: /_items/
Disallow: /_kontakt/
Disallow: /_langs/
Disallow: /_menu/
Disallow: /_newsletter/
Disallow: /_products/
Disallow: /_recomendsite/
Disallow: /_tmp/
Disallow: /_news/
Disallow: /_forms/
