# robots.txt automaticaly generated by PrestaShop e-commerce open-source solution
# http://www.prestashop.com - http://www.prestashop.com/forums
# This file is to prevent the crawling and indexing of certain parts
# of your site by web crawlers and spiders run by sites like Yahoo!
# and Google. By telling these "robots" where not to go on your site,
# you save bandwidth and server resources.
# For more information about the robots.txt standard, see:
# http://www.robotstxt.org/robotstxt.html
User-agent: *
# Allow Directives
Allow: */modules/*.css
Allow: */modules/*.js
# Private pages
Disallow: /*?orderby=
Disallow: /*?orderway=
Disallow: /*?tag=
Disallow: /*?id_currency=
Disallow: /*?search_query=
Disallow: /*?back=
Disallow: /*?n=
Disallow: /*&orderby=
Disallow: /*&orderway=
Disallow: /*&tag=
Disallow: /*&id_currency=
Disallow: /*&search_query=
Disallow: /*&back=
Disallow: /*&n=
Disallow: /*controller=addresses
Disallow: /*controller=address
Disallow: /*controller=authentication
Disallow: /*controller=cart
Disallow: /*controller=discount
Disallow: /*controller=footer
Disallow: /*controller=get-file
Disallow: /*controller=header
Disallow: /*controller=history
Disallow: /*controller=identity
Disallow: /*controller=images.inc
Disallow: /*controller=init
Disallow: /*controller=my-account
Disallow: /*controller=order
Disallow: /*controller=order-opc
Disallow: /*controller=order-slip
Disallow: /*controller=order-detail
Disallow: /*controller=order-follow
Disallow: /*controller=order-return
Disallow: /*controller=order-confirmation
Disallow: /*controller=pagination
Disallow: /*controller=password
Disallow: /*controller=pdf-invoice
Disallow: /*controller=pdf-order-return
Disallow: /*controller=pdf-order-slip
Disallow: /*controller=product-sort
Disallow: /*controller=search
Disallow: /*controller=statistics
Disallow: /*controller=attachment
Disallow: /*controller=guest-tracking
# Directories
Disallow: */classes/
Disallow: */config/
Disallow: */download/
Disallow: */mails/
Disallow: */translations/
Disallow: */tools/
# Files
Disallow: /*odzyskiwanie-hasla
Disallow: /*adres
Disallow: /*adresy
Disallow: /*logowanie
Disallow: /*koszyk
Disallow: /*rabaty
Disallow: /*historia-zamowien
Disallow: /*dane-osobiste
Disallow: /*moje-konto
Disallow: /*sledzenie-zamowienia
Disallow: /*pokwitowania
Disallow: /*zamowienie
Disallow: /*szukaj
Disallow: /*szybkie-zakupy
Disallow: /*sledzenie-zamowienia-gosc
Disallow: /*potwierdzenie-zamowienia
Disallow: /?fc=

Disallow: /content/3-terms-and-conditions-of-use
Disallow: /content/8-polityka-prywatnosci
Disallow: /firanki-dla-dzieci-disney/266-firana-kubus-wzor-da07
Disallow: /gipiury/817-gipiura-nr-7099501
Disallow: /img/cms/d29d7c3f47cfb0a1176616d73fa6.jpg
Disallow: /img/cms/m2-100-P200-20%201,2.jpg
Disallow: /img/cms/m2-25M200-0-1%201,2.jpg
Disallow: /img/cms/m2-25M200-2F-1%201,21.jpg
Disallow: /img/cms/m2-25P200-0-1%201,2.jpg
Disallow: /img/cms/m2-25P250-S-1%201,25.jpg
Disallow: /img/cms/m2-50-P270-2C%201,27.jpg
Disallow: /img/cms/m2-50P200-0-1%201,2.jpg
Disallow: /img/cms/m2-50P200-2F-1%201,21.jpg
Disallow: /img/cms/m2-50P250-2F-1%201,25.jpg
Disallow: /img/cms/m2-50P250-s-1%201,25.jpg
Disallow: /img/cms/m2-50P300-2F-1%201,3.jpg
Disallow: /index.php?controller=404
Disallow: /index.php?id_product=265&controller=product
Disallow: /index.php?id_product=21&controller=product
Disallow: /zazdrostki-dziane/138-zazdrostka-nr-3600
Disallow: /proste/71-firana-nr-3090
Disallow: /img/cms/m2-50P200-s-1%201,2.jpg
Disallow: /5545/piekne-matowe-gotowe-zaslony-155-x-250-cm-na-wymiar.jpg
Disallow: /5545-small_default/piekne-matowe-gotowe-zaslony-155-x-250-cm-na-wymiar.jpg
Disallow: /5546-small_default/piekne-matowe-gotowe-zaslony-155-x-250-cm-na-wymiar.jpg
Disallow: /5546/piekne-matowe-gotowe-zaslony-155-x-250-cm-na-wymiar.jpg

Sitemap: https://sklep.polontex.com.pl/gsitemap.php

