User-agent: *
Disallow: /redirect.php
Disallow: /przekieruj.php
Disallow: /baner.php
Allow: /
User-Agent: AhrefsBot
Disallow: /mobile
User-agent: rogerbot
Disallow: /mobile
User-agent: MJ12bot
Disallow: /mobile
