User-Agent: *
Sitemap: https://www.surebety.pl/sitemap.txt
Disallow: /application/cache/
Disallow: /application/views_c/
Disallow: /cgi-bin/
Disallow: /chart/*
Disallow: /dictionary/
Disallow: /logs/
Disallow: /zdjecia/
Disallow: /index.php/pages/bet_comment/
Disallow: /porownywarka-kursow/

Allow: /typerzy/ahten$
Allow: /typerzy/georgisd$
Allow: /typerzy/guaranga$
Allow: /typerzy/gostek365$
Allow: /typerzy/HAdrenaline$
Allow: /typerzy/Ingelberg$
Allow: /typerzy/inne2000$
Allow: /typerzy/Janas132$
Allow: /typerzy/juras791$
Allow: /typerzy/karse$
Allow: /typerzy/Kreatywnie$
Allow: /typerzy/kwoy$
Allow: /typerzy/lelek$
Allow: /typerzy/liquidfish$
Allow: /typerzy/Liorente$
Allow: /typerzy/Lucand$
Allow: /typerzy/Messinho$
Allow: /typerzy/noname007x$
Allow: /typerzy/ObserwatorM$
Allow: /typerzy/Parnasus$
Allow: /typerzy/Poozon$
Allow: /typerzy/sandacz$
Allow: /typerzy/sebaprosto$
Allow: /typerzy/sejjid$
Allow: /typerzy/waldek93$
Allow: /typerzy/Zajcev$
Disallow: /typerzy/
