User-agent: *
Disallow: /css/
Disallow: /gazetki/
Disallow: /images/
Disallow: /inc/
Disallow: /javascript/
Disallow: /js/
Disallow: /orbitvu12/
Disallow: /phpmailer/
Disallow: /lang_de/
Disallow: /lang_en/
Disallow: /lang_fr/
Disallow: /lang_ru/
Disallow: /strefaokazji/

Disallow: /cart.php
Disallow: /order.php
Disallow: /order_confirm.php
Disallow: /analyticstracking.php
Disallow: /email.php
Disallow: /email_kod.php
Disallow: /emails.php
Disallow: /emails_kod.php
Disallow: /facebook.php
Disallow: /footer.php
Disallow: /form.php
Disallow: /form_sugestia.php
Disallow: /google7535b75d5abe7399.html
Disallow: /header.php
Disallow: /image.php
Disallow: /info_popup.php
Disallow: /jquery.cssmap.js
Disallow: /marquee.php
Disallow: /new_category.php
Disallow: /polaczenie.php
Disallow: /polaczenie_ns.php
Disallow: /popup_header.php
Disallow: /powiazane.php
Disallow: /produkt_crm.php
Disallow: /produkt_karta.php
Disallow: /produkt_karta_barkiszklane.php
Disallow: /produkt_karta_foteleobr.php
Disallow: /produkt_karta_hokery.php
Disallow: /produkt_karta_hover.php
Disallow: /produkt_karta_komody.php
Disallow: /produkt_karta_krzesla.php
Disallow: /produkt_karta_lampy.php
Disallow: /produkt_karta_lampy1.php
Disallow: /produkt_karta_lawy.php
Disallow: /produkt_karta_lozka.php
Disallow: /produkt_karta_materac.php
Disallow: /produkt_karta_parawan.php
Disallow: /produkt_karta_pufa.php
Disallow: /produkt_karta_stoly.php
Disallow: /produkt_karta_stoly_hover.php
Disallow: /produkt_karta_stolybarowe.php
Disallow: /produkt_karta_wieszak1.php
Disallow: /produkt_karta_wieszak2.php
Disallow: /produkt_karta_ww.php
Disallow: /produkt_karta_ww_hover.php
Disallow: /produkt_karta_ww_okr.php
Disallow: /produkt_karta_ww_okr_hover.php
Disallow: /produkt_karta_wwlozka.php
Disallow: /produkt_karta_wwlozka_hover.php
Disallow: /produkt_sugestia.php
Disallow: /punkty_odbioru_woj.php
Disallow: /punkty_odbioru_woj_list_filtr.php
Disallow: /punkty_odbioru_woj_list_filtr_nie.php
Disallow: /punkty_odbioru_woj_list_filtr_tak.php
Disallow: /salony_meblowe_woj.php
Disallow: /salony_meblowe_woj_list_filtr.php
Disallow: /salony_meblowe_woj_list_filtr_nie.php
Disallow: /salony_meblowe_woj_list_filtr_tak.php
Disallow: /salony_partnerskie_woj.php
Disallow: /search.php
Disallow: /sitemap.xml
Disallow: /topmenu.php
Disallow: /writeShoppingCart.php
Disallow: /zam_potwierdzenie.php
Disallow: /zam_potwierdzenie_email.php
Disallow: /zam_rezygnacja.php
Disallow: /zam_rezygnacja_email.php
Disallow: /znaleziono.php
