User-agent: *
Disallow: /administrator/
Disallow: /bin/
Disallow: /cache/
Disallow: /cli/
Disallow: /components/
Disallow: /component/banners/
Disallow: /includes/
Disallow: /installation/
Disallow: /language/
Disallow: /layouts/
Disallow: /libraries/
Disallow: /logs/
Disallow: /modules/
Disallow: /plugins/
Disallow: /tmp/
Disallow: /1/
Disallow: /38-z/
Disallow: /35-z/
Disallow: /25-z/
Disallow: /15-z/
Disallow: /20-z/

User-agent: MJ12bot
Disallow: /
User-agent: AhrefsBot
Disallow: /
User-agent: Dotbot
Disallow: /
User-agent: AlphaBot
Disallow: /
User-agent: SemrushBot
Disallow: /
User-agent: seoscanners.net
Disallow: /
User-agent: SentiBot
Disallow: /
User-agent: MegaIndex
Disallow: /
User-agent: YandexBot
Disallow: /
User-agent: spbot
Disallow: /
User-agent: Mail
Disallow: /
User-agent: Proximic
Disallow: /
User-agent: Bingbot
Disallow: /
User-agent: Obot
Disallow: /
User-agent: SEOkicks-Robot
Disallow: /
User-agent: grapeshot
Disallow: /
User-agent: SeznamBot
Disallow: /
User-agent: Slurp
Disallow: /
