User-agent: *
Disallow: /admin/
Disallow: /onepage
Disallow: /checkout/cart
Disallow: /pts/payment
Disallow: /customer/address
Disallow: /customer/account/edit
Disallow: /sales/order/history
Disallow: /404/
Disallow: /app/
Disallow: /cgi-bin/
Disallow: /downloader/
Disallow: /includes/
Disallow: /js/
Disallow: /lib/
Disallow: /pkginfo/
Disallow: /report/
Disallow: /skin/
Disallow: /stats/
Disallow: /var/
Disallow: /index.php/
Disallow: /catalog/product_compare/
Disallow: /catalog/category/view/
Disallow: /catalog/product/view/
Disallow: /catalogsearch/
Disallow: /checkout/
Disallow: /control/
Disallow: /contacts/
Disallow: /customer/
Disallow: /customize/
Disallow: /newsletter/
Disallow: /poll/
Disallow: /review/
Disallow: /sendfriend/
Disallow: /tag/
Disallow: /wishlist/
Disallow: /*cart*
Disallow: /login*
Disallow: /*member*
Disallow: /*account*
Disallow: /cron.php
Disallow: /cron.sh
Disallow: /error_log
Disallow: /install.php
Disallow: /LICENSE.html
Disallow: /LICENSE.txt
Disallow: /LICENSE_AFL.txt
Disallow: /STATUS.txt
Disallow: /*.js$
Disallow: /*.css$
Disallow: /*.php$
Disallow: /*?p=*&
Disallow: /*?SID=

# Sitemap files
Sitemap: https://www.hihonor.com/sitemap-ar-AE.xml
Sitemap: https://www.hihonor.com/sitemap-ar-EG.xml
Sitemap: https://www.hihonor.com/sitemap-ar-mea.xml
Sitemap: https://www.hihonor.com/sitemap-ar-SA.xml
Sitemap: https://www.hihonor.com/sitemap-en-SA.xml
Sitemap: https://www.hihonor.com/sitemap-en-AE.xml
Sitemap: https://www.hihonor.com/sitemap-bg-BG.xml
Sitemap: https://www.hihonor.com/sitemap-cs-CZ.xml
Sitemap: https://www.hihonor.com/sitemap-de-DE.xml
Sitemap: https://www.hihonor.com/sitemap-el-GR.xml
Sitemap: https://www.hihonor.com/sitemap-en-AU.xml
Sitemap: https://www.hihonor.com/sitemap-en-BD.xml
Sitemap: https://www.hihonor.com/sitemap-en-CA.xml
Sitemap: https://www.hihonor.com/sitemap-en-GB.xml
Sitemap: https://www.hihonor.com/sitemap-en-IN.xml
Sitemap: https://www.hihonor.com/sitemap-en-MENA.xml
Sitemap: https://www.hihonor.com/sitemap-en-MY.xml
Sitemap: https://www.hihonor.com/sitemap-en-PH.xml
Sitemap: https://www.hihonor.com/sitemap-en-SG.xml
Sitemap: https://www.hihonor.com/sitemap-en-US.xml
Sitemap: https://www.hihonor.com/sitemap-en-ZA.xml
Sitemap: https://www.hihonor.com/sitemap-es-CO.xml
Sitemap: https://www.hihonor.com/sitemap-es-ES.xml
Sitemap: https://www.hihonor.com/sitemap-es-MX.xml
Sitemap: https://www.hihonor.com/sitemap-fa.xml
Sitemap: https://www.hihonor.com/sitemap-fi-FI.xml
Sitemap: https://www.hihonor.com/sitemap-fr-FR.xml
Sitemap: https://www.hihonor.com/sitemap-global.xml
Sitemap: https://www.hihonor.com/sitemap-hu-HU.xml
Sitemap: https://www.hihonor.com/sitemap-id-ID.xml
Sitemap: https://www.hihonor.com/sitemap-it-IT.xml
Sitemap: https://www.hihonor.com/sitemap-my-MM.xml
Sitemap: https://www.hihonor.com/sitemap-nl-NL.xml
Sitemap: https://www.hihonor.com/sitemap-no-NO.xml
Sitemap: https://www.hihonor.com/sitemap-pl-PL.xml
Sitemap: https://www.hihonor.com/sitemap-ru-BY.xml
Sitemap: https://www.hihonor.com/sitemap-sr-RS.xml
Sitemap: https://www.hihonor.com/sitemap-sv-SE.xml
Sitemap: https://www.hihonor.com/sitemap-th-TH.xml
Sitemap: https://www.hihonor.com/sitemap-tr-TR.xml
Sitemap: https://www.hihonor.com/sitemap-vi-VN.xml
