User-agent: *
Disallow: /admin/
Disallow: /allegro/
Disallow: /bmz_cache/
Disallow: /cache/
Disallow: /docs/
Disallow: /download/
Disallow: /editors/
Disallow: /email/
Disallow: /extras/
Disallow: /fonts/
Disallow: /img/
Disallow: /lib/
Disallow: /logs/
Disallow: /test/
Disallow: /links/
Disallow: /*sort=
Disallow: /*m=
Disallow: /*vs=
Disallow: /*pp=
Disallow: /*guid=
Disallow: /*zenid=
Disallow: /*?multimedia
Disallow: /*zc=
Disallow: /*w=
Disallow: /*src=
Disallow: /*utm_source=
Disallow: /*utm_medium=
Disallow: /*utm_content=
Disallow: /*utm_campaign=
Disallow: /*zeus=
Disallow: /*id=
Disallow: /Regulamin,a,1.html
Disallow: /Regulamin,a,1.html#warranty
Disallow: /Regulamin,a,1.html#complains
Disallow: /Regulamin,a,1.html#returns
Disallow: /downloadFiles/formularz_reklamacyjny.pdf
Disallow: /Polityka_prywatnosci,a,2.html
Disallow: /mapastrony


User-agent: Googlebot
Disallow: /admin/
Disallow: /allegro/
Disallow: /bmz_cache/
Disallow: /cache/
Disallow: /docs/
Disallow: /download/
Disallow: /editors/
Disallow: /email/
Disallow: /extras/
Disallow: /fonts/
Disallow: /img/
Disallow: /lib/
Disallow: /logs/
Disallow: /test/
Disallow: /links/
Disallow: /*sort=
Disallow: /*m=
Disallow: /*vs=
Disallow: /*pp=
Disallow: /*guid=
Disallow: /*zenid=
Disallow: /*?multimedia
Disallow: /*zc=
Disallow: /*w=
Disallow: /*src=
Disallow: /*utm_source=
Disallow: /*utm_medium=
Disallow: /*utm_content=
Disallow: /*utm_campaign=
Disallow: /*autobuy=*
Disallow: /*.html&*
Disallow: /*zeus=
Disallow: /*id=

user-agent: AhrefsBot
disallow: /

Sitemap: https://www.gimmik.net/tmp/sitemap.xml

