User-Agent: *
Disallow: /templates
Host: www.ofit-travel.com.ua

Sitemap: https://www.ofit-travel.com.ua/ru/uploads/sitemap.xml
Sitemap: https://www.ofit-travel.com.ua/sitemap-list.xml
Sitemap: https://www.ofit-travel.com.ua/de/uploads/sitemap.xml
Sitemap: https://www.ofit-travel.com.ua/en/uploads/sitemap.xml
Sitemap: https://www.ofit-travel.com.ua/pl/uploads/sitemap.xml
Sitemap: https://www.ofit-travel.com.ua/fr/uploads/sitemap.xml
Sitemap: https://www.ofit-travel.com.ua/ua/uploads/sitemap.xml


