Sitemap: http://www.forumsubiekta.pl/sitemap.xml
User-agent: *
Disallow: /Sources/
Disallow: /Smileys/
Disallow: /Packages/
Disallow: /avatars/
Disallow: /attachments/
Disallow: /Themes/
Disallow: index.php?action=admin*
Disallow: /index.php?action=printpage*
Disallow: /index.php?action=post*
Disallow: /index.php?action=permissions*
Disallow: /index.php?action=pm*
Disallow: /index.php?action=help*
Disallow: /index.php?action=register*
Disallow: /index.php?action=login*
Disallow: /index.php?action=mlist*
Disallow: /index.php?action=search*
Disallow: /index.php?action=who*
Disallow: /index.php?*rss*
Disallow: /index.php?action=stats*
Disallow: /index.php?PHPSESSID=
Disallow: /index.php?*wap*
Disallow: /index.php?*imode*
Disallow: /index.php?action=post*
Disallow: /index.php?action=activate*
Disallow: /index.php?action=reminder*
Disallow: /index.php?wap2*
Disallow: /index.php?action=profile
Disallow: */?action=unread
Disallow: /?prev_next=prev#
Disallow: /?prev_next=next#
