User-agent: *
Allow: /
Disallow: /wyniki-wyszukiwania/
Disallow: /pl/wyniki-wyszukiwania/
Disallow: /zglaszanie-bledu/
Disallow: /pl/zglaszanie-bledu/
Disallow: /konto/
Disallow: /pl/konto/
Disallow: /konto/potwierdzenie-rejestracji/
Disallow: /pl/konto/potwierdzenie-rejestracji/
Disallow: /konto/przypomnienie_hasla/
Disallow: /pl/konto/przypomnienie_hasla/
Disallow: /ajax/
Disallow: /pl/ajax/
Disallow: /ajax/ask4product/
Disallow: /pl/ajax/ask4product/
Disallow: /ajax/calendarmini/
Disallow: /pl/ajax/calendarmini/
Disallow: /ajax/calendarminipages/
Disallow: /pl/ajax/calendarminipages/
Disallow: /ajax/zglos-blad/
Disallow: /pl/ajax/zglos-blad/
Disallow: /ajax/wyslij-link/
Disallow: /pl/ajax/wyslij-link/
Disallow: /grupa-prawidlowa/
Disallow: /pl/grupa-prawidlowa/
Sitemap: http://www.recore.pl/sitemap.xml
