sitemap: http://zabawki-modele.pl/1_index_sitemap.xml
User-agent: ichiro
Disallow: /
User-agent:Twiceler
disallow: /
User-agent: psbot
Disallow: /
User-agent: ScoutJet
Disallow: /
User-agent: BLEXBot
Disallow: /
User-agent: Cliqzbot
Disallow: /
User-agent: DeuSu
Disallow: /
User-agent: AhrefsBot
Disallow: /
User-agent: Baiduspider
Disallow: /
User-agent: BUbiNG
Disallow: /
User-agent: Barkrowler
Disallow: /
User-agent: CCBot
Disallow: /
User-agent: SemrushBot
Disallow: /
User-agent: Wotbox
Disallow: /
User-agent: MJ12bot
Disallow: /
User-agent: SEOkicks-Robot
Disallow: /
User-agent: AlphaSeoBot
Disallow: /
User-agent: AlphaSeoBot-SA
Disallow: /
User-agent: YandexBot
Disallow: /
User-agent: YandexImages
Disallow: /
User-agent: YandexImageResizer
Disallow: /

User-agent: Google
Allow: */modules/

User-agent: *
Allow: */modules/*.css
Allow: */modules/*.js
Allow: */modules/*.png
Allow: */modules/*.gif
Allow: */modules/*.jpg
# Private pages
Disallow: /*orderby=
Disallow: /*orderway=
Disallow: /*tag=
Disallow: /*id_currency=
Disallow: /*search_query=
Disallow: /*back=
Disallow: /*n=
Disallow: /*controller=addresses
Disallow: /*controller=address
Disallow: /*controller=authentication
Disallow: /*controller=cart
Disallow: /*controller=discount
Disallow: /*controller=footer
Disallow: /*controller=get-file
Disallow: /*controller=header
Disallow: /*controller=history
Disallow: /*controller=identity
Disallow: /*controller=images.inc
Disallow: /*controller=init
Disallow: /*controller=my-account
Disallow: /*controller=order
Disallow: /*controller=order-opc
Disallow: /*controller=order-slip
Disallow: /*controller=order-detail
Disallow: /*controller=order-follow
Disallow: /*controller=order-return
Disallow: /*controller=order-confirmation
Disallow: /*controller=pagination
Disallow: /*controller=password
Disallow: /*controller=pdf-invoice
Disallow: /*controller=pdf-order-return
Disallow: /*controller=pdf-order-slip
Disallow: /*controller=product-sort
Disallow: /*controller=search
Disallow: /*controller=statistics
Disallow: /*controller=attachment
Disallow: /*controller=guest-tracking
# Directories
Disallow: */classes/
Disallow: */config/
Disallow: */download/
Disallow: */mails/
Allow: */modules/homeslider/images/
Allow: */modules/themeconfigurator/img/
Allow: */modules/santandercredit/js/santanderCredit.js
Allow: */modules/santandercredit/images/bannerBlok.jpg
Allow: */themes/default-bootstrap/css/modules/homeslider/images/bx_loader.gif
Allow: */themes/default-bootstrap/cache/*
Allow: */modules/blockstore/
Disallow: */modules/
Disallow: */translations/
Disallow: */tools/
# Files
Disallow: /*pl/odzyskiwanie-hasla
Disallow: /*pl/adres
Disallow: /*pl/adresy
Disallow: /*pl/logowanie
Disallow: /*pl/koszyk
Disallow: /*pl/rabaty
Disallow: /*pl/historia-zamowien
Disallow: /*pl/dane-osobiste
Disallow: /*pl/moje-konto
Disallow: /*pl/sledzenie-zamowienia
Disallow: /*pl/pokwitowania
Disallow: /*pl/zamowienie
Disallow: /*pl/szukaj
Disallow: /*pl/szybkie-zakupy
Disallow: /*pl/sledzenie-zamowienia-gosc
Disallow: /*pl/potwierdzenie-zamowienia
Disallow: /*en/odzyskiwanie-hasla
Disallow: /*en/adres
Disallow: /*en/adresy
Disallow: /*en/logowanie
Disallow: /*en/koszyk
Disallow: /*en/rabaty
Disallow: /*en/historia-zamowien
Disallow: /*en/dane-osobiste
Disallow: /*en/moje-konto
Disallow: /*en/sledzenie-zamowienia
Disallow: /*en/pokwitowania
Disallow: /*en/zamowienie
Disallow: /*en/szukaj
Disallow: /*en/szybkie-zakupy
Disallow: /*en/sledzenie-zamowienia-gosc
Disallow: /*en/potwierdzenie-zamowienia
Disallow: /*de/odzyskiwanie-hasla
Disallow: /*de/adres
Disallow: /*de/adresy
Disallow: /*de/logowanie
Disallow: /*de/koszyk
Disallow: /*de/rabaty
Disallow: /*de/historia-zamowien
Disallow: /*de/dane-osobiste
Disallow: /*de/moje-konto
Disallow: /*de/sledzenie-zamowienia
Disallow: /*de/pokwitowania
Disallow: /*de/zamowienie
Disallow: /*de/szukaj
Disallow: /*de/szybkie-zakupy
Disallow: /*de/sledzenie-zamowienia-gosc
Disallow: /*de/potwierdzenie-zamowienia

