User-agent: *
Disallow: /calendar/action~posterboard/
Disallow: /calendar/action~agenda/
Disallow: /calendar/action~oneday/
Disallow: /calendar/action~month/
Disallow: /calendar/action~week/
Disallow: /calendar/action~stream/
Disallow: /calendar/action~undefined/
Disallow: /calendar/action~http:/
Disallow: /calendar/action~default/
Disallow: /calendar/action~poster/
Disallow: /calendar/action~*/
Disallow: /*controller=ai1ec_exporter_controller*
Disallow: /*/action~*/
Disallow: /o-nas/o-nasaktualnosci/action~posterboard/
Disallow: /o-nas/o-nasaktualnosci/action~agenda/
Disallow: /o-nas/o-nasaktualnosci/action~oneday/
Disallow: /o-nas/o-nasaktualnosci/action~month/
Disallow: /o-nas/o-nasaktualnosci/action~week/
Disallow: /o-nas/o-nasaktualnosci/action~stream/
Disallow: /o-nas/o-nasaktualnosci/action~undefined/
Disallow: /o-nas/o-nasaktualnosci/action~http:/
Disallow: /o-nas/o-nasaktualnosci/action~default/
Disallow: /o-nas/o-nasaktualnosci/action~poster/
Disallow: /o-nas/o-nasaktualnosci/action~*/
