User-Agent: *
Allow: /
Disallow: /_admin/
Disallow: /Cart
Disallow: /Wyszukiwanie
Disallow: /Rejestracja
Disallow: /cart
Disallow: /wyszukiwanie
Disallow: /rejestracja
Disallow: /login
Disallow: /loginerror
Disallow: /szukaj*
Sitemap: https://www.roslinywodne.com/sitemap.xml
