User-agent: *
Disallow: /DE/
Disallow: /FR/
Disallow: /IT/
Disallow: /NL/
Disallow: /BE_NL/
Disallow: /BE_FR/
Disallow: /ES/
Disallow: /PT/
Disallow: /SE/
Disallow: /NO/
Disallow: /FI/
Disallow: /DK/
Disallow: /IE/
Disallow: /AT/
Disallow: /CH_FR/
Disallow: /CH_DE/
Disallow: /CH_IT/
Disallow: /CZ/
Disallow: /SK/
Disallow: /HU/
Disallow: /*bandSearch.asp?*
Disallow: /*UID=
Disallow: /*viewCart.asp*
Disallow: /*viewCart.asp$
Disallow: /*viewcart.asp*
Disallow: /*viewcart.asp$
Disallow: /_vti_cnf/
Disallow: /admin/
Disallow: /admin_translate/
Disallow: /ASPUploadComponent/
Disallow: /Automation/
Disallow: /intranet/
Disallow: /ir_logo/
Disallow: /stats/
Disallow: /stats1/
Disallow: /test/
Disallow: /upload/
Disallow: /web1/
Disallow: /web/
Disallow: /default2.asp
Disallow: /myOffer.asp
Disallow: /tmexternal/
Disallow: /tmnederland/
Disallow: /tmnordic/
Disallow: /fr//FR/fr.pdf
Disallow: /fr/copyright.asp
Disallow: /fr/privacy.asp
Disallow: /fr/returns.asp
Disallow: /fr/mentionslegales.asp
Disallow: /fr/la-politique-de-responsabilite-sociale-de-lentreeprise.asp

Sitemap: https://www.penseurope.com/at/sitemap/sitemap.xml
Sitemap: https://www.penseurope.com/de/sitemap/sitemap_blog_de.xml
Sitemap: https://www.penseurope.com/de/sitemap/sitemap_categories_de.xml
Sitemap: https://www.penseurope.com/de/sitemap/sitemap_products_de.xml
Sitemap: https://www.penseurope.com/de/sitemap/sitemap_static_de.xml
Sitemap: https://www.penseurope.com/dk/sitemap/sitemap.xml
Sitemap: https://www.penseurope.com/es/sitemap/sitemap.xml
Sitemap: https://www.penseurope.com/fi/sitemap/sitemap.xml
Sitemap: https://www.penseurope.com/fr/sitemap/sitemap_blog_fr.xml
Sitemap: https://www.penseurope.com/fr/sitemap/sitemap_categories_fr.xml
Sitemap: https://www.penseurope.com/fr/sitemap/sitemap_products_fr.xml
Sitemap: https://www.penseurope.com/fr/sitemap/sitemap_static_fr.xml
Sitemap: https://www.penseurope.com/ie/sitemap/sitemap.xml
Sitemap: https://www.penseurope.com/it/sitemap/sitemap.xml
Sitemap: https://www.penseurope.com/nl/sitemap/sitemap.xml
Sitemap: https://www.penseurope.com/no/sitemap/sitemap.xml
Sitemap: https://www.penseurope.com/se/sitemap/sitemap.xml
Sitemap: https://www.penseurope.com/sitemaps/sitemap_bed.xml
Sitemap: https://www.penseurope.com/sitemaps/sitemap_bef.xml
Sitemap: https://www.penseurope.com/sitemaps/sitemap_chd.xml
Sitemap: https://www.penseurope.com/sitemaps/sitemap_chf.xml
Sitemap: https://www.penseurope.com/sitemaps/sitemap_chi.xml
Sitemap: https://www.penseurope.com/sitemaps/sitemap_pt.xml
Sitemap: https://www.penseurope.com/cz/sitemap/sitemap.xml
Sitemap: https://www.penseurope.com/sk/sitemap/sitemap.xml
Sitemap: https://www.penseurope.com/hu/sitemap/sitemap.xml
Sitemap: https://www.pens.jp/jp/sitemap/sitemap_products_jp.xml
Sitemap: https://www.pens.jp/jp/sitemap/sitemap_categories_jp.xml
Sitemap: https://www.pens.jp/jp/sitemap/sitemap_static_jp.xml
Sitemap: https://www.pensnewzealand.com/nz/sitemap/sitemap.xml
Sitemap: https://www.pensaustralia.com/au/sitemap/sitemap.xml

