User-agent: *
Disallow: /wp-admin/profile.php
Disallow: /wp-admin/update-core.php
Disallow: /wp-admin/themes.php
Disallow: /wp-admin/
Disallow: /wp-admin/nav-menus.php
Disallow: /wp-admin/themes.php?page=custom-background
Disallow: /wp-admin/themes.php?page=custom-header
Disallow: /wp-admin/post.php?post=605&action=edit
Disallow: /wp-admin/letnie-i-zimowe-utrzymanie-ulic-i-placow.php
Disallow: /wp-admin/about.php
Disallow: /wp-admin/oczyszczanie-pomieszczen.php
Disallow: /wp-admin/galeria.php
Disallow: /wp-admin/selektywna-zbiorka-odpadow.php
Disallow: /wp-admin/uporzadkowanie-terenow.php
Disallow: /wp-admin/customize.php
Disallow: /wp-admin/o-firmie.php
Disallow: /wp-admin/odbior-padlych-zwierzat.php
Disallow: /wp-admin/pojemniki-na-odpady.php
Disallow: /wp-admin/nasza-oferta.php
Disallow: /wp-admin/odbior-odpadow-wielkogabarytowych.php
Disallow: /wp-admin/user-new.php
Disallow: /wp-admin/post-new.php
Disallow: /wp-admin/inne-uslugi.php
Disallow: /wp-admin/main/index.php
Disallow: /wp-admin/pogotowie-porzadkowe.php
Disallow: /wp-admin/kontenery-kp.php
Disallow: /wp-admin/odbior-odpadow-zabki.php
Disallow: /wp-admin/utwardzanie-drog.php
Disallow: /wp-admin/worki-big-bag.php

