User-agent: Twitterbot
User-agent: Googlebot-Image
Disallow: /check/
Disallow: /contao/
Disallow: /system/
Disallow: /templates/
Disallow: /vendor/
Disallow: /files/extensions/medien/flipbooks/
Disallow: /files/extensions/medien/documents/
Disallow: /files/extensions/events/reviews/
Disallow: /files/extensions/news/
Disallow: /share/index.php
Disallow: /build.xml
Disallow: /composer.json
Disallow: /composer.lock
Disallow: /README.md
Disallow: /maintenance/
Allow: /assets/
Allow: /system/modules/
Allow: /files/extensions/news/images/2018/


User-agent: *
Disallow: /check/
Disallow: /contao/
Disallow: /system/
Disallow: /templates/
Disallow: /files/
Disallow: /vendor/
Disallow: /share/index.php
Disallow: /build.xml
Disallow: /composer.json
Disallow: /composer.lock
Disallow: /README.md
Allow: /system/cron/cron.txt
Allow: /system/modules/*/assets/
Allow: /system/modules/*/html/
Allow: /files/extensions/news/downloads/
Allow: /files/extensions/news/images/2018/
Sitemap: https://www.ser-solutions.pl/share/sitemap_pl.xml
