User-agent: *
Disallow: /config/
Disallow: /application/
Disallow: /doc/
Disallow: /cache/
Disallow: /min/
Disallow: /serialization/
Disallow: /design/_css_panel/
Disallow: /design/_data_frontend/
Disallow: /design/_data_panel/
Disallow: /design/_images_common/
Disallow: /design/_images_installer/
Disallow: /design/_images_panel/
Disallow: /design/_js_panel/
Disallow: /design/_tpl/
Disallow: /design/_virtualproduct/
Disallow: /design/admin/
Disallow: /design/frontend/
Disallow: /informacja/15/regulamin
Disallow: /http://sklep.smary.elub.pl/informacja/15/regulamin
Disallow: http://sklep.smary.elub.pl/informacja/15/regulamin
