# robots.txt automaticaly generated by PrestaShop e-commerce open-source solution
# http://www.prestashop.com - http://www.prestashop.com/forums
# This file is to prevent the crawling and indexing of certain parts
# of your site by web crawlers and spiders run by sites like Yahoo!
# and Google. By telling these "robots" where not to go on your site,
# you save bandwidth and server resources.
# For more information about the robots.txt standard, see:
# http://www.robotstxt.org/robotstxt.html
User-agent: *
Allow: /poszewki/poszewka-na-poduszkowiec-ala-i-as-35x35cm-mix-na-zamowienie-5590.html
Allow: /poszewki/poszewka-na-poduszkowiec-ala-i-as-35x35cm-mix-na-zamowienie-5590.html
Allow: /poszewki/poszewka-na-poduszkowiec-ala-i-as-35x35cm-mix-na-zamowienie-5590.html
Allow: /*-na-zamowienie-*.html
Allow: /modules/themeeditor/fonts/Lobster-Regular.ttf

# Allow Directives
Allow: */modules/*.css
Allow: */modules/*.js
# Private pages
Disallow: /*?orderby=
Disallow: /*?orderway=
Disallow: /*?tag=
Disallow: /*?id_currency=
Disallow: /*?search_query=
Disallow: /*?back=
Disallow: /*?n=
#Disallow: /*&orderby=
#Disallow: /*&orderway=
Disallow: /*&tag=
Disallow: /*&id_currency=
#Disallow: /*&search_query=
Disallow: /*&back=
Disallow: /*&n=
Disallow: /*controller=addresses
Disallow: /*controller=address
Disallow: /*controller=authentication
Disallow: /*controller=cart
Disallow: /*controller=discount
Disallow: /*controller=footer
Disallow: /*controller=get-file
Disallow: /*controller=header
Disallow: /*controller=history
Disallow: /*controller=identity
Disallow: /*controller=images.inc
Disallow: /*controller=init
Disallow: /*controller=my-account
Disallow: /*controller=order
Disallow: /*controller=order-opc
Disallow: /*controller=order-slip
Disallow: /*controller=order-detail
Disallow: /*controller=order-follow
Disallow: /*controller=order-return
Disallow: /*controller=order-confirmation
Disallow: /*controller=pagination
Disallow: /*controller=password
Disallow: /*controller=pdf-invoice
Disallow: /*controller=pdf-order-return
Disallow: /*controller=pdf-order-slip
Disallow: /*controller=product-sort
#Disallow: /*controller=search
Disallow: /*controller=statistics
Disallow: /*controller=attachment
Disallow: /*controller=guest-tracking
# Directories
Disallow: */classes/
Disallow: */config/
Disallow: */download/
Disallow: */mails/
Disallow: */modules/
Disallow: */translations/
Disallow: */tools/
# Files
Disallow: /*odzyskiwanie-hasla
Disallow: /*adres
Disallow: /*adresy
Disallow: /*logowanie
Disallow: /*koszyk
Disallow: /*rabaty
Disallow: /*historia-zamowien
Disallow: /*dane-osobiste
Disallow: /*moje-konto
Disallow: /*sledzenie-zamowienia
Disallow: /*pokwitowania
Disallow: /*zamowienie
#Disallow: /*szukaj
Disallow: /*zakupy-realizacja
Disallow: /*sledzenie-zamowienia-gosc
Disallow: /*potwierdzenie-zamowienia

########################
#Blokady robotow #######
########################

#User-agent: SemrushBot-SA
#Disallow: /

User-agent: ezooms
Disallow: /

User-agent: proximic
Disallow: /

# Block MJ12bot as it is just noise
#User-agent: MJ12bot
#Disallow: /

# Block Ahrefs
#User-agent: AhrefsBot
#Disallow: /

# Block Sogou
User-agent: sogou spider
Disallow: /

# Block SEOkicks
User-agent: SEOkicks-Robot
Disallow: /

# Block BlexBot
User-agent: BLEXBot
Disallow: /

# Block SISTRIX
User-agent: SISTRIX Crawler
Disallow: /

# Block Uptime robot
User-agent: UptimeRobot/2.0
Disallow: /

User-agent: 008
Disallow: /

# Block Ezooms Robot
User-agent: Ezooms Robot
Disallow: /

# Block Perl LWP
User-agent: Perl LWP
Disallow: /

# Block BlexBot
User-agent: BLEXBot
Disallow: /

# Block netEstate NE Crawler (+http://www.website-datenbank.de/)
User-agent: netEstate NE Crawler
Disallow: /

# Block WiseGuys Robot
User-agent: WiseGuys Robot
Disallow: /

# Block Turnitin Robot
User-agent: Turnitin Robot
Disallow: /

User-agent: TurnitinBot
Disallow: /

User-agent: Turnitin Bot
Disallow: /

User-agent: TurnitinBot/3.0 (http://www.turnitin.com/robot/crawlerinfo.html)
Disallow: /

User-agent: TurnitinBot/3.0
Disallow: /

# Block Heritrix
User-agent: Heritrix
Disallow: /

# Block pricepi
User-agent: pimonster
Disallow: /

User-agent: Pimonster
Disallow: /

# Block Searchmetrics Bot
#User-agent: SearchmetricsBot
#Disallow: /

# Block Eniro
User-agent: ECCP/1.0 (search@eniro.com)
Disallow: /

# Block SoGou
User-agent: Sogou Spider
Disallow: /

# Block Youdao
User-agent: YoudaoBot
Disallow: /

# Block Nikon JP Crawler
User-agent: gsa-crawler (Enterprise; T4-KNHH62CDKC2W3; gsa_manage@nikon-sys.co.jp)
Disallow: /

# Block  MegaIndex.ru
User-agent: MegaIndex.ru/2.0
Disallow: /

User-agent: MegaIndex.ru
Disallow: /

User-agent: megaIndex.ru
Disallow: /

################koniec blokady robotow#####################

# Sitemap
Sitemap: https://wyprawkowy.pl/1_index_sitemap.xml

