User-agent: *
Disallow:

Disallow: */listing/*
Disallow: /accounts/*

User-agent: Slurp
Disallow: /
User-agent: baiduspider
Disallow: /
User-agent: rogerbot
Disallow: /
User-agent: MJ12bot
Disallow: /
User-agent: Sosospider
Disallow: /
User-agent: Baiduspider
Disallow: /
User-agent: Yandex
Disallow: /
User-agent: Mail.Ru
Disallow: /
User-agent: YoudaoBot
Disallow: /
User-agent: NaverBot
Disallow: /
User-agent: Yeti
Disallow: /
User-agent: JobboerseBot
Disallow: /
User-agent: Nutch
Disallow: /
User-agent: 360Spider
Disallow: /
User-agent: 80legs
Disallow: /
User-agent: Abonti
Disallow: /
User-agent: AhrefsBot
Disallow: /
user-agent: BacklinkCrawler
Disallow: /
User-agent: Baiduspider
Disallow: /
User-agent: Baiduspider/2.0
Disallow: /
User-agent: BLEXBot
Disallow: /
User-agent: BUbiNG
Disallow: /
User-agent: BuddhaBot
Disallow: /
User-agent: careerbot
Disallow: /
User-agent: CMS Crawler
Disallow: /
User-agent: cometrics-bot
Disallow: /
User-agent: CompSpyBot
Disallow: /
User-agent: dataprovider
Disallow: /
User-agent: Dataprovider Site Explorer
Disallow: /
User-agent: Daumoa
Disallow: /
User-agent: Domain Re-Animator Bot
Disallow: /
User-agent: DomainStatsBot
Disallow: /
User-agent: DnyzBot
Disallow: /
User-agent: dubaiindex
Disallow: /
User-agent: Exabot
Disallow: /
User-agent: Ezooms
Disallow: /
User-agent: FreeWebMonitoring SiteChecker
Disallow: /
User-agent: Gigablast
Disallow: /
User-agent: GigablastOpenSource
Disallow: /
User-agent: Gluten Free Crawler
Disallow: /
User-agent: Gobyus
Disallow: /
User-agent: GrapeshotCrawler
Disallow: /
User-agent: ia_archiver
Disallow: /
User-agent: ICCrawler - iCjobs
Disallow: /
User-agent: iCjobs
Disallow: /
User-agent: ImplisenseBot
Disallow: /
User-agent: ips-agent
Disallow: /
User-agent: JobboerseBot
Disallow: /
User-agent: KomodiaBot
Disallow: /
User-agent: linkdexbot
Disallow: /
User-agent: linkdex.com
Disallow: /
User-agent: LinkpadBot
Disallow: /
User-agent: LinkStats Bot
Disallow: /
User-agent: Lipperhey
Disallow: /
User-agent: Lipperhey Spider
Disallow: /
User-agent: Lipperhey-Kaus-Australis
Disallow: /
User-agent: LoadTimeBot
Disallow: /
User-agent: ltx71
Disallow: /
User-agent: magpie-crawler
Disallow: /
User-agent: Mail.RU_Bot
Disallow: /
User-agent: MegaIndex
Disallow: /
User-agent: MetaJobBot
Disallow: /
User-agent: mindUpBot
Disallow: /
User-agent: MJ12bot
Disallow: /
User-agent: netEstate NE Crawler
Disallow: /
User-agent: netseer
Disallow: /
User-agent: nutch
Disallow: /
User-agent: PiplBot
Disallow: /
User-agent: pixray
Disallow: /
User-agent: Pixray-Seeker
Disallow: /
User-agent: proximic
Disallow: /
User-agent: psbot
Disallow: /
User-agent: QCrawl
Disallow: /
User-agent: Qwantify
Disallow: /
User-agent: SafeDNSBot
Disallow: /
User-agent: ScreenerBot
Disallow: /
User-agent: SearchmetricsBot
Disallow: /
User-agent: SemrushBot
Disallow: /
User-agent: SEOdiver
Disallow: /
User-agent: SEOkicks
Disallow: /
User-agent: SEOkicks-Robot
Disallow: /
User-agent: seolytics
Disallow: /
User-agent: seoscanners
Disallow: /
User-agent: seoscanners.net
Disallow: /
User-agent: seoscanners.net/1
Disallow: /
User-agent: SeznamBot
Disallow: /
User-agent: sistrix
Disallow: /
User-agent: SiteExplorer
Disallow: /
User-agent: SiteCheck-sitecrawl
Disallow: /
User-agent: Siteimprove
Disallow: /
User-agent: SMTBot
Disallow: /
User-agent: spbot
Disallow: /
User-agent: Spiderbot
Disallow: /
User-agent: Spiderbot/Nutch
Disallow: /
User-agent: Spiderlytics
Disallow: /
User-agent: sogou spider
Disallow: /
User-agent: SurveyBot
Disallow: /
User-agent: turnitinbot
Disallow: /
User-agent: UnisterBot
Disallow: /
User-agent: Unister
Disallow: /
User-agent: Uptimebot
Disallow: /
User-agent: Vagabondo
Disallow: /
User-agent: WBSearchBot
Disallow: /
User-agent: Vebidoobot
Disallow: /
User-agent: Webintegration Jobroboter WebSpider
Disallow: /
User-agent: WebThumbnail
Disallow: /
User-agent: WI Job Roboter Spider
Disallow: /
User-agent: wonderbot
Disallow: /
User-agent: wonderbot/JS
Disallow: /
User-agent: wotbox
Disallow: /
User-agent: xovi
Disallow: /
User-agent: XoviBot
Disallow: /
User-agent: Yandex
Disallow: /
User-agent: YandexBot
Disallow: /
User-agent: YandexImages
Disallow: /
User-agent: Yet-Another-Spider
Disallow: /
User-agent: YisouSpider
Disallow: /
User-agent: ZoominfoBot
Disallow: /

User-agent: psbot
Crawl-delay: 60
User-agent: Findxbot
Crawl-delay: 60
User-agent: Cliqzbot
Crawl-delay: 60
User-agent: Applebot
Crawl-delay: 15
User-agent: coccoc
Crawl-delay: 15
User-agent: istellabot
Crawl-delay: 15

