User-agent: *
Disallow: /
User-agent: APIs-Google
Disallow: /
User-agent: Mediapartners-Google
Disallow: /
User-agent: AdsBot-Google-Mobile
Disallow: /
User-agent: AdsBot-Google
Disallow: /
User-agent: Googlebot-Image
Disallow: /
User-agent: Googlebot-News
Disallow: /
User-agent: Googlebot-Video
Disallow: /
User-agent: Googlebot
Disallow: /
User-agent: Mediapartners-Google
Disallow: /
User-agent: AdsBot-Google-Mobile-Apps
Disallow: /
