User-agent: *
Allow: /
Allow: /wp-content/uploads/
Disallow: /wp-*
Disallow: /cgi-bin
Disallow: /wp-admin
Disallow: /wp-includes
Disallow: /wp-content/plugins/
Disallow: /wp-content/cache/
Disallow: /wp-content/themes/
Disallow: /wp-content/uploads/pdf/
