# robots.txt automaticaly generated by PrestaShop e-commerce open-source solution
# http://www.prestashop.com - http://www.prestashop.com/forums

# This file is to prevent the crawling and indexing of certain parts
# of your site by web crawlers and spiders run by sites like Yahoo!
# and Google. By telling these "robots" where not to go on your site,
# you save bandwidth and server resources.

# For more information about the robots.txt standard, see:
# http://www.robotstxt.org/wc/robots.html

User-agent: *
# Directories
Disallow: /www_zestawy/classes/
Disallow: /www_zestawy/config/
Disallow: /www_zestawy/download/
Disallow: /www_zestawy/mails/
Disallow: /www_zestawy/modules/
Disallow: /www_zestawy/translations/
Disallow: /www_zestawy/tools/
Disallow: /www_zestawy/lang-pl/
# Files
Disallow: /www_zestawy/addresses.php
Disallow: /www_zestawy/address.php
Disallow: /www_zestawy/authentication.php
Disallow: /www_zestawy/cart.php
Disallow: /www_zestawy/discount.php
Disallow: /www_zestawy/footer.php
Disallow: /www_zestawy/get-file.php
Disallow: /www_zestawy/header.php
Disallow: /www_zestawy/history.php
Disallow: /www_zestawy/identity.php
Disallow: /www_zestawy/images.inc.php
Disallow: /www_zestawy/init.php
Disallow: /www_zestawy/my-account.php
Disallow: /www_zestawy/order.php
Disallow: /www_zestawy/order-opc.php
Disallow: /www_zestawy/order-slip.php
Disallow: /www_zestawy/order-detail.php
Disallow: /www_zestawy/order-follow.php
Disallow: /www_zestawy/order-return.php
Disallow: /www_zestawy/order-confirmation.php
Disallow: /www_zestawy/pagination.php
Disallow: /www_zestawy/password.php
Disallow: /www_zestawy/pdf-invoice.php
Disallow: /www_zestawy/pdf-order-return.php
Disallow: /www_zestawy/pdf-order-slip.php
Disallow: /www_zestawy/product-sort.php
Disallow: /www_zestawy/search.php
Disallow: /www_zestawy/statistics.php
Disallow: /www_zestawy/attachment.php
Disallow: /www_zestawy/guest-tracking
Disallow: /www_zestawy/*orderby=
Disallow: /www_zestawy/*orderway=
Disallow: /www_zestawy/*tag=
Disallow: /www_zestawy/*id_currency=
Disallow: /www_zestawy/*search_query=
Disallow: /www_zestawy/*id_lang=
Disallow: /www_zestawy/*back=
Disallow: /www_zestawy/*utm_source=
Disallow: /www_zestawy/*utm_medium=
Disallow: /www_zestawy/*utm_campaign=
Disallow: /www_zestawy/*n=
# Sitemap
Sitemap: http://anderian.nazwa.pl/www_zestawy/sitemap.xml


