# robots.txt for http://www.zooplus.pl
#
# created 05.09.2016
#
User-agent: *
Disallow: /ask?*
Disallow: /askdetail?
Disallow: /checkout/
Disallow: /myzooplus/
Disallow: /pictureupload*
Disallow: /stockreminder
Disallow: /supershop/
Disallow: /miva/
Disallow: /web/
Disallow: /feedback/form/
Disallow: /petofday*
Disallow: /postcards/*
Disallow: */topten$
Disallow: /recommendation/
Disallow: /bonuspoints/
Disallow: /customerpicturedisplay/
Disallow: /bonus/
Disallow: /passwordreminder*
Disallow: /?petId*
Disallow: /account*
Disallow: /ov?
Disallow: /specials/
Disallow: /content/jobs/
Disallow: /detailedQuestion.htm$

User-agent: bingbot
Disallow: /ask?*
Disallow: /askdetail?
Disallow: /checkout/
Disallow: /myzooplus/
Disallow: /pictureupload*
Disallow: /stockreminder
Disallow: /supershop/
Disallow: /miva/
Disallow: /web/
Disallow: /feedback/form/
Disallow: /petofday*
Disallow: /postcards/*
Disallow: */topten$
Disallow: /recommendation/
Disallow: /bonuspoints/
Disallow: /customerpicturedisplay/
Disallow: /bonus/
Disallow: /passwordreminder*
Disallow: /?petId*
Disallow: /account*
Disallow: /ov?
Disallow: /specials/
Disallow: /content/jobs/
Disallow: /detailedQuestion.htm$
Crawl-delay: 5

User-agent: msnbot
Disallow: /ask?*
Disallow: /askdetail?
Disallow: /checkout/
Disallow: /myzooplus/
Disallow: /pictureupload*
Disallow: /stockreminder
Disallow: /supershop/
Disallow: /miva/
Disallow: /web/
Disallow: /feedback/form/
Disallow: /petofday*
Disallow: /postcards/*
Disallow: */topten$
Disallow: /recommendation/
Disallow: /bonuspoints/
Disallow: /customerpicturedisplay/
Disallow: /bonus/
Disallow: /passwordreminder*
Disallow: /?petId*
Disallow: /account*
Disallow: /ov?
Disallow: /specials/
Disallow: /content/jobs/
Disallow: /detailedQuestion.htm$
Crawl-delay: 5

User-agent: msnbot-media
Disallow: /ask?*
Disallow: /askdetail?
Disallow: /checkout/
Disallow: /myzooplus/
Disallow: /pictureupload*
Disallow: /stockreminder
Disallow: /supershop/
Disallow: /miva/
Disallow: /web/
Disallow: /feedback/form/
Disallow: /petofday*
Disallow: /postcards/*
Disallow: */topten$
Disallow: /recommendation/
Disallow: /bonuspoints/
Disallow: /customerpicturedisplay/
Disallow: /bonus/
Disallow: /passwordreminder*
Disallow: /?petId*
Disallow: /account*
Disallow: /ov?
Disallow: /specials/
Disallow: /content/jobs/
Disallow: /detailedQuestion.htm$
Crawl-delay: 5
