User-agent: *
Disallow: /kalendarium-wydarzen/action~posterboard/
Disallow: /kalendarium-wydarzen/action~agenda/
Disallow: /kalendarium-wydarzen/action~oneday/
Disallow: /kalendarium-wydarzen/action~month/
Disallow: /kalendarium-wydarzen/action~week/
Disallow: /kalendarium-wydarzen/action~stream/
Disallow: /calendar/action~posterboard/
Disallow: /calendar/action~agenda/
Disallow: /calendar/action~oneday/
Disallow: /calendar/action~month/
Disallow: /calendar/action~week/
Disallow: /calendar/action~stream/
Disallow: /calendar/action~undefined/
Disallow: /calendar/action~http:/
Disallow: /calendar/action~default/
Disallow: /calendar/action~poster/
Disallow: /calendar/action~*/
Disallow: /*controller=ai1ec_exporter_controller*
Disallow: /*/action~*/
Disallow: /kalendarium-wydarzen/action~undefined/
Disallow: /kalendarium-wydarzen/action~http:/
Disallow: /kalendarium-wydarzen/action~default/
Disallow: /kalendarium-wydarzen/action~poster/
Disallow: /kalendarium-wydarzen/action~*/
