User-agent: *
Disallow: /calendar/action~posterboard/
Disallow: /calendar/action~agenda/
Disallow: /calendar/action~oneday/
Disallow: /calendar/action~month/
Disallow: /calendar/action~week/
Disallow: /calendar/action~stream/
Disallow: /calendar/action~undefined/
Disallow: /calendar/action~http:/
Disallow: /calendar/action~default/
Disallow: /calendar/action~poster/
Disallow: /calendar/action~*/
Disallow: /*controller=ai1ec_exporter_controller*
Disallow: /*/action~*/
Disallow: /daty-imienin/action~posterboard/
Disallow: /daty-imienin/action~agenda/
Disallow: /daty-imienin/action~oneday/
Disallow: /daty-imienin/action~month/
Disallow: /daty-imienin/action~week/
Disallow: /daty-imienin/action~stream/
Disallow: /daty-imienin/action~undefined/
Disallow: /daty-imienin/action~http:/
Disallow: /daty-imienin/action~default/
Disallow: /daty-imienin/action~poster/
Disallow: /daty-imienin/action~*/
