<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<title>Jazz Forum</title>
<meta name="description" content="">
<meta name="viewport" content="width=device-width">
<title> Jazz Forum </title>
<meta name='keywords' content='Jazz Forum, jazz, Muzyka, Recenzje, Plyty, CD, Wywiady, Aktualnosci, koncerty,  Magazyn, Miesiecznik ' />
<meta name='description' content='Jazz Forum Jazz Recenzje Muzyka Jazz Magazyn Miesiecznik Jazz Najstarsze polskie czasopismo jazzowe w Polsce. Relacje, wywiady, recenzje plyt, festiwale jazzowe, aktualnosci ze swiata jazzu' />
<link rel='canonical' href='http://jazzforum.com.pl/robots.txt' />
<link rel="shortcut icon" href="http://jazzforum.com.pl/img/jf.ico" type="image/x-icon" />
<!-- generated by seo_lite -->
<!-- CSS -->
<link href="http://jazzforum.com.pl/?css=main/normalize.v.1387198110" type="text/css" rel="stylesheet" media="screen" />
<link href="http://jazzforum.com.pl/?css=main/site_css.v.1414581465" type="text/css" rel="stylesheet" media="screen" />
<link href="http://jazzforum.com.pl/?css=main/colorbox.v.1355187076" type="text/css" rel="stylesheet" media="screen" />
<!--[if IE 6]><link href="http://jazzforum.com.pl/?css=main/css_screen-ie6" type="text/css" rel="stylesheet" media="screen" /><![endif]-->
<!--[if IE 7]><link href="http://jazzforum.com.pl/?css=main/css_screen-ie7" type="text/css" rel="stylesheet" media="screen" /><![endif]-->

<script src="http://jazzforum.com.pl/js/vendor/modernizr-2.6.2.min.js"></script>
<link href='http://fonts.googleapis.com/css?family=Noticia+Text:400,700&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
<link type="text/css" rel="stylesheet" href="http://jazzforum.com.pl/css/rhinoslider-1.05.css" />
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.7/jquery.min.js"></script>
<script type="text/javascript" src="http://jazzforum.com.pl/js/rhinoslider-1.05.min.js"></script>
<script type="text/javascript" src="http://jazzforum.com.pl/js/mousewheel.js"></script>
<script type="text/javascript" src="http://jazzforum.com.pl/js/easing.js"></script>
<script type="text/javascript">
$(document).ready(function() {
$('#slider').rhinoslider({
effect: 'fade',
showTime: 6000,
easing: 'easeInQuad',
controlsKeyboard: false,
controlsPrevNext: false,
controlsPlayPause: false,
autoPlay: true,
showBullets: 'never',
showControls: 'never'
});
});
</script>

<style type="text/css">
#slider {
width:233px;
height:178px;

/*IE bugfix*/
padding:0;
margin:0;
}

#slider li {list-style:none;}
</style>
</head>
<body>
<!--[if lt IE 7]>
<p class="chromeframe">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your experience.</p>
<![endif]-->
<div class="container clearfix">
<div class="header">
<div class="logo"><a href="http://jazzforum.com.pl/">
<img src="http://jazzforum.com.pl//img/jazzforum-logo.png" width="322" height="101"></a>
</div>
<div class="head_pr">
<div class="head_2">
<form class="search_form" method="post" action="http://jazzforum.com.pl/"  >
<div class='hiddenFields'>
<input type="hidden" name="ACT" value="8" />
<input type="hidden" name="XID" value="db2671ebd2ec9bc762e1f4e2502a481c11958fe7" />
<input type="hidden" name="RES" value="20" />
<input type="hidden" name="meta" value="HPZvLesK3ldZtgyNylEXFZE5lvCxULA6mRVRCbshD3u+gD7DPV9zq/V/ylQVn4/fHlzX2PEjDEKUtfcG0lKI2Y4sYakDMYA6sP5ewRKfI4ZKVd72D+FSGvQ5BF+arjfdaZQinE5qTKp+KloVM17/WiigdpjmS9Cu2KnJBX4NAnsAnMUmuP/xsvAmybAFqOwOOiJrUkImkQtUM4VNm5lYrqognE5iViJzEubo7BRy6l0eUSSvblonHNKH/1nxO/SdmcoOr3DU17uS3TJJptXdk0ihlnzGOZVxLr/lwdL6KNvmo9t6XfIeQHD+V/T7Y4JYkA/LY3WvK8Rpr8Z/1RyzGL8FJfg7J6kzfnkzSGViXfSRrgvUFOBhR/dHxMkfYtm2lZOYLXdyTQVE8RaITWQQ5YULfTaGndAG37EjyezAUShFmi+kasTSj+VO6HesXJXAkoziXe+CR+SEo1mKQ3Nh0Zkb4g/tqImvgnpTM6MvlR8Qslyed2sxNq82tVGyYegg" />
<input type="hidden" name="site_id" value="1" />
</div>



<input type="text" name="keywords" id="keywords" value="" size="16" maxlength="50">
<!-- a href="http://jazzforum.com.pl/search">Szukanie zaawansowane</a -->&nbsp;&nbsp;
<input type="submit" value="Szukaj" class="submit">

</form>
<div class="menu_nav"><ul>
<li class="active">
<a href="http://jazzforum.com.pl/">Home</a>&nbsp;|&nbsp;</li>
<li><a href="http://jazzforum.com.pl/main/statyczne/redakcja">Redakcja</a>&nbsp;|&nbsp;</li>
<li><a href="http://jazzforum.com.pl/main/statyczne/reklama">Reklama</a>&nbsp;|&nbsp;</li>
<li><a href="http://jazzforum.com.pl/main/statyczne/kontakt">Kontakt</a>&nbsp;</li>
<!-- li><a href="http://jazzforum.com.pl/main/statyczne/ogloszenia">Ogloszenia</a></li -->
<!-- div class="fb-like" data-href="http://jazzforum.com.pl" data-send="false" data-layout="button_count" data-width="95" data-show-faces="false" data-font="arial"></div -->
</ul>
<a href="http://www.facebook.com/pages/Jazz-Forum/106823076008737" target="_blank"><img style="margin:-2px 10px 0 4px;" src="http://jazzforum.com.pl/images/uploads/doc/facebook-f.png"></a>
<!-- a href="http://jazzforum.com.pl/store/"><img src="/img/sklep.png" style="margin:-2px"></a -->
<a href="http://jazzforum.com.pl/store/"><img src="/img/sklep.png" style="margin:-2px"></a>

</div><!-- menu_nav -->

</div>



<a href="http://jazzforum.com.pl/store/" target="_blank"><img src="http://jazzforum.com.pl/images/uploads/r/sklep-dziala-580x85.gif"></a>




</div>
<!-- head_pr -->
<div class="menu_nav2">
<ul id="menu_nav2">
<li><a href="http://jazzforum.com.pl/main/newsy">Aktualnosci</a></li>
<li><a href="http://jazzforum.com.pl/main/wydania">Numery archiwalne</a></li>
<li><a href="http://jazzforum.com.pl/main/statyczne/prenumerata">Prenumerata</a></li>
<!-- li><a href="http://jazzforum.com.pl/main/artykuly">Artykuly</a -->
<li><a href="#">Artykuly</a>
<ul id="nav_categories" class="nav_categories">
<li>
<a href="http://jazzforum.com.pl/main/artykuly/kategoria/features">Wywiady</a>
</li>
<li>
<a href="http://jazzforum.com.pl/main/artykuly/kategoria/festiwale">Festiwale</a>
</li>
<li>
<a href="http://jazzforum.com.pl/main/artykuly/kategoria/koncerty">Koncerty</a>
</li>
</ul>

</li>
<li><a href="#">Recenzje</a>
<ul>
<li><a href="http://jazzforum.com.pl/main/recenzje-cd">Plyty CD</a></li>
<li><a href="http://jazzforum.com.pl/main/artykuly/kategoria/ksiazki">Ksiazki</a></li>
<li><a href="#">DVD</a></li>
</ul></li>
<li><a href="http://jazzforum.com.pl/main/artykuly/kategoria/Coda">Coda</a></li>
<li><a href="http://jazzforum.com.pl/main/listy">Listy</a></li>
<li><a href="http://jazzforum.com.pl/main/galerie">Galerie</a></li>
<li><a href="http://jazzforum.com.pl/store">Sklep</a></li>


</ul>
</div>
</div><!-- header -->
<div class="glowna">
<div class="srodek">

<div id="featured" >
<ul class="ui-tabs-nav">


<li class="ui-tabs-nav-item ui-tabs-selected" id="nav-fragment-1"><a href="#fragment-1">
<!-- a href="http://jazzforum.com.pl/main/news/polish-jazz-w-kenii" -->


<img src="http://jazzforum.com.pl/images/uploads/news/22656/photo-2019-04-13-16-05-13__mini.jpg" alt="" />



<span>Polish Jazz w Kenii!</span></a></li>


<li class="ui-tabs-nav-item ui-tabs-selected" id="nav-fragment-2"><a href="#fragment-2">
<!-- a href="http://jazzforum.com.pl/main/news/muzyka-pozostaa" -->


<img src="http://jazzforum.com.pl/images/uploads/news/22650/komeda__mini.jpg" alt="" />



<span>Muzyka pozostala</span></a></li>


<li class="ui-tabs-nav-item ui-tabs-selected" id="nav-fragment-3"><a href="#fragment-3">
<!-- a href="http://jazzforum.com.pl/main/news/jazzonalia-2019" -->


<img src="http://jazzforum.com.pl/images/uploads/news/22605/jazzonalia_1920x1080__mini.jpg" alt="" />



<span>Jazzonalia 2019</span></a></li>


<li class="ui-tabs-nav-item ui-tabs-selected" id="nav-fragment-4"><a href="#fragment-4">
<!-- a href="http://jazzforum.com.pl/main/news/starzy-i-modzi-czyli-jazz-w-krakowie6" -->


<img src="http://jazzforum.com.pl/images/uploads/news/22597/logo__mini.jpg" alt="" />



<span>Starzy i Mlodzi, czyli Jazz w Krakowie</span></a></li>

</ul>


<div id="fragment-1" class="ui-tabs-panel" style="">



<img src="http://jazzforum.com.pl/images/uploads/news/22656/photo-2019-04-13-16-05-13__medium.jpg" alt="" />




<div class="info" >
<h2><a href="http://jazzforum.com.pl/main/news/polish-jazz-w-kenii">Polish Jazz w Kenii!</a></h2>
<p>

Jazz Brigade Sylwestra Ostrowskiego wystapi 1 maja podczas Miedzynarodowego Dnia Jazzu w Nairobi.&nbsp;&nbsp;
<a href="http://jazzforum.com.pl/main/news/polish-jazz-w-kenii">wiecej&nbsp;>>></a>
</p>
</div>
</div>



<div id="fragment-2" class="ui-tabs-panel ui-tabs-hide" style="">


<img src="http://jazzforum.com.pl/images/uploads/news/22650/komeda__medium.jpg" alt="" />


<div class="info" >
<h2><a href="http://jazzforum.com.pl/main/news/muzyka-pozostaa">Muzyka pozostala</a></h2>
<p>
Mija 50. rocznica tragicznej smierci Krzysztofa Komedy, ktory zmarl w Warszawie 23 kwietnia 1969 roku.
<a href="http://jazzforum.com.pl/main/news/muzyka-pozostaa">&nbsp;&nbsp;wiecej&nbsp;>>></a>
</p>
</div>
</div>


<div id="fragment-3" class="ui-tabs-panel ui-tabs-hide" style="">


<img src="http://jazzforum.com.pl/images/uploads/news/22605/jazzonalia_1920x1080__medium.jpg" alt="" />


<div class="info" >
<h2><a href="http://jazzforum.com.pl/main/news/jazzonalia-2019">Jazzonalia 2019</a></h2>
<p>
Mozdzer, Jopek i Orzechowski oraz Mlynarski i Masecki - to gwiazdy festiwalu w Koninie, 22-26 maja
<a href="http://jazzforum.com.pl/main/news/jazzonalia-2019">&nbsp;&nbsp;wiecej&nbsp;>>></a>
</p>
</div>
</div>


<div id="fragment-4" class="ui-tabs-panel ui-tabs-hide" style="">


<img src="http://jazzforum.com.pl/images/uploads/news/22597/logo__medium.jpg" alt="" />


<div class="info" >
<h2><a href="http://jazzforum.com.pl/main/news/starzy-i-modzi-czyli-jazz-w-krakowie6">Starzy i Mlodzi, czyli Jazz w Krakowie</a></h2>
<p>
John McLaughlin, Kandace Springs, Joachim Mencel, Adam Baldych, Andrzej Jagodzinski, 16 - 30 kwietnia
<a href="http://jazzforum.com.pl/main/news/starzy-i-modzi-czyli-jazz-w-krakowie6">&nbsp;&nbsp;wiecej&nbsp;>>></a>
</p>
</div>
</div>

</div><!-- featuerd -->
<div id="newsy">
<!-- newsy -->


<div class="news_l">


<img src="http://jazzforum.com.pl/images/uploads/news/22674/international_jazz_day__kwadrat.jpg" alt="" />



<a href="http://jazzforum.com.pl/main/news/international-jazz-day-2019"><h3>International Jazz Day 2019</h3></a>
<p>
Wtorek 30 kwietnia. Globalny Koncert Samych Gwiazd transmitowany bedzie z Melbourne na caly swiat.

<a href="http://jazzforum.com.pl/main/news/international-jazz-day-2019"> Wiecej >>></a></p>
</div>



<div class="news_p">


<img src="http://jazzforum.com.pl/images/uploads/news/22675/56173145_1192444420914995_3073272889558958080_o__kwadrat.jpg" alt="" />



<a href="http://jazzforum.com.pl/main/news/katowice-jazzart-festival-2019"><h3>Katowice JazzArt Festival 2019</h3></a>
<p>
Na tegorocznej, osmej edycji rekordowo az 19 wydarzen, w tym 17 koncertow.

<a href="http://jazzforum.com.pl/main/news/katowice-jazzart-festival-2019"> Wiecej >>></a></p>
</div>



<div class="news_l">


<img src="http://jazzforum.com.pl/images/uploads/news/22673/jno__kwadrat.jpg" alt="" />



<a href="http://jazzforum.com.pl/main/news/santander-jazz-nad-odr-2019"><h3>Santander Jazz nad Odra 2019</h3></a>
<p>
55. edycja slynnego wroclawskiego festiwalu odbywac sie bedzie w&nbsp;dn. 26-30 kwietnia.

<a href="http://jazzforum.com.pl/main/news/santander-jazz-nad-odr-2019"> Wiecej >>></a></p>
</div>



<div class="news_p">


<img src="http://jazzforum.com.pl/images/uploads/news/22672/jazzzzaheads__kwadrat.jpg" alt="" />



<a href="http://jazzforum.com.pl/main/news/jazzahead-2019"><h3>Jazzahead! 2019</h3></a>
<p>
Najwieksze europejskie targi jazzowe odbywac sie beda w Bremie, juz po raz czternasty, w&nbsp;dn. 25-28 kwietnia.

<a href="http://jazzforum.com.pl/main/news/jazzahead-2019"> Wiecej >>></a></p>
</div>



<div class="news_l">


<img src="http://jazzforum.com.pl/images/uploads/news/22671/six_seasons_wielkie_otwarcie__kwadrat.jpg" alt="" />



<a href="http://jazzforum.com.pl/main/news/six-seasons-world-orchestra-house-wielkie-otwarcie"><h3>Six Seasons World Orchestra House - wielkie otwarcie!</h3></a>
<p>
Grzech Piotrowski zagra w nowym klubie na warszawskim Wilanowie 26.04 z Oxen Band, 27.04 z Alchemikiem

<a href="http://jazzforum.com.pl/main/news/six-seasons-world-orchestra-house-wielkie-otwarcie"> Wiecej >>></a></p>
</div>



<div class="news_p">


<img src="http://jazzforum.com.pl/images/uploads/news/22670/jerzy_malek_podziemia_kamedulskie__kwadrat.jpg" alt="" />



<a href="http://jazzforum.com.pl/main/news/jerzy-maek-w-podziemiach-kamedulskich"><h3>Jerzy Malek w Podziemiach Kamedulskich</h3></a>
<p>
Kwintet czolowego trebacza zaprezentuje 25 kwietnia na warszawskich Bielanach program ,,Black Sheep"

<a href="http://jazzforum.com.pl/main/news/jerzy-maek-w-podziemiach-kamedulskich"> Wiecej >>></a></p>
</div>



<div class="clearfix"></div>
</div>      <!-- #newsy -->
<p><a href="http://jazzforum.com.pl/main/newsy">Wczesniejsze wiadomosci >>></a></p>
<div class="srodek_reklama">


<a href="http://jazzforum.com.pl/store/" target="_blank"><img src="http://jazzforum.com.pl/images/uploads/r/sklep-dziala-580x85.gif"></a>



<!-- img src="img/reklama-poziom.png" width="680" height="99" -->     </div>
<!-- srodek_reklama -->
<div class="belka"><p>Z numerow archiwalnych</p></div>
<div class="archiw2">



<div class="archiw_in2">
<h3> <!-- a href="http://jazzforum.com.pl/channel/kategoria/coda" -->Coda<!-- /a --></h3>

<a href="http://jazzforum.com.pl/main/artykul/janusz-skowron"><h2> Janusz Skowron</h2></a>



<img src="http://jazzforum.com.pl/images/uploads/inne/_prostakat/Janusz_Skowron_smill.jpg"/>



<p>Wybitny pianista zmarl 27 lutego 2019 po ciezkiej chorobie nowotworowej.<br></p> <p><a href="http://jazzforum.com.pl/main/artykul/janusz-skowron">wiecej >>></a></p>
</div>


<div class="archiw_in2">
<h3> <!-- a href="http://jazzforum.com.pl/channel/kategoria/coda" -->Coda<!-- /a --></h3>

<a href="http://jazzforum.com.pl/main/artykul/ira-gitler"><h2> Ira Gitler</h2></a>



<img src="http://jazzforum.com.pl/images/uploads/inne/_prostakat/ira_gitler2.jpg"/>



<p><p>Jeden
z&nbsp;najbardziej&nbsp;wplywowych krytykow jazzowych <span>zmarl&nbsp; 23 lutego 2019 w&nbsp;Nowym
Jorku, przezywszy 90 lat.&nbsp;</span></p><br></p> <p><a href="http://jazzforum.com.pl/main/artykul/ira-gitler">wiecej >>></a></p>
</div>


<div class="archiw_in2">
<h3> <!-- a href="http://jazzforum.com.pl/channel/kategoria/coda" -->Coda<!-- /a --></h3>

<a href="http://jazzforum.com.pl/main/artykul/michel-legrand"><h2> Michel Legrand</h2></a>



<img src="http://jazzforum.com.pl/images/uploads/inne/_prostakat/michel-legrand.jpg"/>



<p><p>Legendarny francuski pianista,
aranzer i&nbsp;kompozytor filmowy zmarl <span><span>26 styc</span><span>z</span><span>nia 2019.&nbsp;</span></span></p><br></p> <p><a href="http://jazzforum.com.pl/main/artykul/michel-legrand">wiecej >>></a></p>
</div>

</div>


<div class="belka">
<p>Recenzje</p>
</div>
<div class="recenzje">

<div class="recenzje_in">
<h3>CD</h3>

<img src="/images/sized/images/uploads/okladki/o_china-boy-120x108.jpg" width="120" height="108" />


<p><a href="http://jazzforum.com.pl/main/cd/china-boy"> China Boy</a></p>
<h4><a href="http://jazzforum.com.pl/main/cd/china-boy">Dixie Warsaw Jazzmen</a></h4>


</div>


<div class="recenzje_in">
<h3>CD</h3>

<img src="/images/sized/images/uploads/okladki/Wings-120x120.jpg" width="120" height="119" />


<p><a href="http://jazzforum.com.pl/main/cd/wings"> Adam Pieronczyk & Miroslav&#8230;</a></p>
<h4><a href="http://jazzforum.com.pl/main/cd/wings">Wings</a></h4>

<div class="star-rating" style="position:relative;float:left;clear:both; margin:0 0 0 10px;">
<ul class="rateFav2">
<li>
<span class="starRating white" style="background-position: -0px -32px;">
<span class="ocena">Ocena - 5 </span></span>
</li>
</ul>
</div>

</div>


<div class="recenzje_in">
<h3>CD</h3>

<img src="/images/sized/images/uploads/okladki/Warsaw_Stompers-120x108.jpg" width="120" height="108" />


<p><a href="http://jazzforum.com.pl/main/cd/new-orleans-stompers1"> Warsaw Stompers</a></p>
<h4><a href="http://jazzforum.com.pl/main/cd/new-orleans-stompers1">New Orleans Stompers</a></h4>

<div class="star-rating" style="position:relative;float:left;clear:both; margin:0 0 0 10px;">
<ul class="rateFav2">
<li>
<span class="starRating white" style="background-position: -16px -32px;">
<span class="ocena">Ocena - 4 </span></span>
</li>
</ul>
</div>

</div>


<div class="recenzje_in">
<h3>CD</h3>

<img src="/images/sized/images/uploads/okladki/Tomasz-Stank--December-Avenue-120x108.jpg" width="120" height="107" />


<p><a href="http://jazzforum.com.pl/main/cd/tomasz-stako-new-york-quartet"> December Avenue</a></p>
<h4><a href="http://jazzforum.com.pl/main/cd/tomasz-stako-new-york-quartet">Tomasz Stanko New York Quartet</a></h4>

<div class="star-rating" style="position:relative;float:left;clear:both; margin:0 0 0 10px;">
<ul class="rateFav2">
<li>
<span class="starRating white" style="background-position: -0px -32px;">
<span class="ocena">Ocena - 5 </span></span>
</li>
</ul>
</div>

</div>


<div class="recenzje_in">
<h3>CD</h3>

<img src="/images/sized/images/uploads/okladki/Wendt_acoustic-travel-120x120.jpg" width="120" height="120" />


<p><a href="http://jazzforum.com.pl/main/cd/acoustic-travel"> Adam Wendt Acoustic Set</a></p>
<h4><a href="http://jazzforum.com.pl/main/cd/acoustic-travel">Acoustic Travel</a></h4>

<div class="star-rating" style="position:relative;float:left;clear:both; margin:0 0 0 10px;">
<ul class="rateFav2">
<li>
<span class="starRating white" style="background-position: -24px -32px;">
<span class="ocena">Ocena - 3.5 </span></span>
</li>
</ul>
</div>

</div>


<div class="recenzje_in">
<h3>CD</h3>                                    <img src="http://jazzforum.com.pl/booklet/booklet685.jpg" width="120" height="120"/>

<p><a href="http://jazzforum.com.pl/main/cd/equilibrium">Maciej Obara Quartet</a></p>
<h4><a href="http://jazzforum.com.pl/main/cd/equilibrium">Equilibrium</a></h4>

<div class="star-rating" style="position:relative;float:left;clear:both; margin:0 0 0 10px;">
<ul class="rateFav2">
<li>
<span class="starRating white" style="background-position: -0px -32px;">
<span class="ocena">Ocena - 5 </span></span>
</li>
</ul>
</div>

</div>


<div class="recenzje_in">
<h3>CD</h3>

<img src="/images/sized/images/uploads/okladki/Bloom_M_Kadziela-120x120.jpg" width="120" height="119" />


<p><a href="http://jazzforum.com.pl/main/cd/in-bloom"> Marek Kadziela ADHD</a></p>
<h4><a href="http://jazzforum.com.pl/main/cd/in-bloom">In Bloom</a></h4>

<div class="star-rating" style="position:relative;float:left;clear:both; margin:0 0 0 10px;">
<ul class="rateFav2">
<li>
<span class="starRating white" style="background-position: -16px -32px;">
<span class="ocena">Ocena - 4 </span></span>
</li>
</ul>
</div>

</div>


<div class="recenzje_in">
<h3>CD</h3>                                    <img src="http://jazzforum.com.pl/booklet/booklet679.jpg" width="120" height="120"/>

<p><a href="http://jazzforum.com.pl/main/cd/around-ornette">Giovanni Falzone Quintet </a></p>
<h4><a href="http://jazzforum.com.pl/main/cd/around-ornette">Around Ornette</a></h4>

<div class="star-rating" style="position:relative;float:left;clear:both; margin:0 0 0 10px;">
<ul class="rateFav2">
<li>
<span class="starRating white" style="background-position: -16px -32px;">
<span class="ocena">Ocena - 4 </span></span>
</li>
</ul>
</div>

</div>



<div class="recenzje_in_2">
<h3>Ksiazki</h3>


<img src="/images/sized/images/uploads/inne/Man_of_the_Light-120x172.jpg" width="120" height="171" />


<p><a href="http://jazzforum.com.pl/main/artykul/aneta-norek-man-of-the-light.-ycie-i-tworczo-zbigniewa-seiferta1"> Aneta Norek: Man of the Light</a></p>
<p>
Ukazalo sie drugie, poprawione wydanie biografii Zbigniewa Seiferta.&nbsp;

<a href="http://jazzforum.com.pl/main/artykul/aneta-norek-man-of-the-light.-ycie-i-tworczo-zbigniewa-seiferta1"> Wiecej >>></a></p>
</div>

<div class="recenzje_in_2">
<h3>Ksiazki</h3>


<img src="/images/sized/images/uploads/inne/Pasaze_jazzowe_na_skrzypce-120x170.jpg" width="120" height="170" />


<p><a href="http://jazzforum.com.pl/main/artykul/maciej-afanasjew-pasae-jazzowe-na-skrzypce"> Maciej Afanasjew: Pasaze jazzowe na skrzypce</a></p>
<p>
Publikacja moze posluzyc wielu roznym instrumentalistom, nie tylko skrzypkom.

<a href="http://jazzforum.com.pl/main/artykul/maciej-afanasjew-pasae-jazzowe-na-skrzypce"> Wiecej >>></a></p>
</div>

<div class="recenzje_in_2">
<h3>Ksiazki</h3>


<img src="/images/sized/images/uploads/inne/zima_w_lizbonie_-120x192.jpg" width="120" height="191" />


<p><a href="http://jazzforum.com.pl/main/artykul/zima-w-lizbonie"> Zima w Lizbonie</a></p>
<p> Bohaterem powiesci jest jazzowy pianista. Jednak jazz to wdzieczny pretekst,&#8230;
<a href="http://jazzforum.com.pl/main/artykul/zima-w-lizbonie"> Wiecej >>></a></p>
</div>

<div class="recenzje_in_2">
<h3>Ksiazki</h3>


<img src="/images/sized/images/uploads/inne/Doba_a_scena-120x137.jpg" width="120" height="137" />


<p><a href="http://jazzforum.com.pl/main/artykul/dzhezaky"> DZEZAKY</a></p>
<p> Festiwal Bratislava Jazz Days dla slowackich melomanow jest, jak dla&#8230;
<a href="http://jazzforum.com.pl/main/artykul/dzhezaky"> Wiecej >>></a></p>
</div>

</div>


</div>
<div class="prawa">


<div class="aktualny">
<h3>JAZZ FORUM  4-5/2019</h3><a href="http://jazzforum.com.pl/main/wydanie/4-5-2019">


<img src="/images/sized/images/uploads/inne/I-okl-JF-4-5_19-komeda_big-235x311.jpg" width="235" height="311" />


<p>Aktualnie w sprzedazy <br>
Wiecej >>> </p></a>
<div class="cd">


<a href="http://jazzforum.com.pl/main/cd/with-all-due-respect">


<img src="/images/sized/images/uploads/okladki/wojcinskiszmanda-56x57.jpg" width="56" height="56" />



</a>

<div class="cd2"><img src="http://jazzforum.com.pl//img/cd_napis.png">
<div class="cd3">
<h3> <a href="http://jazzforum.com.pl/main/cd/with-all-due-respect">
With All Due Respect</a></h3>
<p> Wojcinski/Szmanda Q</p>
</div>
</div>
</div>

</div><!-- Aktualny -->

<div id="simplegallery1"></div>
<div class="belka_p">Plyta miesiaca</div>

<h3> Nahorny Trio</h3>
<a href="http://jazzforum.com.pl/main/cd/ballad-book-okruchy-dziecistwa"><h4>Ballad Book - okruchy dziecinstwa</h4></a>
<!--  <p>Wytwornia: Confiteor 011</p> -->


<img src="/images/sized/images/uploads/okladki/na-235x221.jpg" width="235" height="221" />



<div class="star-rating" style="position:relative;">
<ul class="rateFav2">
<li>
<span class="starRating white" style="background-position: -0px -32px;">
<span class="ocena">Ocena - 5 </span></span>
</li>
</ul>
</div>



<a href="http://polishjazzarch.com" target="_blank"><img src="http://jazzforum.com.pl//img/pj-arch.png"></a>
<div class="belka_p">Linki</div><div class="linki">
<ul id="nav_categories" class="linki">
<li>
<a href="http://jazzforum.com.pl/main/linki/kategoria/blogi">Blogi</a>      </li>
<li>
<a href="http://jazzforum.com.pl/main/linki/kategoria/czasopisma">Czasopisma</a>
<ul>
<li>
</li>
<li>
</li>
<li>
</li>
</ul>
</li>
<li>
<a href="http://jazzforum.com.pl/main/linki/kategoria/festiwale">Festiwale</a>
<ul>
<li>
</li>
<li>
</li>
</ul>
</li>
<li>
<a href="http://jazzforum.com.pl/main/linki/kategoria/firmy-pytowe">Firmy Plytowe</a>
<ul>
<li>
</li>
<li>
</li>
</ul>
</li>
<li>
<a href="http://jazzforum.com.pl/main/linki/kategoria/kluby">Kluby</a>      </li>
<li>
<a href="http://jazzforum.com.pl/main/linki/kategoria/konkursy">Konkursy</a>
<ul>
<li>
</li>
<li>
</li>
</ul>
</li>
<li>
<a href="http://jazzforum.com.pl/main/linki/kategoria/muzycy">Muzycy polscy</a>      </li>
<li>
<a href="http://jazzforum.com.pl/main/linki/kategoria/warsztaty">Warsztaty</a>      </li>
</ul>

</div>
<div class="belka_p">Z galerii</div>

<a href="http://jazzforum.com.pl/main/galeria/leszek-moder-te-deum"><h3>Leszek Mozdzer ,,Te Deum"</h3></a>
<!--   -->
<ul class="galeria_thumbs">

<li>
<a class="thumb"  name="image_{image_id}" href="http://jazzforum.com.pl/main/galeria/leszek-moder-te-deum" title="fot. Agnieszka Walulik">
<img src="http://jazzforum.com.pl/images/uploads/gallery/8057/img185__small.jpg" alt="fot. Agnieszka Walulik" />
</a>
<!-- div class="caption">
fot. Agnieszka Walulik
</div -->
</li>

<li>
<a class="thumb"  name="image_{image_id}" href="http://jazzforum.com.pl/main/galeria/leszek-moder-te-deum" title="fot. Agnieszka Walulik">
<img src="http://jazzforum.com.pl/images/uploads/gallery/8057/img186__small.jpg" alt="fot. Agnieszka Walulik" />
</a>
<!-- div class="caption">
fot. Agnieszka Walulik
</div -->
</li>

</ul>

<div class="belka_p"><a href="http://jazzforum.com.pl/main/statyczne/ogloszenia">Ogloszenia >>></a></div>
<div style="clear:both;"></div>





<p><br></p><p><a href="http://www.europejazz.net/europe-jazz-media-chart-april-2019?fbclid=IwAR2SEMM3TrntpjYqJN5OpXtyC9Jk6DWDXd3jWhuKXvmLU2_D0TXXYbNrSvM"><img src="http://jazzforum.com.pl/images/uploads/doc/temp_file_EJM-logotype21.gif" style="width: 240px; height: 240px; float: none; margin: 0px;" alt=""></a></p><br>
</div><!-- PRAWA -->
<div style="clear:both"></div>
</div><!-- Content -->
<div class="container2 clearfix">
</div>

</div><!-- Container -->
<div class="container clearfix">
<div class="stopka1">
<div class="stopka">
<figure style="text-align: center; ">&nbsp;&nbsp;<a href="http://www.mkidn.gov.pl" target="_blank"><img alt="MKIDN" src="http://jazzforum.com.pl/images/uploads/doc/mkidn2.gif" style=""></a>&nbsp; &nbsp; &nbsp;&nbsp;<a href="http://www.stoart.org.pl"><img src="http://jazzforum.com.pl/images/uploads/doc/stoart.gif" style="float: none; margin: 0px; width: 68px; height: 32px; " alt="stoart"></a>
&nbsp; &nbsp; &nbsp;&nbsp;<a href="http://zbigniewseifert.org"><img src="http://jazzforum.com.pl/images/uploads/doc/ZSF.gif" style="float: none; margin: 0px; " alt="stoart"></a>
&nbsp; &nbsp; &nbsp;&nbsp;<a href="http://polishjazz.com"><img src="http://jazzforum.com.pl/images/uploads/doc/polishjazz.gif" style="float: none; margin: 0px; " alt="stoart"></a>&nbsp; &nbsp; &nbsp;<a href="http://www.psj.org.pl"><img src="http://jazzforum.com.pl/images/uploads/doc/logo-PSJ.gif" style="float: none; margin: 0px; " alt="psj"></a>&nbsp; &nbsp; &nbsp;&nbsp;<a href="http://europejazzmedia.net/2013/10/ejm-chart-october-2013/" target="_blank"><img src="http://jazzforum.com.pl/images/uploads/doc/EJM-logotype_male.gif" style="float: none; margin: 0px; " alt="ejm"></a></figure>
</div>
</div>
</div>

<!-- script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script -->
<!-- script>window.jQuery || document.write('<script src="js/vendor/jquery-1.8.2.min.js"><\/script>')</script -->
<script src="http://jazzforum.com.pl/js/plugins.js"></script>
<script src="http://jazzforum.com.pl/js/main.js"></script>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.5.3/jquery-ui.min.js" ></script>
<script type="text/javascript" src="http://jazzforum.com.pl/js/jquery.colorbox-min.js"></script>
<script type="text/javascript" src="http://jazzforum.com.pl//js/simplegallery.js">
/***********************************************
* Simple Controls Gallery- (c) Dynamic Drive DHTML code library (www.dynamicdrive.com)
* This notice MUST stay intact for legal use
* Visit Dynamic Drive at http://www.dynamicdrive.com/ for this script and 100s more
***********************************************/
</script>

<script type="text/javascript">
var simpleGallery_navpanel={
loadinggif: 'ajaxload.gif', //full path or URL to loading gif image
panel: {height:'45px', opacity:0.5, paddingTop:'5px', fontStyle:'bold 11px Verdana'}, //customize nav panel container
images: [ 'http://jazzforum.com.pl/img/left.gif', 'http://jazzforum.com.pl/img/play.gif', 'http://jazzforum.com.pl/img/right.gif', 'http://jazzforum.com.pl/img/pause.gif'], //nav panel images (in that order)
imageSpacing: {offsetTop:[-4, 0, -4], spacing:10}, //top offset of left, play, and right images, PLUS spacing between the 3 images
slideduration: 500 //duration of slide up animation to reveal panel
};

var mygallery=new simpleGallery({
wrapperid: "simplegallery1", //ID of main gallery container,
dimensions: [235, 332], //width/height of gallery in pixels. Should reflect dimensions of the images exactly
imagearray: [

["http://jazzforum.com.pl/images/uploads/r/_pion/Summer_Jazz_Festival_Krakow_2019.jpg", "http://jazzforum.com.pl/main/reklama/summer-jazz-festival-krakow-2019", "", "Summer Jazz Festival Krakow 2019"],

["http://jazzforum.com.pl/images/uploads/r/_pion/MK_Foto_plakat.jpg", "http://jazzforum.com.pl/main/reklama/mk-foto", "", "MK Foto"],

["http://jazzforum.com.pl/images/uploads/r/_pion/kennedy_stern_fb.jpg", "http://jazzforum.com.pl/main/reklama/nigel-kennedy1", "", "Nigel Kennedy"],

["http://jazzforum.com.pl/images/uploads/r/_pion/Santander_Jazz_nad_Odra_2019_baner.jpg", "http://jazzforum.com.pl/main/reklama/jazz-nad-odr-2019", "", "Jazz nad Odra 2019"],

["http://jazzforum.com.pl/images/uploads/r/_pion/Jazz_Forum_small.jpg", "http://jazzforum.com.pl/main/reklama/jazz-forum-special-english-edition-april-2018", "", "Jazz Forum Special English Edition, April 2018"],

["http://jazzforum.com.pl/images/uploads/r/_pion/www_JF_a5_2019_maj.jpg", "http://jazzforum.com.pl/main/reklama/jazz-forum-4-5-2019", "", "Jazz Forum 4-5/2019"],

["http://jazzforum.com.pl/images/uploads/r/_pion/Olbinski_okladki.jpg", "http://jazzforum.com.pl/main/reklama/50-okadek-jazz-forum", "", "50 okladek Jazz Forum"]


],
autoplay: [true, 5000, 2], //[auto_play_boolean, delay_btw_slide_millisec, cycles_before_stopping_int]
persist: false, //remember last viewed slide and recall within same session?
fadeduration: 500, //transition duration (milliseconds)
oninit:function(){ //event that fires when gallery has initialized/ ready to run
//Keyword "this": references current gallery instance (ie: try this.navigate("play/pause"))
//$(".iframe").colorbox({iframe:true, width:"80%", height:"80%"});

},
onslide:function(curslide, i){ //event that fires after each slide is shown
//Keyword "this": references current gallery instance
//curslide: returns DOM reference to current slide's DIV (ie: try alert(curslide.innerHTML)
//i: integer reflecting current image within collection being shown (0=1st image, 1=2nd etc)
}
})
</script>

<script type="text/javascript">
$(document).ready(function(){
$("#featured > ul").tabs({fx:{opacity: "toggle"}}).tabs("rotate", 7000, true);

$('#menu_nav2 li').hover(
function () {
//show its submenu
$('ul', this).stop().slideDown(100);

},
function () {
//hide its submenu
$('ul', this).stop().slideUp(100);
}
);

$("a[rel='colorbox']").colorbox({innerWidth:"80%", innerHeight:"80%"});
});
</script>

<div id="fb-root"></div>
<script>(function(d, s, id) {
var js, fjs = d.getElementsByTagName(s)[0];
if (d.getElementById(id)) return;
js = d.createElement(s); js.id = id;
js.src = "//connect.facebook.net/pl_PL/all.js#xfbml=1";
fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<script type="text/javascript">
var _gaq = _gaq || [];
_gaq.push(
['_setAccount', 'UA-9673020-1'],
['_trackPageview'],
['b._setAccount', 'UA-37435621-1'],
['b._trackPageview']
);
(function() {
var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
})();
</script>
</body>
</html>

