<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,shrink-to-fit=no"><meta name="theme-color" content="#000000"><meta charset="UTF-8"><title>Kursy Programowania, UX, Testera dla Firm - Szkola IT Coders Lab</title><meta name="description" content="Wspieranie cyfrowej transformacji w firmach, rozwoj pracownikow IT oraz dostarczanie nowych pracownikow z kompetencjami programistycznymi, ux i testowania - to nasza specjalnosc."/><meta name="keywords" content="kursy dla firm, kursy programowania dla firm, kursy it dla firm, kursy ux dla firm, kursy testera dla firm, kursy b2b, kursy programowania b2b, kursy front-end dla firm, kursy back-end dla firm"/><meta property="og:type" content="website"/><meta property="og:url" content="http://coderslab.pl/pl/kursy-b2b/robots.txt"/><meta property="og:title" content="Kursy Programowania, UX, Testera dla Firm - Szkola IT Coders Lab"/><meta name="og:description" content="Wspieranie cyfrowej transformacji w firmach, rozwoj pracownikow IT oraz dostarczanie nowych pracownikow z kompetencjami programistycznymi, ux i testowania - to nasza specjalnosc."/><meta property="og:image" content="https://www-api.coderslab.pl/uploads/media/default/0001/01/3db6c8a8a81bb806cebb612a2a98fbd487fe4d9e.png"/><meta property="og:image:width" content="1200"/><meta property="og:image:height" content="630"/><meta name="twitter:card" content="summary"/><meta property="twitter:title" content="Kursy Programowania, UX, Testera dla Firm - Szkola IT Coders Lab"/><meta name="twitter:description" content="Wspieranie cyfrowej transformacji w firmach, rozwoj pracownikow IT oraz dostarczanie nowych pracownikow z kompetencjami programistycznymi, ux i testowania - to nasza specjalnosc."/><meta name="twitter:image" content="https://www-api.coderslab.pl/uploads/media/default/0001/01/3db6c8a8a81bb806cebb612a2a98fbd487fe4d9e.png"/><meta itemprop="image" content="https://www-api.coderslab.pl/uploads/media/default/0001/01/3db6c8a8a81bb806cebb612a2a98fbd487fe4d9e.png"/><!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-KS67KD');</script>
<!-- End Google Tag Manager -->
<meta name="google-site-verification" content="hEN6EVPsQEI2IYUGyuxWDIBXVKdHl6Hl-Qnjs1TK1n8" /><link rel="manifest" href="/manifest.json"><link rel="shortcut icon" href="/favicon.png"><link href="/static/css/main.33d30374.css" rel="stylesheet"></head><body><noscript>You need to enable JavaScript to run this app.</noscript><div id="root"></div><script data-cf async="true" type="text/javascript" src="https://coderslab.user.com/widget.js"></script><!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-KS67KD"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) --><script type="text/javascript" src="/static/js/main.d6aa985c.js"></script></body></html>
