<html><head><title> - KalendarzOnline.pl</title><meta http-equiv="Content-Type" content="text/html; charset=utf-8"/><meta name="keywords" content=""><meta name="description" content=""><meta property="og:title" content=""/><meta property="og:type" content="article"/><meta property="og:image" content="http://i.kalendarzonline.pl/app.png"/><meta property="og:url" content="http://www.kalendarzonline.pl/robots.txt"/><meta property="og:description" content=""/><link rel="image_src" href="http://i.kalendarzonline.pl/app.png"/><link rel="shortcut icon" href="http://i.kalendarzonline.pl/favicon.ico" type="image/x-icon"><style type="text/css">body {width: 100%; background:#ffffff;font-family:Verdana,Arial;font-size:8px;color:#222222;}a:link {text-decoration: none; color: #ed0101;}a:visited {text-decoration: none; color: #ed0101;}a:active {text-decoration: none; color: #ed0101;}a:hover {text-decoration: underline; color: #B30000;}</style></head><body topmargin="0" leftmargin="0" rightmargin="0" bottommargin="0" style="color: #0C0C0C" bgcolor="#FFFFFF"><div align="center"><table border="0" width="100%" cellpadding="0" style="border-collapse: collapse" height="200"><tr><td background="http://i.kalendarzonline.pl/top.png" align="center"><div align="center"><table border="0" width="1004" cellpadding="0" style="border-collapse: collapse" height="200"><tr><td width="313" valign="top"><a title="kalendarz" href="http://www.kalendarzonline.pl/"><img border="0" src="http://i.kalendarzonline.pl/logo.png" width="306" height="140" alt="kalendarz"></a></td><td align="center"><a href="/"><img border="0" src="http://i.kalendarzonline.pl/home_0.png" onmouseover='this.src="http://i.kalendarzonline.pl/home_1.png"' onmouseout='this.src="http://i.kalendarzonline.pl/home_0.png"' width="168" height="200"></a><a href="/terminarz/"><img border="0" src="http://i.kalendarzonline.pl/terminarz_0.png" onmouseover='this.src="http://i.kalendarzonline.pl/terminarz_1.png"' onmouseout='this.src="http://i.kalendarzonline.pl/terminarz_0.png"' width="168" height="200"></a><a href="/zyczenia/"><img border="0" src="http://i.kalendarzonline.pl/zyczenia_0.png" onmouseover='this.src="http://i.kalendarzonline.pl/zyczenia_1.png"' onmouseout='this.src="http://i.kalendarzonline.pl/zyczenia_0.png"' width="168" height="200"></a><a href="/dodatki/"><img border="0" src="http://i.kalendarzonline.pl/dodatki_0.png" onmouseover='this.src="http://i.kalendarzonline.pl/dodatki_1.png"' onmouseout='this.src="http://i.kalendarzonline.pl/dodatki_0.png"' width="168" height="200"></a></td></tr></table></div></td></tr></table></div><br><div align="center"><table border="0" width="1004" cellpadding="0" style="border-collapse: collapse"><tr><td width="180" valign="top" align="center"><br><script type="text/javascript"><!--
google_ad_client = "ca-pub-5293661681258338";
/* kalendarz */
google_ad_slot = "7673805082";
google_ad_width = 160;
google_ad_height = 600;
//-->
</script>
<script type="text/javascript"
src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script><br>&nbsp;</td><td width="644" valign="top"></td><td width="180" valign="top" align="center"><br><script type="text/javascript"><!--
google_ad_client = "ca-pub-5293661681258338";
/* kalendarz */
google_ad_slot = "7673805082";
google_ad_width = 160;
google_ad_height = 600;
//-->
</script>
<script type="text/javascript"
src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script><br>&nbsp;</td></tr></table></div><br><table border="0" width="100%" cellpadding="0" style="border-collapse: collapse" height="138"><tr><td align="center" background="http://i.kalendarzonline.pl/ft.png"><table border="0" width="1004" cellpadding="0" style="border-collapse: collapse" height="130"><tr><td colspan="3" align="center" height="58"><font face="Verdana" size="2" color="#bbbbbb"><b>Warto zobaczyc tez inne serwisy:<br><b><a title="gry dla dzieci" href="http://www.grydladzieci.info/">Gry dla dzieci</a></b> &#9679; <b><a title="nauka dla dzieci" href="http://www.naukadladzieci.net/">Nauka dla dzieci</a></b> &#9679; <b><a title="fryzury" href="http://www.fryzury.net/">Fryzury</a></b></font></td></tr><tr><td colspan="3"><font size="1" face="Verdana" color="#eeeeee"><b>Kalendarz na skroty:</b> <b><a href="/">Kalendarz</a></b> &#9679; <b><a href="/kalendarz/internautow">Kalendarz Internautow</a></b> &#9679; <b><a href="/terminarz/">Terminarz</a></b> &#9679; <b><a href="/zyczenia/">Zyczenia</a></b> &#9679; <b><a href="/dodatki/">Dodatki</a></b> &#9679; <b><a href="/dodatki/kalendarz-na-strone/">Kalendarz na strone</a></b> &#9679; <b><a href="/regulamin">Regulamin</a></b> &#9679; <b><a href="/okalendarzu">O kalendarzu</a></b> &#9679; <b><a href="/kontakt">Kontakt</a></b></font></td></tr><tr><td height="37" width="702"><b><font size="1"><a href="/m/">Wersja mobilna kalendarza</a></font></b></td><td height="37" width="39" align="center"><img border="0" src="http://i.kalendarzonline.pl/kalendarz_icon.png" width="34" height="34"></td><td height="37" width="263" align="right"><i><b><font size="1" face="Verdana"><font color="#BBBBBB">(c) Copyright 2011-2019 by </font><a title="kalendarz" href="http://www.kalendarzonline.pl/">KalendarzOnline</a><font color="#BBBBBB">.pl<br>Wszelkie prawa zastrzezone.</font></font></b></i></td></tr></table></td></tr></table><script type="text/JavaScript"> function setCookie(name,value,expires) {  document.cookie = name + "=" + value + ((expires==null) ? "" : ";expires=" + expires.toGMTString()) }  function closewc() {  var state = document.getElementById('wc').style.display;  document.getElementById('wc').style.display = 'none'; setCookie("id", "0");  } </script>
<div id="wc" style="direction: ltr; color: #111111; min-height: 30px; position: fixed; left: 0; bottom: 0; width: 100%; z-index: 99999; padding:6px 20px 4px; background-color: #aac6e0; font-size: 14px;">Ta strona uzywa plikow COOKIES (niezbedne do prawidlowego dzialania strony).
<button id="wcbtn" style="margin:0 20px; line-height:20px; background:#5478b6; border:none; color: #dddddd; padding:4px 12px; border-radius: 3px; font-size: 14px; font-weight: bold; cursor: pointer;" tabindex=1 onclick="closewc();">OK</button></div></body></html>
