<!DOCTYPE html><html lang="zh-Hant-TW"><head><script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-5H4CW9J');</script><title>AVerMedia</title><meta charset="UTF-8"><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><meta http-equiv="X-UA-Compatible" content="IE=edge, chrome=1" /><meta name="robots" content="index, follow" /><meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, shrink-to-fit=no"><meta name="apple-mobile-web-app-capable" content="yes" /><meta name="format-detection" content="telephone=no" /><meta name="theme-color" content="#000000"><meta name="msapplication-navbutton-color" content="#000000"><meta name="apple-mobile-web-app-status-bar-style" content="#000000"><meta name="msapplication-TileColor" content="#000000"><link rel="canonical" href="https://www.avermedia.com/pl/robots.txt" /><link rel="icon" href="/pl/addons/default/themes/avermedia/img/ico/favicon.ico" type="image/x-icon"><link rel="shortcut icon bookmark" href="/pl/addons/default/themes/avermedia/img/ico/favicon.ico" type="image/x-icon"><link rel="bookmark" href="/pl/addons/default/themes/avermedia/img/ico/favicon.ico" type="image/x-icon"><link rel="icon" href="/pl/addons/default/themes/avermedia/img/ico/favicon.png" type="image/png"><meta name="msapplication-TileImage" content="/pl/addons/default/themes/avermedia/img/ico/favicon.png"><link rel="stylesheet" href="https://www.avermedia.com/pl/assets/cache/fe72c99c722b2183e64ad3f45133ea80.css" /><link rel="stylesheet" href="https://s3-us-west-2.amazonaws.com/avtweb-black/css/web-layout.css" /><script>
if (!console) var console = { log: function () {}};
</script></head><body><noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-5H4CW9J" height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript><div id="app"></div><script src="https://www.avermedia.com/pl/assets/cache/0c5e074258a8210fd3ea468488ed7988.js"></script><script src="https://www.avermedia.com/pl/assets/cache/52732516432766db94abf0e4751d13f2.js"></script><script src="https://www.avermedia.com/pl/assets/cache/06a51544f8d74d7a98a4850c77bf2812.js"></script><script>
var _helper;
_helper = new SITE.Helper();
</script><script src="https://www.youtube.com/iframe_api"></script><script>
var BASE_URI = "/pl/";
var THEME_URL = "https://www.avermedia.com/pl/addons/default/themes/avermedia/";
var SITE_URL = "https://www.avermedia.com/pl/";
var SITE_NAME = "AVerMedia";
var COOKIE_PREFIX = "www_";
var COOKIE_PATH = "/";
var ENVIRONMENT = 'production';
var SUPPORT_LANGUAGES = [{"name":"English","folder":"english","direction":"ltr","codes":["en","english","en_US"],"ckeditor":null,"code":"en"},{"name":"Deutsch","folder":"german","direction":"ltr","codes":["de","german","de_DE"],"ckeditor":null,"code":"de"},{"name":"\u010cesky","folder":"czech","direction":"ltr","codes":["csy","czech","cs_CZ"],"ckeditor":null,"code":"cs"},{"name":"Espa\u00f1ol","folder":"spanish","direction":"ltr","codes":["esp","spanish","es_ES"],"ckeditor":null,"code":"es"},{"name":"Fran\u00e7ais","folder":"french","direction":"ltr","codes":["fra","french","fr_FR"],"ckeditor":null,"code":"fr"},{"name":"Italiano","folder":"italian","direction":"ltr","codes":["ita","italian","it_IT"],"ckeditor":null,"code":"it"},{"name":"Nederlands","folder":"dutch","direction":"ltr","codes":["dutch","nld","nl-NL"],"ckeditor":null,"code":"nl"},{"name":"Polski","folder":"polish","direction":"ltr","codes":["plk","polish","pl_PL"],"ckeditor":null,"code":"pl"},{"name":"Portugu\u00eas de Portugal","folder":"portuguese","direction":"ltr","codes":["ptb","portuguese-portugal","pt_PT"],"ckeditor":"pt-pt","code":"pt"},{"name":"\u0420\u0443\u0441\u0441\u043a\u0438\u0439","folder":"russian","direction":"ltr","codes":["rus","russian","ru_RU"],"ckeditor":null,"code":"ru"},{"name":"\u7b80\u4f53\u4e2d\u6587","folder":"chinese_simplified","direction":"ltr","codes":["cn","chinese-simplified","zh_CN"],"ckeditor":null,"code":"cn"},{"name":"\u7e41\u9ad4\u4e2d\u6587","folder":"chinese_traditional","direction":"ltr","codes":["tw","chinese-traditional","zh_TW"],"ckeditor":null,"code":"tw"},{"name":"\u65e5\u672c\u8a9e","folder":"japanese","direction":"ltr","codes":["jp","japanese","jp_JP"],"ckeditor":null,"code":"jp"},{"name":"Magyar","folder":"hungarian","direction":"ltr","codes":["hu","hungarian","hu_HU"],"ckeditor":null,"code":"hu"}];
var SUPPORT_COUNTRIES = [{"name":"China (\u4e2d\u56fd)","code":"cn","tel":"86"},{"name":"Czech Republic (\u010cesk\u00e1 republika)","code":"cz","tel":"420"},{"name":"France","code":"fr","tel":"33"},{"name":"Germany (Deutschland)","code":"de","tel":"49"},{"name":"Hungary (Magyarorsz\u00e1g)","code":"hu","tel":"36"},{"name":"Italy (Italia)","code":"it","tel":"39"},{"name":"Japan (\u65e5\u672c)","code":"jp","tel":"81"},{"name":"Netherlands (Nederland)","code":"nl","tel":"31"},{"name":"Poland (Polska)","code":"pl","tel":"48"},{"name":"Portugal","code":"pt","tel":"351"},{"name":"Russia (\u0420\u043e\u0441\u0441\u0438\u044f)","code":"ru","tel":"7"},{"name":"Spain (Espa\u00f1a)","code":"es","tel":"34"},{"name":"Taiwan (\u53f0\u7063)","code":"tw","tel":"886"},{"name":"United States","code":"us","tel":"1"}];
var CURRENT_LANGUAGE = 'en';
var CURRENT_COUNTRY = 'pl';
var EXTRA_ROUTER = [{"path":"\/home","name":"Home"},{"path":"\/contact-us","name":"Contact"},{"path":"\/search","name":"Search"},{"path":"\/search\/results","name":"Results"},{"path":"\/404","name":"Page missing"},{"path":"\/privacy","name":"privacy"},{"path":"\/about","name":"about"},{"path":"\/responsibility","name":"Responsibility"},{"path":"\/recruiting","name":"Recruiting"},{"path":"\/services","name":"Services"}];
</script><script src="https://www.avermedia.com/pl/assets/cache/6919b31cff431ffd4097037b9e010a10.js"></script><script src="https://www.avermedia.com/pl/assets/cache/acbc3319b3d91e8459131bac853d0e53.js"></script><script src="https://www.avermedia.com/pl/assets/cache/85a9e1658d55112695ad529b008fa68d.js"></script><script src="https://s3-us-west-2.amazonaws.com/avtweb-black/js/product_layout.js"></script></body></html>
